IccConvertUTF.h File Reference
IccConvertUTF.h File Reference
#include "IccProfLibConf.h"
Macros
#define UNI_REPLACEMENT_CHAR (UTF32)0x0000FFFD
#define UNI_MAX_BMP (UTF32)0x0000FFFF
#define UNI_MAX_UTF16 (UTF32)0x0010FFFF
#define UNI_MAX_UTF32 (UTF32)0x7FFFFFFF
#define UNI_MAX_LEGAL_UTF32 (UTF32)0x0010FFFF
Typedefs
typedef ICCUINT32 UTF32
typedef unsigned short UTF16
typedef unsigned char UTF8
typedef unsigned char Boolean
Enumerations
enum icUtfConversionResult { conversionOK, sourceExhausted, targetExhausted, sourceIllegal }
enum icUtfConversionFlags { strictConversion = 0, lenientConversion }
Functions
icUtfConversionResult ICCPROFLIB_API icConvertUTF8toUTF16 (const UTF8 **sourceStart, const UTF8 *sourceEnd, UTF16 **targetStart, UTF16 *targetEnd, icUtfConversionFlags flags)
icUtfConversionResult ICCPROFLIB_API icConvertUTF16toUTF8 (const UTF16 **sourceStart, const UTF16 *sourceEnd, UTF8 **targetStart, UTF8 *targetEnd, icUtfConversionFlags flags)
icUtfConversionResult ICCPROFLIB_API icConvertUTF8toUTF32 (const UTF8 **sourceStart, const UTF8 *sourceEnd, UTF32 **targetStart, UTF32 *targetEnd, icUtfConversionFlags flags)
icUtfConversionResult ICCPROFLIB_API icConvertUTF32toUTF8 (const UTF32 **sourceStart, const UTF32 *sourceEnd, UTF8 **targetStart, UTF8 *targetEnd, icUtfConversionFlags flags)
icUtfConversionResult ICCPROFLIB_API icConvertUTF16toUTF32 (const UTF16 **sourceStart, const UTF16 *sourceEnd, UTF32 **targetStart, UTF32 *targetEnd, icUtfConversionFlags flags)
icUtfConversionResult ICCPROFLIB_API icConvertUTF32toUTF16 (const UTF32 **sourceStart, const UTF32 *sourceEnd, UTF16 **targetStart, UTF16 *targetEnd, icUtfConversionFlags flags)
Boolean ICCPROFLIB_API icIsLegalUTF8Sequence (const UTF8 *source, const UTF8 *sourceEnd)
Macro Definition Documentation
#define UNI_MAX_BMP (UTF32)0x0000FFFF
Referenced by icConvertUTF32toUTF16(), and icConvertUTF8toUTF16().
#define UNI_MAX_LEGAL_UTF32 (UTF32)0x0010FFFF
Referenced by icConvertUTF32toUTF16(), icConvertUTF32toUTF8(), and icConvertUTF8toUTF32().
#define UNI_MAX_UTF16 (UTF32)0x0010FFFF
Referenced by icConvertUTF8toUTF16().
#define UNI_MAX_UTF32 (UTF32)0x7FFFFFFF
#define UNI_REPLACEMENT_CHAR (UTF32)0x0000FFFD
Referenced by icConvertUTF16toUTF8(), icConvertUTF32toUTF16(), icConvertUTF32toUTF8(), icConvertUTF8toUTF16(), and icConvertUTF8toUTF32().
Typedef Documentation
typedef unsigned char Boolean
typedef unsigned short UTF16
typedef ICCUINT32 UTF32
typedef unsigned char UTF8
Enumeration Type Documentation
enum icUtfConversionFlags
Enumerator
strictConversion
lenientConversion
enum icUtfConversionResult
Enumerator
conversionOK
sourceExhausted
targetExhausted
sourceIllegal
Function Documentation
icUtfConversionResult ICCPROFLIB_API icConvertUTF16toUTF32 (const UTF16 ** sourceStart, const UTF16 * sourceEnd, UTF32 ** targetStart, UTF32 * targetEnd, icUtfConversionFlags flags)
References conversionOK, sourceExhausted, sourceIllegal, strictConversion, targetExhausted, UNI_SUR_HIGH_END, UNI_SUR_HIGH_START, UNI_SUR_LOW_END, and UNI_SUR_LOW_START.
Referenced by CIccUTF16String::ToWString().
icUtfConversionResult ICCPROFLIB_API icConvertUTF16toUTF8 (const UTF16 ** sourceStart, const UTF16 * sourceEnd, UTF8 ** targetStart, UTF8 * targetEnd, icUtfConversionFlags flags)
References conversionOK, sourceExhausted, sourceIllegal, strictConversion, targetExhausted, UNI_REPLACEMENT_CHAR, UNI_SUR_HIGH_END, UNI_SUR_HIGH_START, UNI_SUR_LOW_END, and UNI_SUR_LOW_START.
Referenced by icUtf16ToUtf8().
icUtfConversionResult ICCPROFLIB_API icConvertUTF32toUTF16 (const UTF32 ** sourceStart, const UTF32 * sourceEnd, UTF16 ** targetStart, UTF16 * targetEnd, icUtfConversionFlags flags)
References conversionOK, sourceIllegal, strictConversion, targetExhausted, UNI_MAX_BMP, UNI_MAX_LEGAL_UTF32, UNI_REPLACEMENT_CHAR, UNI_SUR_HIGH_START, UNI_SUR_LOW_END, and UNI_SUR_LOW_START.
Referenced by CIccUTF16String::FromWString(), and CIccLocalizedUnicode::SetText().
icUtfConversionResult ICCPROFLIB_API icConvertUTF32toUTF8 (const UTF32 ** sourceStart, const UTF32 * sourceEnd, UTF8 ** targetStart, UTF8 * targetEnd, icUtfConversionFlags flags)
References conversionOK, sourceIllegal, strictConversion, targetExhausted, UNI_MAX_LEGAL_UTF32, UNI_REPLACEMENT_CHAR, UNI_SUR_HIGH_START, and UNI_SUR_LOW_END.
icUtfConversionResult ICCPROFLIB_API icConvertUTF8toUTF16 (const UTF8 ** sourceStart, const UTF8 * sourceEnd, UTF16 ** targetStart, UTF16 * targetEnd, icUtfConversionFlags flags)
References conversionOK, sourceExhausted, sourceIllegal, strictConversion, targetExhausted, UNI_MAX_BMP, UNI_MAX_UTF16, UNI_REPLACEMENT_CHAR, UNI_SUR_HIGH_START, UNI_SUR_LOW_END, and UNI_SUR_LOW_START.
Referenced by CIccUTF16String::CIccUTF16String(), and CIccUTF16String::FromUtf8().
icUtfConversionResult ICCPROFLIB_API icConvertUTF8toUTF32 (const UTF8 ** sourceStart, const UTF8 * sourceEnd, UTF32 ** targetStart, UTF32 * targetEnd, icUtfConversionFlags flags)
References conversionOK, sourceExhausted, sourceIllegal, strictConversion, targetExhausted, UNI_MAX_LEGAL_UTF32, UNI_REPLACEMENT_CHAR, UNI_SUR_HIGH_START, and UNI_SUR_LOW_END.
Boolean ICCPROFLIB_API icIsLegalUTF8Sequence (const UTF8 * source, const UTF8 * sourceEnd)