CIccTagChromaticity Class Reference
CIccTagChromaticity Class Reference
#include <IccTagBasic.h>
Public Member Functions
CIccTagChromaticity (int nSize=3)
CIccTagChromaticity (const CIccTagChromaticity &ITCh)
CIccTagChromaticity & operator= (const CIccTagChromaticity &ChromTag)
virtual CIccTag * NewCopy () const
virtual ~CIccTagChromaticity ()
virtual bool IsArrayType ()
virtual icTagTypeSignature GetType () const
virtual const icChar * GetClassName () const
virtual void Describe (std::string &sDescription)
virtual bool Read (icUInt32Number size, CIccIO *pIO)
virtual bool Write (CIccIO *pIO)
icChromaticityNumber & operator[] (icUInt32Number index)
icChromaticityNumber * Getxy (icUInt32Number index)
icUInt32Number GetSize () const
void SetSize (icUInt16Number nSize, bool bZeroNew=true)
virtual icValidateStatus Validate (icTagSignature sig, std::string &sReport, const CIccProfile *pProfile=NULL) const
Public Member Functions inherited from CIccTag
CIccTag ()
virtual ~CIccTag ()
virtual bool IsMBBType ()
virtual IIccExtensionTag * GetExtension ()
virtual bool IsSupported ()
Public Attributes
icUInt16Number m_nColorantType
Public Attributes inherited from CIccTag
icUInt32Number m_nReserved
Protected Attributes
icUInt16Number m_nChannels
icChromaticityNumber * m_xy
Additional Inherited Members
Static Public Member Functions inherited from CIccTag
static CIccTag * Create (icTagTypeSignature sig)
Detailed Description
Class: CIccTagChromaticity
Purpose: the chromaticity tag - xy chromaticity values for each channel
Constructor & Destructor Documentation
CIccTagChromaticity::CIccTagChromaticity (int nSize = 3)
Name: CIccTagChromaticity::CIccTagChromaticity
Purpose: Constructor
Args: nSize = number of xy entries
CIccTagChromaticity::CIccTagChromaticity (const CIccTagChromaticity & ITCh)
Name: CIccTagChromaticity::CIccTagChromaticity
Purpose: Copy Constructor
Args: ITCh = The CIccTagChromaticity object to be copied
References m_nChannels, and m_xy.
CIccTagChromaticity::~CIccTagChromaticity () virtual
Name: CIccTagChromaticity::~CIccTagChromaticity
Purpose: Destructor
Member Function Documentation
void CIccTagChromaticity::Describe (std::string & sDescription) virtual
Name: CIccTagChromaticity::Describe
Purpose: Dump data associated with the tag to a string
Args: sDescription - string to concatenate tag dump to
Reimplemented from CIccTag.
References CIccInfo::GetColorantEncoding(), and icUFtoD().
virtual const icChar* CIccTagChromaticity::GetClassName () const inline virtual
Reimplemented from CIccTag.
icUInt32Number CIccTagChromaticity::GetSize () const inline
virtual icTagTypeSignature CIccTagChromaticity::GetType () const inline virtual
Function: GetType()
Purpose: Get Tag Type. Each derived tag will implement it's own GetType() function.
Reimplemented from CIccTag.
References icSigChromaticityType.
icChromaticityNumber* CIccTagChromaticity::Getxy (icUInt32Number index) inline
virtual bool CIccTagChromaticity::IsArrayType () inline virtual
Reimplemented from CIccTag.
virtual CIccTag* CIccTagChromaticity::NewCopy () const inline virtual
Function: NewCopy(sDescription) Each derived tag will implement it's own NewCopy() function.
Parameter(s): none
Returns a new CIccTag object that is a copy of this object.
Reimplemented from CIccTag.
CIccTagChromaticity & CIccTagChromaticity::operator= (const CIccTagChromaticity & ChromTag)
Name: CIccTagChromaticity::operator=
Purpose: Copy Operator
Args: ChromTag = The CIccTagChromaticity object to be copied
References m_nChannels, and m_xy.
icChromaticityNumber& CIccTagChromaticity::operator[] (icUInt32Number index) inline
bool CIccTagChromaticity::Read (icUInt32Number size, CIccIO * pIO) virtual
Name: CIccTagChromaticity::Read
Purpose: Read in the tag contents into a data block
Args: size - # of bytes in tag, pIO - IO object to read tag from
Return: true = successful, false = failure
Reimplemented from CIccTag.
References CIccIO::Read16(), and CIccIO::Read32().
void CIccTagChromaticity::SetSize (icUInt16Number nSize, bool bZeroNew = true)
Name: CIccTagChromaticity::SetSize
Purpose: Sets the size of the xy chromaticity array.
Args: nSize - number of xy entries, bZeroNew - flag to zero newly formed values
icValidateStatus CIccTagChromaticity::Validate (icTagSignature sig, std::string & sReport, const CIccProfile * pProfile = NULL) const virtual
Name: CIccTagChromaticity::Validate
Purpose: Check tag data validity.
Args: sig = signature of tag being validated, sReport = String to add report information to
Return: icValidateStatusOK if valid, or other error status.
Reimplemented from CIccTag.
References CIccInfo::GetSigName(), icColorantEBU, icColorantITU, icColorantP22, icColorantSMPTE, icDtoUF(), icMaxStatus(), icValidateCriticalError, icValidateCriticalErrorMsg, icValidateNonCompliant, icValidateNonCompliantMsg, and CIccTag::Validate().
bool CIccTagChromaticity::Write (CIccIO * pIO) virtual
Name: CIccTagChromaticity::Write
Purpose: Write the tag to a file
Args: pIO - The IO object to write tag to.
Return: true = succesful, false = failure
Reimplemented from CIccTag.
References CIccIO::Write16(), and CIccIO::Write32().
Member Data Documentation
icUInt16Number CIccTagChromaticity::m_nChannels protected
Referenced by CIccTagChromaticity(), and operator=().
icUInt16Number CIccTagChromaticity::m_nColorantType
icChromaticityNumber* CIccTagChromaticity::m_xy protected
Referenced by CIccTagChromaticity(), and operator=().
The documentation for this class was generated from the following files:
IccTagBasic.h
IccTagBasic.cpp