CIccTagSignature Class Reference
CIccTagSignature Class Reference
#include <IccTagBasic.h>
Public Member Functions
CIccTagSignature ()
CIccTagSignature (const CIccTagSignature &ITS)
CIccTagSignature & operator= (const CIccTagSignature &SignatureTag)
virtual CIccTag * NewCopy () const
virtual ~CIccTagSignature ()
virtual icTagTypeSignature GetType () const
virtual const icChar * GetClassName () const
virtual void Describe (std::string &sDescription)
virtual bool Read (icUInt32Number size, CIccIO *pIO)
virtual bool Write (CIccIO *pIO)
icUInt32Number GetValue () const
void SetValue (icUInt32Number sig)
icUInt32Number operator= (icUInt32Number sig)
virtual icValidateStatus Validate (icTagSignature sig, std::string &sReport, const CIccProfile *pProfile=NULL) const
Public Member Functions inherited from CIccTag
CIccTag ()
virtual ~CIccTag ()
virtual bool IsArrayType ()
virtual bool IsMBBType ()
virtual IIccExtensionTag * GetExtension ()
virtual bool IsSupported ()
Protected Attributes
icUInt32Number m_nSig
Additional Inherited Members
Static Public Member Functions inherited from CIccTag
static CIccTag * Create (icTagTypeSignature sig)
Public Attributes inherited from CIccTag
icUInt32Number m_nReserved
Detailed Description
Class: CIccTagSignature
Purpose: The signatureType tag
Constructor & Destructor Documentation
CIccTagSignature::CIccTagSignature ()
Name: CIccTagSignature::CIccTagSignature
Purpose: Constructor
CIccTagSignature::CIccTagSignature (const CIccTagSignature & ITS)
Name: CIccTagSignature::CIccTagSignature
Purpose: Copy Constructor
Args: ITS = The CIccTagSignature object to be copied
References m_nSig.
CIccTagSignature::~CIccTagSignature () virtual
Name: CIccTagSignature::~CIccTagSignature
Purpose: Destructor
Member Function Documentation
void CIccTagSignature::Describe (std::string & sDescription) virtual
Name: CIccTagSignature::Describe
Purpose: Dump data associated with the tag to a string
Args: sDescription - string to concatenate tag dump to
Reimplemented from CIccTag.
References CIccInfo::GetSigName().
virtual const icChar* CIccTagSignature::GetClassName () const inline virtual
Reimplemented from CIccTag.
virtual icTagTypeSignature CIccTagSignature::GetType () const inline virtual
Function: GetType()
Purpose: Get Tag Type. Each derived tag will implement it's own GetType() function.
Reimplemented from CIccTag.
References icSigSignatureType.
icUInt32Number CIccTagSignature::GetValue () const inline
Referenced by CIccPRMG::EvaluateProfile().
virtual CIccTag* CIccTagSignature::NewCopy () const inline virtual
Function: NewCopy(sDescription) Each derived tag will implement it's own NewCopy() function.
Parameter(s): none
Returns a new CIccTag object that is a copy of this object.
Reimplemented from CIccTag.
CIccTagSignature & CIccTagSignature::operator= (const CIccTagSignature & SignatureTag)
Name: CIccTagSignature::operator=
Purpose: Copy Operator
Args: SignatureTag = The CIccTagSignature object to be copied
References m_nSig.
icUInt32Number CIccTagSignature::operator= (icUInt32Number sig) inline
bool CIccTagSignature::Read (icUInt32Number size, CIccIO * pIO) virtual
Name: CIccTagSignature::Read
Purpose: Read in the tag contents into a data block
Args: size - # of bytes in tag, pIO - IO object to read tag from
Return: true = successful, false = failure
Reimplemented from CIccTag.
References CIccIO::Read32().
void CIccTagSignature::SetValue (icUInt32Number sig) inline
icValidateStatus CIccTagSignature::Validate (icTagSignature sig, std::string & sReport, const CIccProfile * pProfile = NULL) const virtual
Name: CIccTagSignature::Validate
Purpose: Check tag data validity.
Args: sig = signature of tag being validated, sReport = String to add report information to
Return: icValidateStatusOK if valid, or other error status.
Reimplemented from CIccTag.
References CIccInfo::GetSigName(), icMaxStatus(), icSigAMDisplay, icSigColorimetricIntentImageStateTag, icSigCRTDisplay, icSigDigitalCamera, icSigDigitalCinemaProjector, icSigDigitalMotionPictureCamera, icSigDyeSublimationPrinter, icSigElectrophotographicPrinter, icSigElectrostaticPrinter, icSigFilmScanner, icSigFilmWriter, icSigFlexography, icSigFocalPlaneColorimetryEstimates, icSigGravure, icSigInkJetPrinter, icSigMotionPictureFilmRecorder, icSigMotionPictureFilmScanner, icSigOffsetLithography, icSigPerceptualReferenceMediumGamut, icSigPerceptualRenderingIntentGamutTag, icSigPhotoCD, icSigPhotographicPaperPrinter, icSigPhotoImageSetter, icSigPMDisplay, icSigProjectionTelevision, icSigReflectionHardcopyOriginalColorimetry, icSigReflectionPrintOutputColorimetry, icSigReflectiveScanner, icSigSaturationRenderingIntentGamutTag, icSigSceneAppearanceEstimates, icSigSceneColorimetryEstimates, icSigSilkscreen, icSigTechnologyTag, icSigThermalWaxPrinter, icSigVideoCamera, icSigVideoMonitor, icValidateNonCompliant, icValidateNonCompliantMsg, and CIccTag::Validate().
bool CIccTagSignature::Write (CIccIO * pIO) virtual
Name: CIccTagSignature::Write
Purpose: Write the tag to a file
Args: pIO - The IO object to write tag to.
Return: true = succesful, false = failure
Reimplemented from CIccTag.
References CIccIO::Write32().
Member Data Documentation
icUInt32Number CIccTagSignature::m_nSig protected
Referenced by CIccTagSignature(), and operator=().
The documentation for this class was generated from the following files:
IccTagBasic.h
IccTagBasic.cpp