CIccTagColorantOrder Class Reference
CIccTagColorantOrder Class Reference
#include <IccTagBasic.h>
Public Member Functions
CIccTagColorantOrder (int nsize=1)
CIccTagColorantOrder (const CIccTagColorantOrder &ITCO)
CIccTagColorantOrder & operator= (const CIccTagColorantOrder &ColorantOrderTag)
virtual CIccTag * NewCopy () const
virtual ~CIccTagColorantOrder ()
virtual icTagTypeSignature GetType () const
virtual const icChar * GetClassName () const
virtual bool Read (icUInt32Number size, CIccIO *pIO)
virtual bool Write (CIccIO *pIO)
virtual void Describe (std::string &sDescription)
icUInt8Number & operator[] (int index)
icUInt8Number * GetData (int index)
void SetSize (icUInt16Number nsize, bool bZeronew=true)
icUInt32Number GetSize () const
virtual icValidateStatus Validate (icTagSignature sig, std::string &sReport, const CIccProfile *pProfile=NULL) const
Public Member Functions inherited from CIccTag
CIccTag ()
virtual ~CIccTag ()
virtual bool IsArrayType ()
virtual bool IsMBBType ()
virtual IIccExtensionTag * GetExtension ()
virtual bool IsSupported ()
Protected Attributes
icUInt32Number m_nCount
icUInt8Number * m_pData
Additional Inherited Members
Static Public Member Functions inherited from CIccTag
static CIccTag * Create (icTagTypeSignature sig)
Public Attributes inherited from CIccTag
icUInt32Number m_nReserved
Detailed Description
Class: CIccTagColorantOrder
Purpose: Colorant Order Tag
Constructor & Destructor Documentation
CIccTagColorantOrder::CIccTagColorantOrder (int nsize = 1)
Name: CIccTagColorantOrder::CIccTagColorantOrder
Purpose: Constructor
Args: nSize = number of channels
CIccTagColorantOrder::CIccTagColorantOrder (const CIccTagColorantOrder & ITCO)
Name: CIccTagColorantOrder::CIccTagColorantOrder
Purpose: Copy Constructor
Args: ITCO = The CIccTagColorantOrder object to be copied
References m_nCount, and m_pData.
CIccTagColorantOrder::~CIccTagColorantOrder () virtual
Name: CIccTagColorantOrder::~CIccTagColorantOrder
Purpose: Destructor
Member Function Documentation
void CIccTagColorantOrder::Describe (std::string & sDescription) virtual
Name: CIccTagColorantOrder::Describe
Purpose: Dump data associated with the tag to a string
Args: sDescription - string to concatenate tag dump to
Reimplemented from CIccTag.
virtual const icChar* CIccTagColorantOrder::GetClassName () const inline virtual
Reimplemented from CIccTag.
icUInt8Number* CIccTagColorantOrder::GetData (int index) inline
icUInt32Number CIccTagColorantOrder::GetSize () const inline
virtual icTagTypeSignature CIccTagColorantOrder::GetType () const inline virtual
Function: GetType()
Purpose: Get Tag Type. Each derived tag will implement it's own GetType() function.
Reimplemented from CIccTag.
References icSigColorantOrderType.
virtual CIccTag* CIccTagColorantOrder::NewCopy () const inline virtual
Function: NewCopy(sDescription) Each derived tag will implement it's own NewCopy() function.
Parameter(s): none
Returns a new CIccTag object that is a copy of this object.
Reimplemented from CIccTag.
CIccTagColorantOrder & CIccTagColorantOrder::operator= (const CIccTagColorantOrder & ColorantOrderTag)
Name: CIccTagColorantOrder::operator=
Purpose: Copy Operator
Args: ColorantOrderTag = The CIccTagColorantOrder object to be copied
References m_nCount, and m_pData.
icUInt8Number& CIccTagColorantOrder::operator[] (int index) inline
bool CIccTagColorantOrder::Read (icUInt32Number size, CIccIO * pIO) virtual
Name: CIccTagColorantOrder::Read
Purpose: Read in the tag contents into a data block
Args: size - # of bytes in tag, pIO - IO object to read tag from
Return: true = successful, false = failure
Reimplemented from CIccTag.
References CIccIO::Read32(), and CIccIO::Read8().
void CIccTagColorantOrder::SetSize (icUInt16Number nSize, bool bZeroNew = true)
Name: CIccTagColorantOrder::SetSize
Purpose: Sets the size of the data array.
Args: nSize - number of channels, bZeroNew - flag to zero newly formed values
icValidateStatus CIccTagColorantOrder::Validate (icTagSignature sig, std::string & sReport, const CIccProfile * pProfile = NULL) const virtual
Name: CIccTagColorantOrder::Validate
Purpose: Check tag data validity.
Args: sig = signature of tag being validated, sReport = String to add report information to
Return: icValidateStatusOK if valid, or other error status.
Reimplemented from CIccTag.
References icHeader::colorSpace, CIccInfo::GetSigName(), icGetSpaceSamples(), icMaxStatus(), icSigColorantTableOutTag, icSigColorantTableTag, icValidateNonCompliant, icValidateNonCompliantMsg, icValidateWarning, icValidateWarningMsg, CIccProfile::m_Header, icHeader::pcs, and CIccTag::Validate().
bool CIccTagColorantOrder::Write (CIccIO * pIO) virtual
Name: CIccTagColorantOrder::Write
Purpose: Write the tag to a file
Args: pIO - The IO object to write tag to.
Return: true = succesful, false = failure
Reimplemented from CIccTag.
References CIccIO::Write32(), and CIccIO::Write8().
Member Data Documentation
icUInt32Number CIccTagColorantOrder::m_nCount protected
Referenced by CIccTagColorantOrder(), and operator=().
icUInt8Number* CIccTagColorantOrder::m_pData protected
Referenced by CIccTagColorantOrder(), and operator=().
The documentation for this class was generated from the following files:
IccTagBasic.h
IccTagBasic.cpp