CIccNamedColorCmm Class Reference
CIccNamedColorCmm Class Reference
#include <IccCmm.h>
Public Member Functions
CIccNamedColorCmm (icColorSpaceSignature nSrcSpace=icSigUnknownData, icColorSpaceSignature nDestSpace=icSigUnknownData, bool bFirstInput=true)
nSrcSpace cannot be icSigUnknownData if first profile is named color
virtual ~CIccNamedColorCmm ()
virtual icStatusCMM AddXform (const icChar *szProfilePath, icRenderingIntent nIntent=icUnknownIntent, icXformInterp nInterp=icInterpLinear, icXformLutType nLutType=icXformLutColor, bool bUseMpeTags=true, CIccCreateXformHintManager *pHintManager=NULL)
Must make at least one call to some form of AddXform() before calling Begin()
virtual icStatusCMM AddXform (CIccProfile *pProfile, icRenderingIntent nIntent=icUnknownIntent, icXformInterp nInterp=icInterpLinear, icXformLutType nLutType=icXformLutColor, bool buseMpeTags=true, CIccCreateXformHintManager *pHintManager=NULL)
virtual icStatusCMM Begin (bool bAllocNewApply=true)
Must be called before calling Apply() or GetNewApply()
virtual CIccApplyCmm * GetNewApply (icStatusCMM &status)
icStatusCMM Apply (icFloatNumber *DstPixel, const icFloatNumber *SrcPixel)
icStatusCMM Apply (icFloatNumber *DstPixel, const icFloatNumber *SrcPixel, icUInt32Number nPixels)
virtual icStatusCMM Apply (icFloatNumber *DstPixel, const icChar *SrcColorName)
virtual icStatusCMM Apply (icChar *DstColorName, const icFloatNumber *SrcPixel)
virtual icStatusCMM Apply (icChar *DstColorName, const icChar *SrcColorName)
icApplyInterface GetInterface () const
Returns the type of interface that will be applied.
icStatusCMM SetLastXformDest (icColorSpaceSignature nDestSpace)
Public Member Functions inherited from CIccCmm
CIccCmm (icColorSpaceSignature nSrcSpace=icSigUnknownData, icColorSpaceSignature nDestSpace=icSigUnknownData, bool bFirstInput=true)
virtual ~CIccCmm ()
virtual CIccPCS * GetPCS ()
virtual icStatusCMM AddXform (icUInt8Number *pProfileMem, icUInt32Number nProfileLen, icRenderingIntent nIntent=icUnknownIntent, icXformInterp nInterp=icInterpLinear, icXformLutType nLutType=icXformLutColor, bool bUseMpeTags=true, CIccCreateXformHintManager *pHintManager=NULL)
virtual icStatusCMM AddXform (CIccProfile &Profile, icRenderingIntent nIntent=icUnknownIntent, icXformInterp nInterp=icInterpLinear, icXformLutType nLutType=icXformLutColor, bool bUseMpeTags=true, CIccCreateXformHintManager *pHintManager=NULL)
virtual CIccApplyCmm * GetNewApplyCmm (icStatusCMM &status)
virtual CIccApplyCmm * GetApply ()
virtual icStatusCMM RemoveAllIO ()
virtual icUInt32Number GetNumXforms () const
Returns the number of profiles/transforms added.
icColorSpaceSignature GetSourceSpace () const
Returns the source color space.
icColorSpaceSignature GetDestSpace () const
Returns the destination color space.
icColorSpaceSignature GetLastSpace () const
Returns the color space of the last profile added.
icRenderingIntent GetLastIntent () const
Returns the rendering intent of the last profile added.
icUInt16Number GetSourceSamples () const
Returns the number of samples in the source color space.
icUInt16Number GetDestSamples () const
Returns the number of samples in the destination color space.
bool Valid () const
Checks if this is a valid CMM object.
icStatusCMM ToInternalEncoding (icFloatNumber *pInternal, const icUInt8Number *pData)
icStatusCMM ToInternalEncoding (icFloatNumber *pInternal, const icUInt16Number *pData)
icStatusCMM FromInternalEncoding (icUInt8Number *pData, icFloatNumber *pInternal)
icStatusCMM FromInternalEncoding (icUInt16Number *pData, icFloatNumber *pInternal)
virtual icColorSpaceSignature GetFirstXformSource ()
virtual icColorSpaceSignature GetLastXformDest ()
Protected Attributes
icApplyInterface m_nApplyInterface
Protected Attributes inherited from CIccCmm
CIccApplyCmm * m_pApply
bool m_bValid
bool m_bLastInput
icColorSpaceSignature m_nSrcSpace
icColorSpaceSignature m_nDestSpace
icColorSpaceSignature m_nLastSpace
icRenderingIntent m_nLastIntent
CIccXformList * m_Xforms
Friends
class CIccApplyNamedColorCmm
Additional Inherited Members
Static Public Member Functions inherited from CIccCmm
static bool IsInGamut (icFloatNumber *pData)
static icStatusCMM ToInternalEncoding (icColorSpaceSignature nSpace, icFloatColorEncoding nEncode, icFloatNumber *pInternal, const icFloatNumber *pData, bool bClip=true)
Functions for converting to Internal representation of pixel colors.
static icStatusCMM ToInternalEncoding (icColorSpaceSignature nSpace, icFloatNumber *pInternal, const icUInt8Number *pData)
static icStatusCMM ToInternalEncoding (icColorSpaceSignature nSpace, icFloatNumber *pInternal, const icUInt16Number *pData)
static icStatusCMM FromInternalEncoding (icColorSpaceSignature nSpace, icFloatColorEncoding nEncode, icFloatNumber *pData, const icFloatNumber *pInternal, bool bClip=true)
Functions for converting from Internal representation of pixel colors.
static icStatusCMM FromInternalEncoding (icColorSpaceSignature nSpace, icUInt8Number *pData, const icFloatNumber *pInternal)
static icStatusCMM FromInternalEncoding (icColorSpaceSignature nSpace, icUInt16Number *pData, const icFloatNumber *pInternal)
static const icChar * GetFloatColorEncoding (icFloatColorEncoding val)
static icFloatColorEncoding GetFloatColorEncoding (const icChar *val)
Detailed Description
Type: Class
Purpose: A Slower Named Color Profile compatible CMM
Constructor & Destructor Documentation
CIccNamedColorCmm::CIccNamedColorCmm (icColorSpaceSignature nSrcSpace = icSigUnknownData, icColorSpaceSignature nDestSpace = icSigUnknownData, bool bFirstInput = true)
nSrcSpace cannot be icSigUnknownData if first profile is named color
Name: CIccNamedColorCmm::CIccNamedColorCmm
Purpose: Constructor
Args: nSrcSpace = signature of the source color space, nDestSpace = signature of the destination color space, bFirstInput = true if the first profile added is an input profile
References icApplyPixel2Pixel, and m_nApplyInterface.
CIccNamedColorCmm::~CIccNamedColorCmm () virtual
Name: CIccNamedColorCmm::~CIccNamedColorCmm
Purpose: Destructor
Member Function Documentation
icStatusCMM CIccNamedColorCmm::AddXform (const icChar * szProfilePath, icRenderingIntent nIntent = icUnknownIntent, icXformInterp nInterp = icInterpLinear, icXformLutType nLutType = icXformLutColor, bool bUseMpeTags = true, CIccCreateXformHintManager * pHintManager = NULL) virtual
Must make at least one call to some form of AddXform() before calling Begin()
Name: CIccNamedColorCmm::AddXform
Purpose: Adds a profile at the end of the Xform list
Args: szProfilePath = file name of the profile to be added, nIntent = rendering intent to be used with the profile, nInterp = type of interpolation to be used with the profile pHintManager = hints for creating the xform
Return: icCmmStatOk, if the profile was added to the list succesfully
Reimplemented from CIccCmm.
References icCmmStatCantOpenProfile, icCmmStatOk, and OpenIccProfile().
icStatusCMM CIccNamedColorCmm::AddXform (CIccProfile * pProfile, icRenderingIntent nIntent = icUnknownIntent, icXformInterp nInterp = icInterpLinear, icXformLutType nLutType = icXformLutColor, bool bUseMpeTags = true, CIccCreateXformHintManager * pHintManager = NULL) virtual
Name: CIccNamedColorCmm::AddXform
Purpose: Adds a profile at the end of the Xform list
Args: pProfile = pointer to the CIccProfile object to be added, nIntent = rendering intent to be used with the profile, nInterp = type of interpolation to be used with the profile nLutType = type of lut to use from the profile pHintManager = hints for creating the xform
Return: icCmmStatOk, if the profile was added to the list succesfully
Reimplemented from CIccCmm.
References icHeader::colorSpace, CIccXform::Create(), icHeader::deviceClass, CIccProfile::FindTag(), icCmmStatBadLutType, icCmmStatBadSpaceLink, icCmmStatBadXform, icCmmStatOk, icPerceptual, icSigAbstractClass, icSigGamutData, icSigLinkClass, icSigNamedColor2Tag, icSigNamedColorClass, icSigNamedData, icSigUnknownData, icUnknownIntent, icXformLutColor, icXformLutGamut, icXformLutNamedColor, icXformLutPreview, IsCompatSpace, CIccCmm::m_bLastInput, CIccProfile::m_Header, CIccCmm::m_nLastIntent, CIccCmm::m_nLastSpace, CIccCmm::m_nSrcSpace, CIccCmm::m_Xforms, icHeader::pcs, CIccXformPtr::ptr, icHeader::renderingIntent, CIccXformNamedColor::SetDestSpace(), and CIccXformNamedColor::SetSrcSpace().
icStatusCMM CIccNamedColorCmm::Apply (icFloatNumber * DstPixel, const icFloatNumber * SrcPixel) inline virtual
Name: CIccCmm::Apply
Purpose: Uses the m_pApply object allocated during Begin to Apply the transformations associated with the CMM.
Reimplemented from CIccCmm.
References CIccCmm::Apply().
icStatusCMM CIccNamedColorCmm::Apply (icFloatNumber * DstPixel, const icFloatNumber * SrcPixel, icUInt32Number nPixels) inline virtual
Name: CIccCmm::Apply
Purpose: Uses the m_pApply object allocated during Begin to Apply the transformations associated with the CMM.
Reimplemented from CIccCmm.
References CIccCmm::Apply().
icStatusCMM CIccNamedColorCmm::Apply (icFloatNumber * DstPixel, const icChar * SrcColorName) virtual
Name: CIccApplyNamedColorCmm::Apply
Purpose: Does the actual application of the Xforms in the list.
Args: DestPixel = Destination pixel where the result is stored, SrcColorName = Source color name which is to be searched.
References CIccCmm::m_pApply.
icStatusCMM CIccNamedColorCmm::Apply (icChar * DstColorName, const icFloatNumber * SrcPixel) virtual
Name: CIccApplyNamedColorCmm::Apply
Purpose: Does the actual application of the Xforms in the list.
Args: DstColorName = Destination string where the result is stored, SrcPoxel = Source pixel
References CIccCmm::m_pApply.
icStatusCMM CIccNamedColorCmm::Apply (icChar * DstColorName, const icChar * SrcColorName) virtual
Name: CIccApplyNamedColorCmm::Apply
Purpose: Does the actual application of the Xforms in the list.
Args: DstColorName = Destination string where the result is stored, SrcColorName = Source color name which is to be searched.
References CIccCmm::m_pApply.
icStatusCMM CIccNamedColorCmm::Begin (bool bAllocNewApply = true) virtual
Must be called before calling Apply() or GetNewApply()
Name: CIccNamedColorCmm::Begin
Purpose: Does the initialization of the Xforms in the list before Apply() is called. Must be called before Apply().
Reimplemented from CIccCmm.
References CIccCmm::GetNewApplyCmm(), icApplyNamed2Named, icApplyNamed2Pixel, icApplyPixel2Named, icApplyPixel2Pixel, icCmmStatBadSpaceLink, icCmmStatOk, icSigNamedData, icSigUnknownData, IsCompatSpace, m_nApplyInterface, CIccCmm::m_nDestSpace, CIccCmm::m_nLastSpace, CIccCmm::m_nSrcSpace, CIccCmm::m_pApply, and CIccCmm::m_Xforms.
icApplyInterface CIccNamedColorCmm::GetInterface () const inline
Returns the type of interface that will be applied.
CIccApplyCmm * CIccNamedColorCmm::GetNewApply (icStatusCMM & status) virtual
Name: CIccNamedColorCmm::GetNewApply
Purpose: Allocates a CIccApplyCmm object that allows one to call apply from multiple threads.
References CIccApplyCmm::AppendApplyXform(), CIccApplyNamedColorCmm, icCmmStatOk, CIccCmm::m_bValid, and CIccCmm::m_Xforms.
icStatusCMM CIccNamedColorCmm::SetLastXformDest (icColorSpaceSignature nDestSpace)
Name: CIccNamedColorCmm::SetLastXformDest
Purpose: Sets the destination Color space of the last Xform in the list
Args: nDestSpace = signature of the color space to be set
References CIccXformNamedColor::GetDstSpace(), CIccXformNamedColor::GetSrcSpace(), CIccXform::GetXformType(), icCmmStatBadSpaceLink, icCmmStatBadXform, icSigNamedData, icXformTypeNamedColor, CIccCmm::m_Xforms, CIccXformPtr::ptr, and CIccXformNamedColor::SetDestSpace().
Friends And Related Function Documentation
friend class CIccApplyNamedColorCmm friend
Referenced by GetNewApply().
Member Data Documentation
icApplyInterface CIccNamedColorCmm::m_nApplyInterface protected
Referenced by Begin(), and CIccNamedColorCmm().
The documentation for this class was generated from the following files:
IccCmm.h
IccCmm.cpp