CIccTagNum< T, Tsig > Class Template Reference
CIccTagNum< T, Tsig > Class Template Reference
#include <IccTagBasic.h>
Public Member Functions
CIccTagNum (int nSize=1)
CIccTagNum (const CIccTagNum &ITNum)
CIccTagNum & operator= (const CIccTagNum &NumTag)
virtual CIccTag * NewCopy () const
virtual ~CIccTagNum ()
virtual bool IsArrayType ()
virtual icTagTypeSignature GetType () const
virtual const icChar * GetClassName () const
virtual void Describe (std::string &sDescription)
virtual bool Read (icUInt32Number size, CIccIO *pIO)
virtual bool Write (CIccIO *pIO)
T & operator[] (icUInt32Number index)
icUInt32Number GetSize () const
Returns the size of the data array.
void SetSize (icUInt32Number nSize, bool bZeroNew=true)
template<>
void Describe (std::string &sDescription)
Public Member Functions inherited from CIccTag
CIccTag ()
virtual ~CIccTag ()
virtual bool IsMBBType ()
virtual IIccExtensionTag * GetExtension ()
virtual bool IsSupported ()
virtual icValidateStatus Validate (icTagSignature sig, std::string &sReport, const CIccProfile *pProfile=NULL) const
Protected Attributes
T * m_Num
icUInt32Number m_nSize
Additional Inherited Members
Static Public Member Functions inherited from CIccTag
static CIccTag * Create (icTagTypeSignature sig)
Public Attributes inherited from CIccTag
icUInt32Number m_nReserved
Detailed Description
template<class T, icTagTypeSignature Tsig>
class CIccTagNum< T, Tsig >
Class: CIccTagNum
Purpose: A template class for arrays of integers
Derived Tags: CIccTagUInt8, CIccTagUInt16, CIccTagUInt32 and CIccTagUInt64
Constructor & Destructor Documentation
template<class T , icTagTypeSignature Tsig> CIccTagNum< T, Tsig >::CIccTagNum (int nSize = 1)
Name: CIccTagNum::CIccTagNum
Purpose: Constructor
Args: nSize = number of data entries
template<class T , icTagTypeSignature Tsig> CIccTagNum< T, Tsig >::CIccTagNum (const CIccTagNum< T, Tsig > & ITNum)
Name: CIccTagNum::CIccTagNum
Purpose: Copy Constructor
Args: ITNum = The CIccTagNum object to be copied
References CIccTagNum< T, Tsig >::m_nSize, and CIccTagNum< T, Tsig >::m_Num.
template<class T , icTagTypeSignature Tsig> CIccTagNum< T, Tsig >::~CIccTagNum () virtual
Name: CIccTagNum::~CIccTagNum
Purpose: Destructor
Member Function Documentation
template<class T , icTagTypeSignature Tsig> void CIccTagNum< T, Tsig >::Describe (std::string & sDescription) virtual
Name: CIccTagNum::Describe
Purpose: Dump data associated with the tag to a string
Args: sDescription - string to concatenate tag dump to
Reimplemented from CIccTag.
template<> void CIccTagNum< icUInt64Number, icSigUInt64ArrayType >::Describe (std::string & sDescription) virtual
Function: Describe(sDescription) Each derived tag will implement it's own Describe() function.
Parameter(s): sDescription - A string to put the tag's description into.
Reimplemented from CIccTag.
template<class T , icTagTypeSignature Tsig> const icChar * CIccTagNum< T, Tsig >::GetClassName () const virtual
Name: CIccTagNum::GetClassName
Purpose: Returns the tag type class name
Reimplemented from CIccTag.
template<class T, icTagTypeSignature Tsig> icUInt32Number CIccTagNum< T, Tsig >::GetSize () const inline
Returns the size of the data array.
template<class T, icTagTypeSignature Tsig> virtual icTagTypeSignature CIccTagNum< T, Tsig >::GetType () const inline virtual
Function: GetType()
Purpose: Get Tag Type. Each derived tag will implement it's own GetType() function.
Reimplemented from CIccTag.
template<class T, icTagTypeSignature Tsig> virtual bool CIccTagNum< T, Tsig >::IsArrayType () inline virtual
Reimplemented from CIccTag.
template<class T, icTagTypeSignature Tsig> virtual CIccTag* CIccTagNum< T, Tsig >::NewCopy () const inline virtual
Function: NewCopy(sDescription) Each derived tag will implement it's own NewCopy() function.
Parameter(s): none
Returns a new CIccTag object that is a copy of this object.
Reimplemented from CIccTag.
template<class T , icTagTypeSignature Tsig> CIccTagNum< T, Tsig > & CIccTagNum< T, Tsig >::operator= (const CIccTagNum< T, Tsig > & NumTag)
Name: CIccTagNum::operator=
Purpose: Copy Operator
Args: ITNum = The CIccTagNum object to be copied
References CIccTagNum< T, Tsig >::m_nSize, and CIccTagNum< T, Tsig >::m_Num.
template<class T, icTagTypeSignature Tsig> T& CIccTagNum< T, Tsig >::operator[] (icUInt32Number index) inline
template<class T , icTagTypeSignature Tsig> bool CIccTagNum< T, Tsig >::Read (icUInt32Number size, CIccIO * pIO) virtual
Name: CIccTagNum::Read
Purpose: Read in the tag contents into a data block
Args: size - # of bytes in tag, pIO - IO object to read tag from
Return: true = successful, false = failure
Reimplemented from CIccTag.
References CIccIO::Read16(), CIccIO::Read32(), CIccIO::Read64(), and CIccIO::Read8().
template<class T , icTagTypeSignature Tsig> void CIccTagNum< T, Tsig >::SetSize (icUInt32Number nSize, bool bZeroNew = true)
Name: CIccTagNum::SetSize
Purpose: Sets the size of the data array.
Args: nSize - number of data entries, bZeroNew - flag to zero newly formed values
template<class T , icTagTypeSignature Tsig> bool CIccTagNum< T, Tsig >::Write (CIccIO * pIO) virtual
Name: CIccTagNum::Write
Purpose: Write the tag to a file
Args: pIO - The IO object to write tag to.
Return: true = succesful, false = failure
Reimplemented from CIccTag.
References CIccIO::Write32().
Member Data Documentation
template<class T, icTagTypeSignature Tsig> icUInt32Number CIccTagNum< T, Tsig >::m_nSize protected
Referenced by CIccTagNum< T, Tsig >::CIccTagNum(), and CIccTagNum< T, Tsig >::operator=().
template<class T, icTagTypeSignature Tsig> T* CIccTagNum< T, Tsig >::m_Num protected
Referenced by CIccTagNum< T, Tsig >::CIccTagNum(), and CIccTagNum< T, Tsig >::operator=().
The documentation for this class was generated from the following files:
IccTagBasic.h
IccTagBasic.cpp