CIccTagXYZ Class Reference
CIccTagXYZ Class Reference
#include <IccTagBasic.h>
Public Member Functions
CIccTagXYZ (int nSize=1)
CIccTagXYZ (const CIccTagXYZ &ITXYZ)
CIccTagXYZ & operator= (const CIccTagXYZ &XYZTag)
virtual CIccTag * NewCopy () const
virtual ~CIccTagXYZ ()
virtual bool IsArrayType ()
virtual icTagTypeSignature GetType () const
virtual const icChar * GetClassName () const
virtual void Describe (std::string &sDescription)
virtual bool Read (icUInt32Number size, CIccIO *pIO)
virtual bool Write (CIccIO *pIO)
icXYZNumber & operator[] (icUInt32Number index) const
icXYZNumber * GetXYZ (icUInt32Number index)
icUInt32Number GetSize () const
void SetSize (icUInt32Number nSize, bool bZeroNew=true)
virtual icValidateStatus Validate (icTagSignature sig, std::string &sReport, const CIccProfile *pProfile=NULL) const
Public Member Functions inherited from CIccTag
CIccTag ()
virtual ~CIccTag ()
virtual bool IsMBBType ()
virtual IIccExtensionTag * GetExtension ()
virtual bool IsSupported ()
Protected Attributes
icXYZNumber * m_XYZ
icUInt32Number m_nSize
Additional Inherited Members
Static Public Member Functions inherited from CIccTag
static CIccTag * Create (icTagTypeSignature sig)
Public Attributes inherited from CIccTag
icUInt32Number m_nReserved
Detailed Description
Class: CIccTagXYZ
Purpose: the XYZType tag - an array of XYZ values
Constructor & Destructor Documentation
CIccTagXYZ::CIccTagXYZ (int nSize = 1)
Name: CIccTagXYZ::CIccTagXYZ
Purpose: Constructor
Args: nSize = number of XYZ entries
CIccTagXYZ::CIccTagXYZ (const CIccTagXYZ & ITXYZ)
Name: CIccTagXYZ::CIccTagXYZ
Purpose: Copy Constructor
Args: ITXYZ = The CIccTagXYZ object to be copied
References m_nSize, and m_XYZ.
CIccTagXYZ::~CIccTagXYZ () virtual
Name: CIccTagXYZ::~CIccTagXYZ
Purpose: Destructor
Member Function Documentation
void CIccTagXYZ::Describe (std::string & sDescription) virtual
Name: CIccTagXYZ::Describe
Purpose: Dump data associated with the tag to a string
Args: sDescription - string to concatenate tag dump to
Reimplemented from CIccTag.
References icFtoD().
virtual const icChar* CIccTagXYZ::GetClassName () const inline virtual
Reimplemented from CIccTag.
icUInt32Number CIccTagXYZ::GetSize () const inline
virtual icTagTypeSignature CIccTagXYZ::GetType () const inline virtual
Function: GetType()
Purpose: Get Tag Type. Each derived tag will implement it's own GetType() function.
Reimplemented from CIccTag.
References icSigXYZType.
icXYZNumber* CIccTagXYZ::GetXYZ (icUInt32Number index) inline
virtual bool CIccTagXYZ::IsArrayType () inline virtual
Reimplemented from CIccTag.
virtual CIccTag* CIccTagXYZ::NewCopy () const inline virtual
Function: NewCopy(sDescription) Each derived tag will implement it's own NewCopy() function.
Parameter(s): none
Returns a new CIccTag object that is a copy of this object.
Reimplemented from CIccTag.
CIccTagXYZ & CIccTagXYZ::operator= (const CIccTagXYZ & XYZTag)
Name: CIccTagXYZ::operator=
Purpose: Copy Operator
Args: XYZTag = The CIccTagXYZ object to be copied
References m_nSize, and m_XYZ.
icXYZNumber& CIccTagXYZ::operator[] (icUInt32Number index) const inline
bool CIccTagXYZ::Read (icUInt32Number size, CIccIO * pIO) virtual
Name: CIccTagXYZ::Read
Purpose: Read in the tag contents into a data block
Args: size - # of bytes in tag, pIO - IO object to read tag from
Return: true = successful, false = failure
Reimplemented from CIccTag.
References CIccIO::Read32().
void CIccTagXYZ::SetSize (icUInt32Number nSize, bool bZeroNew = true)
Name: CIccTagXYZ::SetSize
Purpose: Sets the size of the XYZ array.
Args: nSize - number of XYZ entries, bZeroNew - flag to zero newly formed values
icValidateStatus CIccTagXYZ::Validate (icTagSignature sig, std::string & sReport, const CIccProfile * pProfile = NULL) const virtual
Name: CIccTagXYZ::Validate
Purpose: Check tag data validity.
Args: sig = signature of tag being validated, sReport = String to add report information to
Return: icValidateStatusOK if valid, or other error status.
Reimplemented from CIccTag.
References CIccInfo::CheckData(), CIccInfo::GetSigName(), icMaxStatus(), icValidateWarning, icValidateWarningMsg, and CIccTag::Validate().
bool CIccTagXYZ::Write (CIccIO * pIO) virtual
Name: CIccTagXYZ::Write
Purpose: Write the tag to a file
Args: pIO - The IO object to write tag to.
Return: true = succesful, false = failure
Reimplemented from CIccTag.
References CIccIO::Write32().
Member Data Documentation
icUInt32Number CIccTagXYZ::m_nSize protected
Referenced by CIccTagXYZ(), and operator=().
icXYZNumber* CIccTagXYZ::m_XYZ protected
Referenced by CIccTagXYZ(), and operator=().
The documentation for this class was generated from the following files:
IccTagBasic.h
IccTagBasic.cpp