CIccMpeCurveSet Class Reference
CIccMpeCurveSet Class Reference
#include <IccMpeBasic.h>
Public Member Functions
CIccMpeCurveSet (int nSize=0)
CIccMpeCurveSet (const CIccMpeCurveSet &curveSet)
CIccMpeCurveSet & operator= (const CIccMpeCurveSet &curveSet)
virtual CIccMultiProcessElement * NewCopy () const
virtual ~CIccMpeCurveSet ()
void SetSize (int nNewSize)
bool SetCurve (int nIndex, icCurveSetCurvePtr newCurve)
virtual icElemTypeSignature GetType () const
virtual const icChar * GetClassName () const
virtual void Describe (std::string &sDescription)
virtual bool Read (icUInt32Number size, CIccIO *pIO)
virtual bool Write (CIccIO *pIO)
virtual bool Begin (icElemInterp nInterp, CIccTagMultiProcessElement *pMPE)
virtual void Apply (CIccApplyMpe *pApply, icFloatNumber *dstPixel, const icFloatNumber *srcPixel) const
virtual icValidateStatus Validate (icTagSignature sig, std::string &sReport, const CIccTagMultiProcessElement *pMPE=NULL) const
Public Member Functions inherited from CIccMultiProcessElement
CIccMultiProcessElement ()
virtual ~CIccMultiProcessElement ()
virtual icUInt16Number NumInputChannels () const
virtual icUInt16Number NumOutputChannels () const
virtual bool IsSupported ()
virtual CIccApplyMpe * GetNewApply (CIccApplyTagMpe *pApplyTag)
virtual bool IsAcs ()
virtual icAcsSignature GetBAcsSig ()
virtual icAcsSignature GetEAcsSig ()
virtual IIccExtensionMpe * GetExtension ()
Protected Attributes
icCurveSetCurvePtr * m_curve
icPositionNumber * m_position
Protected Attributes inherited from CIccMultiProcessElement
icUInt16Number m_nInputChannels
icUInt16Number m_nOutputChannels
Additional Inherited Members
Static Public Member Functions inherited from CIccMultiProcessElement
static CIccMultiProcessElement * Create (icElemTypeSignature sig)
Public Attributes inherited from CIccMultiProcessElement
icUInt32Number m_nReserved
Detailed Description
Class: CIccMpeCurveSet
Purpose: The curve set process element
Constructor & Destructor Documentation
CIccMpeCurveSet::CIccMpeCurveSet (int nSize = 0)
Name: CIccMpeCurveSet::CIccMpeCurveSet
Purpose:
Args:
Return:
CIccMpeCurveSet::CIccMpeCurveSet (const CIccMpeCurveSet & curveSet)
Name: CIccMpeCurveSet::CIccMpeCurveSet
Purpose:
Args:
Return:
References m_curve, CIccMultiProcessElement::m_nInputChannels, CIccMultiProcessElement::m_nReserved, and CIccCurveSetCurve::NewCopy().
CIccMpeCurveSet::~CIccMpeCurveSet () virtual
Name: CIccMpeCurveSet::~CIccMpeCurveSet
Purpose:
Args:
Return:
Member Function Documentation
void CIccMpeCurveSet::Apply (CIccApplyMpe * pApply, icFloatNumber * pDestPixel, const icFloatNumber * pSrcPixel) const virtual
Name: CIccMpeCurveSet::Apply
Purpose:
Args:
Return:
Implements CIccMultiProcessElement.
bool CIccMpeCurveSet::Begin (icElemInterp nInterp, CIccTagMultiProcessElement * pMPE) virtual
Name: CIccMpeCurveSet::Begin
Purpose:
Args:
Return:
Implements CIccMultiProcessElement.
void CIccMpeCurveSet::Describe (std::string & sDescription) virtual
Name: CIccMpeCurveSet::Describe
Purpose:
Args:
Return:
Implements CIccMultiProcessElement.
virtual const icChar* CIccMpeCurveSet::GetClassName () const inline virtual
Implements CIccMultiProcessElement.
virtual icElemTypeSignature CIccMpeCurveSet::GetType () const inline virtual
Implements CIccMultiProcessElement.
References icSigCurveSetElemType.
virtual CIccMultiProcessElement* CIccMpeCurveSet::NewCopy () const inline virtual
Implements CIccMultiProcessElement.
CIccMpeCurveSet & CIccMpeCurveSet::operator= (const CIccMpeCurveSet & curveSet)
Name: &CIccMpeCurveSet::operator=
Purpose:
Args:
Return:
References m_curve, CIccMultiProcessElement::m_nInputChannels, and CIccCurveSetCurve::NewCopy().
bool CIccMpeCurveSet::Read (icUInt32Number size, CIccIO * pIO) virtual
Name: CIccMpeCurveSet::Read
Purpose:
Args:
Return:
Implements CIccMultiProcessElement.
References CIccCurveSetCurve::Create(), icSeekSet, CIccIO::Read16(), CIccIO::Read32(), CIccIO::Seek(), and CIccIO::Tell().
bool CIccMpeCurveSet::SetCurve (int nIndex, icCurveSetCurvePtr newCurve)
Name: CIccMpeCurveSet::SetCurve
Purpose:
Args:
Return:
void CIccMpeCurveSet::SetSize (int nNewSize)
Name: CIccMpeCurveSet::SetSize
Purpose:
Args:
Return:
icValidateStatus CIccMpeCurveSet::Validate (icTagSignature sig, std::string & sReport, const CIccTagMultiProcessElement * pMPE = NULL) const virtual
Name: CIccMpeCurveSet::Validate
Purpose:
Args:
Return:
Implements CIccMultiProcessElement.
References CIccInfo::GetSigName(), icMaxStatus(), icValidateCriticalError, icValidateCriticalErrorMsg, and CIccMultiProcessElement::Validate().
bool CIccMpeCurveSet::Write (CIccIO * pIO) virtual
Name: CIccMpeCurveSet::Write
Purpose:
Args:
Return:
Implements CIccMultiProcessElement.
References icSeekSet, icPositionNumber::offset, CIccIO::Seek(), icPositionNumber::size, CIccIO::Sync32(), CIccIO::Tell(), CIccIO::Write16(), and CIccIO::Write32().
Member Data Documentation
icCurveSetCurvePtr* CIccMpeCurveSet::m_curve protected
Referenced by CIccMpeCurveSet(), and operator=().
icPositionNumber* CIccMpeCurveSet::m_position protected
The documentation for this class was generated from the following files:
IccMpeBasic.h
IccMpeBasic.cpp