# - Try to find Sed
# Once done this will define
#
#  SED_FOUND - system has Sed
#  SED_EXECUTABLE - path of the sed executable
#  SED_VERSION - the version string, like "2.5.31"
#


FIND_PROGRAM(SED_EXECUTABLE NAMES sed sed.exe )

IF(SED_EXECUTABLE)
    SET(SED_FOUND TRUE)

    EXECUTE_PROCESS(COMMAND ${SED_EXECUTABLE} --version
        OUTPUT_VARIABLE _SED_VERSION
    )
    string (REGEX MATCH "[0-9]+\\.[0-9]+\\.[0-9]+" SED_VERSION "${_SED_VERSION}")
ENDIF(SED_EXECUTABLE)

IF(SED_FOUND)
  IF(NOT SED_FIND_QUIETLY)
    MESSAGE(STATUS "Found Sed: ${SED_EXECUTABLE}")
  ENDIF(NOT SED_FIND_QUIETLY)
ELSE(SED_FOUND)
  IF(SED_FIND_REQUIRED)
    MESSAGE(FATAL_ERROR "Could not find Sed")
  ENDIF(SED_FIND_REQUIRED)
ENDIF(SED_FOUND)
