#-*-cmake-*-
#
# Test for OpenEXR
#
# Once loaded this will define
#  OPENTIMELINEIO_FOUND        - system has OpenEXR
#  OPENTIMELINEIO_INCLUDE_DIR  - include directory for OpenEXR
#  OPENTIMELINEIO_LIBRARY_DIR  - library directory for OpenEXR
#  OPENTIMELINEIO_LIBRARIES    - libraries you need to link to
#

SET(OPENTIMELINEIO_FOUND "NO")

IF( OPENTIMELINEIO_LIBRARY_DIR )
  SET( SEARCH_DIRS "${OPENTIMELINEIO_LIBRARY_DIR}" )
ELSE( OPENTIMELINEIO_LIBRARY_DIR )
  SET( SEARCH_DIRS
    $ENV{OPENTIMELINEIO_ROOT}/lib/x${CMAKE_BUILD_ARCH}/Release
    $ENV{OPENTIMELINEIO_ROOT}/lib/Win32/Release
    $ENV{OPENTIMELINEIO_ROOT}/lib
    $ENV{OPENTIMELINEIO_ROOT}/lib/Release
    $ENV{OPENTIMELINEIO_ROOT}/lib/Debug
    $ENV{OPENTIMELINEIO_ROOT}/bin/x${CMAKE_BUILD_ARCH}/Release
    $ENV{OPENTIMELINEIO_ROOT}/bin/Win32/Release
    $ENV{OPENTIMELINEIO_ROOT}/bin/Release
    $ENV{OPENTIMELINEIO_ROOT}/bin/Debug
    /usr/local/lib${CMAKE_BUILD_ARCH}
    /usr/local/lib
    /usr/lib${CMAKE_BUILD_ARCH}
    /usr/lib
    )
ENDIF( OPENTIMELINEIO_LIBRARY_DIR )


FIND_LIBRARY( OTIME
  NAMES opentime
  PATHS ${SEARCH_DIRS}
  DOC   "OpenTimelineIO library (0.1 or later)"
  )

FIND_LIBRARY( OTIO
  NAMES opentimelineio
  PATHS ${SEARCH_DIRS}
  DOC   "OpenTimelineIO library (1.0 or later)"
  )

GET_FILENAME_COMPONENT(OPENTIMELINEIO_LIBRARY_DIR "${OTIO}" PATH)

FIND_PATH( OPENTIMELINEIO_INCLUDE_DIR timeline.h
  "$ENV{OPENTIMELINEIO_ROOT}/include/opentimelineio"
  ${CMAKE_PREFIX_PATH}/include/opentimelineio
  /usr/local/include/opentimelineio
  /usr/include/opentimelineio
  DOC   "OpenTimelineIO includes"
  )

FIND_PATH( OPENTIMELINEIO_ANY_DIR any/any.hpp
   PATHS
  "$ENV{OPENTIMELINEIO_ROOT}/include/opentimelineio/deps"
  "$ENV{OPENTIMELINEIO_ROOT}/deps"
  ${CMAKE_PREFIX_PATH}/include/opentimelineio/deps
  /usr/local/include/opentimelineio/deps
  /usr/include/opentimelineio/deps
  DOC   "OpenTimelineIO includes"
  )

SET( OPENTIMELINEIO_INCLUDE_DIR ${OPENTIMELINEIO_INCLUDE_DIR} ${OPENTIMELINEIO_ANY_DIR} )
SET( OPENTIMELINEIO_LIBRARIES ${OTIO} ${OTIME} )

IF(NOT OPENTIMELINEIO_FOUND)
  IF (OPENTIMELINEIO_INCLUDE_DIR)
    IF(OPENTIMELINEIO_LIBRARIES)
      SET(OPENTIMELINEIO_FOUND "YES")
      IF( NOT OPENTIMELINEIO_LIBRARY_DIR )
	GET_FILENAME_COMPONENT(OPENTIMELINEIO_LIBRARY_DIR "${IlmImf}" PATH)
      ENDIF( NOT OPENTIMELINEIO_LIBRARY_DIR )
    ENDIF(OPENTIMELINEIO_LIBRARIES)
  ENDIF(OPENTIMELINEIO_INCLUDE_DIR)
ENDIF(NOT OPENTIMELINEIO_FOUND)

IF(NOT OPENTIMELINEIO_FOUND)
  # make FIND_PACKAGE friendly
  IF(NOT OPENTIMELINEIO_FIND_QUIETLY)
    IF(OPENTIMELINEIO_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR
	      "OpenTimelineIO required, please specify its location with OPENTIMELINEIO_ROOT.")
    ELSE(OPENTIMELINEIO_FIND_REQUIRED)
      MESSAGE( STATUS "OpenTimelineIO was not found!!! " ${OPENTIMELINEIO_INCLUDE_DIR})
    ENDIF(OPENTIMELINEIO_FIND_REQUIRED)
  ENDIF(NOT OPENTIMELINEIO_FIND_QUIETLY)
ENDIF(NOT OPENTIMELINEIO_FOUND)
