#!/bin/bash

export ROOT=/D/code/applications/mrv
export DIST=/D/code/lib/vc14_Windows_32

export OPENEXR_ROOT=$DIST
export     CTL_ROOT=$DIST
export TINYXML2_ROOT=$DIST
export LibRaw_ROOT=$DIST
export OIIO_ROOT=$DIST
export GLEW_ROOT=$DIST
export OCIO_ROOT=$DIST
export GLUT_ROOT_PATH=$DIST

export BOOST_ROOT="$ROOT/dependencies/boost_1_69_0"

export FFMPEG_ROOT="$ROOT/win64_deps/ffmpeg-20190914-8efc9fc-win32-shared"
export FLTK_DIR="$ROOT/../fltk-win32"
export MAGICK_HOME="$ROOT/win64_deps/ImageMagick-Windows32"
export TCLAP_ROOT="$ROOT/dependencies/tclap-1.2.2"
export SampleICC_ROOT="$ROOT/win64_deps/SampleICC-1.6.10-vc14-win32"
export LIBINTL_ROOT="$ROOT/dependencies/libintl-win32/"
export LIBICONV="$ROOT/dependencies/gettext-iconv-win32"
