#!/bin/bash

export ROOT=/D/code/applications/mrv
export DIST=/D/code/lib/vc14_Windows_64

export ZLIB_ROOT=$DIST
export OPENEXR_ROOT=$DIST
export     CTL_ROOT=$DIST
export TINYXML2_ROOT=$DIST
export LibRaw_ROOT=$DIST
export OIIO_ROOT=$DIST
export GLEW_ROOT=$DIST

export BOOST_ROOT="$ROOT/dependencies/boost_1_60_0"

export FFMPEG_ROOT="$ROOT/win64_deps/ffmpeg-20190727-47b6ca0-win64-shared"
export OCIO_ROOT=$DIST
export  GLUT_ROOT_PATH=$DIST
export FLTK_DIR="$ROOT/../fltk-win64"
export MAGICK_HOME="$ROOT/win64_deps/ImageMagick-Windows64"
export TCLAP_ROOT="$ROOT/dependencies/tclap-1.2.2"
export SampleICC_ROOT="$ROOT/dependencies/SampleICC-1.6.10-win64-linux64"
export LIBINTL_ROOT="$ROOT/dependencies/libintl-win64/"
export LIBICONV="$ROOT/dependencies/gettext-iconv-win64"

export PATH=$DIST/bin:$PATH
