#!/bin/bash

echo "Sourcing vc14_win32_vars"
export ROOT=/E/code/applications/mrv
export DIST=/E/code/lib/win32
export SUPERBUILD=$PWD/install-Windows-6.3.9600-32

export ZLIB_ROOT=$SUPERBUILD
export OPENEXR_ROOT=$SUPERBUILD
export     CTL_ROOT=$SUPERBUILD
export TINYXML2_ROOT=$SUPERBUILD
export LibRaw_ROOT=$SUPERBUILD
export OIIO_ROOT=$SUPERBUILD
export OPENTIMELINEIO_ROOT=$SUPERBUILD
export GLEW_ROOT=$DIST
export OCIO_ROOT=$SUPERBUILD
export OpenColorIO_ROOT=$OCIO_ROOT
export PATH=$DIST/gettext/bin:$PATH

export BOOST_ROOT=$SUPERBUILD
export FFMPEG_ROOT="/D/abs/local32/bin-video/ffmpegSHARED"
export FLTK_DIR=$SUPERBUILD
export MAGICK_HOME="$ROOT/win64_deps/ImageMagick-Windows32"
export TCLAP_ROOT=$SUPERBUILD
export SampleICC_ROOT="$ROOT/win64_deps/SampleICC-1.6.10-vc14-win32"
export R3DSDK_ROOT="$ROOT/../R3DSDKv8_1_0"
export LIBINTL_ROOT="$ROOT/dependencies/libintl-win32/"
export LIBICONV="$ROOT/dependencies/gettext-iconv-win32"

export PATH=$SUPERBUILD/bin:$PATH
