#!/bin/bash

export ROOT=/D/code/applications/mrViewer
export DIST=/D/code/lib/vc14_Windows_32

export OPENEXR_ROOT=$DIST
export     CTL_ROOT=$DIST
export TINYXML2_ROOT=$DIST
export LibRaw_ROOT=$DIST
export OIIO_ROOT=$DIST

export BOOST_ROOT="$ROOT/win64_deps/boost_1_60_0"

#export FFMPEG_ROOT="$ROOT/dependencies/ffmpeg-20170404-1229007-win64-shared"
#export FFMPEG_ROOT="$ROOT/dependencies/ffmpeg-20170711-0780ad9-win64-shared"
export FFMPEG_ROOT="$ROOT/dependencies/ffmpeg-3.4-win32-shared"
export OCIO_ROOT=$DIST
export  GLUT_ROOT_PATH=$DIST
export FLTK2_DIR="$ROOT/win64_deps/fltk-2.0-vc14-win32"
export MAGICK_HOME="$ROOT/win64_deps/ImageMagick-7.0.4-10-win32"
export GLEW_ROOT="$ROOT/dependencies/glew-1.11.0"
export TCLAP_ROOT="$ROOT/dependencies/tclap-1.2.1"
export SampleICC_ROOT="$ROOT/win64_deps/SampleICC-1.6.10-vc14-win32"
export LIBINTL_ROOT="$ROOT/dependencies/libintl-win32/"
export LIBICONV="$ROOT/dependencies/gettext-iconv-win32"
