#!/bin/bash

#export  BOOST_ROOT="C:/mrViewer_libs/lib/boost_1_47_0"
export BOOST_ROOT="F:/code/lib/Windows-32/boost_1_51_0"
export OPENEXR_ROOT="C:/mrViewer_libs/lib/Deploy"
export     CTL_ROOT="C:/mrViewer_libs/lib/Deploy"

export FFMPEG_ROOT=F:/code/lib/ffmpeg-20140221-git-76dd01e-win32-shared/

export  GLUT_ROOT_PATH="F:/code/lib/glut/"
export   FLTK2_DIR="F:/code/lib/fltk-2.0-win32"
export MAGICK_HOME="F:/code/lib/ImageMagick-6.7.4"
export GLEW_ROOT="C:/mrViewer_libs/lib/glew-1.7.0"
export POSTGRESQL_ROOT="C:/Program Files (x86)/PostgreSQL/9.1"
export TCLAP_ROOT="C:/mrViewer_libs/lib/tclap-1.2.0"
export SampleICC_ROOT="C:/mrViewer_libs/lib/SampleICC-1.6.5"
export LIBINTL_ROOT="C:/Program Files (x86)/GnuWin32/lib"
