#!/bin/bash

export  BOOST_ROOT=`cd "$PROGRAMFILES/boost/boost_1_34_1" && pwd`
export OPENEXR_ROOT="/z/code/PD/libraries/Deploy/win32/openexr-1.6.1/vc7"
export     CTL_ROOT="/z/code/PD/libraries/Deploy/win32/openexr-1.6.1/vc7"
export  FFMPEG_ROOT="/usr/local/"
export   FLTK2_DIR="Z:/code/PD/libraries/fltk2-trunk"
export MAGICK_HOME="/c/MyProjects/eval/ImageMagick-6.2.9"
export POSTGRESQL_ROOT="/c/MyProjects/eval/postgresql-8.1.5/src"
export TCLAP_ROOT="/z/code/PD/libraries/tclap-1.1.0"
export AO_LOCATION="/usr/local/"
export GLUT_ROOT_PATH="$PROGRAMFILES/Microsoft Visual Studio .NET 2003/Vc7/PlatformSDK/"
export SampleICC_ROOT="/z/code/PD/libraries/SampleICC-1.3.2"
