#!/bin/bash

export ROOT="D:/code/applications/mrViewer"
export DIST="D:/code/lib/Windows_64_debug"

export BOOST_ROOT="$ROOT/dependencies/boost_1_60_0"
export OPENEXR_ROOT=$DIST
export     CTL_ROOT=$DIST
export TINYXML2_ROOT=$DIST

export FFMPEG_ROOT="$ROOT/dependencies/ffmpeg-20170404-1229007-win64-shared"

export  GLUT_ROOT_PATH=$DIST
export FLTK2_DIR="$ROOT/dependencies/fltk-2.0-win64-debug"
export MAGICK_HOME="$ROOT/dependencies/ImageMagick-7.0.4-9-win64"
export GLEW_ROOT="$ROOT/dependencies/glew-1.11.0"
export TCLAP_ROOT="$ROOT/dependencies/tclap-1.2.1"
export SampleICC_ROOT="$ROOT/dependencies/SampleICC-1.6.10-win64-linux64"
export LIBINTL_ROOT="$ROOT/dependencies/libintl-win64/"
