#!/bin/bash

export BOOST_ROOT="F:/code/lib/Windows_64/boost_1_53_0"
export OPENEXR_ROOT="F:/code/lib/Windows_64"
export     CTL_ROOT="F:/code/lib/Windows_64"
export TINYXML2_ROOT="F:/code/lib/Windows_64"

#export FFMPEG_ROOT=F:/code/lib/ffmpeg-20150913-git-d13a2df-win64-shared
export FFMPEG_ROOT=F:/code/lib/ffmpeg-20151015-git-0418541-win64-shared/

export  GLUT_ROOT_PATH="F:/code/lib/freeglut/"
export FLTK2_DIR="F:/code/lib/fltk-2.0-win64"
export MAGICK_HOME="F:/code/lib/ImageMagick-6.8.9-win64"
export GLEW_ROOT="F:/code/lib/x64/glew-1.9.0"
export POSTGRESQL_ROOT="C:/Program Files/PostgreSQL/9.1"
export TCLAP_ROOT="F:/code/lib/tclap-1.2.0"
export SampleICC_ROOT="F:/code/lib/SampleICC-1.6.6"
export LIBINTL_ROOT="F:/code/lib/libintl-win64/"
