#!/bin/bash

export BOOST_ROOT="F:/code/lib/Windows-64/boost_1_51_0"
export OPENEXR_ROOT="F:/code/lib/Deploy"
export     CTL_ROOT="F:/code/lib/Deploy"

export FFMPEG_ROOT="F:/code/lib/ffmpeg-git-cv3591e-64bits" #
#export FFMPEG_ROOT="F:/code/lib/ffmpeg-1.0.1-win64-dev"

export  GLUT_ROOT_PATH="F:/code/lib/freeglut/"
export   FLTK2_DIR="F:/code/lib/Deploy"
export MAGICK_HOME="F:/code/lib/ImageMagick-6.7.4"
export GLEW_ROOT="F:/code/lib/x64/glew-1.7.0"
export POSTGRESQL_ROOT="C:/Program Files/PostgreSQL/9.1"
export TCLAP_ROOT="C:/mrViewer_libs/lib/tclap-1.2.0"
export SampleICC_ROOT="F:/code/lib/SampleICC-1.6.6"
export LIBINTL_ROOT="F:/soft/libintl/lib"
