IccProfile.h File Reference
IccProfile.h File Reference
#include "IccDefs.h"
#include <list>
#include <string>
Classes
struct IccTagEntry
struct IccTagPtr
class CIccProfile
Typedefs
typedef std::list< IccTagEntry > TagEntryList
typedef std::list< IccTagPtr > TagPtrList
Enumerations
enum icProfileIDSaveMethod { icVersionBasedID, icAlwaysWriteID, icNeverWriteID }
Functions
CIccProfile ICCPROFLIB_API * ReadIccProfile (const icChar *szFilename)
CIccProfile ICCPROFLIB_API * ReadIccProfile (const icUInt8Number *pMem, icUInt32Number nSize)
CIccProfile ICCPROFLIB_API * OpenIccProfile (const icChar *szFilename)
CIccProfile ICCPROFLIB_API * OpenIccProfile (const icUInt8Number *pMem, icUInt32Number nSize)
CIccProfile ICCPROFLIB_API * ValidateIccProfile (CIccIO *pIO, std::string &sReport, icValidateStatus &nStatus)
CIccProfile ICCPROFLIB_API * ValidateIccProfile (const icChar *szFilename, std::string &sReport, icValidateStatus &nStatus)
bool ICCPROFLIB_API SaveIccProfile (const icChar *szFilename, CIccProfile *pIcc, icProfileIDSaveMethod nWriteId=icVersionBasedID)
void ICCPROFLIB_API CalcProfileID (CIccIO *pIO, icProfileID *profileID)
bool ICCPROFLIB_API CalcProfileID (const icChar *szFilename, icProfileID *profileID)
Variables
class ICCPROFLIB_API CIccTag
class ICCPROFLIB_API CIccIO
class ICCPROFLIB_API CIccMemIO
Detailed Description
File: IccProfile.h
Contains: Header for implementation of the CIccProfile class.
Version: V1
Copyright: © see ICC Software License
Typedef Documentation
typedef std::list<IccTagEntry> TagEntryList
Type: List
Purpose: List of all the tag entries.
typedef std::list<IccTagPtr> TagPtrList
Type: List
Purpose: List of pointers to the tags.
Enumeration Type Documentation
enum icProfileIDSaveMethod
Enumerator
icVersionBasedID
icAlwaysWriteID
icNeverWriteID
Function Documentation
void ICCPROFLIB_API CalcProfileID (CIccIO * pIO, icProfileID * pProfileID)
Name: CalcProfileID
Purpose: Calculate the Profile ID using MD5 Fingerprinting method.
Args: pIO = The CIccIO object, pProfileID = array where the profileID will be stored
References CIccIO::GetLength(), icMD5Final(), icMD5Init(), icMD5Update(), icSeekSet, icProfileID::ID8, CIccIO::Read8(), CIccIO::Seek(), and CIccIO::Tell().
Referenced by CalcProfileID(), CIccProfile::ReadValidate(), and CIccProfile::Write().
bool ICCPROFLIB_API CalcProfileID (const icChar * szFilename, icProfileID * pProfileID)
Name: CalcProfileID
Purpose: Calculate the Profile ID using MD5 Fingerprinting method.
Args: szFileName = name of the file whose profile ID has to be calculated, pProfileID = array where the profileID will be stored
References CalcProfileID(), and CIccFileIO::Open().
CIccProfile ICCPROFLIB_API* OpenIccProfile (const icChar * szFilename)
Name: OpenIccProfile
Purpose: Open an ICC profile file. This will only read the profile header and tag directory. Loading of actual tags will be deferred until the tags are actually referenced by FindTag().
Args: szFilename - zero terminated string with filename of ICC profile to read
Return: Pointer to icc profile object, or NULL on failure
References CIccProfile::Attach(), CIccProfile, and CIccFileIO::Open().
Referenced by CIccCmm::AddXform(), and CIccNamedColorCmm::AddXform().
CIccProfile ICCPROFLIB_API* OpenIccProfile (const icUInt8Number * pMem, icUInt32Number nSize)
Name: OpenIccProfile
Purpose: Open an ICC profile file. This will only read the profile header and tag directory. Loading of actual tags will be deferred until the tags are actually referenced by FindTag().
Args: pMem = pointer to memory containing profile data nSize = size of memory related to profile
Return: Pointer to icc profile object, or NULL on failure
References CIccProfile::Attach(), CIccMemIO::Attach(), CIccMemIO, and CIccProfile.
CIccProfile ICCPROFLIB_API* ReadIccProfile (const icChar * szFilename)
Name: ReadIccProfile
Purpose: Read an ICC profile file.
Args: szFilename - zero terminated string with filename of ICC profile to read
Return: Pointer to icc profile object, or NULL on failure
References CIccProfile, CIccFileIO::Open(), and CIccProfile::Read().
Referenced by CIccEvalCompare::EvaluateProfile(), and CIccPRMG::EvaluateProfile().
CIccProfile ICCPROFLIB_API* ReadIccProfile (const icUInt8Number * pMem, icUInt32Number nSize)
Name: ReadIccProfile
Purpose: Read an ICC profile file.
Args: pMem = pointer to memory containing profile data nSize = size of memory related to profile
Return: Pointer to icc profile object, or NULL on failure
References CIccMemIO::Attach(), CIccMemIO, CIccProfile, and CIccProfile::Read().
bool ICCPROFLIB_API SaveIccProfile (const icChar * szFilename, CIccProfile * pIcc, icProfileIDSaveMethod nWriteId)
Name: SaveIccProfile
Purpose: Save an ICC profile file.
Args: szFilename - zero terminated string with filename of ICC profile to create
Return: true = success, false = failure
References CIccFileIO::Open(), and CIccProfile::Write().
CIccProfile ICCPROFLIB_API* ValidateIccProfile (CIccIO * pIO, std::string & sReport, icValidateStatus & nStatus)
Name: ValidateIccProfile
Purpose: Open an ICC profile file. This will only read the profile header and tag directory. Loading of actual tags will be deferred until the tags are actually referenced by FindTag().
Args: pIO - Handle to IO access object (Not ValidateIccProfile assumes ownership of this object) sReport - std::string to put report into nStatus - return status value
Return: Pointer to icc profile object, or NULL on failure
References CIccProfile, icValidateCriticalError, icValidateCriticalErrorMsg, CIccProfile::ReadValidate(), and CIccProfile::Validate().
CIccProfile ICCPROFLIB_API* ValidateIccProfile (const icChar * szFilename, std::string & sReport, icValidateStatus & nStatus)
Name: ValidateIccProfile
Purpose: Open an ICC profile file. This will only read the profile header and tag directory. Loading of actual tags will be deferred until the tags are actually referenced by FindTag().
Args: szFilename - zero terminated string with filename of ICC profile to read sReport - std::string to put report into nStatus - return status value
Return: Pointer to icc profile object, or NULL on failure
References CIccProfile, icValidateCriticalError, icValidateCriticalErrorMsg, CIccFileIO::Open(), CIccProfile::ReadValidate(), and CIccProfile::Validate().
Variable Documentation
class ICCPROFLIB_API CIccIO
class ICCPROFLIB_API CIccMemIO
Referenced by CIccCmm::AddXform(), CIccProfile::GetTagIO(), OpenIccProfile(), and ReadIccProfile().
class ICCPROFLIB_API CIccTag
Referenced by CIccTag::NewCopy().