IccUtil.cpp File Reference
IccUtil.cpp File Reference
#include "IccIO.h"
#include "IccUtil.h"
#include "IccTagFactory.h"
#include "IccConvertUTF.h"
#include <stdlib.h>
#include <memory.h>
#include <ctype.h>
#include <math.h>
#include <string.h>
#include <time.h>
Macros
#define PI 3.1415926535897932384626433832795
#define DUMPBYTESPERLINE 16
Functions
double icRoundOffset (double v)
icValidateStatus icMaxStatus (icValidateStatus s1, icValidateStatus s2)
bool icIsSpaceCLR (icColorSpaceSignature sig)
void icColorIndexName (icChar *szName, icColorSpaceSignature csSig, int nIndex, int nColors, const icChar *szUnknown)
void icColorValue (icChar *szValue, icFloatNumber nValue, icColorSpaceSignature csSig, int nIndex, bool bUseLegacy)
bool icMatrixInvert3x3 (icFloatNumber *M)
void icMatrixMultiply3x3 (icFloatNumber *result, const icFloatNumber *l, const icFloatNumber *r)
void icVectorApplyMatrix3x3 (icFloatNumber *result, const icFloatNumber *m, const icFloatNumber *v)
icFloatNumber icDeltaE (icFloatNumber *lab1, icFloatNumber *lab2)
icS15Fixed16Number icDtoF (icFloatNumber num)
icFloatNumber icFtoD (icS15Fixed16Number num)
icU16Fixed16Number icDtoUF (icFloatNumber num)
icFloatNumber icUFtoD (icU16Fixed16Number num)
icU1Fixed15Number icDtoUSF (icFloatNumber num)
icFloatNumber icUSFtoD (icU1Fixed15Number num)
icU8Fixed8Number icDtoUCF (icFloatNumber num)
icFloatNumber icUCFtoD (icU8Fixed8Number num)
icUInt8Number icFtoU8 (icFloatNumber num)
icFloatNumber icU8toF (icUInt8Number num)
icUInt16Number icFtoU16 (icFloatNumber num)
icFloatNumber icU16toF (icUInt16Number num)
icUInt8Number icABtoU8 (icFloatNumber num)
icFloatNumber icU8toAB (icUInt8Number num)
void icNormXyz (icFloatNumber *XYZ, icFloatNumber *WhiteXYZ)
void icDeNormXyz (icFloatNumber *XYZ, icFloatNumber *WhiteXYZ)
void icLabtoXYZ (icFloatNumber *XYZ, icFloatNumber *Lab, icFloatNumber *WhiteXYZ)
void icXYZtoLab (icFloatNumber *Lab, icFloatNumber *XYZ, icFloatNumber *WhiteXYZ)
void icLch2Lab (icFloatNumber *Lab, icFloatNumber *Lch)
void icLab2Lch (icFloatNumber *Lch, icFloatNumber *Lab)
icFloatNumber icMin (icFloatNumber v1, icFloatNumber v2)
icFloatNumber icMax (icFloatNumber v1, icFloatNumber v2)
icUInt32Number icIntMin (icUInt32Number v1, icUInt32Number v2)
icUInt32Number icIntMax (icUInt32Number v1, icUInt32Number v2)
void icLabFromPcs (icFloatNumber *Lab)
Here are some conversion routines to convert to regular Lab encoding.
void icLabToPcs (icFloatNumber *Lab)
void icXyzFromPcs (icFloatNumber *XYZ)
Here are some conversion routines to convert to regular XYZ encoding.
void icXyzToPcs (icFloatNumber *XYZ)
void icMemDump (std::string &sDump, void *pBuf, icUInt32Number nNum)
void icMatrixDump (std::string &sDump, icS15Fixed16Number *pMatrix)
const icChar * icGetSig (icChar *pBuf, icUInt32Number nSig, bool bGetHexVal)
const icChar * icGetSigStr (icChar *pBuf, icUInt32Number nSig)
icUInt32Number icGetSigVal (const icChar *pBuf)
icUInt32Number icGetSpaceSamples (icColorSpaceSignature sig)
const char * icUtf16ToUtf8 (std::string &buf, const icUInt16Number *szSrc, int sizeSrc)
const unsigned short * icUtf8ToUtf16 (CIccUTF16String &buf, const char *szSrc, int sizeSrc)
Variables
const char * icValidateWarningMsg = "Warning! - "
const char * icValidateNonCompliantMsg = "NonCompliant! - "
const char * icValidateCriticalErrorMsg = "Error! - "
icFloatNumber icD50XYZ [3] = { 0.9642f, 1.0000f, 0.8249f }
icFloatNumber icD50XYZxx [3] = { 96.42f, 100.00f, 82.49f }
Macro Definition Documentation
#define DUMPBYTESPERLINE 16
Referenced by icMemDump().
#define PI 3.1415926535897932384626433832795
Referenced by icLab2Lch(), and icLch2Lab().
Function Documentation
icUInt8Number icABtoU8 (icFloatNumber num)
Referenced by CIccCmm::FromInternalEncoding().
void icColorIndexName (icChar * szName, icColorSpaceSignature csSig, int nIndex, int nColors, const icChar * szUnknown)
References icSigUnknownData.
Referenced by CIccMBB::Describe(), CIccTagNamedColor2::Describe(), and CIccCLUT::DumpLut().
void icColorValue (icChar * szValue, icFloatNumber nValue, icColorSpaceSignature csSig, int nIndex, bool bUseLegacy)
References icSigLabData, and icSigUnknownData.
Referenced by CIccTagCurve::Describe(), CIccTagNamedColor2::Describe(), CIccTagCurve::DumpLut(), CIccCLUT::DumpLut(), and CIccCLUT::Iterate().
icFloatNumber icDeltaE (icFloatNumber * lab1, icFloatNumber * lab2)
Referenced by CIccPRMG::EvaluateProfile(), and CIccTagNamedColor2::FindCachedPCSColor().
void icDeNormXyz (icFloatNumber * XYZ, icFloatNumber * WhiteXYZ)
References icD50XYZ.
icS15Fixed16Number icDtoF (icFloatNumber num)
References icRoundOffset().
Referenced by CIccTagLut16::CIccTagLut16(), CIccTagLut8::CIccTagLut8(), CIccProfile::InitHeader(), CIccTagLut8::SetColorSpaces(), CIccTagLut16::SetColorSpaces(), CIccTagParametricCurve::Write(), CIccTagLutAtoB::Write(), CIccTagLut8::Write(), and CIccTagLut16::Write().
icU8Fixed8Number icDtoUCF (icFloatNumber num)
References icRoundOffset().
icU16Fixed16Number icDtoUF (icFloatNumber num)
References icRoundOffset().
Referenced by CIccTagChromaticity::Validate().
icU1Fixed15Number icDtoUSF (icFloatNumber num)
References icRoundOffset().
Referenced by CIccCmm::FromInternalEncoding().
icFloatNumber icFtoD (icS15Fixed16Number num)
Referenced by CIccXformMatrixTRC::Begin(), CIccProfile::CheckHeader(), CIccTagXYZ::Describe(), CIccTagFixedNum< T, Tsig >::Describe(), CIccTagMeasurement::Describe(), CIccTagViewingConditions::Describe(), CIccResponseCurveStruct::Describe(), icMatrixDump(), CIccTagParametricCurve::Read(), CIccTagLutAtoB::Read(), CIccTagLut8::SetColorSpaces(), and CIccTagLut16::SetColorSpaces().
icUInt16Number icFtoU16 (icFloatNumber num)
References icRoundOffset().
Referenced by CIccCmm::FromInternalEncoding().
icUInt8Number icFtoU8 (icFloatNumber num)
References icRoundOffset().
Referenced by CIccCmm::FromInternalEncoding().
const icChar* icGetSig (icChar * pBuf, icUInt32Number nSig, bool bGetHexVal)
Referenced by CIccMpeAcs::Describe(), CIccMpeUnknown::Describe(), CIccTagProfileSeqDesc::Describe(), CIccInfo::GetUnknownName(), and CIccMpeUnknown::Validate().
const icChar* icGetSigStr (icChar * pBuf, icUInt32Number nSig)
icUInt32Number icGetSigVal (const icChar * pBuf)
icUInt32Number icGetSpaceSamples (icColorSpaceSignature sig)
References icSig10colorData, icSig11colorData, icSig12colorData, icSig13colorData, icSig14colorData, icSig15colorData, icSig2colorData, icSig3colorData, icSig4colorData, icSig5colorData, icSig6colorData, icSig7colorData, icSig8colorData, icSig9colorData, icSigCmyData, icSigCmykData, icSigDevLabData, icSigDevXYZData, icSigGamutData, icSigGrayData, icSigHlsData, icSigHsvData, icSigLabData, icSigLuvData, icSigNamedData, icSigRgbData, icSigXYZData, icSigYCbCrData, and icSigYxyData.
Referenced by CIccEvalCompare::EvaluateProfile(), CIccCmm::FromInternalEncoding(), CIccCmm::GetDestSamples(), CIccCmm::GetSourceSamples(), CIccCmm::ToInternalEncoding(), CIccMBB::Validate(), CIccTagNamedColor2::Validate(), CIccTagLutAtoB::Validate(), CIccTagLutBtoA::Validate(), CIccTagLut8::Validate(), CIccTagLut16::Validate(), CIccTagColorantOrder::Validate(), CIccTagColorantTable::Validate(), and CIccTagResponseCurveSet16::Validate().
icUInt32Number icIntMax (icUInt32Number v1, icUInt32Number v2)
icUInt32Number icIntMin (icUInt32Number v1, icUInt32Number v2)
bool icIsSpaceCLR (icColorSpaceSignature sig)
References icSig10colorData, icSig11colorData, icSig12colorData, icSig13colorData, icSig14colorData, icSig15colorData, icSig2colorData, icSig3colorData, icSig4colorData, icSig5colorData, icSig6colorData, icSig7colorData, icSig8colorData, and icSig9colorData.
Referenced by CIccProfile::CheckRequiredTags(), CIccCmm::FromInternalEncoding(), and CIccCmm::ToInternalEncoding().
void icLab2Lch (icFloatNumber * Lch, icFloatNumber * Lab)
References PI.
Referenced by CIccPRMG::InGamut().
void icLabFromPcs (icFloatNumber * Lab)
Here are some conversion routines to convert to regular Lab encoding.
Floating point encoding of Lab in PCS is in range 0.0 to 1.0
Referenced by CIccXformMpe::Apply(), CIccTagColorantTable::Describe(), CIccEvalCompare::EvaluateProfile(), CIccPRMG::EvaluateProfile(), CIccTagNamedColor2::FindCachedPCSColor(), CIccCmm::FromInternalEncoding(), CIccTagNamedColor2::InitFindCachedPCSColor(), and CIccPCS::LabToXyz().
void icLabToPcs (icFloatNumber * Lab)
Referenced by CIccXformMpe::Apply(), CIccCmm::ToInternalEncoding(), and CIccPCS::XyzToLab().
void icLabtoXYZ (icFloatNumber * XYZ, icFloatNumber * Lab, icFloatNumber * WhiteXYZ)
References icD50XYZ.
Referenced by CIccPCS::LabToXyz().
void icLch2Lab (icFloatNumber * Lab, icFloatNumber * Lch)
References PI.
void icMatrixDump (std::string & sDump, icS15Fixed16Number * pMatrix)
References icFtoD().
Referenced by CIccTagFixedNum< T, Tsig >::Describe().
bool icMatrixInvert3x3 (icFloatNumber * M)
Name: icMatrixInvert3x3
Purpose: Inversion of a 3x3 matrix using the Adjoint Cofactor and the determinant of the 3x3 matrix.
Note: Matrix index positions: 0 1 2 3 4 5 6 7 8
Args: M = matrix to invert.
Return: true = matrix is invertible and stored back into M, false = matrix is not invertible.
Referenced by CIccXformMatrixTRC::Begin().
void icMatrixMultiply3x3 (icFloatNumber * result, const icFloatNumber * l, const icFloatNumber * r)
Name: icMatrixMultiply3x3
Purpose: Multiply two 3x3 matricies resulting in a 3x3 matrix.
Note: Matrix index positions: 0 1 2 3 4 5 6 7 8
Args: result = matrix to recieve result. l = left matrix to multiply (matrix multiplication is order dependent) r = right matrix to multiply (matrix multiplicaiton is order dependent)
icFloatNumber icMax (icFloatNumber v1, icFloatNumber v2)
icValidateStatus icMaxStatus (icValidateStatus s1, icValidateStatus s2)
Name: icMaxStatus
Purpose: return worst status
Args: s1, s2
Return:
Referenced by CIccInfo::CheckData(), CIccProfile::CheckHeader(), CIccProfile::CheckRequiredTags(), CIccProfile::CheckTagTypes(), CIccProfile::ReadValidate(), CIccTagProfileSequenceId::Validate(), CIccTagCurve::Validate(), CIccProfile::Validate(), CIccTagDict::Validate(), CIccSampledCurveSegment::Validate(), CIccTagParametricCurve::Validate(), CIccTagText::Validate(), CIccSegmentedCurve::Validate(), CIccTagTextDescription::Validate(), CIccCLUT::Validate(), CIccMpeCurveSet::Validate(), CIccTagSignature::Validate(), CIccTagMultiProcessElement::Validate(), CIccMBB::Validate(), CIccTagNamedColor2::Validate(), CIccTagLutAtoB::Validate(), CIccTagLutBtoA::Validate(), CIccTagXYZ::Validate(), CIccTagLut8::Validate(), CIccTagLut16::Validate(), CIccTagChromaticity::Validate(), CIccTagMeasurement::Validate(), CIccTagMultiLocalizedUnicode::Validate(), CIccTagData::Validate(), CIccTagDateTime::Validate(), CIccTagColorantOrder::Validate(), CIccTagColorantTable::Validate(), CIccTagViewingConditions::Validate(), CIccTagProfileSeqDesc::Validate(), CIccResponseCurveStruct::Validate(), and CIccTagResponseCurveSet16::Validate().
void icMemDump (std::string & sDump, void * pBuf, icUInt32Number nNum)
References DUMPBYTESPERLINE.
Referenced by CIccMpeAcs::Describe(), CIccTagUnknown::Describe(), and CIccMpeUnknown::Describe().
icFloatNumber icMin (icFloatNumber v1, icFloatNumber v2)
Referenced by CIccEvalCompare::EvaluateProfile().
void icNormXyz (icFloatNumber * XYZ, icFloatNumber * WhiteXYZ)
References icD50XYZ.
double icRoundOffset (double v)
Name: icRoundOffset
Purpose: Adds offset to floating point value for purposes of rounding by casting to and integer based value
Args: v - value to offset
Return: v with offset added - suitable for casting to some form of integer
Referenced by icDtoF(), icDtoUCF(), icDtoUF(), icDtoUSF(), icFtoU16(), and icFtoU8().
icFloatNumber icU16toF (icUInt16Number num)
Referenced by CIccTagColorantTable::Describe(), and CIccCmm::ToInternalEncoding().
icFloatNumber icU8toAB (icUInt8Number num)
Referenced by CIccCmm::ToInternalEncoding().
icFloatNumber icU8toF (icUInt8Number num)
Referenced by CIccCmm::ToInternalEncoding().
icFloatNumber icUCFtoD (icU8Fixed8Number num)
icFloatNumber icUFtoD (icU16Fixed16Number num)
Referenced by CIccTagChromaticity::Describe(), and CIccTagFixedNum< T, Tsig >::Describe().
icFloatNumber icUSFtoD (icU1Fixed15Number num)
Referenced by CIccTagColorantTable::Describe(), and CIccCmm::ToInternalEncoding().
const char* icUtf16ToUtf8 (std::string & buf, const icUInt16Number * szSrc, int sizeSrc)
References icConvertUTF16toUTF8(), lenientConversion, and CIccUTF16String::WStrlen().
Referenced by CIccUTF16String::ToUtf8().
const unsigned short* icUtf8ToUtf16 (CIccUTF16String & buf, const char * szSrc, int sizeSrc)
References CIccUTF16String::c_str(), and CIccUTF16String::FromUtf8().
void icVectorApplyMatrix3x3 (icFloatNumber * result, const icFloatNumber * m, const icFloatNumber * v)
Name: icVectorApplyMatrix3x3
Purpose: Applies a 3x3 matrix to a 3 element column vector.
Note: Matrix index positions: 0 1 2 3 4 5 6 7 8
Note: result = m x v
Args: result = vector to receive result. m = matrix to multiply v = vector to apply matrix to
void icXyzFromPcs (icFloatNumber * XYZ)
Here are some conversion routines to convert to regular XYZ encoding.
Floating point encoding of XYZ in PCS is in range 0.0 to 1.0 (Note: X=1.0 is encoded as about 0.5)
Referenced by CIccXformMpe::Apply(), CIccTagNamedColor2::FindCachedPCSColor(), CIccCmm::FromInternalEncoding(), CIccTagNamedColor2::InitFindCachedPCSColor(), and CIccPCS::XyzToLab().
void icXYZtoLab (icFloatNumber * Lab, icFloatNumber * XYZ, icFloatNumber * WhiteXYZ)
References icD50XYZ.
Referenced by CIccTagNamedColor2::FindCachedPCSColor(), CIccTagNamedColor2::InitFindCachedPCSColor(), and CIccPCS::XyzToLab().
void icXyzToPcs (icFloatNumber * XYZ)
Referenced by CIccXformMonochrome::Apply(), CIccXformMpe::Apply(), CIccApplyBPC::CalcFactors(), CIccPCS::LabToXyz(), and CIccCmm::ToInternalEncoding().
Variable Documentation
icFloatNumber icD50XYZ[3] = { 0.9642f, 1.0000f, 0.8249f }
Referenced by icDeNormXyz(), icLabtoXYZ(), icNormXyz(), and icXYZtoLab().
icFloatNumber icD50XYZxx[3] = { 96.42f, 100.00f, 82.49f }
const char* icValidateCriticalErrorMsg = "Error! - "
Referenced by CIccProfile::CheckHeader(), CIccProfile::CheckRequiredTags(), CIccProfile::ReadValidate(), CIccFormulaCurveSegment::Validate(), CIccSampledCurveSegment::Validate(), CIccTagParametricCurve::Validate(), CIccMpeUnknown::Validate(), CIccSegmentedCurve::Validate(), CIccCLUT::Validate(), CIccMpeCurveSet::Validate(), CIccMpeMatrix::Validate(), CIccTagMultiProcessElement::Validate(), CIccMBB::Validate(), CIccMpeCLUT::Validate(), CIccTagLutAtoB::Validate(), CIccTagLutBtoA::Validate(), CIccTagLut8::Validate(), CIccTagLut16::Validate(), CIccTagChromaticity::Validate(), and ValidateIccProfile().
const char* icValidateNonCompliantMsg = "NonCompliant! - "
Referenced by CIccInfo::CheckData(), CIccProfile::CheckHeader(), CIccProfile::CheckRequiredTags(), CIccProfile::CheckTagTypes(), CIccProfile::ReadValidate(), CIccMultiProcessElement::Validate(), CIccTag::Validate(), CIccTagParametricCurve::Validate(), CIccMatrix::Validate(), CIccTagText::Validate(), CIccCLUT::Validate(), CIccTagTextDescription::Validate(), CIccTagSignature::Validate(), CIccTagNamedColor2::Validate(), CIccTagLutAtoB::Validate(), CIccTagLutBtoA::Validate(), CIccTagChromaticity::Validate(), CIccTagMeasurement::Validate(), CIccTagData::Validate(), CIccTagColorantOrder::Validate(), CIccTagColorantTable::Validate(), CIccTagProfileSeqDesc::Validate(), and CIccResponseCurveStruct::Validate().
const char* icValidateWarningMsg = "Warning! - "
Referenced by CIccInfo::CheckData(), CIccProfile::CheckHeader(), CIccProfile::CheckTagExclusion(), CIccFormulaCurveSegment::Validate(), CIccTagCurve::Validate(), CIccSampledCurveSegment::Validate(), CIccTagParametricCurve::Validate(), CIccTagText::Validate(), CIccSegmentedCurve::Validate(), CIccTagMultiProcessElement::Validate(), CIccMBB::Validate(), CIccTagNamedColor2::Validate(), CIccTagLutBtoA::Validate(), CIccTagXYZ::Validate(), CIccTagLut8::Validate(), CIccTagLut16::Validate(), CIccTagMultiLocalizedUnicode::Validate(), CIccTagColorantOrder::Validate(), CIccTagColorantTable::Validate(), and CIccTagResponseCurveSet16::Validate().