CIccTagText Class Reference
CIccTagText Class Reference
#include <IccTagBasic.h>
Public Member Functions
CIccTagText ()
CIccTagText (const CIccTagText &ITT)
CIccTagText & operator= (const CIccTagText &TextTag)
virtual CIccTag * NewCopy () const
virtual ~CIccTagText ()
virtual icTagTypeSignature GetType () const
virtual const icChar * GetClassName () const
virtual bool Read (icUInt32Number size, CIccIO *pIO)
virtual bool Write (CIccIO *pIO)
virtual void Describe (std::string &sDescription)
const icChar * GetText () const
void SetText (const icChar *szText)
const icChar * operator= (const icChar *szText)
icChar * GetBuffer (icUInt32Number nSize)
void Release ()
icUInt32Number Capacity () const
virtual icValidateStatus Validate (icTagSignature sig, std::string &sReport, const CIccProfile *pProfile=NULL) const
Public Member Functions inherited from CIccTag
CIccTag ()
virtual ~CIccTag ()
virtual bool IsArrayType ()
virtual bool IsMBBType ()
virtual IIccExtensionTag * GetExtension ()
virtual bool IsSupported ()
Protected Attributes
icChar * m_szText
icUInt32Number m_nBufSize
Additional Inherited Members
Static Public Member Functions inherited from CIccTag
static CIccTag * Create (icTagTypeSignature sig)
Public Attributes inherited from CIccTag
icUInt32Number m_nReserved
Detailed Description
Class: CIccTagText()
Purpose: The textType ICC tag
Constructor & Destructor Documentation
CIccTagText::CIccTagText ()
Name: CIccTagText::CIccTagText
Purpose: Constructor
CIccTagText::CIccTagText (const CIccTagText & ITT)
Name: CIccTagText::CIccTagText
Purpose: Copy Constructor
Args: ITT = The CIccTagText object to be copied
References m_szText.
CIccTagText::~CIccTagText () virtual
Name: CIccTagText::~CIccTagText
Purpose: Destructor
Member Function Documentation
icUInt32Number CIccTagText::Capacity () const inline
void CIccTagText::Describe (std::string & sDescription) virtual
Name: CIccTagText::Describe
Purpose: Dump data associated with the tag to a string
Args: sDescription - string to concatenate tag dump to
Reimplemented from CIccTag.
icChar * CIccTagText::GetBuffer (icUInt32Number nSize)
Name: CIccTagText::GetBuffer
Purpose: This function allocates room and returns pointer to data buffer to put string into
Args: nSize = Requested size of data buffer.
Return: The character buffer array
virtual const icChar* CIccTagText::GetClassName () const inline virtual
Reimplemented from CIccTag.
const icChar* CIccTagText::GetText () const inline
Referenced by CIccProfileIdDesc::CIccProfileIdDesc().
virtual icTagTypeSignature CIccTagText::GetType () const inline virtual
Function: GetType()
Purpose: Get Tag Type. Each derived tag will implement it's own GetType() function.
Reimplemented from CIccTag.
References icSigTextType.
virtual CIccTag* CIccTagText::NewCopy () const inline virtual
Function: NewCopy(sDescription) Each derived tag will implement it's own NewCopy() function.
Parameter(s): none
Returns a new CIccTag object that is a copy of this object.
Reimplemented from CIccTag.
CIccTagText & CIccTagText::operator= (const CIccTagText & TextTag)
Name: CIccTagText::operator=
Purpose: Copy Operator
Args: TextTag = The CIccTagText object to be copied
References m_szText.
const icChar * CIccTagText::operator= (const icChar * szText)
Name: *CIccTagText::operator=
Purpose: Define assignment operator to associate text with tag.
Args: szText - zero terminated string to put in the tag
Return: A pointer to the string assigned to the tag.
bool CIccTagText::Read (icUInt32Number size, CIccIO * pIO) virtual
Name: CIccTagText::Read
Purpose: Read in a text type tag into a data block
Args: size - # of bytes in tag, pIO - IO object to read tag from
Return: true = successful, false = failure
Reimplemented from CIccTag.
References CIccIO::Read32(), and CIccIO::Read8().
void CIccTagText::Release ()
Name: CIccTagText::Release
Purpose: This will resize the buffer to fit the zero terminated string in the buffer.
void CIccTagText::SetText (const icChar * szText)
Name: CIccTagText::SetText
Purpose: Allows text data associated with the tag to be set.
Args: szText - zero terminated string to put in tag
icValidateStatus CIccTagText::Validate (icTagSignature sig, std::string & sReport, const CIccProfile * pProfile = NULL) const virtual
Name: CIccTagText::Validate
Purpose: Check tag data validity.
Args: sig = signature of tag being validated, sReport = String to add report information to
Return: icValidateStatusOK if valid, or other error status.
Reimplemented from CIccTag.
References CIccInfo::GetSigName(), icMaxStatus(), icSigCharTargetTag, icSigCopyrightTag, icValidateNonCompliant, icValidateNonCompliantMsg, icValidateWarning, icValidateWarningMsg, and CIccTag::Validate().
bool CIccTagText::Write (CIccIO * pIO) virtual
Name: CIccTagText::Write
Purpose: Write a text type tag to a file
Args: pIO - The IO object to write tag to.
Return: true = succesful, false = failure
Reimplemented from CIccTag.
References CIccIO::Write32(), and CIccIO::Write8().
Member Data Documentation
icUInt32Number CIccTagText::m_nBufSize protected
icChar* CIccTagText::m_szText protected
Referenced by CIccTagText(), and operator=().
The documentation for this class was generated from the following files:
IccTagBasic.h
IccTagBasic.cpp