CIccXformMpe Class Reference
CIccXformMpe Class Reference
#include <IccCmm.h>
Public Member Functions
CIccXformMpe (CIccTag *pTag)
virtual ~CIccXformMpe ()
virtual icXformType GetXformType () const
virtual icStatusCMM Begin ()
virtual CIccApplyXform * GetNewApply (icStatusCMM &status)
virtual void Apply (CIccApplyXform *pApplyXform, icFloatNumber *DstPixel, const icFloatNumber *SrcPixel) const
virtual bool UseLegacyPCS () const
Checks if version 2 PCS is to be used.
virtual LPIccCurve * ExtractInputCurves ()
Use these functions to extract the input/output curves from the xform.
virtual LPIccCurve * ExtractOutputCurves ()
virtual bool NoClipPCS () const
Public Member Functions inherited from CIccXform
CIccXform ()
virtual ~CIccXform ()
virtual bool RemoveIO ()
virtual icColorSpaceSignature GetSrcSpace () const
Returns the source color space of the transform.
virtual icColorSpaceSignature GetDstSpace () const
Returns the destination color space of the transform.
virtual bool IsVersion2 () const
Checks if the profile is version 2.
bool IsInput () const
Checks if the profile is to be used as input profile.
void SetParams (CIccProfile *pProfile, bool bInput, icRenderingIntent nIntent, icXformInterp nInterp, CIccCreateXformHintManager *pHintManager=NULL)
The following function is for Overridden create function.
const CIccProfile * GetProfile () const
Returns the profile pointer. Profile is still owned by the Xform.
icRenderingIntent GetIntent () const
Returns the rendering intent being used by the Xform.
Static Public Member Functions
static CIccXform * Create (CIccProfile *pProfile, bool bInput=true, icRenderingIntent nIntent=icUnknownIntent, icXformInterp nInterp=icInterpLinear, icXformLutType nLutType=icXformLutColor, CIccCreateXformHintManager *pHintManager=NULL)
Note: The returned CIccXform will own the profile.
Static Public Member Functions inherited from CIccXform
static CIccXform * Create (CIccProfile *pProfile, bool bInput=true, icRenderingIntent nIntent=icUnknownIntent, icXformInterp nInterp=icInterpLinear, icXformLutType nLutType=icXformLutColor, bool bUseMpeTags=true, CIccCreateXformHintManager *pHintManager=NULL)
Note: The returned CIccXform will own the profile.
static CIccXform * Create (CIccProfile &pProfile, bool bInput=true, icRenderingIntent nIntent=icUnknownIntent, icXformInterp nInterp=icInterpLinear, icXformLutType nLutType=icXformLutColor, bool bUseMpeTags=true, CIccCreateXformHintManager *pHintManager=NULL)
Protected Attributes
CIccTagMultiProcessElement * m_pTag
bool m_bUsingAcs
Protected Attributes inherited from CIccXform
CIccProfile * m_pProfile
bool m_bInput
icRenderingIntent m_nIntent
icXYZNumber m_MediaXYZ
icXformInterp m_nInterp
IIccAdjustPCSXform * m_pAdjustPCS
bool m_bAdjustPCS
icFloatNumber m_PCSScale [3]
icFloatNumber m_PCSOffset [3]
Additional Inherited Members
Protected Member Functions inherited from CIccXform
const icFloatNumber * CheckSrcAbs (CIccApplyXform *pApply, const icFloatNumber *Pixel) const
void CheckDstAbs (icFloatNumber *Pixel) const
void AdjustPCS (icFloatNumber *DstPixel, const icFloatNumber *SrcPixel) const
virtual bool HasPerceptualHandling ()
Detailed Description
Type: Class
Purpose: This is the general Xform for Multi Processing Elements.
Constructor & Destructor Documentation
CIccXformMpe::CIccXformMpe (CIccTag * pTag)
Name: CIccXformMPE::CIccXformMPE
Purpose: Constructor
References CIccTag::GetType(), and icSigMultiProcessElementType.
CIccXformMpe::~CIccXformMpe () virtual
Name: CIccXformMPE::~CIccXformMPE
Purpose: Destructor
Member Function Documentation
void CIccXformMpe::Apply (CIccApplyXform * pApply, icFloatNumber * DstPixel, const icFloatNumber * SrcPixel) const virtual
Name: CIccXformMPE::Apply
Purpose: Does the actual application of the Xform.
Args: pApply = ApplyXform object containging temporary storage used during Apply DstPixel = Destination pixel where the result is stored, SrcPixel = Source pixel which is to be applied.
Implements CIccXform.
References CIccTagMultiProcessElement::Apply(), icAbsoluteColorimetric, icLabFromPcs(), icLabToPcs(), icSigLabData, icSigXYZData, icXyzFromPcs(), icXyzToPcs(), and CIccApplyXformMpe::m_pApply.
icStatusCMM CIccXformMpe::Begin () virtual
Name: CIccXformMPE::Begin
Purpose: This function will be called before the xform is applied. Derived objects should also call the base class function to initialize for Absolute Colorimetric Intent handling which is performed through the use of the CheckSrcAbs and CheckDstAbs functions.
Reimplemented from CIccXform.
References CIccXform::Begin(), icCmmStatInvalidLut, icCmmStatInvalidProfile, and icCmmStatOk.
CIccXform * CIccXformMpe::Create (CIccProfile * pProfile, bool bInput = true, icRenderingIntent nIntent = icUnknownIntent, icXformInterp nInterp = icInterpLinear, icXformLutType nLutType = icXformLutColor, CIccCreateXformHintManager * pHintManager = NULL) static
Note: The returned CIccXform will own the profile.
Name: CIccXformMPE::Create
Purpose: This is a static Creation function that creates derived CIccXform objects and initializes them.
Args: pProfile = pointer to a CIccProfile object that will be owned by the transform. This object will be destroyed when the returned CIccXform object is destroyed. The means that the CIccProfile object needs to be allocated on the heap. bInput = flag to indicate whether to use the input or output side of the profile, nIntent = the rendering intent to apply to the profile, nInterp = the interpolation algorithm to use for N-D luts. nLutType = selection of which transform lut to use pHintManager = hints for creating the xform
Return: A suitable pXform object
References icHeader::colorSpace, CIccProfile::FindTag(), CIccTag::GetType(), icAbsoluteColorimetric, icPerceptual, icRelativeColorimetric, icSig3colorData, icSig4colorData, icSigAToB0Tag, icSigBToA0Tag, icSigBToD0Tag, icSigBToD1Tag, icSigCmyData, icSigCmykData, icSigDToB0Tag, icSigDToB1Tag, icSigGamutTag, icSigHlsData, icSigHsvData, icSigLabData, icSigLuvData, icSigMultiProcessElementType, icSigNamedColor2Tag, icSigPreview0Tag, icSigRgbData, icSigXYZData, icSigYCbCrData, icSigYxyData, icUnknownIntent, icXformLutColor, icXformLutGamut, icXformLutNamedColor, icXformLutPreview, CIccTag::IsSupported(), CIccProfile::m_Header, icHeader::pcs, and CIccXform::SetParams().
virtual LPIccCurve* CIccXformMpe::ExtractInputCurves () inline virtual
Use these functions to extract the input/output curves from the xform.
Implements CIccXform.
virtual LPIccCurve* CIccXformMpe::ExtractOutputCurves () inline virtual
Implements CIccXform.
CIccApplyXform * CIccXformMpe::GetNewApply (icStatusCMM & status) virtual
Name: CIccXformMpe::GetNewApply
Purpose: This Factory function allocates data specific for the application of the xform. This allows multiple threads to simultaneously use the same xform.
Reimplemented from CIccXform.
References icCmmStatAllocErr, icCmmStatOk, and CIccApplyXformMpe::m_pApply.
virtual icXformType CIccXformMpe::GetXformType () const inline virtual
Implements CIccXform.
References icXformTypeMpe.
virtual bool CIccXformMpe::NoClipPCS () const inline virtual
Reimplemented from CIccXform.
virtual bool CIccXformMpe::UseLegacyPCS () const inline virtual
Checks if version 2 PCS is to be used.
Reimplemented from CIccXform.
Member Data Documentation
bool CIccXformMpe::m_bUsingAcs protected
CIccTagMultiProcessElement* CIccXformMpe::m_pTag protected
The documentation for this class was generated from the following files:
IccCmm.h
IccCmm.cpp