CIccSegmentedCurve Class Reference
CIccSegmentedCurve Class Reference
#include <IccMpeBasic.h>
Public Member Functions
CIccSegmentedCurve ()
CIccSegmentedCurve (const CIccSegmentedCurve &ITPC)
CIccSegmentedCurve & operator= (const CIccSegmentedCurve &ParamCurveTag)
virtual CIccCurveSetCurve * NewCopy () const
virtual ~CIccSegmentedCurve ()
virtual icCurveElemSignature GetType () const
virtual const icChar * GetClassName () const
virtual void Describe (std::string &sDescription)
virtual bool Read (icUInt32Number size, CIccIO *pIO)
virtual bool Write (CIccIO *pIO)
void Reset ()
bool Insert (CIccCurveSegment *pCurveSegment)
virtual bool Begin ()
virtual icFloatNumber Apply (icFloatNumber v) const
virtual icValidateStatus Validate (icTagSignature sig, std::string &sReport, const CIccTagMultiProcessElement *pMPE=NULL) const
Public Member Functions inherited from CIccCurveSetCurve
virtual ~CIccCurveSetCurve ()
Protected Attributes
CIccCurveSegmentList * m_list
icUInt32Number m_nReserved1
icUInt32Number m_nReserved2
Additional Inherited Members
Static Public Member Functions inherited from CIccCurveSetCurve
static CIccCurveSetCurve * Create (icCurveElemSignature sig)
Detailed Description
Class: CIccSegmentedCurve
Purpose: The Curve Set Segmented Curve Type
Constructor & Destructor Documentation
CIccSegmentedCurve::CIccSegmentedCurve ()
Name: CIccSegmentedCurve::CIccSegmentedCurve
Purpose:
Args:
Return:
CIccSegmentedCurve::CIccSegmentedCurve (const CIccSegmentedCurve & curve)
Name: CIccSegmentedCurve::CIccSegmentedCurve
Purpose:
Args:
Return:
References m_list, m_nReserved1, and m_nReserved2.
CIccSegmentedCurve::~CIccSegmentedCurve () virtual
Name: CIccSegmentedCurve::~CIccSegmentedCurve
Purpose:
Args:
Return:
Member Function Documentation
icFloatNumber CIccSegmentedCurve::Apply (icFloatNumber v) const virtual
Name: CIccSegmentedCurve::Apply
Purpose:
Args:
Return:
Implements CIccCurveSetCurve.
bool CIccSegmentedCurve::Begin () virtual
Name: CIccSegmentedCurve::Begin
Purpose:
Args:
Return:
Implements CIccCurveSetCurve.
void CIccSegmentedCurve::Describe (std::string & sDescription) virtual
Name: CIccSegmentedCurve::Describe
Purpose:
Args:
Return:
Implements CIccCurveSetCurve.
virtual const icChar* CIccSegmentedCurve::GetClassName () const inline virtual
Implements CIccCurveSetCurve.
virtual icCurveElemSignature CIccSegmentedCurve::GetType () const inline virtual
Implements CIccCurveSetCurve.
References icSigSementedCurve.
bool CIccSegmentedCurve::Insert (CIccCurveSegment * pCurveSegment)
Name: CIccSegmentedCurve::Insert
Purpose:
Args:
Return:
References CIccCurveSegment::StartPoint().
virtual CIccCurveSetCurve* CIccSegmentedCurve::NewCopy () const inline virtual
Implements CIccCurveSetCurve.
CIccSegmentedCurve & CIccSegmentedCurve::operator= (const CIccSegmentedCurve & curve)
Name: &CIccSegmentedCurve::operator=
Purpose:
Args:
Return:
References m_list, m_nReserved1, and m_nReserved2.
bool CIccSegmentedCurve::Read (icUInt32Number size, CIccIO * pIO) virtual
Name: CIccSegmentedCurve::Read
Purpose:
Args:
Return:
Implements CIccCurveSetCurve.
References CIccCurveSegment::Create(), icMaxFloat32Number, icMinFloat32Number, icSeekSet, CIccCurveSegment::Read(), CIccIO::Read16(), CIccIO::Read32(), CIccIO::ReadFloat32Float(), CIccIO::Seek(), and CIccIO::Tell().
void CIccSegmentedCurve::Reset ()
Name: CIccSegmentedCurve::Reset
Purpose:
Args:
Return:
icValidateStatus CIccSegmentedCurve::Validate (icTagSignature sig, std::string & sReport, const CIccTagMultiProcessElement * pMPE = NULL) const virtual
Name: CIccSegmentedCurve::Validate
Purpose:
Args:
Return:
Implements CIccCurveSetCurve.
References CIccInfo::GetSigName(), icMaxStatus(), icValidateCriticalError, icValidateCriticalErrorMsg, icValidateOK, icValidateWarning, and icValidateWarningMsg.
bool CIccSegmentedCurve::Write (CIccIO * pIO) virtual
Name: CIccSegmentedCurve::Write
Purpose:
Args:
Return:
Implements CIccCurveSetCurve.
References CIccIO::Write16(), CIccIO::Write32(), and CIccIO::WriteFloat32Float().
Member Data Documentation
CIccCurveSegmentList* CIccSegmentedCurve::m_list protected
Referenced by CIccSegmentedCurve(), and operator=().
icUInt32Number CIccSegmentedCurve::m_nReserved1 protected
Referenced by CIccSegmentedCurve(), and operator=().
icUInt32Number CIccSegmentedCurve::m_nReserved2 protected
Referenced by CIccSegmentedCurve(), and operator=().
The documentation for this class was generated from the following files:
IccMpeBasic.h
IccMpeBasic.cpp