CIccProfileIdDesc Class Reference
CIccProfileIdDesc Class Reference
#include <IccTagProfSeqId.h>
Public Member Functions
CIccProfileIdDesc ()
CIccProfileIdDesc (CIccProfile &profile)
CIccProfileIdDesc (icProfileID id, CIccTagMultiLocalizedUnicode desc)
CIccProfileIdDesc (const CIccProfileIdDesc &pid)
CIccProfileIdDesc & operator= (const CIccProfileIdDesc &pid)
void Describe (std::string &sDescription)
bool Read (icUInt32Number size, CIccIO *pIO)
bool Write (CIccIO *pIO)
icValidateStatus Validate (icTagSignature sig, std::string &sReport, const CIccProfile *pProfile=NULL) const
Public Attributes
CIccTagMultiLocalizedUnicode m_desc
icProfileID m_profileID
Constructor & Destructor Documentation
CIccProfileIdDesc::CIccProfileIdDesc ()
Name: sampleICC::CIccProfileIdDesc::CIccProfileIdDesc
Purpose:
Args:
Return:
References m_profileID.
CIccProfileIdDesc::CIccProfileIdDesc (CIccProfile & profile)
Name: sampleICC::CIccProfileIdDesc::CIccProfileIdDesc
Purpose:
Args: CIccProfile &profile
Return:
References CIccProfile::FindTag(), CIccTagText::GetText(), CIccTagTextDescription::GetText(), CIccTag::GetType(), icSigMultiLocalizedUnicodeType, icSigProfileDescriptionTag, icSigTextDescriptionType, icSigTextType, m_desc, CIccProfile::m_Header, m_profileID, icHeader::profileID, and CIccTagMultiLocalizedUnicode::SetText().
CIccProfileIdDesc::CIccProfileIdDesc (icProfileID id, CIccTagMultiLocalizedUnicode desc)
Name: sampleICC::CIccProfileIdDesc::CIccProfileIdDesc
Purpose:
Args: icProfileID id CIccMultiLocalizedUnicode desc
Return:
References m_desc, and m_profileID.
CIccProfileIdDesc::CIccProfileIdDesc (const CIccProfileIdDesc & pid)
Name: sampleICC::CIccProfileIdDesc::CIccProfileIdDesc
Purpose:
Args: const CIccProfileIdDesc &pid
Return:
References m_desc, and m_profileID.
Member Function Documentation
void CIccProfileIdDesc::Describe (std::string & sDescription)
Name: sampleICC::CIccProfileIdDesc::Describe
Purpose:
Args: std::string &sDescription
Return: void
References CIccTagMultiLocalizedUnicode::Describe(), icProfileID::ID8, m_desc, and m_profileID.
CIccProfileIdDesc & CIccProfileIdDesc::operator= (const CIccProfileIdDesc & pid)
Name: sampleICC::CIccProfileIdDesc::operator=
Purpose:
Args: const CIccProfileIdDesc &pid
Return: CIccProfileIdDesc &
References m_desc, and m_profileID.
bool CIccProfileIdDesc::Read (icUInt32Number size, CIccIO * pIO)
Name: sampleICC::CIccProfileIdDesc::Read
Purpose:
Args: icUInt32Number size CIccIO *pIO
Return: bool
References m_desc, m_profileID, CIccTagMultiLocalizedUnicode::Read(), and CIccIO::Read8().
Referenced by CIccTagProfileSequenceId::Read().
icValidateStatus CIccProfileIdDesc::Validate (icTagSignature sig, std::string & sReport, const CIccProfile * pProfile = NULL) const
Name: sampleICC::CIccProfileIdDesc::Validate
Purpose:
Args: std::string &sReport
Return: icValidateStatus
References m_desc, and CIccTagMultiLocalizedUnicode::Validate().
bool CIccProfileIdDesc::Write (CIccIO * pIO)
Name: sampleICC::CIccProfileIdDesc::Write
Purpose:
Args: CIccIO *pIO
Return: bool
References m_desc, m_profileID, CIccTagMultiLocalizedUnicode::Write(), and CIccIO::Write8().
Member Data Documentation
CIccTagMultiLocalizedUnicode CIccProfileIdDesc::m_desc
Referenced by CIccProfileIdDesc(), Describe(), operator=(), Read(), Validate(), and Write().
icProfileID CIccProfileIdDesc::m_profileID
Referenced by CIccProfileIdDesc(), Describe(), operator=(), Read(), and Write().
The documentation for this class was generated from the following files:
IccTagProfSeqId.h
IccTagProfSeqId.cpp