CIccMemIO Class Reference
CIccMemIO Class Reference
#include <IccIO.h>
Public Member Functions
CIccMemIO ()
virtual ~CIccMemIO ()
bool Alloc (icUInt32Number nSize, bool bWrite=false)
bool Attach (icUInt8Number *pData, icUInt32Number nSize, bool bWrite=false)
virtual void Close ()
virtual icInt32Number Read8 (void *pBuf, icInt32Number nNum=1)
virtual icInt32Number Write8 (void *pBuf, icInt32Number nNum=1)
virtual icInt32Number GetLength ()
virtual icInt32Number Seek (icInt32Number nOffset, icSeekVal pos)
virtual icInt32Number Tell ()
icUInt8Number * GetData ()
Public Member Functions inherited from CIccIO
virtual ~CIccIO ()
icInt32Number ReadLine (void *pBuf8, icInt32Number nNum=256)
icInt32Number Read16 (void *pBuf16, icInt32Number nNum=1)
icInt32Number Write16 (void *pBuf16, icInt32Number nNum=1)
icInt32Number Read32 (void *pBuf32, icInt32Number nNum=1)
icInt32Number Write32 (void *pBuf32, icInt32Number nNum=1)
icInt32Number Read64 (void *pBuf64, icInt32Number nNum=1)
icInt32Number Write64 (void *pBuf64, icInt32Number nNum=1)
icInt32Number Read8Float (void *pBufFloat, icInt32Number nNum=1)
icInt32Number Write8Float (void *pBuf16, icInt32Number nNum=1)
icInt32Number Read16Float (void *pBufFloat, icInt32Number nNum=1)
icInt32Number Write16Float (void *pBuf16, icInt32Number nNum=1)
icInt32Number ReadFloat32Float (void *pBufFloat, icInt32Number nNum=1)
icInt32Number WriteFloat32Float (void *pBufFloat, icInt32Number nNum=1)
bool Align32 ()
Write operation to make sure that filelength is evenly divisible by 4.
bool Sync32 (icUInt32Number nOffset=0)
Operation to make sure read position is evenly divisible by 4.
Protected Attributes
icUInt8Number * m_pData
icUInt32Number m_nSize
icUInt32Number m_nAvail
icUInt32Number m_nPos
bool m_bFreeData
Detailed Description
Type: Class
Purpose: Handles generic memory IO
Constructor & Destructor Documentation
CIccMemIO::CIccMemIO ()
References m_bFreeData, m_nAvail, m_nPos, m_nSize, and m_pData.
CIccMemIO::~CIccMemIO () virtual
References Close().
Member Function Documentation
bool CIccMemIO::Alloc (icUInt32Number nSize, bool bWrite = false)
References Attach(), Close(), m_bFreeData, and m_pData.
Referenced by CIccProfile::GetTagIO().
bool CIccMemIO::Attach (icUInt8Number * pData, icUInt32Number nSize, bool bWrite = false)
References Close(), m_nAvail, m_nPos, m_nSize, and m_pData.
Referenced by CIccCmm::AddXform(), Alloc(), OpenIccProfile(), CIccTagProfileSequenceId::ParseMem(), and ReadIccProfile().
void CIccMemIO::Close () virtual
Reimplemented from CIccIO.
References m_bFreeData, and m_pData.
Referenced by Alloc(), Attach(), and ~CIccMemIO().
icUInt8Number* CIccMemIO::GetData () inline
Referenced by CIccProfile::GetTagIO().
icInt32Number CIccMemIO::GetLength () virtual
Reimplemented from CIccIO.
References m_nSize, and m_pData.
Referenced by CIccProfile::GetTagIO().
icInt32Number CIccMemIO::Read8 (void * pBuf, icInt32Number nNum = 1) virtual
Reimplemented from CIccIO.
References __min, m_nPos, m_nSize, and m_pData.
icInt32Number CIccMemIO::Seek (icInt32Number nOffset, icSeekVal pos) virtual
Reimplemented from CIccIO.
References icSeekCur, icSeekEnd, icSeekSet, m_nAvail, m_nPos, m_nSize, and m_pData.
Referenced by CIccProfile::GetTagIO().
icInt32Number CIccMemIO::Tell () virtual
Reimplemented from CIccIO.
References m_nPos, and m_pData.
icInt32Number CIccMemIO::Write8 (void * pBuf, icInt32Number nNum = 1) virtual
Reimplemented from CIccIO.
References __min, m_nAvail, m_nPos, m_nSize, and m_pData.
Member Data Documentation
bool CIccMemIO::m_bFreeData protected
Referenced by Alloc(), CIccMemIO(), and Close().
icUInt32Number CIccMemIO::m_nAvail protected
Referenced by Attach(), CIccMemIO(), Seek(), and Write8().
icUInt32Number CIccMemIO::m_nPos protected
Referenced by Attach(), CIccMemIO(), Read8(), Seek(), Tell(), and Write8().
icUInt32Number CIccMemIO::m_nSize protected
Referenced by Attach(), CIccMemIO(), GetLength(), Read8(), Seek(), and Write8().
icUInt8Number* CIccMemIO::m_pData protected
Referenced by Alloc(), Attach(), CIccMemIO(), Close(), GetLength(), Read8(), Seek(), Tell(), and Write8().
The documentation for this class was generated from the following files:
IccIO.h
IccIO.cpp