CIccFileIO Class Reference
CIccFileIO Class Reference
#include <IccIO.h>
Public Member Functions
CIccFileIO ()
virtual ~CIccFileIO ()
bool Open (const icChar *szFilename, const icChar *szAttr)
virtual void Close ()
virtual icInt32Number Read8 (void *pBuf, icInt32Number nNum=1)
virtual icInt32Number Write8 (void *pBuf, icInt32Number nNum=1)
virtual icInt32Number GetLength ()
virtual icInt32Number Seek (icInt32Number nOffset, icSeekVal pos)
virtual icInt32Number Tell ()
Public Member Functions inherited from CIccIO
virtual ~CIccIO ()
icInt32Number ReadLine (void *pBuf8, icInt32Number nNum=256)
icInt32Number Read16 (void *pBuf16, icInt32Number nNum=1)
icInt32Number Write16 (void *pBuf16, icInt32Number nNum=1)
icInt32Number Read32 (void *pBuf32, icInt32Number nNum=1)
icInt32Number Write32 (void *pBuf32, icInt32Number nNum=1)
icInt32Number Read64 (void *pBuf64, icInt32Number nNum=1)
icInt32Number Write64 (void *pBuf64, icInt32Number nNum=1)
icInt32Number Read8Float (void *pBufFloat, icInt32Number nNum=1)
icInt32Number Write8Float (void *pBuf16, icInt32Number nNum=1)
icInt32Number Read16Float (void *pBufFloat, icInt32Number nNum=1)
icInt32Number Write16Float (void *pBuf16, icInt32Number nNum=1)
icInt32Number ReadFloat32Float (void *pBufFloat, icInt32Number nNum=1)
icInt32Number WriteFloat32Float (void *pBufFloat, icInt32Number nNum=1)
bool Align32 ()
Write operation to make sure that filelength is evenly divisible by 4.
bool Sync32 (icUInt32Number nOffset=0)
Operation to make sure read position is evenly divisible by 4.
Protected Attributes
FILE * m_fFile
Detailed Description
Type: Class
Purpose: Handles generic File IO
Constructor & Destructor Documentation
CIccFileIO::CIccFileIO ()
References m_fFile.
CIccFileIO::~CIccFileIO () virtual
References Close().
Member Function Documentation
void CIccFileIO::Close () virtual
Reimplemented from CIccIO.
References m_fFile.
Referenced by ~CIccFileIO().
icInt32Number CIccFileIO::GetLength () virtual
Reimplemented from CIccIO.
References m_fFile.
bool CIccFileIO::Open (const icChar * szFilename, const icChar * szAttr)
References m_fFile.
Referenced by CalcProfileID(), OpenIccProfile(), ReadIccProfile(), SaveIccProfile(), and ValidateIccProfile().
icInt32Number CIccFileIO::Read8 (void * pBuf, icInt32Number nNum = 1) virtual
Reimplemented from CIccIO.
References m_fFile.
icInt32Number CIccFileIO::Seek (icInt32Number nOffset, icSeekVal pos) virtual
Reimplemented from CIccIO.
References m_fFile.
icInt32Number CIccFileIO::Tell () virtual
Reimplemented from CIccIO.
References m_fFile.
icInt32Number CIccFileIO::Write8 (void * pBuf, icInt32Number nNum = 1) virtual
Reimplemented from CIccIO.
References m_fFile.
Member Data Documentation
FILE* CIccFileIO::m_fFile protected
Referenced by CIccFileIO(), Close(), GetLength(), Open(), Read8(), Seek(), Tell(), and Write8().
The documentation for this class was generated from the following files:
IccIO.h
IccIO.cpp