CIccFormulaCurveSegment Class Reference
CIccFormulaCurveSegment Class Reference
#include <IccMpeBasic.h>
Public Member Functions
CIccFormulaCurveSegment (icFloatNumber start, icFloatNumber end)
CIccFormulaCurveSegment (const CIccFormulaCurveSegment &seg)
CIccFormulaCurveSegment & operator= (const CIccFormulaCurveSegment &seg)
virtual CIccCurveSegment * NewCopy () const
virtual ~CIccFormulaCurveSegment ()
virtual icCurveSegSignature GetType () const
virtual const icChar * GetClassName () const
virtual void Describe (std::string &sDescription)
void SetFunction (icUInt16Number functionType, icUInt8Number num_parameters, icFloatNumber *parameters)
virtual bool Read (icUInt32Number size, CIccIO *pIO)
virtual bool Write (CIccIO *pIO)
virtual bool Begin (CIccCurveSegment *pPrevSeg)
virtual icFloatNumber Apply (icFloatNumber v) const
virtual icValidateStatus Validate (icTagSignature sig, std::string &sReport, const CIccTagMultiProcessElement *pMPE=NULL) const
Public Member Functions inherited from CIccCurveSegment
virtual ~CIccCurveSegment ()
icFloatNumber StartPoint ()
icFloatNumber EndPoint ()
Protected Attributes
icUInt16Number m_nReserved2
icUInt8Number m_nParameters
icUInt16Number m_nFunctionType
icFloatNumber * m_params
Protected Attributes inherited from CIccCurveSegment
icFloatNumber m_startPoint
icFloatNumber m_endPoint
icUInt32Number m_nReserved
Additional Inherited Members
Static Public Member Functions inherited from CIccCurveSegment
static CIccCurveSegment * Create (icCurveSegSignature sig, icFloatNumber start, icFloatNumber end)
Detailed Description
Class: CIccTagFormulaCurveSegment
Purpose: The parametric curve segment
Constructor & Destructor Documentation
CIccFormulaCurveSegment::CIccFormulaCurveSegment (icFloatNumber start, icFloatNumber end)
Name: CIccFormulaCurveSegment::CIccFormulaCurveSegment
Purpose:
Args:
Return:
CIccFormulaCurveSegment::CIccFormulaCurveSegment (const CIccFormulaCurveSegment & seg)
Name: CIccFormulaCurveSegment::CIccFormulaCurveSegment
Purpose:
Args:
Return:
References CIccCurveSegment::m_endPoint, m_nFunctionType, m_nParameters, CIccCurveSegment::m_nReserved, m_nReserved2, m_params, and CIccCurveSegment::m_startPoint.
CIccFormulaCurveSegment::~CIccFormulaCurveSegment () virtual
Name: CIccFormulaCurveSegment::~CIccFormulaCurveSegment
Purpose:
Args:
Return:
Member Function Documentation
icFloatNumber CIccFormulaCurveSegment::Apply (icFloatNumber v) const virtual
Name: CIccFormulaCurveSegment::Apply
Purpose:
Args:
Return:
Implements CIccCurveSegment.
bool CIccFormulaCurveSegment::Begin (CIccCurveSegment * pPrevSeg = NULL) virtual
Name: CIccFormulaCurveSegment::Begin
Purpose:
Args:
Return:
Implements CIccCurveSegment.
void CIccFormulaCurveSegment::Describe (std::string & sDescription) virtual
Name: CIccFormulaCurveSegment::Describe
Purpose:
Args:
Return:
Implements CIccCurveSegment.
References icMaxFloat32Number, and icMinFloat32Number.
virtual const icChar* CIccFormulaCurveSegment::GetClassName () const inline virtual
Implements CIccCurveSegment.
virtual icCurveSegSignature CIccFormulaCurveSegment::GetType () const inline virtual
Implements CIccCurveSegment.
References icSigFormulaCurveSeg.
virtual CIccCurveSegment* CIccFormulaCurveSegment::NewCopy () const inline virtual
Implements CIccCurveSegment.
CIccFormulaCurveSegment & CIccFormulaCurveSegment::operator= (const CIccFormulaCurveSegment & seg)
Name: &CIccFormulaCurveSegment::operator=
Purpose:
Args:
Return:
References CIccCurveSegment::m_endPoint, m_nFunctionType, m_nParameters, CIccCurveSegment::m_nReserved, m_nReserved2, m_params, and CIccCurveSegment::m_startPoint.
bool CIccFormulaCurveSegment::Read (icUInt32Number size, CIccIO * pIO) virtual
Name: CIccFormulaCurveSegment::Read
Purpose:
Args:
Return:
Implements CIccCurveSegment.
References CIccIO::Read16(), CIccIO::Read32(), and CIccIO::ReadFloat32Float().
void CIccFormulaCurveSegment::SetFunction (icUInt16Number functionType, icUInt8Number num_parameters, icFloatNumber * parameters)
Name: CIccFormulaCurveSegment::SetFunction
Purpose:
Args:
Return:
icValidateStatus CIccFormulaCurveSegment::Validate (icTagSignature sig, std::string & sReport, const CIccTagMultiProcessElement * pMPE = NULL) const virtual
Name: CIccFormulaCurveSegment::Validate
Purpose:
Args:
Return:
Implements CIccCurveSegment.
References CIccInfo::GetSigName(), icValidateCriticalError, icValidateCriticalErrorMsg, icValidateOK, icValidateWarning, and icValidateWarningMsg.
bool CIccFormulaCurveSegment::Write (CIccIO * pIO) virtual
Name: CIccFormulaCurveSegment::Write
Purpose:
Args:
Return:
Implements CIccCurveSegment.
References CIccIO::Write16(), CIccIO::Write32(), and CIccIO::WriteFloat32Float().
Member Data Documentation
icUInt16Number CIccFormulaCurveSegment::m_nFunctionType protected
Referenced by CIccFormulaCurveSegment(), and operator=().
icUInt8Number CIccFormulaCurveSegment::m_nParameters protected
Referenced by CIccFormulaCurveSegment(), and operator=().
icUInt16Number CIccFormulaCurveSegment::m_nReserved2 protected
Referenced by CIccFormulaCurveSegment(), and operator=().
icFloatNumber* CIccFormulaCurveSegment::m_params protected
Referenced by CIccFormulaCurveSegment(), and operator=().
The documentation for this class was generated from the following files:
IccMpeBasic.h
IccMpeBasic.cpp