CIccTagFixedNum< T, Tsig > Class Template Reference
CIccTagFixedNum< T, Tsig > Class Template Reference
#include <IccTagBasic.h>
Public Member Functions
CIccTagFixedNum (int nSize=1)
CIccTagFixedNum (const CIccTagFixedNum &ITFN)
CIccTagFixedNum & operator= (const CIccTagFixedNum &FixedNumTag)
virtual CIccTag * NewCopy () const
virtual ~CIccTagFixedNum ()
virtual bool IsArrayType ()
virtual icTagTypeSignature GetType () const
virtual const icChar * GetClassName () const
virtual void Describe (std::string &sDescription)
virtual bool Read (icUInt32Number size, CIccIO *pIO)
virtual bool Write (CIccIO *pIO)
T & operator[] (icUInt32Number index)
icUInt32Number GetSize () const
Returns the size of the data array.
void SetSize (icUInt32Number nSize, bool bZeroNew=true)
Public Member Functions inherited from CIccTag
CIccTag ()
virtual ~CIccTag ()
virtual bool IsMBBType ()
virtual IIccExtensionTag * GetExtension ()
virtual bool IsSupported ()
virtual icValidateStatus Validate (icTagSignature sig, std::string &sReport, const CIccProfile *pProfile=NULL) const
Protected Attributes
T * m_Num
icUInt32Number m_nSize
Additional Inherited Members
Static Public Member Functions inherited from CIccTag
static CIccTag * Create (icTagTypeSignature sig)
Public Attributes inherited from CIccTag
icUInt32Number m_nReserved
Detailed Description
template<class T, icTagTypeSignature Tsig>
class CIccTagFixedNum< T, Tsig >
Class: CIccTagFixedNum
Purpose: A template class for arrays of Fixed point numbers
Derived Tags: CIccTagS15Fixed16 and CIccTagU16Fixed16
Constructor & Destructor Documentation
template<class T , icTagTypeSignature Tsig> CIccTagFixedNum< T, Tsig >::CIccTagFixedNum (int nSize = 1)
Name: CIccTagFixedNum
Purpose: ConstrCIccTagFixedNumuctor
Args: nSize = number of data entries
template<class T , icTagTypeSignature Tsig> CIccTagFixedNum< T, Tsig >::CIccTagFixedNum (const CIccTagFixedNum< T, Tsig > & ITFN)
Name: CIccTagFixedNum::CIccTagFixedNum
Purpose: Copy Constructor
Args: ITFN = The CIccTagFixedNum object to be copied
References CIccTagFixedNum< T, Tsig >::m_nSize, and CIccTagFixedNum< T, Tsig >::m_Num.
template<class T , icTagTypeSignature Tsig> CIccTagFixedNum< T, Tsig >::~CIccTagFixedNum () virtual
Name: CIccTagFixedNum::~CIccTagFixedNum
Purpose: Destructor
Member Function Documentation
template<class T , icTagTypeSignature Tsig> void CIccTagFixedNum< T, Tsig >::Describe (std::string & sDescription) virtual
Name: CIccTagFixedNum::Describe
Purpose: Dump data associated with the tag to a string
Args: sDescription - string to concatenate tag dump to
Reimplemented from CIccTag.
References icFtoD(), icMatrixDump(), icSigS15Fixed16ArrayType, and icUFtoD().
template<class T , icTagTypeSignature Tsig> const icChar * CIccTagFixedNum< T, Tsig >::GetClassName () const virtual
Name: CIccTagFixedNum::GetClassName
Purpose: Returns the tag type class name
Reimplemented from CIccTag.
References icSigS15Fixed16ArrayType.
template<class T, icTagTypeSignature Tsig> icUInt32Number CIccTagFixedNum< T, Tsig >::GetSize () const inline
Returns the size of the data array.
template<class T, icTagTypeSignature Tsig> virtual icTagTypeSignature CIccTagFixedNum< T, Tsig >::GetType () const inline virtual
Function: GetType()
Purpose: Get Tag Type. Each derived tag will implement it's own GetType() function.
Reimplemented from CIccTag.
template<class T, icTagTypeSignature Tsig> virtual bool CIccTagFixedNum< T, Tsig >::IsArrayType () inline virtual
Reimplemented from CIccTag.
template<class T, icTagTypeSignature Tsig> virtual CIccTag* CIccTagFixedNum< T, Tsig >::NewCopy () const inline virtual
Function: NewCopy(sDescription) Each derived tag will implement it's own NewCopy() function.
Parameter(s): none
Returns a new CIccTag object that is a copy of this object.
Reimplemented from CIccTag.
template<class T , icTagTypeSignature Tsig> CIccTagFixedNum< T, Tsig > & CIccTagFixedNum< T, Tsig >::operator= (const CIccTagFixedNum< T, Tsig > & FixedNumTag)
Name: CIccTagFixedNum::operator=
Purpose: Copy Operator
Args: ITFN = The CIccTagFixedNum object to be copied
References CIccTagFixedNum< T, Tsig >::m_nSize, and CIccTagFixedNum< T, Tsig >::m_Num.
template<class T, icTagTypeSignature Tsig> T& CIccTagFixedNum< T, Tsig >::operator[] (icUInt32Number index) inline
template<class T , icTagTypeSignature Tsig> bool CIccTagFixedNum< T, Tsig >::Read (icUInt32Number size, CIccIO * pIO) virtual
Name: CIccTagFixedNum::Read
Purpose: Read in the tag contents into a data block
Args: size - # of bytes in tag, pIO - IO object to read tag from
Return: true = successful, false = failure
Reimplemented from CIccTag.
References CIccIO::Read32().
template<class T , icTagTypeSignature Tsig> void CIccTagFixedNum< T, Tsig >::SetSize (icUInt32Number nSize, bool bZeroNew = true)
Name: CIccTagFixedNum::SetSize
Purpose: Sets the size of the data array.
Args: nSize - number of data entries, bZeroNew - flag to zero newly formed values
template<class T , icTagTypeSignature Tsig> bool CIccTagFixedNum< T, Tsig >::Write (CIccIO * pIO) virtual
Name: CIccTagFixedNum::Write
Purpose: Write the tag to a file
Args: pIO - The IO object to write tag to.
Return: true = succesful, false = failure
Reimplemented from CIccTag.
References CIccIO::Write32().
Member Data Documentation
template<class T, icTagTypeSignature Tsig> icUInt32Number CIccTagFixedNum< T, Tsig >::m_nSize protected
Referenced by CIccTagFixedNum< T, Tsig >::CIccTagFixedNum(), and CIccTagFixedNum< T, Tsig >::operator=().
template<class T, icTagTypeSignature Tsig> T* CIccTagFixedNum< T, Tsig >::m_Num protected
Referenced by CIccTagFixedNum< T, Tsig >::CIccTagFixedNum(), and CIccTagFixedNum< T, Tsig >::operator=().
The documentation for this class was generated from the following files:
IccTagBasic.h
IccTagBasic.cpp