CIccTag Class Reference
CIccTag Class Reference
#include <IccTagBasic.h>
Public Member Functions
CIccTag ()
virtual CIccTag * NewCopy () const
virtual ~CIccTag ()
virtual icTagTypeSignature GetType () const
virtual bool IsArrayType ()
virtual bool IsMBBType ()
virtual const icChar * GetClassName () const
virtual IIccExtensionTag * GetExtension ()
virtual bool IsSupported ()
virtual bool Read (icUInt32Number size, CIccIO *pIO)
virtual bool Write (CIccIO *pIO)
virtual void Describe (std::string &sDescription)
virtual icValidateStatus Validate (icTagSignature sig, std::string &sReport, const CIccProfile *pProfile=NULL) const
Static Public Member Functions
static CIccTag * Create (icTagTypeSignature sig)
Public Attributes
icUInt32Number m_nReserved
Detailed Description
Class: CIccTag
Purpose: CIccTag is the base class that all Icc Tags are derived from. It defines basic tag functionality, and provides a static function that acts as an object construction factory.
Constructor & Destructor Documentation
CIccTag::CIccTag ()
Name: CIccTag::CIccTag
Purpose: Constructor
CIccTag::~CIccTag () virtual
Name: CIccTag::CIccTag
Purpose: Destructor
Member Function Documentation
CIccTag * CIccTag::Create (icTagTypeSignature sig) static
Name: CIccTag::Create
Purpose: This is a static tag creator based upon tag signature type
Args: sig = tag type signature
Return: Pointer to Allocated tag
References CIccTagCreator::CreateTag().
Referenced by CIccProfile::LoadTag(), CIccTagLutAtoB::Read(), CIccTagLut8::Read(), CIccTagLut16::Read(), CIccTagLut8::SetColorSpaces(), CIccTagLut16::SetColorSpaces(), and CIccProfileDescText::SetType().
virtual void CIccTag::Describe (std::string & sDescription) inline virtual
Function: Describe(sDescription) Each derived tag will implement it's own Describe() function.
Parameter(s): sDescription - A string to put the tag's description into.
Reimplemented in CIccTagNum< T, Tsig >, CIccTagResponseCurveSet16, CIccTagProfileSeqDesc, CIccTagViewingConditions, CIccTagColorantTable, CIccTagColorantOrder, CIccTagDateTime, CIccTagData, CIccTagMultiLocalizedUnicode, CIccTagMeasurement, CIccTagNum< T, Tsig >, CIccTagFixedNum< T, Tsig >, CIccTagChromaticity, CIccTagXYZ, CIccTagNamedColor2, CIccMBB, CIccTagMultiProcessElement, CIccTagSignature, CIccTagTextDescription, CIccTagText, CIccTagUnknown, CIccTagParametricCurve, CIccTagDict, CIccTagCurve, and CIccTagProfileSequenceId.
virtual const icChar* CIccTag::GetClassName () const inline virtual
Reimplemented in CIccTagResponseCurveSet16, CIccTagProfileSeqDesc, CIccTagViewingConditions, CIccTagColorantTable, CIccTagColorantOrder, CIccTagDateTime, CIccTagData, CIccTagMultiLocalizedUnicode, CIccTagMeasurement, CIccTagNum< T, Tsig >, CIccTagFixedNum< T, Tsig >, CIccTagChromaticity, CIccTagXYZ, CIccTagNamedColor2, CIccTagMultiProcessElement, CIccTagSignature, CIccTagTextDescription, CIccTagText, CIccTagUnknown, CIccTagParametricCurve, CIccTagDict, CIccTagCurve, and CIccTagProfileSequenceId.
virtual IIccExtensionTag* CIccTag::GetExtension () inline virtual
virtual icTagTypeSignature CIccTag::GetType () const inline virtual
Function: GetType()
Purpose: Get Tag Type. Each derived tag will implement it's own GetType() function.
Reimplemented in CIccTagResponseCurveSet16, CIccTagProfileSeqDesc, CIccTagViewingConditions, CIccTagColorantTable, CIccTagColorantOrder, CIccTagDateTime, CIccTagData, CIccTagMultiLocalizedUnicode, CIccTagMeasurement, CIccTagNum< T, Tsig >, CIccTagFixedNum< T, Tsig >, CIccTagLut16, CIccTagChromaticity, CIccTagLut8, CIccTagXYZ, CIccTagLutBtoA, CIccTagLutAtoB, CIccTagNamedColor2, CIccTagMultiProcessElement, CIccTagSignature, CIccTagTextDescription, CIccTagText, CIccTagUnknown, CIccTagParametricCurve, CIccTagDict, CIccTagCurve, and CIccTagProfileSequenceId.
References icMaxEnumType.
Referenced by CIccXform::Begin(), CIccProfileIdDesc::CIccProfileIdDesc(), CIccXformMpe::CIccXformMpe(), CIccXformNamedColor::CIccXformNamedColor(), CIccXform::Create(), CIccXformMpe::Create(), CIccPRMG::EvaluateProfile(), CIccXformMatrixTRC::GetColumn(), CIccXformMonochrome::GetCurve(), and CIccXformMatrixTRC::GetCurve().
virtual bool CIccTag::IsArrayType () inline virtual
Reimplemented in CIccTagData, CIccTagNum< T, Tsig >, CIccTagFixedNum< T, Tsig >, CIccTagChromaticity, and CIccTagXYZ.
virtual bool CIccTag::IsMBBType () inline virtual
Reimplemented in CIccMBB.
Referenced by CIccXform3DLut::CIccXform3DLut(), CIccXform4DLut::CIccXform4DLut(), CIccXformNDLut::CIccXformNDLut(), and CIccProfile::LoadTag().
virtual bool CIccTag::IsSupported () inline virtual
Function: IsSupported(size, pIO) - Check if tag fully supported for apply purposes. By Default inherited classes are supported. Unknown tag types are not supported.
Returns true if tag type is supported.
Reimplemented in CIccTagMultiProcessElement, and CIccTagUnknown.
Referenced by CIccXform::Create(), and CIccXformMpe::Create().
virtual CIccTag* CIccTag::NewCopy () const inline virtual
Function: NewCopy(sDescription) Each derived tag will implement it's own NewCopy() function.
Parameter(s): none
Returns a new CIccTag object that is a copy of this object.
Reimplemented in CIccTagResponseCurveSet16, CIccTagProfileSeqDesc, CIccTagViewingConditions, CIccTagColorantTable, CIccTagColorantOrder, CIccTagDateTime, CIccTagData, CIccTagMultiLocalizedUnicode, CIccTagMeasurement, CIccTagNum< T, Tsig >, CIccTagFixedNum< T, Tsig >, CIccTagLut16, CIccTagChromaticity, CIccTagLut8, CIccTagXYZ, CIccTagLutBtoA, CIccTagLutAtoB, CIccTagNamedColor2, CIccMBB, CIccTagMultiProcessElement, CIccTagSignature, CIccTagTextDescription, CIccTagText, CIccTagUnknown, CIccTagParametricCurve, CIccTagDict, CIccTagCurve, CIccTagProfileSequenceId, and CIccCurve.
References CIccTag.
Referenced by CIccProfile::CIccProfile(), CIccProfileDescText::CIccProfileDescText(), CIccProfile::operator=(), and CIccProfileDescText::operator=().
virtual bool CIccTag::Read (icUInt32Number size, CIccIO * pIO) inline virtual
Function: Read(size, pIO) - Read tag from file. Each derived tag will implement it's own Read() function.
Parameter(s): size - number of bytes in tag including the type signature. pIO - IO object used to read in tag. The IO object should already be initialized to point to the begining of the tag.
Returns true if Read is successful.
Reimplemented in CIccTagResponseCurveSet16, CIccTagProfileSeqDesc, CIccTagViewingConditions, CIccTagColorantTable, CIccTagColorantOrder, CIccTagDateTime, CIccTagData, CIccTagMultiLocalizedUnicode, CIccTagMeasurement, CIccTagNum< T, Tsig >, CIccTagFixedNum< T, Tsig >, CIccTagLut16, CIccTagChromaticity, CIccTagLut8, CIccTagXYZ, CIccTagLutAtoB, CIccTagNamedColor2, CIccTagMultiProcessElement, CIccTagSignature, CIccTagTextDescription, CIccTagText, CIccTagUnknown, CIccTagParametricCurve, CIccTagDict, CIccTagCurve, and CIccTagProfileSequenceId.
Referenced by CIccProfile::LoadTag().
icValidateStatus CIccTag::Validate (icTagSignature sig, std::string & sReport, const CIccProfile * pProfile = NULL) const virtual
Function: Validate Each derived tag will implement it's own IsValid() function
Parameter(s): sig - signature of tag being validated, sDescription - A string to put tag validation report.
Name: CIccTag::Validate
Purpose: Check tag data validity. In base class we only look at the tag's reserved data value
Args: sig = signature of tag being validated, sReport = String to add report information to
Return: icValidateStatusOK if valid, or other error status.
Reimplemented in CIccTagResponseCurveSet16, CIccTagProfileSeqDesc, CIccTagViewingConditions, CIccTagColorantTable, CIccTagColorantOrder, CIccTagDateTime, CIccTagData, CIccTagMultiLocalizedUnicode, CIccTagMeasurement, CIccTagChromaticity, CIccTagLut16, CIccTagLut8, CIccTagXYZ, CIccTagLutBtoA, CIccTagLutAtoB, CIccTagNamedColor2, CIccMBB, CIccTagMultiProcessElement, CIccTagSignature, CIccTagTextDescription, CIccTagText, CIccTagParametricCurve, CIccTagDict, CIccTagCurve, and CIccTagProfileSequenceId.
References CIccInfo::GetSigName(), icValidateNonCompliant, icValidateNonCompliantMsg, and icValidateOK.
Referenced by CIccTagProfileSequenceId::Validate(), CIccTagCurve::Validate(), CIccTagDict::Validate(), CIccTagParametricCurve::Validate(), CIccTagText::Validate(), CIccTagTextDescription::Validate(), CIccTagSignature::Validate(), CIccMBB::Validate(), CIccTagNamedColor2::Validate(), CIccTagXYZ::Validate(), CIccTagChromaticity::Validate(), CIccTagMeasurement::Validate(), CIccTagMultiLocalizedUnicode::Validate(), CIccTagData::Validate(), CIccTagDateTime::Validate(), CIccTagColorantOrder::Validate(), CIccTagColorantTable::Validate(), CIccTagViewingConditions::Validate(), CIccTagProfileSeqDesc::Validate(), and CIccTagResponseCurveSet16::Validate().
virtual bool CIccTag::Write (CIccIO * pIO) inline virtual
Function: Write(pIO) Each derived tag will implement it's own Write() function.
Parameter(s): pIO - IO object used to write a tag. The IO object should already be initialized to point to the begining of the tag.
Returns true if Write is successful.
Reimplemented in CIccTagResponseCurveSet16, CIccTagProfileSeqDesc, CIccTagViewingConditions, CIccTagColorantTable, CIccTagColorantOrder, CIccTagDateTime, CIccTagData, CIccTagMultiLocalizedUnicode, CIccTagMeasurement, CIccTagNum< T, Tsig >, CIccTagFixedNum< T, Tsig >, CIccTagLut16, CIccTagChromaticity, CIccTagLut8, CIccTagXYZ, CIccTagLutAtoB, CIccTagNamedColor2, CIccTagMultiProcessElement, CIccTagSignature, CIccTagTextDescription, CIccTagText, CIccTagUnknown, CIccTagParametricCurve, CIccTagDict, CIccTagCurve, and CIccTagProfileSequenceId.
Member Data Documentation
icUInt32Number CIccTag::m_nReserved
Referenced by CIccTagMultiProcessElement::CIccTagMultiProcessElement(), CIccTagMultiProcessElement::operator=(), CIccTagProfileSequenceId::Read(), CIccTagDict::Read(), CIccTagLutAtoB::Read(), CIccTagLut8::Read(), CIccTagLut16::Read(), CIccTagProfileSequenceId::Write(), CIccTagDict::Write(), CIccTagLutAtoB::Write(), CIccTagLut8::Write(), and CIccTagLut16::Write().
The documentation for this class was generated from the following files:
IccTagBasic.h
IccTagBasic.cpp