CIccMpeMatrix Class Reference
CIccMpeMatrix Class Reference
#include <IccMpeBasic.h>
Public Member Functions
CIccMpeMatrix ()
CIccMpeMatrix (const CIccMpeMatrix &ITPC)
CIccMpeMatrix & operator= (const CIccMpeMatrix &ParamCurveTag)
virtual CIccMultiProcessElement * NewCopy () const
virtual ~CIccMpeMatrix ()
virtual icElemTypeSignature GetType () const
virtual const icChar * GetClassName () const
virtual void Describe (std::string &sDescription)
virtual bool Read (icUInt32Number size, CIccIO *pIO)
virtual bool Write (CIccIO *pIO)
void SetSize (icUInt16Number nInputChannels, icUInt16Number nOutputChannels)
icFloatNumber * GetMatrix ()
icFloatNumber * GetConstants ()
virtual bool Begin (icElemInterp nInterp, CIccTagMultiProcessElement *pMPE)
virtual void Apply (CIccApplyMpe *pApply, icFloatNumber *dstPixel, const icFloatNumber *srcPixel) const
virtual icValidateStatus Validate (icTagSignature sig, std::string &sReport, const CIccTagMultiProcessElement *pMPE=NULL) const
Public Member Functions inherited from CIccMultiProcessElement
CIccMultiProcessElement ()
virtual ~CIccMultiProcessElement ()
virtual icUInt16Number NumInputChannels () const
virtual icUInt16Number NumOutputChannels () const
virtual bool IsSupported ()
virtual CIccApplyMpe * GetNewApply (CIccApplyTagMpe *pApplyTag)
virtual bool IsAcs ()
virtual icAcsSignature GetBAcsSig ()
virtual icAcsSignature GetEAcsSig ()
virtual IIccExtensionMpe * GetExtension ()
Protected Attributes
icFloatNumber * m_pMatrix
icFloatNumber * m_pConstants
icUInt32Number m_size
icMatrixElemType m_type
Protected Attributes inherited from CIccMultiProcessElement
icUInt16Number m_nInputChannels
icUInt16Number m_nOutputChannels
Additional Inherited Members
Static Public Member Functions inherited from CIccMultiProcessElement
static CIccMultiProcessElement * Create (icElemTypeSignature sig)
Public Attributes inherited from CIccMultiProcessElement
icUInt32Number m_nReserved
Detailed Description
Class: CIccMpeMatrix
Purpose: The sampled float curve segment tag
Constructor & Destructor Documentation
CIccMpeMatrix::CIccMpeMatrix ()
Name: CIccMpeMatrix::CIccMpeMatrix
Purpose:
Args:
Return:
CIccMpeMatrix::CIccMpeMatrix (const CIccMpeMatrix & matrix)
Name: CIccMpeMatrix::CIccMpeMatrix
Purpose:
Args:
Return:
References CIccMultiProcessElement::m_nInputChannels, CIccMultiProcessElement::m_nOutputChannels, CIccMultiProcessElement::m_nReserved, m_pConstants, m_pMatrix, and m_size.
CIccMpeMatrix::~CIccMpeMatrix () virtual
Name: CIccMpeMatrix::~CIccMpeMatrix
Purpose:
Args:
Return:
Member Function Documentation
void CIccMpeMatrix::Apply (CIccApplyMpe * pApply, icFloatNumber * dstPixel, const icFloatNumber * srcPixel) const virtual
Name: CIccMpeMatrix::Apply
Purpose:
Args:
Return:
Implements CIccMultiProcessElement.
References ic3x3Matrix, ic3x4Matrix, ic4x3Matrix, ic4x4Matrix, and icOtherMatrix.
bool CIccMpeMatrix::Begin (icElemInterp nInterp, CIccTagMultiProcessElement * pMPE) virtual
Name: CIccMpeMatrix::Begin
Purpose:
Args:
Return:
Implements CIccMultiProcessElement.
References ic3x3Matrix, ic3x4Matrix, ic4x3Matrix, ic4x4Matrix, and icOtherMatrix.
void CIccMpeMatrix::Describe (std::string & sDescription) virtual
Name: CIccMpeMatrix::Describe
Purpose:
Args:
Return:
Implements CIccMultiProcessElement.
virtual const icChar* CIccMpeMatrix::GetClassName () const inline virtual
Implements CIccMultiProcessElement.
icFloatNumber* CIccMpeMatrix::GetConstants () inline
icFloatNumber* CIccMpeMatrix::GetMatrix () inline
virtual icElemTypeSignature CIccMpeMatrix::GetType () const inline virtual
Implements CIccMultiProcessElement.
References icSigMatrixElemType.
virtual CIccMultiProcessElement* CIccMpeMatrix::NewCopy () const inline virtual
Implements CIccMultiProcessElement.
CIccMpeMatrix & CIccMpeMatrix::operator= (const CIccMpeMatrix & matrix)
Name: &CIccMpeMatrix::operator=
Purpose:
Args:
Return:
References CIccMultiProcessElement::m_nInputChannels, CIccMultiProcessElement::m_nOutputChannels, CIccMultiProcessElement::m_nReserved, m_pConstants, m_pMatrix, and m_size.
bool CIccMpeMatrix::Read (icUInt32Number size, CIccIO * pIO) virtual
Name: CIccMpeMatrix::Read
Purpose:
Args:
Return:
Implements CIccMultiProcessElement.
References CIccIO::Read16(), CIccIO::Read32(), and CIccIO::ReadFloat32Float().
void CIccMpeMatrix::SetSize (icUInt16Number nInputChannels, icUInt16Number nOutputChannels)
Name: CIccMpeMatrix::SetSize
Purpose:
Args:
Return:
icValidateStatus CIccMpeMatrix::Validate (icTagSignature sig, std::string & sReport, const CIccTagMultiProcessElement * pMPE = NULL) const virtual
Name: CIccMpeMatrix::Validate
Purpose:
Args:
Return:
Implements CIccMultiProcessElement.
References CIccInfo::GetSigName(), icValidateCriticalError, icValidateCriticalErrorMsg, and CIccMultiProcessElement::Validate().
bool CIccMpeMatrix::Write (CIccIO * pIO) virtual
Name: CIccMpeMatrix::Write
Purpose:
Args:
Return:
Implements CIccMultiProcessElement.
References CIccIO::Write16(), CIccIO::Write32(), and CIccIO::WriteFloat32Float().
Member Data Documentation
icFloatNumber* CIccMpeMatrix::m_pConstants protected
Referenced by CIccMpeMatrix(), and operator=().
icFloatNumber* CIccMpeMatrix::m_pMatrix protected
Referenced by CIccMpeMatrix(), and operator=().
icUInt32Number CIccMpeMatrix::m_size protected
Referenced by CIccMpeMatrix(), and operator=().
icMatrixElemType CIccMpeMatrix::m_type protected
The documentation for this class was generated from the following files:
IccMpeBasic.h
IccMpeBasic.cpp