CIccTagMultiProcessElement Class Reference
CIccTagMultiProcessElement Class Reference
#include <IccTagMPE.h>
Public Member Functions
CIccTagMultiProcessElement (icUInt16Number nInputChannels=0, icUInt16Number nOutputChannels=0)
CIccTagMultiProcessElement (const CIccTagMultiProcessElement &lut)
CIccTagMultiProcessElement & operator= (const CIccTagMultiProcessElement &lut)
virtual CIccTag * NewCopy () const
virtual ~CIccTagMultiProcessElement ()
virtual bool IsSupported ()
virtual icTagTypeSignature GetType () const
virtual const icChar * GetClassName () const
virtual void Describe (std::string &sDescription)
virtual bool Read (icUInt32Number size, CIccIO *pIO)
virtual bool Write (CIccIO *pIO)
virtual void Attach (CIccMultiProcessElement *pElement)
CIccMultiProcessElement * GetElement (int nIndex)
void DeleteElement (int nIndex)
virtual bool Begin (icElemInterp nInterp=icElemInterpLinear)
virtual CIccApplyTagMpe * GetNewApply ()
virtual void Apply (CIccApplyTagMpe *pApply, icFloatNumber *pDestPixel, const icFloatNumber *pSrcPixel) const
virtual icValidateStatus Validate (icTagSignature sig, std::string &sReport, const CIccProfile *pProfile=NULL) const
icUInt16Number NumInputChannels () const
icUInt16Number NumOutputChannels () const
Public Member Functions inherited from CIccTag
CIccTag ()
virtual ~CIccTag ()
virtual bool IsArrayType ()
virtual bool IsMBBType ()
virtual IIccExtensionTag * GetExtension ()
Protected Member Functions
virtual void Clean ()
virtual void GetNextElemIterator (CIccMultiProcessElementList::iterator &itr)
virtual icInt32Number ElementIndex (CIccMultiProcessElement *pElem)
virtual CIccMultiProcessElementList::iterator GetFirstElem ()
virtual CIccMultiProcessElementList::iterator GetLastElem ()
Protected Attributes
icUInt16Number m_nInputChannels
icUInt16Number m_nOutputChannels
CIccMultiProcessElementList * m_list
icUInt32Number m_nProcElements
icPositionNumber * m_position
icUInt16Number m_nBufChannels
Additional Inherited Members
Static Public Member Functions inherited from CIccTag
static CIccTag * Create (icTagTypeSignature sig)
Public Attributes inherited from CIccTag
icUInt32Number m_nReserved
Detailed Description
Class: CIccTagMultiProcessElement
Purpose: A general purpose processing tag
Constructor & Destructor Documentation
CIccTagMultiProcessElement::CIccTagMultiProcessElement (icUInt16Number nInputChannels = 0, icUInt16Number nOutputChannels = 0)
Name: CIccTagMultiProcessElement::CIccTagMultiProcessElement
Purpose:
Args:
Return:
CIccTagMultiProcessElement::CIccTagMultiProcessElement (const CIccTagMultiProcessElement & lut)
Name: CIccTagMultiProcessElement::CIccTagMultiProcessElement
Purpose:
Args:
Return:
References m_list, m_nInputChannels, m_nOutputChannels, m_nProcElements, CIccTag::m_nReserved, m_position, CIccMultiProcessElement::NewCopy(), and CIccMultiProcessElementPtr::ptr.
CIccTagMultiProcessElement::~CIccTagMultiProcessElement () virtual
Name: CIccTagMultiProcessElement::~CIccTagMultiProcessElement
Purpose:
Args:
Return:
Member Function Documentation
void CIccTagMultiProcessElement::Apply (CIccApplyTagMpe * pApply, icFloatNumber * pDestPixel, const icFloatNumber * pSrcPixel) const virtual
Name: CIccTagMultiProcessElement::Apply
Purpose:
Args:
Return:
References CIccMultiProcessElement::Apply(), CIccApplyTagMpe::begin(), CIccApplyTagMpe::end(), CIccApplyTagMpe::GetBuf(), CIccDblPixelBuffer::GetDstBuf(), CIccApplyTagMpe::GetList(), CIccDblPixelBuffer::GetSrcBuf(), CIccMultiProcessElement::IsAcs(), and CIccDblPixelBuffer::Switch().
Referenced by CIccXformMpe::Apply().
void CIccTagMultiProcessElement::Attach (CIccMultiProcessElement * pElement) virtual
Name: CIccTagMultiProcessElement::Attach
Purpose:
Args:
Return:
References CIccMultiProcessElementPtr::ptr.
bool CIccTagMultiProcessElement::Begin (icElemInterp nInterp = icElemInterpLinear) virtual
Name: CIccTagMultiProcessElement::Begin
Purpose:
Args:
Return:
References CIccMultiProcessElement::Begin(), and CIccMultiProcessElement::NumOutputChannels().
void CIccTagMultiProcessElement::Clean () protected virtual
Name: CIccTagMultiProcessElement::Clean
Purpose:
Args:
Return:
void CIccTagMultiProcessElement::DeleteElement (int nIndex)
void CIccTagMultiProcessElement::Describe (std::string & sDescription) virtual
Name: CIccTagMultiProcessElement::Describe
Purpose:
Args:
Return:
Reimplemented from CIccTag.
icInt32Number CIccTagMultiProcessElement::ElementIndex (CIccMultiProcessElement * pElem) protected virtual
Name: CIccTagMultiProcessElement::ElementIndex
Purpose:
Args:
Return:
virtual const icChar* CIccTagMultiProcessElement::GetClassName () const inline virtual
Reimplemented from CIccTag.
CIccMultiProcessElement * CIccTagMultiProcessElement::GetElement (int nIndex)
Name: CIccTagMultiProcessElement::GetElement
Purpose:
Args:
Return:
CIccMultiProcessElementList::iterator CIccTagMultiProcessElement::GetFirstElem () protected virtual
CIccMultiProcessElementList::iterator CIccTagMultiProcessElement::GetLastElem () protected virtual
CIccApplyTagMpe * CIccTagMultiProcessElement::GetNewApply () virtual
Name: CIccTagMultiProcessElement::GetNewApply
Purpose:
Args:
Return:
References CIccApplyTagMpe::AppendElem(), CIccDblPixelBuffer::Begin(), CIccApplyTagMpe::GetBuf(), and CIccDblPixelBuffer::UpdateChannels().
void CIccTagMultiProcessElement::GetNextElemIterator (CIccMultiProcessElementList::iterator & itr) protected virtual
Name: CIccTagMultiProcessElement::GetNextElemIterator
Purpose:
Args:
Return:
virtual icTagTypeSignature CIccTagMultiProcessElement::GetType () const inline virtual
Function: GetType()
Purpose: Get Tag Type. Each derived tag will implement it's own GetType() function.
Reimplemented from CIccTag.
References icSigMultiProcessElementType.
bool CIccTagMultiProcessElement::IsSupported () virtual
Name: CIccTagMultiProcessElement::IsSupported
Purpose:
Args:
Return:
Reimplemented from CIccTag.
virtual CIccTag* CIccTagMultiProcessElement::NewCopy () const inline virtual
Function: NewCopy(sDescription) Each derived tag will implement it's own NewCopy() function.
Parameter(s): none
Returns a new CIccTag object that is a copy of this object.
Reimplemented from CIccTag.
icUInt16Number CIccTagMultiProcessElement::NumInputChannels () const inline
icUInt16Number CIccTagMultiProcessElement::NumOutputChannels () const inline
CIccTagMultiProcessElement & CIccTagMultiProcessElement::operator= (const CIccTagMultiProcessElement & lut)
Name: &operator=
Purpose:
Args:
Return:
References m_list, m_nInputChannels, m_nOutputChannels, m_nProcElements, CIccTag::m_nReserved, m_position, CIccMultiProcessElement::NewCopy(), and CIccMultiProcessElementPtr::ptr.
bool CIccTagMultiProcessElement::Read (icUInt32Number size, CIccIO * pIO) virtual
Name: CIccTagMultiProcessElement::Read
Purpose:
Args:
Return:
Reimplemented from CIccTag.
References CIccMultiProcessElement::Create(), icSeekSet, CIccMultiProcessElementPtr::ptr, CIccMultiProcessElement::Read(), CIccIO::Read16(), CIccIO::Read32(), CIccIO::Seek(), and CIccIO::Tell().
icValidateStatus CIccTagMultiProcessElement::Validate (icTagSignature sig, std::string & sReport, const CIccProfile * pProfile = NULL) const virtual
Name: CIccTagMultiProcessElement::Validate
Purpose:
Args:
Return:
Reimplemented from CIccTag.
References CIccMultiProcessElement::GetClassName(), CIccInfo::GetSigName(), icMaxStatus(), icValidateCriticalError, icValidateCriticalErrorMsg, icValidateOK, icValidateWarning, icValidateWarningMsg, CIccMultiProcessElement::NumOutputChannels(), and CIccMultiProcessElement::Validate().
bool CIccTagMultiProcessElement::Write (CIccIO * pIO) virtual
Name: CIccTagMultiProcessElement::Write
Purpose:
Args:
Return:
Reimplemented from CIccTag.
References icSeekSet, icPositionNumber::offset, CIccIO::Seek(), icPositionNumber::size, CIccIO::Sync32(), CIccIO::Tell(), CIccIO::Write16(), and CIccIO::Write32().
Member Data Documentation
CIccMultiProcessElementList* CIccTagMultiProcessElement::m_list protected
Referenced by CIccTagMultiProcessElement(), and operator=().
icUInt16Number CIccTagMultiProcessElement::m_nBufChannels protected
icUInt16Number CIccTagMultiProcessElement::m_nInputChannels protected
Referenced by CIccTagMultiProcessElement(), and operator=().
icUInt16Number CIccTagMultiProcessElement::m_nOutputChannels protected
Referenced by CIccTagMultiProcessElement(), and operator=().
icUInt32Number CIccTagMultiProcessElement::m_nProcElements protected
Referenced by CIccTagMultiProcessElement(), and operator=().
icPositionNumber* CIccTagMultiProcessElement::m_position protected
Referenced by CIccTagMultiProcessElement(), and operator=().
The documentation for this class was generated from the following files:
IccTagMPE.h
IccTagMPE.cpp