CIccCmm Class Reference
CIccCmm Class Reference
#include <IccCmm.h>
Public Member Functions
CIccCmm (icColorSpaceSignature nSrcSpace=icSigUnknownData, icColorSpaceSignature nDestSpace=icSigUnknownData, bool bFirstInput=true)
virtual ~CIccCmm ()
virtual CIccPCS * GetPCS ()
virtual icStatusCMM AddXform (const icChar *szProfilePath, icRenderingIntent nIntent=icUnknownIntent, icXformInterp nInterp=icInterpLinear, icXformLutType nLutType=icXformLutColor, bool bUseMpeTags=true, CIccCreateXformHintManager *pHintManager=NULL)
Must make at least one call to some form of AddXform() before calling Begin()
virtual icStatusCMM AddXform (icUInt8Number *pProfileMem, icUInt32Number nProfileLen, icRenderingIntent nIntent=icUnknownIntent, icXformInterp nInterp=icInterpLinear, icXformLutType nLutType=icXformLutColor, bool bUseMpeTags=true, CIccCreateXformHintManager *pHintManager=NULL)
virtual icStatusCMM AddXform (CIccProfile *pProfile, icRenderingIntent nIntent=icUnknownIntent, icXformInterp nInterp=icInterpLinear, icXformLutType nLutType=icXformLutColor, bool bUseMpeTags=true, CIccCreateXformHintManager *pHintManager=NULL)
virtual icStatusCMM AddXform (CIccProfile &Profile, icRenderingIntent nIntent=icUnknownIntent, icXformInterp nInterp=icInterpLinear, icXformLutType nLutType=icXformLutColor, bool bUseMpeTags=true, CIccCreateXformHintManager *pHintManager=NULL)
virtual icStatusCMM Begin (bool bAllocNewApply=true)
virtual CIccApplyCmm * GetNewApplyCmm (icStatusCMM &status)
virtual CIccApplyCmm * GetApply ()
virtual icStatusCMM Apply (icFloatNumber *DstPixel, const icFloatNumber *SrcPixel)
virtual icStatusCMM Apply (icFloatNumber *DstPixel, const icFloatNumber *SrcPixel, icUInt32Number nPixels)
virtual icStatusCMM RemoveAllIO ()
virtual icUInt32Number GetNumXforms () const
Returns the number of profiles/transforms added.
icColorSpaceSignature GetSourceSpace () const
Returns the source color space.
icColorSpaceSignature GetDestSpace () const
Returns the destination color space.
icColorSpaceSignature GetLastSpace () const
Returns the color space of the last profile added.
icRenderingIntent GetLastIntent () const
Returns the rendering intent of the last profile added.
icUInt16Number GetSourceSamples () const
Returns the number of samples in the source color space.
icUInt16Number GetDestSamples () const
Returns the number of samples in the destination color space.
bool Valid () const
Checks if this is a valid CMM object.
icStatusCMM ToInternalEncoding (icFloatNumber *pInternal, const icUInt8Number *pData)
icStatusCMM ToInternalEncoding (icFloatNumber *pInternal, const icUInt16Number *pData)
icStatusCMM FromInternalEncoding (icUInt8Number *pData, icFloatNumber *pInternal)
icStatusCMM FromInternalEncoding (icUInt16Number *pData, icFloatNumber *pInternal)
virtual icColorSpaceSignature GetFirstXformSource ()
virtual icColorSpaceSignature GetLastXformDest ()
Static Public Member Functions
static bool IsInGamut (icFloatNumber *pData)
static icStatusCMM ToInternalEncoding (icColorSpaceSignature nSpace, icFloatColorEncoding nEncode, icFloatNumber *pInternal, const icFloatNumber *pData, bool bClip=true)
Functions for converting to Internal representation of pixel colors.
static icStatusCMM ToInternalEncoding (icColorSpaceSignature nSpace, icFloatNumber *pInternal, const icUInt8Number *pData)
static icStatusCMM ToInternalEncoding (icColorSpaceSignature nSpace, icFloatNumber *pInternal, const icUInt16Number *pData)
static icStatusCMM FromInternalEncoding (icColorSpaceSignature nSpace, icFloatColorEncoding nEncode, icFloatNumber *pData, const icFloatNumber *pInternal, bool bClip=true)
Functions for converting from Internal representation of pixel colors.
static icStatusCMM FromInternalEncoding (icColorSpaceSignature nSpace, icUInt8Number *pData, const icFloatNumber *pInternal)
static icStatusCMM FromInternalEncoding (icColorSpaceSignature nSpace, icUInt16Number *pData, const icFloatNumber *pInternal)
static const icChar * GetFloatColorEncoding (icFloatColorEncoding val)
static icFloatColorEncoding GetFloatColorEncoding (const icChar *val)
Protected Attributes
CIccApplyCmm * m_pApply
bool m_bValid
bool m_bLastInput
icColorSpaceSignature m_nSrcSpace
icColorSpaceSignature m_nDestSpace
icColorSpaceSignature m_nLastSpace
icRenderingIntent m_nLastIntent
CIccXformList * m_Xforms
Friends
class CIccApplyCmm
Detailed Description
Type: Class
Purpose: Defines a class that allows one or more profiles to be applied in order that they are Added.
Constructor & Destructor Documentation
CIccCmm::CIccCmm (icColorSpaceSignature nSrcSpace = icSigUnknownData, icColorSpaceSignature nDestSpace = icSigUnknownData, bool bFirstInput = true)
Name: CIccCmm::CIccCmm
Purpose: Constructor
Args: nSrcSpace = signature of the source color space, nDestSpace = signature of the destination color space, bFirstInput = true if the first profile added is an input profile
References icUnknownIntent, m_bLastInput, m_bValid, m_nDestSpace, m_nLastIntent, m_nLastSpace, m_nSrcSpace, m_pApply, and m_Xforms.
CIccCmm::~CIccCmm () virtual
Name: CIccCmm::~CIccCmm
Purpose: Destructor
References m_pApply, and m_Xforms.
Member Function Documentation
icStatusCMM CIccCmm::AddXform (const icChar * szProfilePath, icRenderingIntent nIntent = icUnknownIntent, icXformInterp nInterp = icInterpLinear, icXformLutType nLutType = icXformLutColor, bool bUseMpeTags = true, CIccCreateXformHintManager * pHintManager = NULL) virtual
Must make at least one call to some form of AddXform() before calling Begin()
Name: CIccCmm::AddXform
Purpose: Adds a profile at the end of the Xform list
Args: szProfilePath = file name of the profile to be added, nIntent = rendering intent to be used with the profile, nInterp = type of interpolation to be used with the profile, nLutType = selection of which transform lut to use pHintManager = hints for creating the xform
Return: icCmmStatOk, if the profile was added to the list succesfully
Reimplemented in CIccMruCmm, and CIccNamedColorCmm.
References icCmmStatCantOpenProfile, icCmmStatOk, and OpenIccProfile().
Referenced by AddXform(), CIccEvalCompare::EvaluateProfile(), and CIccPRMG::EvaluateProfile().
icStatusCMM CIccCmm::AddXform (icUInt8Number * pProfileMem, icUInt32Number nProfileLen, icRenderingIntent nIntent = icUnknownIntent, icXformInterp nInterp = icInterpLinear, icXformLutType nLutType = icXformLutColor, bool bUseMpeTags = true, CIccCreateXformHintManager * pHintManager = NULL) virtual
Name: CIccCmm::AddXform
Purpose: Adds a profile at the end of the Xform list
Args: pProfileMem = ptr to profile loaded into memory. Note: this memory needs to be available until after the Begin() function is called. nProfileLen = size in bytes of profile loaded into memory nIntent = rendering intent to be used with the profile, nInterp = type of interpolation to be used with the profile, nLutType = selection of which transform lut to use bUseMpeTags = flag to indicate the use MPE flags if available pHintManager = hints for creating the xform
Return: icCmmStatOk, if the profile was added to the list succesfully
Reimplemented in CIccMruCmm.
References AddXform(), CIccProfile::Attach(), CIccMemIO::Attach(), CIccMemIO, CIccProfile, icCmmStatCantOpenProfile, and icCmmStatOk.
icStatusCMM CIccCmm::AddXform (CIccProfile * pProfile, icRenderingIntent nIntent = icUnknownIntent, icXformInterp nInterp = icInterpLinear, icXformLutType nLutType = icXformLutColor, bool bUseMpeTags = true, CIccCreateXformHintManager * pHintManager = NULL) virtual
Name: CIccCmm::AddXform
Purpose: Adds a profile at the end of the Xform list
Args: pProfile = pointer to the CIccProfile object to be added, nIntent = rendering intent to be used with the profile, nInterp = type of interpolation to be used with the profile, nLutType = selection of which transform lut to use bUseMpeTags = flag to indicate the use MPE flags if available pHintManager = hints for creating the xform
Return: icCmmStatOk, if the profile was added to the list succesfully
Reimplemented in CIccMruCmm, and CIccNamedColorCmm.
References icHeader::colorSpace, CIccXform::Create(), icHeader::deviceClass, icCmmStatBadLutType, icCmmStatBadSpaceLink, icCmmStatBadXform, icCmmStatInvalidProfile, icCmmStatOk, icPerceptual, icSigAbstractClass, icSigGamutData, icSigLinkClass, icSigNamedData, icSigUnknownData, icUnknownIntent, icXformLutColor, icXformLutGamut, icXformLutPreview, IsCompatSpace, m_bLastInput, CIccProfile::m_Header, m_nLastIntent, m_nLastSpace, m_nSrcSpace, m_Xforms, icHeader::pcs, CIccXformPtr::ptr, and icHeader::renderingIntent.
icStatusCMM CIccCmm::AddXform (CIccProfile & Profile, icRenderingIntent nIntent = icUnknownIntent, icXformInterp nInterp = icInterpLinear, icXformLutType nLutType = icXformLutColor, bool bUseMpeTags = true, CIccCreateXformHintManager * pHintManager = NULL) virtual
Name: CIccCmm::AddXform
Purpose: Adds a profile at the end of the Xform list
Args: Profile = reference a CIccProfile object that will be copies and added, nIntent = rendering intent to be used with the profile, nInterp = type of interpolation to be used with the profile, nLutType = selection of which transform lut to use bUseMpeTags = flag to indicate the use MPE flags if available pHintManager = hints for creating the xform
Return: icCmmStatOk, if the profile was added to the list succesfully
Reimplemented in CIccMruCmm.
References AddXform(), CIccProfile, icCmmStatAllocErr, and icCmmStatOk.
icStatusCMM CIccCmm::Apply (icFloatNumber * DstPixel, const icFloatNumber * SrcPixel) virtual
Name: CIccCmm::Apply
Purpose: Uses the m_pApply object allocated during Begin to Apply the transformations associated with the CMM.
Reimplemented in CIccNamedColorCmm.
References CIccApplyCmm::Apply(), and m_pApply.
Referenced by CIccNamedColorCmm::Apply(), CIccApplyMruCmm::Apply(), CIccEvalCompare::EvaluateProfile(), and CIccPRMG::EvaluateProfile().
icStatusCMM CIccCmm::Apply (icFloatNumber * DstPixel, const icFloatNumber * SrcPixel, icUInt32Number nPixels) virtual
Name: CIccCmm::Apply
Purpose: Uses the m_pApply object allocated during Begin to Apply the transformations associated with the CMM.
Reimplemented in CIccNamedColorCmm.
References CIccApplyCmm::Apply(), and m_pApply.
icStatusCMM CIccCmm::Begin (bool bAllocApplyCmm = true) virtual
Name: CIccCmm::GetNewApplyCmm
Purpose: Does the initialization of the Xforms before Apply() is called. Must be called before Apply().
Reimplemented in CIccNamedColorCmm.
References GetNewApplyCmm(), icCmmStatBadSpaceLink, icCmmStatOk, icSigNamedData, icSigUnknownData, IsCompatSpace, m_nDestSpace, m_nLastSpace, m_nSrcSpace, m_pApply, and m_Xforms.
Referenced by CIccMruCmm::Attach(), CIccEvalCompare::EvaluateProfile(), and CIccPRMG::EvaluateProfile().
icStatusCMM CIccCmm::FromInternalEncoding (icColorSpaceSignature nSpace, icFloatColorEncoding nEncode, icFloatNumber * pData, const icFloatNumber * pInternal, bool bClip = true) static
Functions for converting from Internal representation of pixel colors.
Name: CIccCmm::FromInternalEncoding
Purpose: Functions for converting from Internal representation of pixel colors.
Args: nSpace = color space signature of the data, nEncode = icFloatColorEncoding type of the data, pData = converted data is stored here, pInternal = the data to be converted bClip = flag to clip data to internal range
References icABtoU8(), icCmmStatBadColorEncoding, icCmmStatOk, icDtoUSF(), icEncode16Bit, icEncode16BitV2, icEncode8Bit, icEncodeFloat, icEncodePercent, icEncodeValue, icFtoU16(), icFtoU8(), icGetSpaceSamples(), icIsSpaceCLR(), icLabFromPcs(), icSigLabData, icSigNamedData, icSigXYZData, icXyzFromPcs(), and CIccPCS::Lab4ToLab2().
Referenced by FromInternalEncoding().
icStatusCMM CIccCmm::FromInternalEncoding (icColorSpaceSignature nSpace, icUInt8Number * pData, const icFloatNumber * pInternal) static
Name: CIccCmm::FromInternalEncoding
Purpose: Functions for converting from Internal representation of 8 bit pixel colors.
Args: nSpace = color space signature of the data, nEncode = icFloatColorEncoding type of the data, pData = converted data is stored here, pInternal = the data to be converted bClip = flag to clip data to internal range
References FromInternalEncoding(), icCmmStatOk, icEncode8Bit, icFtoU8(), icGetSpaceSamples(), icSigCmykData, and icSigRgbData.
icStatusCMM CIccCmm::FromInternalEncoding (icColorSpaceSignature nSpace, icUInt16Number * pData, const icFloatNumber * pInternal) static
Name: CIccCmm::FromInternalEncoding
Purpose: Functions for converting from Internal representation of 16 bit pixel colors.
Args: nSpace = color space signature of the data, nEncode = icFloatColorEncoding type of the data, pData = converted data is stored here, pInternal = the data to be converted bClip = flag to clip data to internal range
References FromInternalEncoding(), icCmmStatOk, icEncode16Bit, icFtoU16(), icGetSpaceSamples(), icSigCmykData, and icSigRgbData.
icStatusCMM CIccCmm::FromInternalEncoding (icUInt8Number * pData, icFloatNumber * pInternal) inline
References FromInternalEncoding().
Referenced by FromInternalEncoding().
icStatusCMM CIccCmm::FromInternalEncoding (icUInt16Number * pData, icFloatNumber * pInternal) inline
References FromInternalEncoding().
Referenced by FromInternalEncoding().
virtual CIccApplyCmm* CIccCmm::GetApply () inline virtual
icUInt16Number CIccCmm::GetDestSamples () const inline
Returns the number of samples in the destination color space.
References icGetSpaceSamples().
Referenced by CIccApplyCmm::Apply(), CIccApplyNamedColorCmm::Apply(), and CIccApplyMruCmm::Init().
icColorSpaceSignature CIccCmm::GetDestSpace () const inline
Returns the destination color space.
Referenced by CIccApplyNamedColorCmm::Apply(), and CIccMruCmm::Attach().
icColorSpaceSignature CIccCmm::GetFirstXformSource () virtual
Name: CIccCmm::GetFirstXformSource
Purpose: Get source colorspace of first transform (similar to m_nSrcSpace with differences in dev colorimetric spaces)
Return: colorspace
Reimplemented in CIccMruCmm.
References m_nSrcSpace, and m_Xforms.
Referenced by CIccMruCmm::GetFirstXformSource().
const icChar * CIccCmm::GetFloatColorEncoding (icFloatColorEncoding val) static
Name: CIccCmm::GetFloatColorEncoding
Purpose: Converts the encoding type to characters for printing
Args: val = encoding type
Return: characters for printing
References icEncode16Bit, icEncode16BitV2, icEncode8Bit, icEncodeFloat, icEncodePercent, and icEncodeValue.
icFloatColorEncoding CIccCmm::GetFloatColorEncoding (const icChar * val) static
Name: CIccCmm::GetFloatColorEncoding
Purpose: Converts the string containing encoding type to icFloatColorEncoding
Args: val = string containing encoding type
Return: encoding type
References icEncode16Bit, icEncode16BitV2, icEncode8Bit, icEncodeFloat, icEncodePercent, icEncodeUnknown, icEncodeValue, and stricmp.
icRenderingIntent CIccCmm::GetLastIntent () const inline
Returns the rendering intent of the last profile added.
Referenced by CIccMruCmm::Attach().
icColorSpaceSignature CIccCmm::GetLastSpace () const inline
Returns the color space of the last profile added.
Referenced by CIccMruCmm::Attach().
icColorSpaceSignature CIccCmm::GetLastXformDest () virtual
Name: CIccCmm::GetNumXforms
Purpose: Get source colorspace of last transform (similar to m_nSrcSpace with differences in dev colorimetric spaces)
Return: colorspace
Reimplemented in CIccMruCmm.
References m_nDestSpace, and m_Xforms.
Referenced by CIccMruCmm::GetLastXformDest().
CIccApplyCmm * CIccCmm::GetNewApplyCmm (icStatusCMM & status) virtual
Name: CIccCmm::GetNewApplyCmm
Purpose: Allocates an CIccApplyCmm object that does the initialization of the Xforms that provides an Apply() function. Multiple CIccApplyCmm objects can be allocated and used in separate threads.
Reimplemented in CIccMruCmm.
References CIccApplyCmm::AppendApplyXform(), CIccApplyCmm, icCmmStatAllocErr, icCmmStatOk, m_bValid, and m_Xforms.
Referenced by Begin(), and CIccNamedColorCmm::Begin().
icUInt32Number CIccCmm::GetNumXforms () const virtual
Returns the number of profiles/transforms added.
Name: CIccCmm::GetNumXforms
Purpose: Get number of xforms in the xform list
Return: number of m_Xforms
Reimplemented in CIccMruCmm.
References m_Xforms.
Referenced by CIccMruCmm::GetNumXforms().
virtual CIccPCS* CIccCmm::GetPCS () inline virtual
Reimplemented in CIccMruCmm.
Referenced by CIccApplyCmm::CIccApplyCmm(), and CIccMruCmm::GetPCS().
icUInt16Number CIccCmm::GetSourceSamples () const inline
Returns the number of samples in the source color space.
References icGetSpaceSamples().
Referenced by CIccApplyCmm::Apply(), CIccApplyNamedColorCmm::Apply(), and CIccApplyMruCmm::Init().
icColorSpaceSignature CIccCmm::GetSourceSpace () const inline
Returns the source color space.
Referenced by CIccApplyNamedColorCmm::Apply(), and CIccMruCmm::Attach().
bool CIccCmm::IsInGamut (icFloatNumber * pInternal) static
Name: CIccCmm::IsInGamut
Purpose: Function to check if internal representation of gamut is in gamut. Note since gamut table is 8 bit and a color is considered to be in out of gamut if the value is not zero. Then we need to check where the 8 bit representation of the internal value is not zero.
Args: pInternal = internal pixel representation of gamut value
Return: true if in gamut, false if out of gamut
icStatusCMM CIccCmm::RemoveAllIO () virtual
Name: CIccCmm::RemoveAllIO()
Purpose: Remove any attachments to CIccIO objects associated with the profiles related to the transforms attached to the CMM. Must be called after Begin().
Return: icCmmStatOK - All IO objects removed icCmmStatBadXform - Begin() has not been performed.
Reimplemented in CIccMruCmm.
References icCmmStatBadXform, icCmmStatOk, m_Xforms, and Valid().
Referenced by CIccMruCmm::RemoveAllIO().
icStatusCMM CIccCmm::ToInternalEncoding (icColorSpaceSignature nSpace, icFloatColorEncoding nEncode, icFloatNumber * pInternal, const icFloatNumber * pData, bool bClip = true) static
Functions for converting to Internal representation of pixel colors.
Name: CIccCmm::ToInternalEncoding
Purpose: Functions for converting to Internal representation of pixel colors.
Args: nSpace = color space signature of the data, nEncode = icFloatColorEncoding type of the data, pInternal = converted data is stored here, pData = the data to be converted bClip = flag to clip to internal range
References icCmmStatBadColorEncoding, icCmmStatOk, icEncode16Bit, icEncode16BitV2, icEncode8Bit, icEncodeFloat, icEncodePercent, icEncodeValue, icGetSpaceSamples(), icIsSpaceCLR(), icLabToPcs(), icSigLabData, icSigNamedData, icSigXYZData, icU16toF(), icU8toAB(), icU8toF(), icUSFtoD(), icXyzToPcs(), and CIccPCS::Lab2ToLab4().
Referenced by ToInternalEncoding().
icStatusCMM CIccCmm::ToInternalEncoding (icColorSpaceSignature nSpace, icFloatNumber * pInternal, const icUInt8Number * pData) static
Name: CIccCmm::ToInternalEncoding
Purpose: Functions for converting to Internal representation of 8 bit pixel colors.
Args: nSpace = color space signature of the data, nEncode = icFloatColorEncoding type of the data, pInternal = converted data is stored here, pData = the data to be converted bClip = flag to clip to internal range
References icCmmStatOk, icEncode8Bit, icGetSpaceSamples(), icSigCmykData, icSigRgbData, and ToInternalEncoding().
icStatusCMM CIccCmm::ToInternalEncoding (icColorSpaceSignature nSpace, icFloatNumber * pInternal, const icUInt16Number * pData) static
Name: CIccCmm::ToInternalEncoding
Purpose: Functions for converting to Internal representation of 16 bit pixel colors.
Args: nSpace = color space signature of the data, nEncode = icFloatColorEncoding type of the data, pInternal = converted data is stored here, pData = the data to be converted bClip = flag to clip to internal range
References icCmmStatOk, icEncode16Bit, icGetSpaceSamples(), icSigCmykData, icSigRgbData, and ToInternalEncoding().
icStatusCMM CIccCmm::ToInternalEncoding (icFloatNumber * pInternal, const icUInt8Number * pData) inline
References ToInternalEncoding().
Referenced by ToInternalEncoding().
icStatusCMM CIccCmm::ToInternalEncoding (icFloatNumber * pInternal, const icUInt16Number * pData) inline
References ToInternalEncoding().
Referenced by ToInternalEncoding().
bool CIccCmm::Valid () const inline
Checks if this is a valid CMM object.
Referenced by CIccMruCmm::Attach(), and RemoveAllIO().
Friends And Related Function Documentation
friend class CIccApplyCmm friend
Referenced by GetNewApplyCmm().
Member Data Documentation
bool CIccCmm::m_bLastInput protected
Referenced by AddXform(), CIccNamedColorCmm::AddXform(), and CIccCmm().
bool CIccCmm::m_bValid protected
Referenced by CIccCmm(), CIccNamedColorCmm::GetNewApply(), and GetNewApplyCmm().
icColorSpaceSignature CIccCmm::m_nDestSpace protected
Referenced by CIccApplyCmm::Apply(), CIccMruCmm::Attach(), Begin(), CIccNamedColorCmm::Begin(), CIccCmm(), and GetLastXformDest().
icRenderingIntent CIccCmm::m_nLastIntent protected
Referenced by AddXform(), CIccNamedColorCmm::AddXform(), CIccMruCmm::Attach(), and CIccCmm().
icColorSpaceSignature CIccCmm::m_nLastSpace protected
Referenced by AddXform(), CIccNamedColorCmm::AddXform(), CIccMruCmm::Attach(), Begin(), CIccNamedColorCmm::Begin(), and CIccCmm().
icColorSpaceSignature CIccCmm::m_nSrcSpace protected
Referenced by AddXform(), CIccNamedColorCmm::AddXform(), CIccApplyCmm::Apply(), CIccMruCmm::Attach(), Begin(), CIccNamedColorCmm::Begin(), CIccCmm(), and GetFirstXformSource().
CIccApplyCmm* CIccCmm::m_pApply protected
Referenced by Apply(), CIccNamedColorCmm::Apply(), Begin(), CIccNamedColorCmm::Begin(), CIccCmm(), and ~CIccCmm().
CIccXformList* CIccCmm::m_Xforms protected
Referenced by AddXform(), CIccNamedColorCmm::AddXform(), Begin(), CIccNamedColorCmm::Begin(), CIccCmm(), GetFirstXformSource(), GetLastXformDest(), CIccNamedColorCmm::GetNewApply(), GetNewApplyCmm(), GetNumXforms(), RemoveAllIO(), CIccNamedColorCmm::SetLastXformDest(), and ~CIccCmm().
The documentation for this class was generated from the following files:
IccCmm.h
IccCmm.cpp