CIccProfileDescText Class Reference
CIccProfileDescText Class Reference
#include <IccTagBasic.h>
Public Member Functions
CIccProfileDescText ()
CIccProfileDescText (const CIccProfileDescText &IPDC)
CIccProfileDescText & operator= (const CIccProfileDescText &ProfDescText)
virtual ~CIccProfileDescText ()
bool SetType (icTagTypeSignature nType)
virtual icTagTypeSignature GetType () const
CIccTag * GetTag () const
virtual void Describe (std::string &sDescription)
virtual bool Read (icUInt32Number size, CIccIO *pIO)
virtual bool Write (CIccIO *pIO)
Public Attributes
bool m_bNeedsPading
Protected Attributes
CIccTag * m_pTag
Detailed Description
Data Class: CIccProfileDescText
Purpose: Private text class for CIccProfileDescStruct. Text can be either a CIccTagTextDescription or a CIccTagMultiLocalizedUnicode so this class provides a single interface to both.
Constructor & Destructor Documentation
CIccProfileDescText::CIccProfileDescText ()
Name: CIccProfileDescText::CIccProfileDescText
Purpose: Constructor
CIccProfileDescText::CIccProfileDescText (const CIccProfileDescText & IPDC)
Name: CIccProfileDescText::CIccProfileDescText
Purpose: Copy Constructor
Args: IPDC = The CIccTagUnknown object to be copied
References m_bNeedsPading, m_pTag, and CIccTag::NewCopy().
CIccProfileDescText::~CIccProfileDescText () virtual
Name: CIccProfileDescText::~CIccProfileDescText
Purpose: Destructor
Member Function Documentation
void CIccProfileDescText::Describe (std::string & sDescription) virtual
Name: CIccProfileDescText::Describe
Purpose: Dump data associated with the tag to a string
Args: sDescription - string to concatenate tag dump to
CIccTag* CIccProfileDescText::GetTag () const inline
icTagTypeSignature CIccProfileDescText::GetType () const virtual
Name: CIccProfileDescText::SetType
Purpose: Gets the type of the profile description text. Could be either a MultiLocalizedUnicodeType or a TextDescriptionType.
References icSigUnknownType.
CIccProfileDescText & CIccProfileDescText::operator= (const CIccProfileDescText & ProfDescText)
Name: CIccProfileDescText::operator=
Purpose: Copy Operator
Args: ProfDescText = The CIccProfileDescText object to be copied
References m_bNeedsPading, m_pTag, and CIccTag::NewCopy().
bool CIccProfileDescText::Read (icUInt32Number size, CIccIO * pIO) virtual
Name: CIccProfileDescText::Read
Purpose: Read in the tag contents into a data block
Args: size - # of bytes in tag, pIO - IO object to read tag from
Return: true = successful, false = failure
References icSeekSet, icSigTextDescriptionType, CIccIO::Read32(), CIccIO::Seek(), CIccIO::Sync32(), and CIccIO::Tell().
Referenced by CIccTagProfileSeqDesc::Read().
bool CIccProfileDescText::SetType (icTagTypeSignature nType)
Name: CIccProfileDescText::SetType
Purpose: Sets the type of the profile description text. Could be either a MultiLocalizedUnicodeType or a TextDescriptionType.
Args: nType = the tag type signature
Return: true = successful, false = failure
References CIccTag::Create(), icSigMultiLocalizedUnicodeType, and icSigTextDescriptionType.
bool CIccProfileDescText::Write (CIccIO * pIO) virtual
Name: CIccProfileDescText::Write
Purpose: Write the tag to a file
Args: pIO - The IO object to write tag to.
Return: true = succesful, false = failure
References CIccIO::Align32(), and icSigTextDescriptionType.
Member Data Documentation
bool CIccProfileDescText::m_bNeedsPading
Referenced by CIccProfileDescText(), and operator=().
CIccTag* CIccProfileDescText::m_pTag protected
Referenced by CIccProfileDescText(), and operator=().
The documentation for this class was generated from the following files:
IccTagBasic.h
IccTagBasic.cpp