CIccResponseCurveStruct Class Reference
CIccResponseCurveStruct Class Reference
#include <IccTagBasic.h>
Public Member Functions
CIccResponseCurveStruct (icMeasurementUnitSig sig, icUInt16Number nChannels=0)
CIccResponseCurveStruct (icUInt16Number nChannels=0)
CIccResponseCurveStruct (const CIccResponseCurveStruct &IRCS)
CIccResponseCurveStruct & operator= (const CIccResponseCurveStruct &RespCurveStruct)
virtual ~CIccResponseCurveStruct ()
bool Read (icUInt32Number size, CIccIO *pIO)
bool Write (CIccIO *pIO)
void Describe (std::string &sDescription)
icMeasurementUnitSig GetMeasurementType () const
icUInt16Number GetNumChannels () const
icXYZNumber * GetXYZ (icUInt32Number index)
CIccResponse16List * GetResponseList (icUInt16Number nChannel)
CIccResponseCurveStruct * GetThis ()
icValidateStatus Validate (std::string &sReport) const
Protected Attributes
icUInt16Number m_nChannels
icMeasurementUnitSig m_measurementUnitSig
icXYZNumber * m_maxColorantXYZ
CIccResponse16List * m_Response16ListArray
Friends
class ICCPROFLIB_API CIccTagResponseCurveSet16
Detailed Description
Data Class: CIccResponseCurveStruct
Purpose: The base class for response curve structure
Constructor & Destructor Documentation
CIccResponseCurveStruct::CIccResponseCurveStruct (icMeasurementUnitSig sig, icUInt16Number nChannels = 0)
Name: CIccResponseCurveStruct::CIccResponseCurveStruct
Purpose: Constructor
Args: sig = measurement unit signature indicating the type of measurement data, nChannels = number of channels
CIccResponseCurveStruct::CIccResponseCurveStruct (icUInt16Number nChannels = 0)
Name: CIccResponseCurveStruct::CIccResponseCurveStruct
Purpose: Constructor
Args: nChannels = number of channels
CIccResponseCurveStruct::CIccResponseCurveStruct (const CIccResponseCurveStruct & IRCS)
Name: CIccResponseCurveStruct::CIccResponseCurveStruct
Purpose: Copy Constructor
Args: IRCS = The CIccTagUnknown object to be copied
References m_maxColorantXYZ, m_measurementUnitSig, m_nChannels, and m_Response16ListArray.
CIccResponseCurveStruct::~CIccResponseCurveStruct () virtual
Name: CIccResponseCurveStruct::~CIccResponseCurveStruct
Purpose: Destructor
Member Function Documentation
void CIccResponseCurveStruct::Describe (std::string & sDescription)
Name: CIccResponseCurveStruct::Describe
Purpose: Dump data associated with the tag to a string
Args: sDescription - string to concatenate tag dump to
References CIccInfo::GetMeasurementUnit(), and icFtoD().
icMeasurementUnitSig CIccResponseCurveStruct::GetMeasurementType () const inline
icUInt16Number CIccResponseCurveStruct::GetNumChannels () const inline
CIccResponse16List* CIccResponseCurveStruct::GetResponseList (icUInt16Number nChannel) inline
CIccResponseCurveStruct* CIccResponseCurveStruct::GetThis () inline
Referenced by CIccTagResponseCurveSet16::GetFirstCurves(), and CIccTagResponseCurveSet16::GetNextCurves().
icXYZNumber* CIccResponseCurveStruct::GetXYZ (icUInt32Number index) inline
CIccResponseCurveStruct & CIccResponseCurveStruct::operator= (const CIccResponseCurveStruct & RespCurveStruct)
Name: CIccResponseCurveStruct::operator=
Purpose: Copy Operator
Args: RespCurveStruct = The CIccResponseCurveStruct object to be copied
References m_maxColorantXYZ, m_measurementUnitSig, m_nChannels, and m_Response16ListArray.
bool CIccResponseCurveStruct::Read (icUInt32Number size, CIccIO * pIO)
Name: CIccResponseCurveStruct::Read
Purpose: Read in the tag contents into a data block
Args: size - # of bytes in tag, pIO - IO object to read tag from
Return: true = successful, false = failure
References icResponse16Number::deviceCode, icResponse16Number::measurementValue, CIccIO::Read16(), CIccIO::Read32(), and icResponse16Number::reserved.
Referenced by CIccTagResponseCurveSet16::Read().
icValidateStatus CIccResponseCurveStruct::Validate (std::string & sReport) const
Name: CIccResponseCurveStruct::Validate
Purpose: Check tag data validity.
Args: sig = signature of tag being validated, sReport = String to add report information to
Return: icValidateStatusOK if valid, or other error status.
References CIccInfo::CheckData(), CIccInfo::GetSigName(), icMaxStatus(), icSigDN, icSigDNN, icSigDNNP, icSigDNP, icSigStatusA, icSigStatusE, icSigStatusI, icSigStatusM, icSigStatusT, icValidateNonCompliant, icValidateNonCompliantMsg, and icValidateOK.
bool CIccResponseCurveStruct::Write (CIccIO * pIO)
Name: CIccResponseCurveStruct::Write
Purpose: Write the tag to a file
Args: pIO - The IO object to write tag to.
Return: true = succesful, false = failure
References CIccIO::Write16(), and CIccIO::Write32().
Friends And Related Function Documentation
friend class ICCPROFLIB_API CIccTagResponseCurveSet16 friend
Member Data Documentation
icXYZNumber* CIccResponseCurveStruct::m_maxColorantXYZ protected
Referenced by CIccResponseCurveStruct(), and operator=().
icMeasurementUnitSig CIccResponseCurveStruct::m_measurementUnitSig protected
Referenced by CIccResponseCurveStruct(), and operator=().
icUInt16Number CIccResponseCurveStruct::m_nChannels protected
Referenced by CIccResponseCurveStruct(), and operator=().
CIccResponse16List* CIccResponseCurveStruct::m_Response16ListArray protected
Referenced by CIccResponseCurveStruct(), and operator=().
The documentation for this class was generated from the following files:
IccTagBasic.h
IccTagBasic.cpp