CIccTagDict Class Reference
CIccTagDict Class Reference
#include <IccTagDict.h>
Public Member Functions
CIccTagDict ()
CIccTagDict (const CIccTagDict &dict)
CIccTagDict & operator= (const CIccTagDict &dict)
virtual CIccTag * NewCopy () const
virtual ~CIccTagDict ()
virtual icTagTypeSignature GetType () const
virtual const icChar * GetClassName () const
virtual void Describe (std::string &sDescription)
virtual bool Read (icUInt32Number size, CIccIO *pIO)
virtual bool Write (CIccIO *pIO)
virtual icValidateStatus Validate (icTagSignature sig, std::string &sReport, const CIccProfile *pProfile=NULL) const
bool AreNamesUnique () const
bool AreNamesNonzero () const
CIccDictEntry * Get (const char *szName) const
CIccDictEntry * Get (const icUInt16Number *szName) const
CIccDictEntry * Get (const CIccUTF16String &sName) const
CIccUTF16String GetValue (const char *szName, bool *bIsSet=NULL) const
CIccUTF16String GetValue (const icUnicodeChar *szName, bool *bIsSet=NULL) const
CIccUTF16String GetValue (const CIccUTF16String &sName, bool *bIsSet=NULL) const
CIccTagMultiLocalizedUnicode * GetNameLocalized (const CIccUTF16String &sName) const
CIccTagMultiLocalizedUnicode * GetNameLocalized (const icUnicodeChar *szName) const
CIccTagMultiLocalizedUnicode * GetNameLocalized (const char *szName) const
CIccTagMultiLocalizedUnicode * GetValueLocalized (const CIccUTF16String &sName) const
CIccTagMultiLocalizedUnicode * GetValueLocalized (const icUnicodeChar *szName) const
CIccTagMultiLocalizedUnicode * GetValueLocalized (const char *szName) const
bool Remove (const CIccUTF16String &sName)
bool Remove (const icUnicodeChar *szName)
bool Remove (const char *szName)
bool Set (const char *szName, const char *szValue=NULL)
bool Set (const icUnicodeChar *szName, const icUnicodeChar *szValue=NULL)
bool Set (const CIccUTF16String &sName, const CIccUTF16String &sValue, bool bUnSet=false)
bool SetNameLocalized (const char *szName, CIccTagMultiLocalizedUnicode *pTag)
bool SetNameLocalized (const icUnicodeChar *szName, CIccTagMultiLocalizedUnicode *pTag)
bool SetNameLocalized (const CIccUTF16String &sName, CIccTagMultiLocalizedUnicode *pTag)
bool SetValueLocalized (const char *szName, CIccTagMultiLocalizedUnicode *pTag)
bool SetValueLocalized (const icUnicodeChar *szName, CIccTagMultiLocalizedUnicode *pTag)
bool SetValueLocalized (const CIccUTF16String &sName, CIccTagMultiLocalizedUnicode *pTag)
Public Member Functions inherited from CIccTag
CIccTag ()
virtual ~CIccTag ()
virtual bool IsArrayType ()
virtual bool IsMBBType ()
virtual IIccExtensionTag * GetExtension ()
virtual bool IsSupported ()
Public Attributes
CIccNameValueDict * m_Dict
Public Attributes inherited from CIccTag
icUInt32Number m_nReserved
Protected Member Functions
void Cleanup ()
icUInt32Number MaxPosRecSize ()
Protected Attributes
bool m_bBadAlignment
icUInt32Number m_tagSize
icUInt32Number m_tagStart
Additional Inherited Members
Static Public Member Functions inherited from CIccTag
static CIccTag * Create (icTagTypeSignature sig)
Detailed Description
Class: CIccTagDict
Purpose: A name-value dictionary tag with optional localization
Constructor & Destructor Documentation
CIccTagDict::CIccTagDict ()
Name: CIccTagDict::CIccTagDict
Purpose:
Args:
Return:
References m_bBadAlignment, and m_Dict.
CIccTagDict::CIccTagDict (const CIccTagDict & dict)
Name: CIccTagDict::CIccTagDict
Purpose:
Args:
Return:
References m_bBadAlignment, m_Dict, and CIccDictEntryPtr::ptr.
CIccTagDict::~CIccTagDict () virtual
Name: CIccTagDict::~CIccTagDict
Purpose:
Args:
Return:
References Cleanup(), and m_Dict.
Member Function Documentation
bool CIccTagDict::AreNamesNonzero () const
Name: CIccTagDict::AreNamesNonzero
Purpose: For each tag it checks to see if any other tags have the same signature.
Return: true if all tags have unique signatures, or false if there are duplicate tag signatures.
References m_Dict.
Referenced by Validate().
bool CIccTagDict::AreNamesUnique () const
Name: CIccTagDict::AreNamesUnique
Purpose: For each tag it checks to see if any other tags have the same signature.
Return: true if all tags have unique signatures, or false if there are duplicate tag signatures.
References m_Dict.
Referenced by Validate().
void CIccTagDict::Cleanup () protected
Name: CIccTagDict::Cleanup
Purpose: Detach from a pending IO object
References m_Dict.
Referenced by operator=(), Read(), and ~CIccTagDict().
void CIccTagDict::Describe (std::string & sDescription) virtual
Name: CIccTagDict::Describe
Purpose:
Args:
Return:
Reimplemented from CIccTag.
References m_Dict.
CIccDictEntry * CIccTagDict::Get (const char * szName) const
Name: CIccTagDict::Get
Purpose: Get a dictionary entry with a given name
Args: sName - name to find in dictionary
Return: Pointer to desired dictionary entry, or NULL if not found.
Referenced by Get(), GetNameLocalized(), GetValue(), GetValueLocalized(), Set(), SetNameLocalized(), and SetValueLocalized().
CIccDictEntry * CIccTagDict::Get (const icUInt16Number * szName) const
Name: CIccTagDict::Get
Purpose: Get a dictionary entry with a given name
Args: sName - name to find in dictionary
Return: Pointer to desired dictionary entry, or NULL if not found.
References Get().
CIccDictEntry * CIccTagDict::Get (const CIccUTF16String & sName) const
Name: CIccTagDict::Get
Purpose: Get a dictionary entry with a given name
Args: sName - name to find in dictionary
Return: Pointer to desired dictionary entry, or NULL if not found.
References m_Dict.
virtual const icChar* CIccTagDict::GetClassName () const inline virtual
Reimplemented from CIccTag.
CIccTagMultiLocalizedUnicode * CIccTagDict::GetNameLocalized (const CIccUTF16String & sName) const
Name: CIccTagDict::GetNameLocalized
Purpose: Get a localized name information associated with a given name
Args: sName - name to find in dictionary
Return: localized information for name
References Get(), and CIccDictEntry::GetNameLocalized().
Referenced by GetNameLocalized().
CIccTagMultiLocalizedUnicode * CIccTagDict::GetNameLocalized (const icUnicodeChar * szName) const
Name: CIccTagDict::GetNameLocalized
Purpose: Get a localized name information associated with a given name
Args: sName - name to find in dictionary
Return: localized information for name
References GetNameLocalized().
CIccTagMultiLocalizedUnicode * CIccTagDict::GetNameLocalized (const char * szName) const
Name: CIccTagDict::GetNameLocalized
Purpose: Get a localized name information associated with a given name
Args: sName - name to find in dictionary
Return: localized information for name
References GetNameLocalized().
virtual icTagTypeSignature CIccTagDict::GetType () const inline virtual
Function: GetType()
Purpose: Get Tag Type. Each derived tag will implement it's own GetType() function.
Reimplemented from CIccTag.
References icSigDictType.
Referenced by Write().
CIccUTF16String CIccTagDict::GetValue (const char * szName, bool * bIsSet = NULL) const
Name: CIccTagDict::GetValue
Purpose: Get a value associated with a given name
Args: szName - name to find in dictionary
Return: Pointer to desired dictionary entry, or NULL if not found.
Referenced by GetValue().
CIccUTF16String CIccTagDict::GetValue (const icUnicodeChar * szName, bool * bIsSet = NULL) const
Name: CIccTagDict::GetValue
Purpose: Get a value associated with a given name
Args: szName - name to find in dictionary
Return: Pointer to desired dictionary entry, or NULL if not found.
References GetValue().
CIccUTF16String CIccTagDict::GetValue (const CIccUTF16String & sName, bool * bIsSet = NULL) const
Name: CIccTagDict::GetValue
Purpose: Get a value associated with a given name
Args: sName - name to find in dictionary
Return: Pointer to desired dictionary entry, or NULL if not found.
References Get(), CIccDictEntry::GetValue(), and CIccDictEntry::IsValueSet().
CIccTagMultiLocalizedUnicode * CIccTagDict::GetValueLocalized (const CIccUTF16String & sName) const
Name: CIccTagDict::GetValueLocalized
Purpose: Get a localized name information for value associated with a given name
Args: sName - name to find in dictionary
Return: localized information for name's value
References Get(), and CIccDictEntry::GetValueLocalized().
Referenced by GetValueLocalized().
CIccTagMultiLocalizedUnicode * CIccTagDict::GetValueLocalized (const icUnicodeChar * szName) const
Name: CIccTagDict::GetValueLocalized
Purpose: Get a localized name information for value associated with a given name
Args: sName - name to find in dictionary
Return: localized information for name's value
References GetValueLocalized().
CIccTagMultiLocalizedUnicode * CIccTagDict::GetValueLocalized (const char * szName) const
Name: CIccTagDict::GetValueLocalized
Purpose: Get a localized name information for value associated with a given name
Args: sName - name to find in dictionary
Return: localized information for name's value
References GetValueLocalized().
icUInt32Number CIccTagDict::MaxPosRecSize () protected
Name: CIccTagDict::MaxPosRecSize;
Purpose:
Args:
Return:
References m_Dict, and CIccDictEntry::PosRecSize().
Referenced by Write().
virtual CIccTag* CIccTagDict::NewCopy () const inline virtual
Function: NewCopy(sDescription) Each derived tag will implement it's own NewCopy() function.
Parameter(s): none
Returns a new CIccTag object that is a copy of this object.
Reimplemented from CIccTag.
CIccTagDict & CIccTagDict::operator= (const CIccTagDict & dict)
Name: &operator=
Purpose:
Args:
Return:
References Cleanup(), m_Dict, and CIccDictEntryPtr::ptr.
bool CIccTagDict::Read (icUInt32Number size, CIccIO * pIO) virtual
Name: CIccTagDict::Read
Purpose:
Args:
Return:
Reimplemented from CIccTag.
References Cleanup(), CIccUTF16String::Clear(), icSeekSet, icSigMultiLocalizedUnicodeType, m_bBadAlignment, m_Dict, CIccTag::m_nReserved, CIccDictEntry::m_sName, m_tagSize, m_tagStart, icPositionNumber::offset, icDictRecordPos::posName, icDictRecordPos::posNameLocalized, icDictRecordPos::posValue, icDictRecordPos::posValueLocalized, CIccDictEntryPtr::ptr, CIccTagMultiLocalizedUnicode::Read(), CIccIO::Read16(), CIccIO::Read32(), CIccIO::Seek(), CIccDictEntry::SetNameLocalized(), CIccDictEntry::SetValue(), CIccDictEntry::SetValueLocalized(), icPositionNumber::size, and CIccIO::Tell().
bool CIccTagDict::Remove (const CIccUTF16String & sName)
Name: CIccTagDict::Remove
Purpose: Remove a name value pair from the dictionary
Args: sName = the name to look for in the dictionary
Return: true if sName exists and was removed, or false otherwise
References m_Dict.
Referenced by Remove().
bool CIccTagDict::Remove (const icUnicodeChar * szName)
Name: CIccTagDict::Remove
Purpose: Remove a name value pair from the dictionary
Args: sName = the name to look for in the dictionary
Return: true if sName exists and was remove , or false otherwise
References Remove().
bool CIccTagDict::Remove (const char * szName)
Name: CIccTagDict::Remove
Purpose: Remove a name value pair from the dictionary
Args: sName = the name to look for in the dictionary
Return: true if sName exists and was remove , or false otherwise
References Remove().
bool CIccTagDict::Set (const char * szName, const char * szValue = NULL)
Referenced by Set().
bool CIccTagDict::Set (const icUnicodeChar * szName, const icUnicodeChar * szValue = NULL)
References Set().
bool CIccTagDict::Set (const CIccUTF16String & sName, const CIccUTF16String & sValue, bool bUnSet = false)
Name: CIccTagDict::Set
Purpose: Associate a value with a name in the dictionary
Args: sName = the name to look for in the dictionary sValue = value to associate with sName bUnset = flag to indicate that value has not been set (no data for value in tag)
Return: true if value associate with sName was changed, or false if no change
References CIccUTF16String::Empty(), Get(), CIccDictEntry::GetValue(), CIccDictEntry::IsValueSet(), m_Dict, CIccDictEntry::m_sName, CIccDictEntryPtr::ptr, CIccDictEntry::SetValue(), and CIccDictEntry::UnsetValue().
bool CIccTagDict::SetNameLocalized (const char * szName, CIccTagMultiLocalizedUnicode * pTag)
Referenced by SetNameLocalized().
bool CIccTagDict::SetNameLocalized (const icUnicodeChar * szName, CIccTagMultiLocalizedUnicode * pTag)
References SetNameLocalized().
bool CIccTagDict::SetNameLocalized (const CIccUTF16String & sName, CIccTagMultiLocalizedUnicode * pTag)
References Get(), m_Dict, CIccDictEntry::m_sName, CIccDictEntryPtr::ptr, and CIccDictEntry::SetNameLocalized().
bool CIccTagDict::SetValueLocalized (const char * szName, CIccTagMultiLocalizedUnicode * pTag)
Referenced by SetValueLocalized().
bool CIccTagDict::SetValueLocalized (const icUnicodeChar * szName, CIccTagMultiLocalizedUnicode * pTag)
References SetValueLocalized().
bool CIccTagDict::SetValueLocalized (const CIccUTF16String & sName, CIccTagMultiLocalizedUnicode * pTag)
References Get(), m_Dict, CIccDictEntry::m_sName, CIccDictEntryPtr::ptr, and CIccDictEntry::SetValueLocalized().
icValidateStatus CIccTagDict::Validate (icTagSignature sig, std::string & sReport, const CIccProfile * pProfile = NULL) const virtual
Name: CIccTagDict::Validate
Purpose:
Args:
Return:
Reimplemented from CIccTag.
References AreNamesNonzero(), AreNamesUnique(), CIccInfo::GetSigName(), icMaxStatus(), icValidateWarning, m_bBadAlignment, and CIccTag::Validate().
bool CIccTagDict::Write (CIccIO * pIO) virtual
Name: CIccTagDict::Write
Purpose:
Args:
Return:
Reimplemented from CIccTag.
References CIccIO::Align32(), CIccUTF16String::c_str(), GetType(), icSeekSet, m_Dict, CIccTag::m_nReserved, m_tagStart, MaxPosRecSize(), icPositionNumber::offset, icDictRecordPos::posName, icDictRecordPos::posNameLocalized, icDictRecordPos::posValue, icDictRecordPos::posValueLocalized, CIccIO::Seek(), CIccUTF16String::Size(), icPositionNumber::size, CIccIO::Tell(), CIccIO::Write16(), CIccIO::Write32(), and CIccIO::Write8().
Member Data Documentation
bool CIccTagDict::m_bBadAlignment protected
Referenced by CIccTagDict(), Read(), and Validate().
CIccNameValueDict* CIccTagDict::m_Dict
Referenced by AreNamesNonzero(), AreNamesUnique(), CIccTagDict(), Cleanup(), Describe(), Get(), MaxPosRecSize(), operator=(), Read(), Remove(), Set(), SetNameLocalized(), SetValueLocalized(), Write(), and ~CIccTagDict().
icUInt32Number CIccTagDict::m_tagSize protected
Referenced by Read().
icUInt32Number CIccTagDict::m_tagStart protected
Referenced by Read(), and Write().
The documentation for this class was generated from the following files:
IccTagDict.h
IccTagDict.cpp