CIccInfo Class Reference
CIccInfo Class Reference
#include <IccUtil.h>
Public Member Functions
const icChar * GetVersionName (icUInt32Number val)
const icChar * GetDeviceAttrName (icUInt64Number val)
const icChar * GetProfileFlagsName (icUInt32Number val)
const icChar * GetTagSigName (icTagSignature sig)
const icChar * GetTechnologySigName (icTechnologySignature sig)
const icChar * GetTagTypeSigName (icTagTypeSignature sig)
const icChar * GetColorSpaceSigName (icColorSpaceSignature sig)
const icChar * GetProfileClassSigName (icProfileClassSignature sig)
const icChar * GetPlatformSigName (icPlatformSignature sig)
const icChar * GetCmmSigName (icCmmSignature sig)
const icChar * GetReferenceMediumGamutSigNameName (icReferenceMediumGamutSignature sig)
const icChar * GetColorimetricIntentImageStateName (icColorimetricIntentImageStateSignature sig)
const icChar * GetSigName (icUInt32Number val)
const icChar * GetMeasurementFlareName (icMeasurementFlare val)
const icChar * GetMeasurementGeometryName (icMeasurementGeometry val)
const icChar * GetRenderingIntentName (icRenderingIntent val)
const icChar * GetSpotShapeName (icSpotShape val)
const icChar * GetStandardObserverName (icStandardObserver val)
const icChar * GetIlluminantName (icIlluminant val)
const icChar * GetUnknownName (icUInt32Number val)
const icChar * GetMeasurementUnit (icSignature sig)
const icChar * GetProfileID (icProfileID *profileID)
const icChar * GetColorantEncoding (icColorantEncoding colorant)
bool IsProfileIDCalculated (icProfileID *profileID)
icValidateStatus CheckData (std::string &sReport, const icDateTimeNumber &dateTime)
icValidateStatus CheckData (std::string &sReport, const icXYZNumber &XYZ)
bool IsValidSpace (icColorSpaceSignature sig)
Protected Attributes
icChar m_szStr [128]
icChar m_szSigStr [128]
Detailed Description
Type: Class
Purpose: This is a utility class which can be used to get profile info for printing. The member functions are used to convert signatures and other enum values to character strings for printing.
Member Function Documentation
icValidateStatus CIccInfo::CheckData (std::string & sReport, const icDateTimeNumber & dateTime)
References icDateTimeNumber::day, icDateTimeNumber::hours, icMaxStatus(), icValidateOK, icValidateWarning, icValidateWarningMsg, icDateTimeNumber::minutes, icDateTimeNumber::month, icDateTimeNumber::seconds, and icDateTimeNumber::year.
Referenced by CIccProfile::CheckHeader(), CIccTagXYZ::Validate(), CIccTagDateTime::Validate(), CIccTagViewingConditions::Validate(), and CIccResponseCurveStruct::Validate().
icValidateStatus CIccInfo::CheckData (std::string & sReport, const icXYZNumber & XYZ)
References icMaxStatus(), icValidateNonCompliant, icValidateNonCompliantMsg, icValidateOK, icXYZNumber::X, icXYZNumber::Y, and icXYZNumber::Z.
const icChar * CIccInfo::GetCmmSigName (icCmmSignature sig)
References icSigAdobe, icSigApple, icSigArgyllCMS, icSigColorGear, icSigColorGearLite, icSigFujiFilm, icSigHarlequinRIP, icSigHeidelberg, icSigKodak, icSigKonicaMinolta, icSigLittleCMS, icSigLogoSync, icSigMutoh, icSigSampleICC, and icSigTheImagingFactory.
Referenced by CIccProfile::CheckHeader().
const icChar * CIccInfo::GetColorantEncoding (icColorantEncoding colorant)
References icColorantEBU, icColorantITU, icColorantP22, and icColorantSMPTE.
Referenced by CIccTagChromaticity::Describe().
const icChar * CIccInfo::GetColorimetricIntentImageStateName (icColorimetricIntentImageStateSignature sig)
References icSigFocalPlaneColorimetryEstimates, icSigReflectionHardcopyOriginalColorimetry, icSigReflectionPrintOutputColorimetry, icSigSceneAppearanceEstimates, and icSigSceneColorimetryEstimates.
const icChar * CIccInfo::GetColorSpaceSigName (icColorSpaceSignature sig)
References icSigCmyData, icSigCmykData, icSigDevLabData, icSigDevXYZData, icSigGamutData, icSigGrayData, icSigHlsData, icSigHsvData, icSigLabData, icSigLuvData, icSigMCH1Data, icSigMCH2Data, icSigMCH3Data, icSigMCH4Data, icSigMCH5Data, icSigMCH6Data, icSigMCH7Data, icSigMCH8Data, icSigMCH9Data, icSigMCHAData, icSigMCHBData, icSigMCHCData, icSigMCHDData, icSigMCHEData, icSigMCHFData, icSigNamedData, icSigRgbData, icSigXYZData, icSigYCbCrData, and icSigYxyData.
Referenced by CIccProfile::CheckHeader().
const icChar * CIccInfo::GetDeviceAttrName (icUInt64Number val)
References icMatte, and icTransparency.
const icChar * CIccInfo::GetIlluminantName (icIlluminant val)
References icIlluminantA, icIlluminantD50, icIlluminantD55, icIlluminantD65, icIlluminantD93, icIlluminantEquiPowerE, icIlluminantF2, icIlluminantF8, and icIlluminantUnknown.
Referenced by CIccTagMeasurement::Describe(), and CIccTagViewingConditions::Describe().
const icChar * CIccInfo::GetMeasurementFlareName (icMeasurementFlare val)
References icFlare0, icFlare100, and icMaxEnumFlare.
Referenced by CIccTagMeasurement::Describe().
const icChar * CIccInfo::GetMeasurementGeometryName (icMeasurementGeometry val)
References icGeometry045or450, icGeometry0dord0, icGeometryUnknown, and icMaxEnumGeometry.
Referenced by CIccTagMeasurement::Describe().
const icChar * CIccInfo::GetMeasurementUnit (icSignature sig)
References icSigDN, icSigDNN, icSigDNNP, icSigDNP, icSigStatusA, icSigStatusE, icSigStatusI, icSigStatusM, and icSigStatusT.
Referenced by CIccResponseCurveStruct::Describe().
const icChar * CIccInfo::GetPlatformSigName (icPlatformSignature sig)
References icSigMacintosh, icSigMicrosoft, icSigSGI, icSigSolaris, icSigTaligent, and icSigUnkownPlatform.
Referenced by CIccProfile::CheckHeader().
const icChar * CIccInfo::GetProfileClassSigName (icProfileClassSignature sig)
References icSigAbstractClass, icSigColorSpaceClass, icSigDisplayClass, icSigInputClass, icSigLinkClass, icSigNamedColorClass, and icSigOutputClass.
Referenced by CIccProfile::CheckHeader().
const icChar * CIccInfo::GetProfileFlagsName (icUInt32Number val)
References icEmbeddedProfileTrue, and icUseWithEmbeddedDataOnly.
const icChar * CIccInfo::GetProfileID (icProfileID * profileID)
References icProfileID::ID8.
const icChar * CIccInfo::GetReferenceMediumGamutSigNameName (icReferenceMediumGamutSignature sig)
References icSigPerceptualReferenceMediumGamut.
const icChar * CIccInfo::GetRenderingIntentName (icRenderingIntent val)
References icAbsoluteColorimetric, icPerceptual, icRelativeColorimetric, and icSaturation.
Referenced by CIccProfile::CheckHeader().
const icChar * CIccInfo::GetSigName (icUInt32Number val)
Referenced by CIccProfile::CheckTagExclusion(), CIccProfile::CheckTagTypes(), CIccTagSignature::Describe(), CIccTagProfileSequenceId::Validate(), CIccFormulaCurveSegment::Validate(), CIccTagCurve::Validate(), CIccMultiProcessElement::Validate(), CIccTagDict::Validate(), CIccTag::Validate(), CIccSampledCurveSegment::Validate(), CIccTagParametricCurve::Validate(), CIccMatrix::Validate(), CIccMpeUnknown::Validate(), CIccTagText::Validate(), CIccSegmentedCurve::Validate(), CIccTagTextDescription::Validate(), CIccCLUT::Validate(), CIccMpeCurveSet::Validate(), CIccTagSignature::Validate(), CIccMpeMatrix::Validate(), CIccTagMultiProcessElement::Validate(), CIccMBB::Validate(), CIccMpeCLUT::Validate(), CIccTagNamedColor2::Validate(), CIccTagLutAtoB::Validate(), CIccTagLutBtoA::Validate(), CIccTagXYZ::Validate(), CIccTagLut8::Validate(), CIccTagLut16::Validate(), CIccTagChromaticity::Validate(), CIccTagMeasurement::Validate(), CIccTagMultiLocalizedUnicode::Validate(), CIccTagData::Validate(), CIccTagColorantOrder::Validate(), CIccTagColorantTable::Validate(), CIccTagViewingConditions::Validate(), CIccTagProfileSeqDesc::Validate(), CIccResponseCurveStruct::Validate(), and CIccTagResponseCurveSet16::Validate().
const icChar * CIccInfo::GetSpotShapeName (icSpotShape val)
References icSpotShapeCross, icSpotShapeDiamond, icSpotShapeEllipse, icSpotShapeLine, icSpotShapePrinterDefault, icSpotShapeRound, icSpotShapeSquare, and icSpotShapeUnknown.
const icChar * CIccInfo::GetStandardObserverName (icStandardObserver val)
References icStdObs1931TwoDegrees, icStdObs1964TenDegrees, and icStdObsUnknown.
Referenced by CIccTagMeasurement::Describe().
const icChar * CIccInfo::GetTagSigName (icTagSignature sig)
References CIccTagCreator::GetTagSigName().
Referenced by CIccProfile::ReadValidate().
const icChar * CIccInfo::GetTagTypeSigName (icTagTypeSignature sig)
References CIccTagCreator::GetTagTypeSigName().
Referenced by CIccProfile::CheckTagTypes().
const icChar * CIccInfo::GetTechnologySigName (icTechnologySignature sig)
References icSigAMDisplay, icSigCRTDisplay, icSigDigitalCamera, icSigDyeSublimationPrinter, icSigElectrophotographicPrinter, icSigElectrostaticPrinter, icSigFilmScanner, icSigFilmWriter, icSigFlexography, icSigGravure, icSigInkJetPrinter, icSigOffsetLithography, icSigPhotoCD, icSigPhotographicPaperPrinter, icSigPhotoImageSetter, icSigPMDisplay, icSigProjectionTelevision, icSigReflectiveScanner, icSigSilkscreen, icSigThermalWaxPrinter, icSigVideoCamera, and icSigVideoMonitor.
const icChar * CIccInfo::GetUnknownName (icUInt32Number val)
References icGetSig().
const icChar * CIccInfo::GetVersionName (icUInt32Number val)
bool CIccInfo::IsProfileIDCalculated (icProfileID * profileID)
References icProfileID::ID8.
Referenced by CIccProfile::ReadValidate().
bool CIccInfo::IsValidSpace (icColorSpaceSignature sig)
References icSig10colorData, icSig11colorData, icSig12colorData, icSig13colorData, icSig14colorData, icSig15colorData, icSig2colorData, icSig3colorData, icSig4colorData, icSig5colorData, icSig6colorData, icSig7colorData, icSig8colorData, icSig9colorData, icSigCmyData, icSigCmykData, icSigGamutData, icSigGrayData, icSigHlsData, icSigHsvData, icSigLabData, icSigLuvData, icSigMCH1Data, icSigNamedData, icSigRgbData, icSigXYZData, icSigYCbCrData, and icSigYxyData.
Referenced by CIccProfile::CheckHeader().
Member Data Documentation
icChar CIccInfo::m_szSigStr[128] protected
icChar CIccInfo::m_szStr[128] protected
The documentation for this class was generated from the following files:
IccUtil.h
IccUtil.cpp