CIccCurveSetCurve Class Reference
CIccCurveSetCurve Class Reference abstract
#include <IccMpeBasic.h>
Public Member Functions
virtual ~CIccCurveSetCurve ()
virtual CIccCurveSetCurve * NewCopy () const =0
virtual icCurveElemSignature GetType () const =0
virtual const icChar * GetClassName () const =0
virtual void Describe (std::string &sDescription)=0
virtual bool Read (icUInt32Number size, CIccIO *pIO)=0
virtual bool Write (CIccIO *pIO)=0
virtual bool Begin ()=0
virtual icFloatNumber Apply (icFloatNumber v) const =0
virtual icValidateStatus Validate (icTagSignature sig, std::string &sReport, const CIccTagMultiProcessElement *pMPE=NULL) const =0
Static Public Member Functions
static CIccCurveSetCurve * Create (icCurveElemSignature sig)
Detailed Description
Class: CIccCurveSetCurve
Purpose: Base class for Curve Set Curves
Constructor & Destructor Documentation
virtual CIccCurveSetCurve::~CIccCurveSetCurve () inline virtual
Member Function Documentation
virtual icFloatNumber CIccCurveSetCurve::Apply (icFloatNumber v) const pure virtual
Implemented in CIccSegmentedCurve.
virtual bool CIccCurveSetCurve::Begin () pure virtual
Implemented in CIccSegmentedCurve.
CIccCurveSetCurve * CIccCurveSetCurve::Create (icCurveElemSignature sig) static
Name: CIccCurveSetCurve::Create
Purpose:
Args:
Return:
References icSigSementedCurve.
Referenced by CIccMpeCurveSet::Read().
virtual void CIccCurveSetCurve::Describe (std::string & sDescription) pure virtual
Implemented in CIccSegmentedCurve.
virtual const icChar* CIccCurveSetCurve::GetClassName () const pure virtual
Implemented in CIccSegmentedCurve.
virtual icCurveElemSignature CIccCurveSetCurve::GetType () const pure virtual
Implemented in CIccSegmentedCurve.
virtual CIccCurveSetCurve* CIccCurveSetCurve::NewCopy () const pure virtual
Implemented in CIccSegmentedCurve.
Referenced by CIccMpeCurveSet::CIccMpeCurveSet(), and CIccMpeCurveSet::operator=().
virtual bool CIccCurveSetCurve::Read (icUInt32Number size, CIccIO * pIO) pure virtual
Implemented in CIccSegmentedCurve.
virtual icValidateStatus CIccCurveSetCurve::Validate (icTagSignature sig, std::string & sReport, const CIccTagMultiProcessElement * pMPE = NULL) const pure virtual
Implemented in CIccSegmentedCurve.
virtual bool CIccCurveSetCurve::Write (CIccIO * pIO) pure virtual
Implemented in CIccSegmentedCurve.
The documentation for this class was generated from the following files:
IccMpeBasic.h
IccMpeBasic.cpp