CIccCreateXformHintManager Class Reference
CIccCreateXformHintManager Class Reference
#include <IccCmm.h>
Public Member Functions
CIccCreateXformHintManager ()
~CIccCreateXformHintManager ()
bool AddHint (IIccCreateXformHint *pHint)
Adds and owns the passed named hint to it's list.
bool DeleteHint (IIccCreateXformHint *pHint)
Deletes the object referenced by the passed named hint pointer and removes it from the list.
IIccCreateXformHint * GetHint (const char *hintName)
Finds and returns a pointer to the named hint.
Detailed Description
Type: Class
Purpose: Manages the named xform hints
Constructor & Destructor Documentation
CIccCreateXformHintManager::CIccCreateXformHintManager () inline
CIccCreateXformHintManager::~CIccCreateXformHintManager ()
Name: CIccCreateXformHintManager::CIccCreateXformHintManager
Purpose: Destructor
Member Function Documentation
bool CIccCreateXformHintManager::AddHint (IIccCreateXformHint * pHint)
Adds and owns the passed named hint to it's list.
Name: CIccCreateXformHintManager::AddHint
Purpose: Adds and owns the passed named hint to it's list.
Args: pHint = pointer to the hint object to be added
Return: true = hint added to the list false = hint not added
References IIccCreateXformHint::GetHintType().
Referenced by CIccXform::Create().
bool CIccCreateXformHintManager::DeleteHint (IIccCreateXformHint * pHint)
Deletes the object referenced by the passed named hint pointer and removes it from the list.
Name: CIccCreateXformHintManager::DeleteHint
Purpose: Deletes the object referenced by the passed named hint pointer and removes it from the list.
Args: pHint = pointer to the hint object to be deleted
Return: true = hint found and deleted false = hint not found
Referenced by CIccXform::Create().
IIccCreateXformHint * CIccCreateXformHintManager::GetHint (const char * hintName)
Finds and returns a pointer to the named hint.
Name: CIccCreateXformHintManager::GetHint
Purpose: Finds and returns a pointer to the named hint.
Args: hintName = name of the desired hint
Return: Appropriate IIccCreateXformHint pointer
Referenced by CIccBaseXformFactory::CreateXform(), and CIccXform::SetParams().
The documentation for this class was generated from the following files:
IccCmm.h
IccCmm.cpp