CIccMpeAcs Class Reference
CIccMpeAcs Class Reference
#include <IccMpeACS.h>
Public Member Functions
virtual ~CIccMpeAcs ()
virtual void Describe (std::string &sDescription)
virtual bool Read (icUInt32Number size, CIccIO *pIO)
virtual bool Write (CIccIO *pIO)
virtual bool Begin (icElemInterp nInterp, CIccTagMultiProcessElement *pMPE)
virtual void Apply (CIccApplyMpe *pApply, icFloatNumber *dstPixel, const icFloatNumber *srcPixel) const
virtual icValidateStatus Validate (icTagSignature sig, std::string &sReport, const CIccTagMultiProcessElement *pMPE=NULL) const
virtual bool IsAcs ()
bool AllocData (icUInt32Number size)
icUInt8Number * GetData ()
icUInt32Number GetDataSize ()
virtual icAcsSignature GetAcsSig ()
Public Member Functions inherited from CIccMultiProcessElement
CIccMultiProcessElement ()
virtual ~CIccMultiProcessElement ()
virtual CIccMultiProcessElement * NewCopy () const =0
virtual icElemTypeSignature GetType () const =0
virtual const icChar * GetClassName () const =0
virtual icUInt16Number NumInputChannels () const
virtual icUInt16Number NumOutputChannels () const
virtual bool IsSupported ()
virtual CIccApplyMpe * GetNewApply (CIccApplyTagMpe *pApplyTag)
virtual icAcsSignature GetBAcsSig ()
virtual icAcsSignature GetEAcsSig ()
virtual IIccExtensionMpe * GetExtension ()
Protected Member Functions
CIccMpeAcs ()
Protected Attributes
icAcsSignature m_signature
icUInt32Number m_nDataSize
icUInt8Number * m_pData
Protected Attributes inherited from CIccMultiProcessElement
icUInt16Number m_nInputChannels
icUInt16Number m_nOutputChannels
Additional Inherited Members
Static Public Member Functions inherited from CIccMultiProcessElement
static CIccMultiProcessElement * Create (icElemTypeSignature sig)
Public Attributes inherited from CIccMultiProcessElement
icUInt32Number m_nReserved
Detailed Description
Class: CIccMpeAcs
Purpose: The alternate connection space base class element
Constructor & Destructor Documentation
CIccMpeAcs::~CIccMpeAcs () virtual
Name: CIccMpeAcs::~CIccMpeAcs
Purpose: Base destructor
CIccMpeAcs::CIccMpeAcs () protected
Name: CIccMpeAcs::CIccMpeACS
Purpose: Base constructor (protected)
Member Function Documentation
bool CIccMpeAcs::AllocData (icUInt32Number size)
Name: CIccMpeAcs::AllocData
Purpose:
Args:
Return:
void CIccMpeAcs::Apply (CIccApplyMpe * pApply, icFloatNumber * dstPixel, const icFloatNumber * srcPixel) const virtual
Name: CIccMpeAcs::Apply
Purpose:
Args:
Return:
Implements CIccMultiProcessElement.
bool CIccMpeAcs::Begin (icElemInterp nInterp, CIccTagMultiProcessElement * pMPE) virtual
Name: CIccMpeAcs::Begin
Purpose:
Args:
Return:
Implements CIccMultiProcessElement.
void CIccMpeAcs::Describe (std::string & sDescription) virtual
Name: CIccMpeAcs::Describe
Purpose:
Args:
Return:
Implements CIccMultiProcessElement.
References icGetSig(), and icMemDump().
virtual icAcsSignature CIccMpeAcs::GetAcsSig () inline virtual
icUInt8Number* CIccMpeAcs::GetData () inline
icUInt32Number CIccMpeAcs::GetDataSize () inline
virtual bool CIccMpeAcs::IsAcs () inline virtual
Reimplemented from CIccMultiProcessElement.
bool CIccMpeAcs::Read (icUInt32Number size, CIccIO * pIO) virtual
Name: CIccMpeAcs::Read
Purpose:
Args:
Return:
Implements CIccMultiProcessElement.
References CIccIO::Read16(), CIccIO::Read32(), and CIccIO::Read8().
icValidateStatus CIccMpeAcs::Validate (icTagSignature sig, std::string & sReport, const CIccTagMultiProcessElement * pMPE = NULL) const virtual
Name: CIccMpeAcs::Validate
Purpose:
Args:
Return:
Implements CIccMultiProcessElement.
References CIccMultiProcessElement::Validate().
bool CIccMpeAcs::Write (CIccIO * pIO) virtual
Name: CIccMpeAcs::Write
Purpose:
Args:
Return:
Implements CIccMultiProcessElement.
References CIccIO::Write16(), CIccIO::Write32(), and CIccIO::Write8().
Member Data Documentation
icUInt32Number CIccMpeAcs::m_nDataSize protected
Referenced by CIccMpeBAcs::CIccMpeBAcs(), CIccMpeEAcs::CIccMpeEAcs(), CIccMpeBAcs::operator=(), and CIccMpeEAcs::operator=().
icUInt8Number* CIccMpeAcs::m_pData protected
Referenced by CIccMpeBAcs::CIccMpeBAcs(), CIccMpeEAcs::CIccMpeEAcs(), CIccMpeBAcs::operator=(), and CIccMpeEAcs::operator=().
icAcsSignature CIccMpeAcs::m_signature protected
Referenced by CIccMpeBAcs::CIccMpeBAcs(), CIccMpeEAcs::CIccMpeEAcs(), CIccMpeBAcs::operator=(), and CIccMpeEAcs::operator=().
The documentation for this class was generated from the following files:
IccMpeACS.h
IccMpeACS.cpp