CIccMruCmm Class Reference
CIccMruCmm Class Reference
#include <IccCmm.h>
Public Member Functions
virtual ~CIccMruCmm ()
virtual icStatusCMM AddXform (const icChar *szProfilePath, icRenderingIntent nIntent=icUnknownIntent, icXformInterp nInterp=icInterpLinear, icXformLutType nLutType=icXformLutColor, bool bUseMpeTags=true, CIccCreateXformHintManager *pHintManager=NULL)
Must make at least one call to some form of AddXform() before calling Begin()
virtual icStatusCMM AddXform (icUInt8Number *pProfileMem, icUInt32Number nProfileLen, icRenderingIntent nIntent=icUnknownIntent, icXformInterp nInterp=icInterpLinear, icXformLutType nLutType=icXformLutColor, bool bUseMpeTags=true, CIccCreateXformHintManager *pHintManager=NULL)
virtual icStatusCMM AddXform (CIccProfile *pProfile, icRenderingIntent nIntent=icUnknownIntent, icXformInterp nInterp=icInterpLinear, icXformLutType nLutType=icXformLutColor, bool bUseMpeTags=true, CIccCreateXformHintManager *pHintManager=NULL)
virtual icStatusCMM AddXform (CIccProfile &Profile, icRenderingIntent nIntent=icUnknownIntent, icXformInterp nInterp=icInterpLinear, icXformLutType nLutType=icXformLutColor, bool bUseMpeTags=true, CIccCreateXformHintManager *pHintManager=NULL)
virtual CIccApplyCmm * GetNewApplyCmm (icStatusCMM &status)
virtual icStatusCMM RemoveAllIO ()
virtual CIccPCS * GetPCS ()
virtual icUInt32Number GetNumXforms () const
Returns the number of profiles/transforms added.
virtual icColorSpaceSignature GetFirstXformSource ()
virtual icColorSpaceSignature GetLastXformDest ()
Public Member Functions inherited from CIccCmm
CIccCmm (icColorSpaceSignature nSrcSpace=icSigUnknownData, icColorSpaceSignature nDestSpace=icSigUnknownData, bool bFirstInput=true)
virtual ~CIccCmm ()
virtual icStatusCMM Begin (bool bAllocNewApply=true)
virtual CIccApplyCmm * GetApply ()
virtual icStatusCMM Apply (icFloatNumber *DstPixel, const icFloatNumber *SrcPixel)
virtual icStatusCMM Apply (icFloatNumber *DstPixel, const icFloatNumber *SrcPixel, icUInt32Number nPixels)
icColorSpaceSignature GetSourceSpace () const
Returns the source color space.
icColorSpaceSignature GetDestSpace () const
Returns the destination color space.
icColorSpaceSignature GetLastSpace () const
Returns the color space of the last profile added.
icRenderingIntent GetLastIntent () const
Returns the rendering intent of the last profile added.
icUInt16Number GetSourceSamples () const
Returns the number of samples in the source color space.
icUInt16Number GetDestSamples () const
Returns the number of samples in the destination color space.
bool Valid () const
Checks if this is a valid CMM object.
icStatusCMM ToInternalEncoding (icFloatNumber *pInternal, const icUInt8Number *pData)
icStatusCMM ToInternalEncoding (icFloatNumber *pInternal, const icUInt16Number *pData)
icStatusCMM FromInternalEncoding (icUInt8Number *pData, icFloatNumber *pInternal)
icStatusCMM FromInternalEncoding (icUInt16Number *pData, icFloatNumber *pInternal)
Static Public Member Functions
static CIccMruCmm * Attach (CIccCmm *pCmm, icUInt8Number nCacheSize=6)
Static Public Member Functions inherited from CIccCmm
static bool IsInGamut (icFloatNumber *pData)
static icStatusCMM ToInternalEncoding (icColorSpaceSignature nSpace, icFloatColorEncoding nEncode, icFloatNumber *pInternal, const icFloatNumber *pData, bool bClip=true)
Functions for converting to Internal representation of pixel colors.
static icStatusCMM ToInternalEncoding (icColorSpaceSignature nSpace, icFloatNumber *pInternal, const icUInt8Number *pData)
static icStatusCMM ToInternalEncoding (icColorSpaceSignature nSpace, icFloatNumber *pInternal, const icUInt16Number *pData)
static icStatusCMM FromInternalEncoding (icColorSpaceSignature nSpace, icFloatColorEncoding nEncode, icFloatNumber *pData, const icFloatNumber *pInternal, bool bClip=true)
Functions for converting from Internal representation of pixel colors.
static icStatusCMM FromInternalEncoding (icColorSpaceSignature nSpace, icUInt8Number *pData, const icFloatNumber *pInternal)
static icStatusCMM FromInternalEncoding (icColorSpaceSignature nSpace, icUInt16Number *pData, const icFloatNumber *pInternal)
static const icChar * GetFloatColorEncoding (icFloatColorEncoding val)
static icFloatColorEncoding GetFloatColorEncoding (const icChar *val)
Protected Attributes
CIccCmm * m_pCmm
icUInt16Number m_nCacheSize
Protected Attributes inherited from CIccCmm
CIccApplyCmm * m_pApply
bool m_bValid
bool m_bLastInput
icColorSpaceSignature m_nSrcSpace
icColorSpaceSignature m_nDestSpace
icColorSpaceSignature m_nLastSpace
icRenderingIntent m_nLastIntent
CIccXformList * m_Xforms
Friends
class CIccApplyMruCmm
Detailed Description
Type: Class
Purpose: A CMM decorator class that provides limited caching of results
Constructor & Destructor Documentation
CIccMruCmm::~CIccMruCmm () virtual
Name: CIccMruCmm::~CIccMruCmm
Purpose: destructor
References m_pCmm.
Member Function Documentation
virtual icStatusCMM CIccMruCmm::AddXform (const icChar * szProfilePath, icRenderingIntent nIntent = icUnknownIntent, icXformInterp nInterp = icInterpLinear, icXformLutType nLutType = icXformLutColor, bool bUseMpeTags = true, CIccCreateXformHintManager * pHintManager = NULL) inline virtual
Must make at least one call to some form of AddXform() before calling Begin()
Name: CIccCmm::AddXform
Purpose: Adds a profile at the end of the Xform list
Args: szProfilePath = file name of the profile to be added, nIntent = rendering intent to be used with the profile, nInterp = type of interpolation to be used with the profile, nLutType = selection of which transform lut to use pHintManager = hints for creating the xform
Return: icCmmStatOk, if the profile was added to the list succesfully
Reimplemented from CIccCmm.
References icCmmStatBad.
virtual icStatusCMM CIccMruCmm::AddXform (icUInt8Number * pProfileMem, icUInt32Number nProfileLen, icRenderingIntent nIntent = icUnknownIntent, icXformInterp nInterp = icInterpLinear, icXformLutType nLutType = icXformLutColor, bool bUseMpeTags = true, CIccCreateXformHintManager * pHintManager = NULL) inline virtual
Name: CIccCmm::AddXform
Purpose: Adds a profile at the end of the Xform list
Args: pProfileMem = ptr to profile loaded into memory. Note: this memory needs to be available until after the Begin() function is called. nProfileLen = size in bytes of profile loaded into memory nIntent = rendering intent to be used with the profile, nInterp = type of interpolation to be used with the profile, nLutType = selection of which transform lut to use bUseMpeTags = flag to indicate the use MPE flags if available pHintManager = hints for creating the xform
Return: icCmmStatOk, if the profile was added to the list succesfully
Reimplemented from CIccCmm.
References icCmmStatBad.
virtual icStatusCMM CIccMruCmm::AddXform (CIccProfile * pProfile, icRenderingIntent nIntent = icUnknownIntent, icXformInterp nInterp = icInterpLinear, icXformLutType nLutType = icXformLutColor, bool bUseMpeTags = true, CIccCreateXformHintManager * pHintManager = NULL) inline virtual
Name: CIccCmm::AddXform
Purpose: Adds a profile at the end of the Xform list
Args: pProfile = pointer to the CIccProfile object to be added, nIntent = rendering intent to be used with the profile, nInterp = type of interpolation to be used with the profile, nLutType = selection of which transform lut to use bUseMpeTags = flag to indicate the use MPE flags if available pHintManager = hints for creating the xform
Return: icCmmStatOk, if the profile was added to the list succesfully
Reimplemented from CIccCmm.
References icCmmStatBad.
virtual icStatusCMM CIccMruCmm::AddXform (CIccProfile & Profile, icRenderingIntent nIntent = icUnknownIntent, icXformInterp nInterp = icInterpLinear, icXformLutType nLutType = icXformLutColor, bool bUseMpeTags = true, CIccCreateXformHintManager * pHintManager = NULL) inline virtual
Name: CIccCmm::AddXform
Purpose: Adds a profile at the end of the Xform list
Args: Profile = reference a CIccProfile object that will be copies and added, nIntent = rendering intent to be used with the profile, nInterp = type of interpolation to be used with the profile, nLutType = selection of which transform lut to use bUseMpeTags = flag to indicate the use MPE flags if available pHintManager = hints for creating the xform
Return: icCmmStatOk, if the profile was added to the list succesfully
Reimplemented from CIccCmm.
References icCmmStatBad.
CIccMruCmm * CIccMruCmm::Attach (CIccCmm * pCmm, icUInt8Number nCacheSize = 6) static
Name: CIccMruCmm::Attach
Purpose: Create a Cmm decorator object that implements a cache of most recently used pixel transformations.
Args: pCmm - pointer to cmm object that we are attaching to. nCacheSize - number of most recently used transformations to cache
Return: A CIccMruCmm object that represents a cached form of the pCmm passed in. The pCmm will be owned by the returned object.
If this function fails the pCmm object will be deleted.
References CIccCmm::Begin(), CIccCmm::GetDestSpace(), CIccCmm::GetLastIntent(), CIccCmm::GetLastSpace(), CIccCmm::GetSourceSpace(), icCmmStatOk, m_nCacheSize, CIccCmm::m_nDestSpace, CIccCmm::m_nLastIntent, CIccCmm::m_nLastSpace, CIccCmm::m_nSrcSpace, m_pCmm, and CIccCmm::Valid().
virtual icColorSpaceSignature CIccMruCmm::GetFirstXformSource () inline virtual
Name: CIccCmm::GetFirstXformSource
Purpose: Get source colorspace of first transform (similar to m_nSrcSpace with differences in dev colorimetric spaces)
Return: colorspace
Reimplemented from CIccCmm.
References CIccCmm::GetFirstXformSource(), and CIccApplyCmm::m_pCmm.
virtual icColorSpaceSignature CIccMruCmm::GetLastXformDest () inline virtual
Name: CIccCmm::GetNumXforms
Purpose: Get source colorspace of last transform (similar to m_nSrcSpace with differences in dev colorimetric spaces)
Return: colorspace
Reimplemented from CIccCmm.
References CIccCmm::GetLastXformDest(), and CIccApplyCmm::m_pCmm.
CIccApplyCmm * CIccMruCmm::GetNewApplyCmm (icStatusCMM & status) virtual
Name: CIccCmm::GetNewApplyCmm
Purpose: Allocates an CIccApplyCmm object that does the initialization of the Xforms that provides an Apply() function. Multiple CIccApplyCmm objects can be allocated and used in separate threads.
Reimplemented from CIccCmm.
References CIccApplyMruCmm, icCmmStatAllocErr, icCmmStatBad, CIccApplyMruCmm::Init(), m_nCacheSize, and m_pCmm.
virtual icUInt32Number CIccMruCmm::GetNumXforms () const inline virtual
Returns the number of profiles/transforms added.
Name: CIccCmm::GetNumXforms
Purpose: Get number of xforms in the xform list
Return: number of m_Xforms
Reimplemented from CIccCmm.
References CIccCmm::GetNumXforms(), and CIccApplyCmm::m_pCmm.
virtual CIccPCS* CIccMruCmm::GetPCS () inline virtual
Reimplemented from CIccCmm.
References CIccCmm::GetPCS(), and CIccApplyCmm::m_pCmm.
virtual icStatusCMM CIccMruCmm::RemoveAllIO () inline virtual
Name: CIccCmm::RemoveAllIO()
Purpose: Remove any attachments to CIccIO objects associated with the profiles related to the transforms attached to the CMM. Must be called after Begin().
Return: icCmmStatOK - All IO objects removed icCmmStatBadXform - Begin() has not been performed.
Reimplemented from CIccCmm.
References CIccApplyCmm::m_pCmm, and CIccCmm::RemoveAllIO().
Friends And Related Function Documentation
friend class CIccApplyMruCmm friend
Referenced by GetNewApplyCmm().
Member Data Documentation
icUInt16Number CIccMruCmm::m_nCacheSize protected
Referenced by Attach(), and GetNewApplyCmm().
CIccCmm* CIccMruCmm::m_pCmm protected
Referenced by Attach(), GetNewApplyCmm(), and ~CIccMruCmm().
The documentation for this class was generated from the following files:
IccCmm.h
IccCmm.cpp