CIccCurve Class Reference
CIccCurve Class Reference
#include <IccTagLut.h>
Public Member Functions
CIccCurve ()
virtual CIccTag * NewCopy () const
virtual ~CIccCurve ()
virtual void DumpLut (std::string &sDescription, const icChar *szName, icColorSpaceSignature csSig, int nIndex)
virtual void Begin ()
virtual icFloatNumber Apply (icFloatNumber v)
icFloatNumber Find (icFloatNumber v)
virtual bool IsIdentity ()
Public Member Functions inherited from CIccTag
CIccTag ()
virtual ~CIccTag ()
virtual icTagTypeSignature GetType () const
virtual bool IsArrayType ()
virtual bool IsMBBType ()
virtual const icChar * GetClassName () const
virtual IIccExtensionTag * GetExtension ()
virtual bool IsSupported ()
virtual bool Read (icUInt32Number size, CIccIO *pIO)
virtual bool Write (CIccIO *pIO)
virtual void Describe (std::string &sDescription)
virtual icValidateStatus Validate (icTagSignature sig, std::string &sReport, const CIccProfile *pProfile=NULL) const
Protected Member Functions
icFloatNumber Find (icFloatNumber v, icFloatNumber p0, icFloatNumber v0, icFloatNumber p1, icFloatNumber v1)
Additional Inherited Members
Static Public Member Functions inherited from CIccTag
static CIccTag * Create (icTagTypeSignature sig)
Public Attributes inherited from CIccTag
icUInt32Number m_nReserved
Detailed Description
Class: CIccCurve
Purpose: The base curve class
Constructor & Destructor Documentation
CIccCurve::CIccCurve () inline
virtual CIccCurve::~CIccCurve () inline virtual
Member Function Documentation
virtual icFloatNumber CIccCurve::Apply (icFloatNumber v) inline virtual
Reimplemented in CIccTagParametricCurve, and CIccTagCurve.
virtual void CIccCurve::Begin () inline virtual
Reimplemented in CIccTagCurve.
Referenced by CIccXform3DLut::Begin(), CIccXform4DLut::Begin(), CIccXformNDLut::Begin(), CIccXformMonochrome::GetInvCurve(), and CIccXformMatrixTRC::GetInvCurve().
virtual void CIccCurve::DumpLut (std::string & sDescription, const icChar * szName, icColorSpaceSignature csSig, int nIndex) inline virtual
Reimplemented in CIccTagParametricCurve, and CIccTagCurve.
icFloatNumber CIccCurve::Find (icFloatNumber v) inline
References Find().
Referenced by Find(), CIccXformMonochrome::GetInvCurve(), and CIccXformMatrixTRC::GetInvCurve().
icFloatNumber CIccCurve::Find (icFloatNumber v, icFloatNumber p0, icFloatNumber v0, icFloatNumber p1, icFloatNumber v1) protected
Name: CIccCurve::Find
Purpose: Read in the tag contents into a data block
Args: v = index to be searched, v0 = index less than/equal to v, p0 = the value at index v0, v1 = index greater than/equal to v, p1 = value at index v1
Return: The value at the requested index
virtual bool CIccCurve::IsIdentity () inline virtual
Reimplemented in CIccTagParametricCurve, and CIccTagCurve.
virtual CIccTag* CIccCurve::NewCopy () const inline virtual
Function: NewCopy(sDescription) Each derived tag will implement it's own NewCopy() function.
Parameter(s): none
Returns a new CIccTag object that is a copy of this object.
Reimplemented from CIccTag.
Reimplemented in CIccTagParametricCurve, and CIccTagCurve.
Referenced by CIccMBB::CIccMBB(), and CIccMBB::operator=().
The documentation for this class was generated from the following files:
IccTagLut.h
IccTagLut.cpp