CIccTagMultiLocalizedUnicode Class Reference
CIccTagMultiLocalizedUnicode Class Reference
#include <IccTagBasic.h>
Public Member Functions
CIccTagMultiLocalizedUnicode ()
CIccTagMultiLocalizedUnicode (const CIccTagMultiLocalizedUnicode &ITMLU)
CIccTagMultiLocalizedUnicode & operator= (const CIccTagMultiLocalizedUnicode &MultiLocalizedTag)
virtual CIccTag * NewCopy () const
virtual ~CIccTagMultiLocalizedUnicode ()
virtual icTagTypeSignature GetType () const
virtual const icChar * GetClassName () const
virtual void Describe (std::string &sDescription)
virtual bool Read (icUInt32Number size, CIccIO *pIO)
virtual bool Write (CIccIO *pIO)
virtual icValidateStatus Validate (icTagSignature sig, std::string &sReport, const CIccProfile *pProfile=NULL) const
CIccLocalizedUnicode * Find (icLanguageCode nLanguageCode=icLanguageCodeEnglish, icCountryCode nRegionCode=icCountryCodeUSA)
void SetText (const icChar *szText, icLanguageCode nLanguageCode=icLanguageCodeEnglish, icCountryCode nRegionCode=icCountryCodeUSA)
void SetText (const icUInt16Number *sszUnicode16Text, icLanguageCode nLanguageCode=icLanguageCodeEnglish, icCountryCode nRegionCode=icCountryCodeUSA)
void SetText (const icUInt32Number *sszUnicode32Text, icLanguageCode nLanguageCode=icLanguageCodeEnglish, icCountryCode nRegionCode=icCountryCodeUSA)
Public Member Functions inherited from CIccTag
CIccTag ()
virtual ~CIccTag ()
virtual bool IsArrayType ()
virtual bool IsMBBType ()
virtual IIccExtensionTag * GetExtension ()
virtual bool IsSupported ()
Public Attributes
CIccMultiLocalizedUnicode * m_Strings
Public Attributes inherited from CIccTag
icUInt32Number m_nReserved
Additional Inherited Members
Static Public Member Functions inherited from CIccTag
static CIccTag * Create (icTagTypeSignature sig)
Detailed Description
Class: CIccTagMultiLocalizedUnicode
Purpose: The MultiLocalizedUnicode tag
Constructor & Destructor Documentation
CIccTagMultiLocalizedUnicode::CIccTagMultiLocalizedUnicode ()
Name: CIccTagMultiLocalizedUnicode::CIccTagMultiLocalizedUnicode
Purpose: Constructor
CIccTagMultiLocalizedUnicode::CIccTagMultiLocalizedUnicode (const CIccTagMultiLocalizedUnicode & ITMLU)
Name: CIccTagMultiLocalizedUnicode::CIccTagMultiLocalizedUnicode
Purpose: Copy Constructor
Args: ITMLU = The CIccTagMultiLocalizedUnicode object to be copied
References m_Strings.
CIccTagMultiLocalizedUnicode::~CIccTagMultiLocalizedUnicode () virtual
Name: CIccTagMultiLocalizedUnicode::~CIccTagMultiLocalizedUnicode
Purpose: Destructor
Member Function Documentation
void CIccTagMultiLocalizedUnicode::Describe (std::string & sDescription) virtual
Name: CIccTagMultiLocalizedUnicode::Describe
Purpose: Dump data associated with the tag to a string
Args: sDescription - string to concatenate tag dump to
Reimplemented from CIccTag.
Referenced by CIccProfileIdDesc::Describe(), and CIccDictEntry::Describe().
CIccLocalizedUnicode * CIccTagMultiLocalizedUnicode::Find (icLanguageCode nLanguageCode = icLanguageCodeEnglish, icCountryCode nRegionCode = icCountryCodeUSA)
Name: sampleICC::CIccTagMultiLocalizedUnicode::Find
Purpose:
Args: nLanguageCode nRegionCode
Return: Pointer to CIccLocalizedUnicode object associated with the nLanguageCode and nRegionCode or NULL if not found
virtual const icChar* CIccTagMultiLocalizedUnicode::GetClassName () const inline virtual
Reimplemented from CIccTag.
virtual icTagTypeSignature CIccTagMultiLocalizedUnicode::GetType () const inline virtual
Function: GetType()
Purpose: Get Tag Type. Each derived tag will implement it's own GetType() function.
Reimplemented from CIccTag.
References icSigMultiLocalizedUnicodeType.
virtual CIccTag* CIccTagMultiLocalizedUnicode::NewCopy () const inline virtual
Function: NewCopy(sDescription) Each derived tag will implement it's own NewCopy() function.
Parameter(s): none
Returns a new CIccTag object that is a copy of this object.
Reimplemented from CIccTag.
Referenced by CIccDictEntry::CIccDictEntry(), and CIccDictEntry::operator=().
CIccTagMultiLocalizedUnicode & CIccTagMultiLocalizedUnicode::operator= (const CIccTagMultiLocalizedUnicode & MultiLocalizedTag)
Name: CIccTagMultiLocalizedUnicode::operator=
Purpose: Copy Operator
Args: MultiLocalizedTag = The CIccTagMultiLocalizedUnicode object to be copied
References m_Strings.
bool CIccTagMultiLocalizedUnicode::Read (icUInt32Number size, CIccIO * pIO) virtual
Name: CIccTagMultiLocalizedUnicode::Read
Purpose: Read in the tag contents into a data block
Since MultiLocalizedUnicode tags can be embedded in other tags this function ensures that the current read pointer will be set to the position just after the last name record.
Args: size - # of bytes in tag, pIO - IO object to read tag from
Return: true = successful, false = failure
Reimplemented from CIccTag.
References CIccLocalizedUnicode::GetBuf(), icSeekSet, CIccLocalizedUnicode::m_nCountryCode, CIccLocalizedUnicode::m_nLanguageCode, CIccIO::Read16(), CIccIO::Read32(), CIccIO::Seek(), CIccLocalizedUnicode::SetSize(), and CIccIO::Tell().
Referenced by CIccProfileIdDesc::Read(), and CIccTagDict::Read().
void CIccTagMultiLocalizedUnicode::SetText (const icChar * szText, icLanguageCode nLanguageCode = icLanguageCodeEnglish, icCountryCode nRegionCode = icCountryCodeUSA)
Name: sampleICC::CIccTagMultiLocalizedUnicode::SetText
Purpose:
Args: sszUnicodeText nLanguageCode RegionCode
References CIccLocalizedUnicode::SetText().
Referenced by CIccProfileIdDesc::CIccProfileIdDesc().
void CIccTagMultiLocalizedUnicode::SetText (const icUInt16Number * sszUnicode16Text, icLanguageCode nLanguageCode = icLanguageCodeEnglish, icCountryCode nRegionCode = icCountryCodeUSA)
Name: sampleICC::CIccTagMultiLocalizedUnicode::SetText
Purpose:
Args: sszUnicodeText nLanguageCode RegionCode
References CIccLocalizedUnicode::SetText().
void CIccTagMultiLocalizedUnicode::SetText (const icUInt32Number * sszUnicode32Text, icLanguageCode nLanguageCode = icLanguageCodeEnglish, icCountryCode nRegionCode = icCountryCodeUSA)
Name: sampleICC::CIccTagMultiLocalizedUnicode::SetText
Purpose:
Args: sszUnicodeText nLanguageCode RegionCode
References CIccLocalizedUnicode::SetText().
icValidateStatus CIccTagMultiLocalizedUnicode::Validate (icTagSignature sig, std::string & sReport, const CIccProfile * pProfile = NULL) const virtual
Name: CIccTagMultiLocalizedUnicode::Validate
Purpose: Check tag data validity.
Args: sig = signature of tag being validated, sReport = String to add report information to
Return: icValidateStatusOK if valid, or other error status.
Reimplemented from CIccTag.
References CIccInfo::GetSigName(), icMaxStatus(), icValidateWarning, icValidateWarningMsg, and CIccTag::Validate().
Referenced by CIccProfileIdDesc::Validate().
bool CIccTagMultiLocalizedUnicode::Write (CIccIO * pIO) virtual
Name: CIccTagMultiLocalizedUnicode::Write
Purpose: Write the tag to a file
Args: pIO - The IO object to write tag to.
Return: true = succesful, false = failure
Reimplemented from CIccTag.
References CIccIO::Write16(), and CIccIO::Write32().
Referenced by CIccProfileIdDesc::Write().
Member Data Documentation
CIccMultiLocalizedUnicode* CIccTagMultiLocalizedUnicode::m_Strings
Referenced by CIccTagMultiLocalizedUnicode(), and operator=().
The documentation for this class was generated from the following files:
IccTagBasic.h
IccTagBasic.cpp