CIccTagMeasurement Class Reference
CIccTagMeasurement Class Reference
#include <IccTagBasic.h>
Public Member Functions
CIccTagMeasurement ()
CIccTagMeasurement (const CIccTagMeasurement &ITM)
CIccTagMeasurement & operator= (const CIccTagMeasurement &MeasTag)
virtual CIccTag * NewCopy () const
virtual ~CIccTagMeasurement ()
virtual icTagTypeSignature GetType () const
virtual const icChar * GetClassName () const
virtual void Describe (std::string &sDescription)
virtual bool Read (icUInt32Number size, CIccIO *pIO)
virtual bool Write (CIccIO *pIO)
virtual icValidateStatus Validate (icTagSignature sig, std::string &sReport, const CIccProfile *pProfile=NULL) const
Public Member Functions inherited from CIccTag
CIccTag ()
virtual ~CIccTag ()
virtual bool IsArrayType ()
virtual bool IsMBBType ()
virtual IIccExtensionTag * GetExtension ()
virtual bool IsSupported ()
Public Attributes
icMeasurement m_Data
Public Attributes inherited from CIccTag
icUInt32Number m_nReserved
Additional Inherited Members
Static Public Member Functions inherited from CIccTag
static CIccTag * Create (icTagTypeSignature sig)
Detailed Description
Class: CIccTagMeasurement
Purpose: The measurmentType tag
Constructor & Destructor Documentation
CIccTagMeasurement::CIccTagMeasurement ()
Name: CIccTagMeasurement::CIccTagMeasurement
Purpose: Constructor
CIccTagMeasurement::CIccTagMeasurement (const CIccTagMeasurement & ITM)
Name: CIccTagMeasurement::CIccTagMeasurement
Purpose: Copy Constructor
Args: ITM = The CIccTagMeasurement object to be copied
References m_Data.
CIccTagMeasurement::~CIccTagMeasurement () virtual
Name: CIccTagMeasurement::~CIccTagMeasurement
Purpose: Destructor
Member Function Documentation
void CIccTagMeasurement::Describe (std::string & sDescription) virtual
Name: CIccTagMeasurement::Describe
Purpose: Dump data associated with the tag to a string
Args: sDescription - string to concatenate tag dump to
Reimplemented from CIccTag.
References CIccInfo::GetIlluminantName(), CIccInfo::GetMeasurementFlareName(), CIccInfo::GetMeasurementGeometryName(), CIccInfo::GetStandardObserverName(), and icFtoD().
virtual const icChar* CIccTagMeasurement::GetClassName () const inline virtual
Reimplemented from CIccTag.
virtual icTagTypeSignature CIccTagMeasurement::GetType () const inline virtual
Function: GetType()
Purpose: Get Tag Type. Each derived tag will implement it's own GetType() function.
Reimplemented from CIccTag.
References icSigMeasurementType.
virtual CIccTag* CIccTagMeasurement::NewCopy () const inline virtual
Function: NewCopy(sDescription) Each derived tag will implement it's own NewCopy() function.
Parameter(s): none
Returns a new CIccTag object that is a copy of this object.
Reimplemented from CIccTag.
CIccTagMeasurement & CIccTagMeasurement::operator= (const CIccTagMeasurement & MeasTag)
Name: CIccTagMeasurement::operator=
Purpose: Copy Operator
Args: MeasTag = The CIccTagMeasurement object to be copied
References m_Data.
bool CIccTagMeasurement::Read (icUInt32Number size, CIccIO * pIO) virtual
Name: CIccTagMeasurement::Read
Purpose: Read in the tag contents into a data block
Args: size - # of bytes in tag, pIO - IO object to read tag from
Return: true = successful, false = failure
Reimplemented from CIccTag.
References CIccIO::Read32().
icValidateStatus CIccTagMeasurement::Validate (icTagSignature sig, std::string & sReport, const CIccProfile * pProfile = NULL) const virtual
Name: CIccTagMeasurement::Validate
Purpose: Check tag data validity.
Args: sig = signature of tag being validated, sReport = String to add report information to
Return: icValidateStatusOK if valid, or other error status.
Reimplemented from CIccTag.
References CIccInfo::GetSigName(), icGeometry045or450, icGeometry0dord0, icGeometryUnknown, icIlluminantA, icIlluminantD50, icIlluminantD55, icIlluminantD65, icIlluminantD93, icIlluminantEquiPowerE, icIlluminantF2, icIlluminantF8, icIlluminantUnknown, icMaxStatus(), icStdObs1931TwoDegrees, icStdObs1964TenDegrees, icStdObsUnknown, icValidateNonCompliant, icValidateNonCompliantMsg, and CIccTag::Validate().
bool CIccTagMeasurement::Write (CIccIO * pIO) virtual
Name: CIccTagMeasurement::Write
Purpose: Write the tag to a file
Args: pIO - The IO object to write tag to.
Return: true = succesful, false = failure
Reimplemented from CIccTag.
References CIccIO::Write32().
Member Data Documentation
icMeasurement CIccTagMeasurement::m_Data
Referenced by CIccTagMeasurement(), and operator=().
The documentation for this class was generated from the following files:
IccTagBasic.h
IccTagBasic.cpp