CIccTagColorantTable Class Reference
CIccTagColorantTable Class Reference
#include <IccTagBasic.h>
Public Member Functions
CIccTagColorantTable (int nsize=1)
CIccTagColorantTable (const CIccTagColorantTable &ITCT)
CIccTagColorantTable & operator= (const CIccTagColorantTable &ColorantTableTag)
virtual CIccTag * NewCopy () const
virtual ~CIccTagColorantTable ()
virtual icTagTypeSignature GetType () const
virtual const icChar * GetClassName () const
virtual void Describe (std::string &sDescription)
virtual bool Read (icUInt32Number size, CIccIO *pIO)
virtual bool Write (CIccIO *pIO)
icColorantTableEntry & operator[] (icUInt32Number index)
icColorantTableEntry * GetEntry (icUInt32Number index)
icUInt32Number GetSize () const
void SetSize (icUInt16Number nSize, bool bZeroNew=true)
void SetPCS (icColorSpaceSignature sig)
icColorSpaceSignature GetPCS () const
virtual icValidateStatus Validate (icTagSignature sig, std::string &sReport, const CIccProfile *pProfile=NULL) const
Public Member Functions inherited from CIccTag
CIccTag ()
virtual ~CIccTag ()
virtual bool IsArrayType ()
virtual bool IsMBBType ()
virtual IIccExtensionTag * GetExtension ()
virtual bool IsSupported ()
Protected Attributes
icUInt32Number m_nCount
icColorantTableEntry * m_pData
icColorSpaceSignature m_PCS
Additional Inherited Members
Static Public Member Functions inherited from CIccTag
static CIccTag * Create (icTagTypeSignature sig)
Public Attributes inherited from CIccTag
icUInt32Number m_nReserved
Detailed Description
Class: CIccTagColorantTable
Purpose: Colorant Table Tag
Constructor & Destructor Documentation
CIccTagColorantTable::CIccTagColorantTable (int nSize = 1)
Name: CIccTagColorantTable::CIccTagColorantTable
Purpose: Constructor
Args: nSize = number of entries
CIccTagColorantTable::CIccTagColorantTable (const CIccTagColorantTable & ITCT)
Name: CIccTagColorantTable::CIccTagColorantTable
Purpose: Copy Constructor
Args: ITCT = The CIccTagUnknown object to be copied
References m_nCount, m_PCS, and m_pData.
CIccTagColorantTable::~CIccTagColorantTable () virtual
Name: CIccTagColorantTable::~CIccTagColorantTable
Purpose: Destructor
Member Function Documentation
void CIccTagColorantTable::Describe (std::string & sDescription) virtual
Name: CIccTagColorantTable::Describe
Purpose: Dump data associated with the tag to a string
Args: sDescription - string to concatenate tag dump to
Reimplemented from CIccTag.
References icLabFromPcs(), icSigXYZData, icU16toF(), and icUSFtoD().
virtual const icChar* CIccTagColorantTable::GetClassName () const inline virtual
Reimplemented from CIccTag.
icColorantTableEntry* CIccTagColorantTable::GetEntry (icUInt32Number index) inline
icColorSpaceSignature CIccTagColorantTable::GetPCS () const inline
icUInt32Number CIccTagColorantTable::GetSize () const inline
virtual icTagTypeSignature CIccTagColorantTable::GetType () const inline virtual
Function: GetType()
Purpose: Get Tag Type. Each derived tag will implement it's own GetType() function.
Reimplemented from CIccTag.
References icSigColorantTableType.
virtual CIccTag* CIccTagColorantTable::NewCopy () const inline virtual
Function: NewCopy(sDescription) Each derived tag will implement it's own NewCopy() function.
Parameter(s): none
Returns a new CIccTag object that is a copy of this object.
Reimplemented from CIccTag.
CIccTagColorantTable & CIccTagColorantTable::operator= (const CIccTagColorantTable & ColorantTableTag)
Name: CIccTagColorantTable::operator=
Purpose: Copy Operator
Args: ColorantTableTag = The CIccTagColorantTable object to be copied
References m_nCount, m_PCS, and m_pData.
icColorantTableEntry& CIccTagColorantTable::operator[] (icUInt32Number index) inline
bool CIccTagColorantTable::Read (icUInt32Number size, CIccIO * pIO) virtual
Name: CIccTagColorantTable::Read
Purpose: Read in the tag contents into a data block
Args: size - # of bytes in tag, pIO - IO object to read tag from
Return: true = successful, false = failure
Reimplemented from CIccTag.
References CIccIO::Read16(), CIccIO::Read32(), and CIccIO::Read8().
void CIccTagColorantTable::SetPCS (icColorSpaceSignature sig) inline
void CIccTagColorantTable::SetSize (icUInt16Number nSize, bool bZeroNew = true)
Name: CIccTagColorantTable::SetSize
Purpose: Sets the size of the data array.
Args: nSize - number of entries, bZeroNew - flag to zero newly formed values
icValidateStatus CIccTagColorantTable::Validate (icTagSignature sig, std::string & sReport, const CIccProfile * pProfile = NULL) const virtual
Name: CIccTagColorantTable::Validate
Purpose: Check tag data validity.
Args: sig = signature of tag being validated, sReport = String to add report information to
Return: icValidateStatusOK if valid, or other error status.
Reimplemented from CIccTag.
References icHeader::colorSpace, icHeader::deviceClass, CIccInfo::GetSigName(), icGetSpaceSamples(), icMaxStatus(), icSigColorantTableOutTag, icSigLinkClass, icValidateNonCompliant, icValidateNonCompliantMsg, icValidateWarning, icValidateWarningMsg, CIccProfile::m_Header, icHeader::pcs, and CIccTag::Validate().
bool CIccTagColorantTable::Write (CIccIO * pIO) virtual
Name: CIccTagColorantTable::Write
Purpose: Write the tag to a file
Args: pIO - The IO object to write tag to.
Return: true = succesful, false = failure
Reimplemented from CIccTag.
References CIccIO::Write16(), CIccIO::Write32(), and CIccIO::Write8().
Member Data Documentation
icUInt32Number CIccTagColorantTable::m_nCount protected
Referenced by CIccTagColorantTable(), and operator=().
icColorSpaceSignature CIccTagColorantTable::m_PCS protected
Referenced by CIccTagColorantTable(), and operator=().
icColorantTableEntry* CIccTagColorantTable::m_pData protected
Referenced by CIccTagColorantTable(), and operator=().
The documentation for this class was generated from the following files:
IccTagBasic.h
IccTagBasic.cpp