CIccTagViewingConditions Class Reference
CIccTagViewingConditions Class Reference
#include <IccTagBasic.h>
Public Member Functions
CIccTagViewingConditions ()
CIccTagViewingConditions (const CIccTagViewingConditions &ITVC)
CIccTagViewingConditions & operator= (const CIccTagViewingConditions &ViewCondTag)
virtual CIccTag * NewCopy () const
virtual ~CIccTagViewingConditions ()
virtual icTagTypeSignature GetType () const
virtual const icChar * GetClassName () const
virtual void Describe (std::string &sDescription)
virtual bool Read (icUInt32Number size, CIccIO *pIO)
virtual bool Write (CIccIO *pIO)
virtual icValidateStatus Validate (icTagSignature sig, std::string &sReport, const CIccProfile *pProfile=NULL) const
Public Member Functions inherited from CIccTag
CIccTag ()
virtual ~CIccTag ()
virtual bool IsArrayType ()
virtual bool IsMBBType ()
virtual IIccExtensionTag * GetExtension ()
virtual bool IsSupported ()
Public Attributes
icXYZNumber m_XYZIllum
icXYZNumber m_XYZSurround
icIlluminant m_illumType
Public Attributes inherited from CIccTag
icUInt32Number m_nReserved
Additional Inherited Members
Static Public Member Functions inherited from CIccTag
static CIccTag * Create (icTagTypeSignature sig)
Detailed Description
Class: CIccTagViewingConditions
Purpose: Viewing conditions tag type
Constructor & Destructor Documentation
CIccTagViewingConditions::CIccTagViewingConditions ()
Name: CIccTagViewingConditions::CIccTagViewingConditions
Purpose: Constructor
References icIlluminantUnknown.
CIccTagViewingConditions::CIccTagViewingConditions (const CIccTagViewingConditions & ITVC)
Name: CIccTagViewingConditions::CIccTagViewingConditions
Purpose: Copy Constructor
Args: ITVC = The CIccTagViewingConditions object to be copied
References m_illumType, m_XYZIllum, and m_XYZSurround.
CIccTagViewingConditions::~CIccTagViewingConditions () virtual
Name: CIccTagViewingConditions::~CIccTagViewingConditions
Purpose: Destructor
Member Function Documentation
void CIccTagViewingConditions::Describe (std::string & sDescription) virtual
Name: CIccTagViewingConditions::Describe
Purpose: Dump data associated with the tag to a string
Args: sDescription - string to concatenate tag dump to
Reimplemented from CIccTag.
References CIccInfo::GetIlluminantName(), and icFtoD().
virtual const icChar* CIccTagViewingConditions::GetClassName () const inline virtual
Reimplemented from CIccTag.
virtual icTagTypeSignature CIccTagViewingConditions::GetType () const inline virtual
Function: GetType()
Purpose: Get Tag Type. Each derived tag will implement it's own GetType() function.
Reimplemented from CIccTag.
References icSigViewingConditionsType.
virtual CIccTag* CIccTagViewingConditions::NewCopy () const inline virtual
Function: NewCopy(sDescription) Each derived tag will implement it's own NewCopy() function.
Parameter(s): none
Returns a new CIccTag object that is a copy of this object.
Reimplemented from CIccTag.
CIccTagViewingConditions & CIccTagViewingConditions::operator= (const CIccTagViewingConditions & ViewCondTag)
Name: CIccTagViewingConditions::operator=
Purpose: Copy Operator
Args: ViewCondTag = The CIccTagViewingConditions object to be copied
References m_illumType, m_XYZIllum, and m_XYZSurround.
bool CIccTagViewingConditions::Read (icUInt32Number size, CIccIO * pIO) virtual
Name: CIccTagViewingConditions::Read
Purpose: Read in the tag contents into a data block
Args: size - # of bytes in tag, pIO - IO object to read tag from
Return: true = successful, false = failure
Reimplemented from CIccTag.
References CIccIO::Read32().
icValidateStatus CIccTagViewingConditions::Validate (icTagSignature sig, std::string & sReport, const CIccProfile * pProfile = NULL) const virtual
Name: CIccTagViewingConditions::Validate
Purpose: Check tag data validity.
Args: sig = signature of tag being validated, sReport = String to add report information to
Return: icValidateStatusOK if valid, or other error status.
Reimplemented from CIccTag.
References CIccInfo::CheckData(), CIccInfo::GetSigName(), icMaxStatus(), and CIccTag::Validate().
bool CIccTagViewingConditions::Write (CIccIO * pIO) virtual
Name: CIccTagViewingConditions::Write
Purpose: Write the tag to a file
Args: pIO - The IO object to write tag to.
Return: true = succesful, false = failure
Reimplemented from CIccTag.
References CIccIO::Write32().
Member Data Documentation
icIlluminant CIccTagViewingConditions::m_illumType
Referenced by CIccTagViewingConditions(), and operator=().
icXYZNumber CIccTagViewingConditions::m_XYZIllum
Referenced by CIccTagViewingConditions(), and operator=().
icXYZNumber CIccTagViewingConditions::m_XYZSurround
Referenced by CIccTagViewingConditions(), and operator=().
The documentation for this class was generated from the following files:
IccTagBasic.h
IccTagBasic.cpp