CIccTagData Class Reference
CIccTagData Class Reference
#include <IccTagBasic.h>
Public Member Functions
CIccTagData (int nSize=1)
CIccTagData (const CIccTagData &ITD)
CIccTagData & operator= (const CIccTagData &DataTag)
virtual CIccTag * NewCopy () const
virtual ~CIccTagData ()
virtual icTagTypeSignature GetType () const
virtual const icChar * GetClassName () const
virtual bool IsArrayType ()
virtual void Describe (std::string &sDescription)
virtual bool Read (icUInt32Number size, CIccIO *pIO)
virtual bool Write (CIccIO *pIO)
icUInt32Number GetSize () const
void SetSize (icUInt32Number nSize, bool bZeroNew=true)
icUInt8Number & operator[] (icUInt32Number index)
icUInt8Number * GetData (icUInt32Number index)
void SetTypeAscii (bool bIsAscii=true)
bool IsTypeAscii ()
virtual icValidateStatus Validate (icTagSignature sig, std::string &sReport, const CIccProfile *pProfile=NULL) const
Public Member Functions inherited from CIccTag
CIccTag ()
virtual ~CIccTag ()
virtual bool IsMBBType ()
virtual IIccExtensionTag * GetExtension ()
virtual bool IsSupported ()
Protected Attributes
icUInt32Number m_nDataFlag
icUInt8Number * m_pData
icUInt32Number m_nSize
Additional Inherited Members
Static Public Member Functions inherited from CIccTag
static CIccTag * Create (icTagTypeSignature sig)
Public Attributes inherited from CIccTag
icUInt32Number m_nReserved
Detailed Description
Class: CIccTagData
Purpose: The data type tag
Constructor & Destructor Documentation
CIccTagData::CIccTagData (int nSize = 1)
Name: CIccTagData::CIccTagData
Purpose: Constructor
Args: nSize = number of data entries
CIccTagData::CIccTagData (const CIccTagData & ITD)
Name: CIccTagData::CIccTagData
Purpose: Copy Constructor
Args: ITD = The CIccTagData object to be copied
References m_nDataFlag, m_nSize, and m_pData.
CIccTagData::~CIccTagData () virtual
Name: CIccTagData::~CIccTagData
Purpose: Destructor
Member Function Documentation
void CIccTagData::Describe (std::string & sDescription) virtual
Name: CIccTagData::Describe
Purpose: Dump data associated with the tag to a string
Args: sDescription - string to concatenate tag dump to
Reimplemented from CIccTag.
virtual const icChar* CIccTagData::GetClassName () const inline virtual
Reimplemented from CIccTag.
icUInt8Number* CIccTagData::GetData (icUInt32Number index) inline
icUInt32Number CIccTagData::GetSize () const inline
virtual icTagTypeSignature CIccTagData::GetType () const inline virtual
Function: GetType()
Purpose: Get Tag Type. Each derived tag will implement it's own GetType() function.
Reimplemented from CIccTag.
References icSigDataType.
virtual bool CIccTagData::IsArrayType () inline virtual
Reimplemented from CIccTag.
bool CIccTagData::IsTypeAscii () inline
References icAsciiData.
virtual CIccTag* CIccTagData::NewCopy () const inline virtual
Function: NewCopy(sDescription) Each derived tag will implement it's own NewCopy() function.
Parameter(s): none
Returns a new CIccTag object that is a copy of this object.
Reimplemented from CIccTag.
CIccTagData & CIccTagData::operator= (const CIccTagData & DataTag)
Name: CIccTagData::operator=
Purpose: Copy Operator
Args: DataTag = The CIccTagData object to be copied
References m_nDataFlag, m_nSize, and m_pData.
icUInt8Number& CIccTagData::operator[] (icUInt32Number index) inline
bool CIccTagData::Read (icUInt32Number size, CIccIO * pIO) virtual
Name: CIccTagData::Read
Purpose: Read in the tag contents into a data block
Args: size - # of bytes in tag, pIO - IO object to read tag from
Return: true = successful, false = failure
Reimplemented from CIccTag.
References CIccIO::Read32(), and CIccIO::Read8().
void CIccTagData::SetSize (icUInt32Number nSize, bool bZeroNew = true)
Name: CIccTagData::SetSize
Purpose: Sets the size of the data array.
Args: nSize - number of data entries, bZeroNew - flag to zero newly formed values
void CIccTagData::SetTypeAscii (bool bIsAscii = true) inline
References icAsciiData, and icBinaryData.
icValidateStatus CIccTagData::Validate (icTagSignature sig, std::string & sReport, const CIccProfile * pProfile = NULL) const virtual
Name: CIccTagData::Validate
Purpose: Check tag data validity.
Args: sig = signature of tag being validated, sReport = String to add report information to
Return: icValidateStatusOK if valid, or other error status.
Reimplemented from CIccTag.
References CIccInfo::GetSigName(), icMaxStatus(), icValidateNonCompliant, icValidateNonCompliantMsg, and CIccTag::Validate().
bool CIccTagData::Write (CIccIO * pIO) virtual
Name: CIccTagData::Write
Purpose: Write the tag to a file
Args: pIO - The IO object to write tag to.
Return: true = succesful, false = failure
Reimplemented from CIccTag.
References CIccIO::Write32(), and CIccIO::Write8().
Member Data Documentation
icUInt32Number CIccTagData::m_nDataFlag protected
Referenced by CIccTagData(), and operator=().
icUInt32Number CIccTagData::m_nSize protected
Referenced by CIccTagData(), and operator=().
icUInt8Number* CIccTagData::m_pData protected
Referenced by CIccTagData(), and operator=().
The documentation for this class was generated from the following files:
IccTagBasic.h
IccTagBasic.cpp