CIccApplyCmm Class Reference
CIccApplyCmm Class Reference
#include <IccCmm.h>
Public Member Functions
virtual ~CIccApplyCmm ()
virtual icStatusCMM Apply (icFloatNumber *DstPixel, const icFloatNumber *SrcPixel)
virtual icStatusCMM Apply (icFloatNumber *DstPixel, const icFloatNumber *SrcPixel, icUInt32Number nPixels)
void AppendApplyXform (CIccApplyXform *pApplyXform)
CIccCmm * GetCmm ()
Protected Member Functions
CIccApplyCmm (CIccCmm *pCmm)
Protected Attributes
CIccApplyXformList * m_Xforms
CIccCmm * m_pCmm
CIccPCS * m_pPCS
Friends
class CIccCmm
Detailed Description
Type: Class
Purpose: Defines a class that provides and interface for applying pixel transformations through a CMM. Multiply CIccCmmApply objects can use a single CIccCmm Object.
Constructor & Destructor Documentation
CIccApplyCmm::~CIccApplyCmm () virtual
Name: CIccApplyCmm::~CIccApplyCmm
Purpose: Destructor
References m_pPCS, and m_Xforms.
CIccApplyCmm::CIccApplyCmm (CIccCmm * pCmm) protected
Name: CIccApplyCmm::CIccApplyCmm
Purpose: Constructor
Args: pCmm = ptr to CMM to apply against
References CIccCmm::GetPCS(), m_pCmm, m_pPCS, and m_Xforms.
Member Function Documentation
void CIccApplyCmm::AppendApplyXform (CIccApplyXform * pApplyXform)
References m_Xforms, and CIccApplyXformPtr::ptr.
Referenced by CIccNamedColorCmm::GetNewApply(), and CIccCmm::GetNewApplyCmm().
icStatusCMM CIccApplyCmm::Apply (icFloatNumber * DstPixel, const icFloatNumber * SrcPixel) virtual
Name: CIccApplyCmm::Apply
Purpose: Does the actual application of the Xforms in the list.
Args: DstPixel = Destination pixel where the result is stored, SrcPixel = Source pixel which is to be applied.
Reimplemented in CIccApplyMruCmm, and CIccApplyNamedColorCmm.
References CIccXform::Apply(), CIccPCS::Check(), CIccPCS::CheckLast(), icCmmStatBadXform, icCmmStatOk, CIccCmm::m_nDestSpace, CIccCmm::m_nSrcSpace, m_pCmm, m_pPCS, m_Xforms, CIccXform::NoClipPCS(), and CIccPCS::Reset().
Referenced by CIccCmm::Apply().
icStatusCMM CIccApplyCmm::Apply (icFloatNumber * DstPixel, const icFloatNumber * SrcPixel, icUInt32Number nPixels) virtual
Name: CIccApplyCmm::Apply
Purpose: Does the actual application of the Xforms in the list.
Args: DstPixel = Destination pixel where the result is stored, SrcPixel = Source pixel which is to be applied.
Reimplemented in CIccApplyMruCmm, and CIccApplyNamedColorCmm.
References CIccPCS::Check(), CIccPCS::CheckLast(), CIccCmm::GetDestSamples(), CIccCmm::GetSourceSamples(), icCmmStatBadXform, icCmmStatOk, CIccCmm::m_nDestSpace, CIccCmm::m_nSrcSpace, m_pCmm, m_pPCS, m_Xforms, and CIccPCS::Reset().
CIccCmm* CIccApplyCmm::GetCmm () inline
Friends And Related Function Documentation
friend class CIccCmm friend
Member Data Documentation
CIccCmm* CIccApplyCmm::m_pCmm protected
Referenced by Apply(), CIccApplyNamedColorCmm::Apply(), CIccApplyCmm(), CIccMruCmm::GetFirstXformSource(), CIccMruCmm::GetLastXformDest(), CIccMruCmm::GetNumXforms(), CIccMruCmm::GetPCS(), CIccApplyMruCmm::Init(), and CIccMruCmm::RemoveAllIO().
CIccPCS* CIccApplyCmm::m_pPCS protected
Referenced by Apply(), CIccApplyNamedColorCmm::Apply(), CIccApplyCmm(), and ~CIccApplyCmm().
CIccApplyXformList* CIccApplyCmm::m_Xforms protected
Referenced by AppendApplyXform(), Apply(), CIccApplyNamedColorCmm::Apply(), CIccApplyCmm(), and ~CIccApplyCmm().
The documentation for this class was generated from the following files:
IccCmm.h
IccCmm.cpp