CIccIO Class Reference
CIccIO Class Reference
#include <IccIO.h>
Public Member Functions
virtual ~CIccIO ()
virtual void Close ()
virtual icInt32Number Read8 (void *pBuf8, icInt32Number nNum=1)
virtual icInt32Number Write8 (void *pBuf8, icInt32Number nNum=1)
icInt32Number ReadLine (void *pBuf8, icInt32Number nNum=256)
icInt32Number Read16 (void *pBuf16, icInt32Number nNum=1)
icInt32Number Write16 (void *pBuf16, icInt32Number nNum=1)
icInt32Number Read32 (void *pBuf32, icInt32Number nNum=1)
icInt32Number Write32 (void *pBuf32, icInt32Number nNum=1)
icInt32Number Read64 (void *pBuf64, icInt32Number nNum=1)
icInt32Number Write64 (void *pBuf64, icInt32Number nNum=1)
icInt32Number Read8Float (void *pBufFloat, icInt32Number nNum=1)
icInt32Number Write8Float (void *pBuf16, icInt32Number nNum=1)
icInt32Number Read16Float (void *pBufFloat, icInt32Number nNum=1)
icInt32Number Write16Float (void *pBuf16, icInt32Number nNum=1)
icInt32Number ReadFloat32Float (void *pBufFloat, icInt32Number nNum=1)
icInt32Number WriteFloat32Float (void *pBufFloat, icInt32Number nNum=1)
virtual icInt32Number GetLength ()
virtual icInt32Number Seek (icInt32Number nOffset, icSeekVal pos)
virtual icInt32Number Tell ()
bool Align32 ()
Write operation to make sure that filelength is evenly divisible by 4.
bool Sync32 (icUInt32Number nOffset=0)
Operation to make sure read position is evenly divisible by 4.
Detailed Description
Type: Class
Purpose: This is the base object that handles the IO with an ICC profile.
Constructor & Destructor Documentation
virtual CIccIO::~CIccIO () inline virtual
Member Function Documentation
bool CIccIO::Align32 ()
Write operation to make sure that filelength is evenly divisible by 4.
References icSeekEnd.
Referenced by CIccTagProfileSequenceId::Write(), CIccTagCurve::Write(), CIccProfile::Write(), CIccTagDict::Write(), CIccTagParametricCurve::Write(), CIccTagLutAtoB::Write(), and CIccProfileDescText::Write().
virtual void CIccIO::Close () inline virtual
Reimplemented in CIccNullIO, CIccMemIO, and CIccFileIO.
virtual icInt32Number CIccIO::GetLength () inline virtual
Reimplemented in CIccNullIO, CIccMemIO, and CIccFileIO.
Referenced by CalcProfileID(), CIccProfile::Write(), and CIccTagResponseCurveSet16::Write().
icInt32Number CIccIO::Read16 (void * pBuf16, icInt32Number nNum = 1)
References icSwab16Array().
Referenced by CIccMpeAcs::Read(), CIccFormulaCurveSegment::Read(), CIccTagDict::Read(), CIccTagParametricCurve::Read(), CIccMpeUnknown::Read(), CIccSegmentedCurve::Read(), CIccTagTextDescription::Read(), CIccMpeCurveSet::Read(), CIccMpeMatrix::Read(), CIccTagMultiProcessElement::Read(), CIccMpeCLUT::Read(), CIccTagLutAtoB::Read(), CIccTagChromaticity::Read(), CIccTagLut16::Read(), CIccTagNum< T, Tsig >::Read(), CIccTagMultiLocalizedUnicode::Read(), CIccTagDateTime::Read(), CIccTagColorantTable::Read(), CIccResponseCurveStruct::Read(), CIccTagResponseCurveSet16::Read(), and CIccProfile::ReadBasic().
icInt32Number CIccIO::Read16Float (void * pBufFloat, icInt32Number nNum = 1)
Referenced by CIccTagCurve::Read(), CIccTagNamedColor2::Read(), CIccTagLut16::Read(), and CIccCLUT::ReadData().
icInt32Number CIccIO::Read32 (void * pBuf32, icInt32Number nNum = 1)
References icSwab32Array().
Referenced by CIccProfile::LoadTag(), CIccMpeAcs::Read(), CIccTagProfileSequenceId::Read(), CIccTagCurve::Read(), CIccFormulaCurveSegment::Read(), CIccTagDict::Read(), CIccTagParametricCurve::Read(), CIccSampledCurveSegment::Read(), CIccTagUnknown::Read(), CIccMpeUnknown::Read(), CIccTagText::Read(), CIccSegmentedCurve::Read(), CIccTagTextDescription::Read(), CIccMpeCurveSet::Read(), CIccMpeMatrix::Read(), CIccTagSignature::Read(), CIccTagMultiProcessElement::Read(), CIccTagNamedColor2::Read(), CIccMpeCLUT::Read(), CIccTagLutAtoB::Read(), CIccTagXYZ::Read(), CIccTagLut8::Read(), CIccTagChromaticity::Read(), CIccTagLut16::Read(), CIccTagFixedNum< T, Tsig >::Read(), CIccTagNum< T, Tsig >::Read(), CIccTagMeasurement::Read(), CIccTagMultiLocalizedUnicode::Read(), CIccTagData::Read(), CIccTagDateTime::Read(), CIccTagColorantOrder::Read(), CIccTagColorantTable::Read(), CIccTagViewingConditions::Read(), CIccProfileDescText::Read(), CIccTagProfileSeqDesc::Read(), CIccResponseCurveStruct::Read(), CIccTagResponseCurveSet16::Read(), and CIccProfile::ReadBasic().
icInt32Number CIccIO::Read64 (void * pBuf64, icInt32Number nNum = 1)
References icSwab64Array().
Referenced by CIccTagNum< T, Tsig >::Read(), CIccTagProfileSeqDesc::Read(), and CIccProfile::ReadBasic().
virtual icInt32Number CIccIO::Read8 (void * pBuf8, icInt32Number nNum = 1) inline virtual
Reimplemented in CIccNullIO, CIccMemIO, and CIccFileIO.
Referenced by CalcProfileID(), CIccProfileIdDesc::Read(), CIccMpeAcs::Read(), CIccTagUnknown::Read(), CIccMpeUnknown::Read(), CIccTagText::Read(), CIccCLUT::Read(), CIccTagTextDescription::Read(), CIccTagNamedColor2::Read(), CIccMpeCLUT::Read(), CIccTagLutAtoB::Read(), CIccTagLut8::Read(), CIccTagLut16::Read(), CIccTagNum< T, Tsig >::Read(), CIccTagData::Read(), CIccTagColorantOrder::Read(), CIccTagColorantTable::Read(), and CIccProfile::ReadBasic().
icInt32Number CIccIO::Read8Float (void * pBufFloat, icInt32Number nNum = 1)
Referenced by CIccTagLut8::Read(), and CIccCLUT::ReadData().
icInt32Number CIccIO::ReadFloat32Float (void * pBufFloat, icInt32Number nNum = 1)
Referenced by CIccFormulaCurveSegment::Read(), CIccSampledCurveSegment::Read(), CIccSegmentedCurve::Read(), CIccMpeMatrix::Read(), and CIccMpeCLUT::Read().
icInt32Number CIccIO::ReadLine (void * pBuf8, icInt32Number nNum = 256)
virtual icInt32Number CIccIO::Seek (icInt32Number nOffset, icSeekVal pos) inline virtual
Reimplemented in CIccNullIO, CIccMemIO, and CIccFileIO.
Referenced by CalcProfileID(), CIccProfile::CheckFileSize(), CIccProfile::LoadTag(), CIccTagProfileSequenceId::Read(), CIccTagDict::Read(), CIccSegmentedCurve::Read(), CIccMpeCurveSet::Read(), CIccTagMultiProcessElement::Read(), CIccTagLutAtoB::Read(), CIccTagMultiLocalizedUnicode::Read(), CIccProfileDescText::Read(), CIccProfile::ReadBasic(), CIccProfile::ReadTags(), CIccTagProfileSequenceId::Write(), CIccProfile::Write(), CIccTagDict::Write(), CIccMpeCurveSet::Write(), CIccTagMultiProcessElement::Write(), CIccTagLutAtoB::Write(), and CIccTagResponseCurveSet16::Write().
bool CIccIO::Sync32 (icUInt32Number nOffset = 0)
Operation to make sure read position is evenly divisible by 4.
References icSeekSet.
Referenced by CIccTagLutAtoB::Read(), CIccProfileDescText::Read(), CIccMpeCurveSet::Write(), and CIccTagMultiProcessElement::Write().
virtual icInt32Number CIccIO::Tell () inline virtual
Reimplemented in CIccNullIO, CIccMemIO, and CIccFileIO.
Referenced by CalcProfileID(), CIccProfile::CheckFileSize(), CIccTagProfileSequenceId::Read(), CIccTagDict::Read(), CIccSegmentedCurve::Read(), CIccTagTextDescription::Read(), CIccMpeCurveSet::Read(), CIccTagMultiProcessElement::Read(), CIccTagLutAtoB::Read(), CIccTagLut8::Read(), CIccTagLut16::Read(), CIccTagMultiLocalizedUnicode::Read(), CIccProfileDescText::Read(), CIccTagProfileSeqDesc::Read(), CIccProfile::ReadTags(), CIccTagProfileSequenceId::Write(), CIccTagDict::Write(), CIccMpeCurveSet::Write(), CIccTagMultiProcessElement::Write(), and CIccTagLutAtoB::Write().
icInt32Number CIccIO::Write16 (void * pBuf16, icInt32Number nNum = 1)
References icSwab16.
Referenced by CIccMpeAcs::Write(), CIccFormulaCurveSegment::Write(), CIccProfile::Write(), CIccTagDict::Write(), CIccTagParametricCurve::Write(), CIccMpeUnknown::Write(), CIccSegmentedCurve::Write(), CIccTagTextDescription::Write(), CIccMpeCurveSet::Write(), CIccMpeMatrix::Write(), CIccTagMultiProcessElement::Write(), CIccMpeCLUT::Write(), CIccTagLutAtoB::Write(), CIccTagChromaticity::Write(), CIccTagLut16::Write(), CIccTagMultiLocalizedUnicode::Write(), CIccTagDateTime::Write(), CIccTagColorantTable::Write(), CIccResponseCurveStruct::Write(), and CIccTagResponseCurveSet16::Write().
icInt32Number CIccIO::Write16Float (void * pBuf16, icInt32Number nNum = 1)
References __max, and __min.
Referenced by CIccTagCurve::Write(), CIccTagNamedColor2::Write(), CIccTagLut16::Write(), and CIccCLUT::WriteData().
icInt32Number CIccIO::Write32 (void * pBuf32, icInt32Number nNum = 1)
References icSwab32.
Referenced by CIccMpeAcs::Write(), CIccTagProfileSequenceId::Write(), CIccTagCurve::Write(), CIccFormulaCurveSegment::Write(), CIccProfile::Write(), CIccTagDict::Write(), CIccTagParametricCurve::Write(), CIccSampledCurveSegment::Write(), CIccTagUnknown::Write(), CIccMpeUnknown::Write(), CIccTagText::Write(), CIccSegmentedCurve::Write(), CIccTagTextDescription::Write(), CIccMpeCurveSet::Write(), CIccMpeMatrix::Write(), CIccTagSignature::Write(), CIccTagMultiProcessElement::Write(), CIccTagNamedColor2::Write(), CIccMpeCLUT::Write(), CIccTagLutAtoB::Write(), CIccTagXYZ::Write(), CIccTagLut8::Write(), CIccTagChromaticity::Write(), CIccTagLut16::Write(), CIccTagFixedNum< T, Tsig >::Write(), CIccTagNum< T, Tsig >::Write(), CIccTagMeasurement::Write(), CIccTagMultiLocalizedUnicode::Write(), CIccTagData::Write(), CIccTagDateTime::Write(), CIccTagColorantOrder::Write(), CIccTagColorantTable::Write(), CIccTagViewingConditions::Write(), CIccTagProfileSeqDesc::Write(), CIccResponseCurveStruct::Write(), and CIccTagResponseCurveSet16::Write().
icInt32Number CIccIO::Write64 (void * pBuf64, icInt32Number nNum = 1)
References icSwab64.
Referenced by CIccProfile::Write(), and CIccTagProfileSeqDesc::Write().
virtual icInt32Number CIccIO::Write8 (void * pBuf8, icInt32Number nNum = 1) inline virtual
Reimplemented in CIccNullIO, CIccMemIO, and CIccFileIO.
Referenced by CIccProfileIdDesc::Write(), CIccMpeAcs::Write(), CIccProfile::Write(), CIccTagDict::Write(), CIccTagUnknown::Write(), CIccMpeUnknown::Write(), CIccTagText::Write(), CIccCLUT::Write(), CIccTagTextDescription::Write(), CIccTagNamedColor2::Write(), CIccMpeCLUT::Write(), CIccTagLutAtoB::Write(), CIccTagLut8::Write(), CIccTagLut16::Write(), CIccTagData::Write(), CIccTagColorantOrder::Write(), and CIccTagColorantTable::Write().
icInt32Number CIccIO::Write8Float (void * pBuf16, icInt32Number nNum = 1)
References __max, and __min.
Referenced by CIccTagLut8::Write(), and CIccCLUT::WriteData().
icInt32Number CIccIO::WriteFloat32Float (void * pBufFloat, icInt32Number nNum = 1)
Referenced by CIccFormulaCurveSegment::Write(), CIccSampledCurveSegment::Write(), CIccSegmentedCurve::Write(), CIccMpeMatrix::Write(), and CIccMpeCLUT::Write().
The documentation for this class was generated from the following files:
IccIO.h
IccIO.cpp