CIccApplyNamedColorCmm Class Reference
CIccApplyNamedColorCmm Class Reference
#include <IccCmm.h>
Public Member Functions
virtual ~CIccApplyNamedColorCmm ()
virtual icStatusCMM Apply (icFloatNumber *DstPixel, const icFloatNumber *SrcPixel)
virtual icStatusCMM Apply (icFloatNumber *DstPixel, const icFloatNumber *SrcPixel, icUInt32Number nPixels)
virtual icStatusCMM Apply (icChar *DstColorName, const icFloatNumber *SrcPixel)
Define 4 apply interfaces that are used depending upon the source and destination xforms.
virtual icStatusCMM Apply (icFloatNumber *DstPixel, const icChar *SrcColorName)
virtual icStatusCMM Apply (icChar *DstColorName, const icChar *SrcColorName)
Public Member Functions inherited from CIccApplyCmm
virtual ~CIccApplyCmm ()
void AppendApplyXform (CIccApplyXform *pApplyXform)
CIccCmm * GetCmm ()
Protected Member Functions
CIccApplyNamedColorCmm (CIccNamedColorCmm *pCmm)
Protected Member Functions inherited from CIccApplyCmm
CIccApplyCmm (CIccCmm *pCmm)
Friends
class CIccNamedColorCmm
Additional Inherited Members
Protected Attributes inherited from CIccApplyCmm
CIccApplyXformList * m_Xforms
CIccCmm * m_pCmm
CIccPCS * m_pPCS
Detailed Description
Type: Class
Purpose: Defines a class that provides and interface for applying pixel transformations through a Named Color CMM. Multiply CIccApplyNamedColorCmm objects can refer to a single CIccNamedColorCmm Object.
Constructor & Destructor Documentation
CIccApplyNamedColorCmm::~CIccApplyNamedColorCmm () virtual
Name: CIccApplyCmm::CIccApplyCmm
Purpose: Destructor
CIccApplyNamedColorCmm::CIccApplyNamedColorCmm (CIccNamedColorCmm * pCmm) protected
Name: CIccApplyCmm::CIccApplyCmm
Purpose: Constructor
Args: pCmm = ptr to CMM to apply against
Member Function Documentation
icStatusCMM CIccApplyNamedColorCmm::Apply (icFloatNumber * DstPixel, const icFloatNumber * SrcPixel) virtual
Name: CIccApplyNamedColorCmm::Apply
Purpose: Does the actual application of the Xforms in the list.
Args: DstPixel = Destination pixel where the result is stored, SrcPixel = Source pixel which is to be applied.
Reimplemented from CIccApplyCmm.
References CIccXform::Apply(), CIccXformNamedColor::Apply(), CIccPCS::Check(), CIccPCS::CheckLast(), CIccCmm::GetDestSpace(), CIccXformNamedColor::GetInterface(), CIccCmm::GetSourceSpace(), CIccApplyXform::GetXform(), CIccXform::GetXformType(), icApplyNamed2Pixel, icApplyPixel2Named, icApplyPixel2Pixel, icCmmStatBadXform, icCmmStatIncorrectApply, icCmmStatOk, icXformTypeNamedColor, CIccApplyCmm::m_pCmm, CIccApplyCmm::m_pPCS, CIccApplyCmm::m_Xforms, and CIccPCS::Reset().
icStatusCMM CIccApplyNamedColorCmm::Apply (icFloatNumber * DstPixel, const icFloatNumber * SrcPixel, icUInt32Number nPixels) virtual
Name: CIccApplyNamedColorCmm::Apply
Purpose: Does the actual application of the Xforms in the list.
Args: DstPixel = Destination pixel where the result is stored, SrcPixel = Source pixel which is to be applied.
Reimplemented from CIccApplyCmm.
References CIccXform::Apply(), CIccXformNamedColor::Apply(), CIccPCS::Check(), CIccPCS::CheckLast(), CIccCmm::GetDestSamples(), CIccCmm::GetDestSpace(), CIccXformNamedColor::GetInterface(), CIccCmm::GetSourceSamples(), CIccCmm::GetSourceSpace(), CIccApplyXform::GetXform(), CIccXform::GetXformType(), icApplyNamed2Pixel, icApplyPixel2Named, icApplyPixel2Pixel, icCmmStatBadXform, icCmmStatIncorrectApply, icCmmStatOk, icXformTypeNamedColor, CIccApplyCmm::m_pCmm, CIccApplyCmm::m_pPCS, CIccApplyCmm::m_Xforms, and CIccPCS::Reset().
icStatusCMM CIccApplyNamedColorCmm::Apply (icChar * DstColorName, const icFloatNumber * SrcPixel) virtual
Define 4 apply interfaces that are used depending upon the source and destination xforms.
Name: CIccApplyNamedColorCmm::Apply
Purpose: Does the actual application of the Xforms in the list.
Args: DstColorName = Destination string where the result is stored, SrcPixel = Source pixel which is to be applied.
References CIccXform::Apply(), CIccXformNamedColor::Apply(), CIccPCS::Check(), CIccXformNamedColor::GetInterface(), CIccCmm::GetSourceSpace(), CIccApplyXform::GetXform(), CIccXform::GetXformType(), icApplyNamed2Pixel, icApplyPixel2Named, icApplyPixel2Pixel, icCmmStatBadXform, icCmmStatIncorrectApply, icCmmStatOk, icXformTypeNamedColor, CIccApplyCmm::m_pCmm, CIccApplyCmm::m_pPCS, CIccApplyCmm::m_Xforms, and CIccPCS::Reset().
icStatusCMM CIccApplyNamedColorCmm::Apply (icFloatNumber * DstPixel, const icChar * SrcColorName) virtual
Name: CIccApplyNamedColorCmm::Apply
Purpose: Does the actual application of the Xforms in the list.
Args: DstPixel = Destination pixel where the result is stored, SrcColorName = Source color name which is to be searched.
References CIccXform::Apply(), CIccXformNamedColor::Apply(), CIccPCS::Check(), CIccPCS::CheckLast(), CIccCmm::GetDestSpace(), CIccXformNamedColor::GetInterface(), CIccXformNamedColor::GetSrcSpace(), CIccApplyXform::GetXform(), CIccXform::GetXformType(), icApplyNamed2Pixel, icApplyPixel2Named, icApplyPixel2Pixel, icCmmStatBadXform, icCmmStatIncorrectApply, icCmmStatOk, icXformTypeNamedColor, CIccApplyCmm::m_pCmm, CIccApplyCmm::m_pPCS, CIccApplyCmm::m_Xforms, CIccPCS::Reset(), and CIccXformNamedColor::UseLegacyPCS().
icStatusCMM CIccApplyNamedColorCmm::Apply (icChar * DstColorName, const icChar * SrcColorName) virtual
Name: CIccApplyNamedColorCmm::Apply
Purpose: Does the actual application of the Xforms in the list.
Args: DstColorName = Destination string where the result is stored, SrcColorName = Source color name which is to be searched.
References CIccXform::Apply(), CIccXformNamedColor::Apply(), CIccPCS::Check(), CIccXformNamedColor::GetInterface(), CIccXformNamedColor::GetSrcSpace(), CIccApplyXform::GetXform(), CIccXform::GetXformType(), icApplyNamed2Pixel, icApplyPixel2Named, icApplyPixel2Pixel, icCmmStatBadXform, icCmmStatIncorrectApply, icCmmStatOk, icXformTypeNamedColor, CIccApplyCmm::m_pPCS, CIccApplyCmm::m_Xforms, CIccPCS::Reset(), and CIccXformNamedColor::UseLegacyPCS().
Friends And Related Function Documentation
friend class CIccNamedColorCmm friend
The documentation for this class was generated from the following files:
IccCmm.h
IccCmm.cpp