CIccProfile Class Reference
CIccProfile Class Reference
#include <IccProfile.h>
Public Member Functions
CIccProfile ()
CIccProfile (const CIccProfile &Profile)
CIccProfile & operator= (const CIccProfile &Profile)
virtual ~CIccProfile ()
CIccTag * FindTag (icSignature sig)
bool AttachTag (icSignature sig, CIccTag *pTag)
bool DeleteTag (icSignature sig)
CIccMemIO * GetTagIO (icSignature sig)
bool ReadTags (CIccProfile *pProfile)
bool Attach (CIccIO *pIO)
bool Detach ()
bool Read (CIccIO *pIO)
icValidateStatus ReadValidate (CIccIO *pIO, std::string &sReport)
bool Write (CIccIO *pIO, icProfileIDSaveMethod nWriteId=icVersionBasedID)
void InitHeader ()
icValidateStatus Validate (std::string &sReport) const
icUInt16Number GetSpaceSamples () const
bool AreTagsUnique () const
bool IsTagPresent (icSignature sig) const
Public Attributes
icHeader m_Header
TagEntryList * m_Tags
Protected Member Functions
void Cleanup ()
IccTagEntry * GetTag (icSignature sig) const
IccTagEntry * GetTag (CIccTag *pTag) const
bool ReadBasic (CIccIO *pIO)
bool LoadTag (IccTagEntry *pTagEntry, CIccIO *pIO)
bool DetachTag (CIccTag *pTag)
icValidateStatus CheckRequiredTags (std::string &sReport) const
bool CheckTagExclusion (std::string &sReport) const
icValidateStatus CheckHeader (std::string &sReport) const
icValidateStatus CheckTagTypes (std::string &sReport) const
bool IsTypeValid (icTagSignature tagSig, icTagTypeSignature typeSig) const
bool CheckFileSize (CIccIO *pIO) const
Protected Attributes
CIccIO * m_pAttachIO
TagPtrList * m_TagVals
Detailed Description
Type: Class
Purpose: This is the base class for an ICC profile. All the operations on a profile is done using this object.
Constructor & Destructor Documentation
CIccProfile::CIccProfile ()
Name: CIccProfile::CIccProfile
Purpose: Constructor
CIccProfile::CIccProfile (const CIccProfile & Profile)
Name: CIccProfile::CIccProfile
Purpose: Copy Constructor. The copy constructor makes the copy of the CIccProfile object in it's present state. It DOES NOT make a copy of the m_pAttachIO member variable. Any operation with the IO object should be done before making a copy.
Args: Profile = CIccProfile object which is to be copied.
References m_Header, m_Tags, m_TagVals, CIccTag::NewCopy(), IccTagEntry::pTag, IccTagPtr::ptr, and IccTagEntry::TagInfo.
CIccProfile::~CIccProfile () virtual
Name: CIccProfile::CIccProfile
Purpose: Destructor
Member Function Documentation
bool CIccProfile::AreTagsUnique () const
Name: CIccProfile::AreTagsUnique
Purpose: For each tag it checks to see if any other tags have the same signature.
Return: true if all tags have unique signatures, or false if there are duplicate tag signatures.
bool CIccProfile::Attach (CIccIO * pIO)
Name: CIccProfile::Attach
Purpose: This allows for deferred IO with a profile. The profile header and tag directory will be read, but tag data will not be read. The IO object will remain attached to the profile for the purpose of reading data in as needed.
Args: pIO - pointer to IO object to begin reading profile file with.
Return: true - the IO object (file) is an ICC profile, and the CIccProfile object is now attached to the object, false - the IO object (file) is not an ICC profile.
Referenced by CIccCmm::AddXform(), and OpenIccProfile().
bool CIccProfile::AttachTag (icSignature sig, CIccTag * pTag)
Name: CIccProfile::AttachTag
Purpose: Assign a tag object to a directory entry in the profile. This will assume ownership of the tag object.
Args: sig - signature of tag 'name' to use to assign tag object with, pTag - pointer to tag object to attach to profile.
Return: true = tag assigned to profile, false - tag not assigned to profile (tag already exists).
References icTag::offset, IccTagEntry::pTag, IccTagPtr::ptr, icTag::sig, icTag::size, and IccTagEntry::TagInfo.
bool CIccProfile::CheckFileSize (CIccIO * pIO) const protected
Name: CIccProfile::CheckFileSize()
Purpose: Check if the Profile file size matches with the size mentioned in the header and is evenly divisible by four.
Args:
Return: true - size matches, false - size mismatches
References icSeekEnd, icSeekSet, icVersionNumberV4_2, CIccIO::Seek(), and CIccIO::Tell().
icValidateStatus CIccProfile::CheckHeader (std::string & sReport) const protected
Name: CIccProfile::CheckHeader
Purpose: Validates profile header.
Return: icValidateOK if valid, or other error status.
References CIccInfo::CheckData(), CIccInfo::GetCmmSigName(), CIccInfo::GetColorSpaceSigName(), CIccInfo::GetPlatformSigName(), CIccInfo::GetProfileClassSigName(), CIccInfo::GetRenderingIntentName(), icAbsoluteColorimetric, icFtoD(), icMaxStatus(), icPerceptual, icRelativeColorimetric, icSaturation, icSigAbstractClass, icSigAdobe, icSigApple, icSigArgyllCMS, icSigColorGear, icSigColorGearLite, icSigColorSpaceClass, icSigDisplayClass, icSigFujiFilm, icSigHarlequinRIP, icSigHeidelberg, icSigInputClass, icSigKodak, icSigKonicaMinolta, icSigLabData, icSigLinkClass, icSigLittleCMS, icSigLogoSync, icSigMacintosh, icSigMicrosoft, icSigMutoh, icSigNamedColorClass, icSigOutputClass, icSigSampleICC, icSigSGI, icSigSolaris, icSigTaligent, icSigTheImagingFactory, icSigUnkownPlatform, icSigXYZData, icValidateCriticalError, icValidateCriticalErrorMsg, icValidateNonCompliant, icValidateNonCompliantMsg, icValidateOK, icValidateWarning, icValidateWarningMsg, and CIccInfo::IsValidSpace().
icValidateStatus CIccProfile::CheckRequiredTags (std::string & sReport) const protected
Name: CIccProfile::CheckRequiredTags
Purpose: Check if the Profile has the required tags for the specified Profile/Device class.
Return: icValidateOK if valid, or other error status.
References icIsSpaceCLR(), icMaxStatus(), icSig10colorData, icSig11colorData, icSig12colorData, icSig13colorData, icSig14colorData, icSig15colorData, icSig16colorData, icSig2colorData, icSig3colorData, icSig4colorData, icSig5colorData, icSig6colorData, icSig7colorData, icSig8colorData, icSig9colorData, icSigAbstractClass, icSigAToB0Tag, icSigAToB1Tag, icSigAToB2Tag, icSigBlueMatrixColumnTag, icSigBlueTRCTag, icSigBToA0Tag, icSigBToA1Tag, icSigBToA2Tag, icSigColorantTableOutTag, icSigColorantTableTag, icSigColorSpaceClass, icSigCopyrightTag, icSigDisplayClass, icSigGamutTag, icSigGrayData, icSigGrayTRCTag, icSigGreenMatrixColumnTag, icSigGreenTRCTag, icSigInputClass, icSigLinkClass, icSigMediaWhitePointTag, icSigNamedColor2Tag, icSigNamedColorClass, icSigOutputClass, icSigProfileDescriptionTag, icSigProfileSequenceDescTag, icSigRedMatrixColumnTag, icSigRedTRCTag, icValidateCriticalError, icValidateCriticalErrorMsg, icValidateNonCompliant, icValidateNonCompliantMsg, icValidateOK, and icValidateWarning.
bool CIccProfile::CheckTagExclusion (std::string & sReport) const protected
Name: CIccProfile::CheckTagExclusion
Purpose: Some tags does not have a defined interpretation for a profile of a specific class. This function does these tests.
Return: true if test successful, else false.
References CIccInfo::GetSigName(), icSigAbstractClass, icSigAToB0Tag, icSigAToB1Tag, icSigAToB2Tag, icSigBlueColorantTag, icSigBlueTRCTag, icSigBToA0Tag, icSigBToA1Tag, icSigBToA2Tag, icSigDisplayClass, icSigGamutTag, icSigGrayTRCTag, icSigGreenColorantTag, icSigGreenTRCTag, icSigInputClass, icSigLinkClass, icSigMediaWhitePointTag, icSigNamedColor2Tag, icSigNamedColorClass, icSigProfileSequenceDescTag, icSigRedColorantTag, icSigRedTRCTag, and icValidateWarningMsg.
icValidateStatus CIccProfile::CheckTagTypes (std::string & sReport) const protected
Name: CIccProfile::CheckTagTypes
Purpose: Check if tags have allowed tag types.
Return: icValidateOK if valid, or other error status.
References CIccInfo::GetSigName(), CIccInfo::GetTagTypeSigName(), icMaxStatus(), icValidateNonCompliant, icValidateNonCompliantMsg, and icValidateOK.
void CIccProfile::Cleanup () protected
Name: CIccProfile::Cleanup
Purpose: Detach from a pending IO object
bool CIccProfile::DeleteTag (icSignature sig)
Name: CIccProfile::DeleteTag
Purpose: Delete tag directory entry with given signature. If no other tag directory entries use the tag object, the tag object will also be deleted.
Args: sig - signature of tag directory entry to remove
Return: true - desired tag directory entry was found and deleted, false - desired tag directory entry was not found
bool CIccProfile::Detach ()
Name: CIccProfile::Detach
Purpose: Discontinues the use of defferred IO with a profile. This can be done once all the information needed for performing a transform has been extracted from the profile.
Args: true - If an IO object was attached to the profile false - if no IO object was attached to the profile
bool CIccProfile::DetachTag (CIccTag * pTag) protected
Name: CIccProfile::DetachTag
Purpose: Remove association of a tag object from all tag directory entries. Associated tag directory entries will be removed from the tag directory. The tag object is NOT deleted from memory, but is considered to be no longer associated with the CIccProfile object. The caller assumes ownership of the tag object.
Args: pTag - pointer to tag object unassociate with the profile object
Return: true - tag object found and unassociated with profile object, false - tag object not found
CIccTag * CIccProfile::FindTag (icSignature sig)
Name: CIccProfile::FindTag
Purpose: Finds the tag object associated with the directory entry with the given signature. If the profile object is attached to an IO object then the tag may need to be loaded first.
Args: sig - tag signature to find in profile
Return: The desired tag object, or NULL if unable to find in the directory or load tag object.
References IccTagEntry::pTag.
Referenced by CIccNamedColorCmm::AddXform(), CIccProfileIdDesc::CIccProfileIdDesc(), CIccXform::Create(), CIccXformMpe::Create(), CIccEvalCompare::EvaluateProfile(), and CIccPRMG::EvaluateProfile().
icUInt16Number CIccProfile::GetSpaceSamples () const
Name: CIccProfile::GetSpaceSamples
Purpose: Get the number of device channels from the color space of data.
Return: Number of device channels.
References icSig10colorData, icSig11colorData, icSig12colorData, icSig13colorData, icSig14colorData, icSig15colorData, icSig3colorData, icSig4colorData, icSig5colorData, icSig6colorData, icSig7colorData, icSig8colorData, icSig9colorData, icSigCmyData, icSigCmykData, icSigHlsData, icSigHsvData, icSigLabData, icSigLuvData, icSigRgbData, icSigXYZData, icSigYCbCrData, and icSigYxyData.
IccTagEntry * CIccProfile::GetTag (icSignature sig) const protected
Name: CIccProfile::GetTag
Purpose: Get a tag entry with a given signature
Args: sig - signature id to find in tag directory
Return: Pointer to desired tag directory entry, or NULL if not found.
IccTagEntry * CIccProfile::GetTag (CIccTag * pTag) const protected
Name: CIccProfile::GetTag
Purpose: Finds the first tag entry that points to the indicated tag object
Args: pTag - pointer to tag object desired to be found
Return: pointer to first tag directory entry that points to the desired tag object, or NULL if tag object is not pointed to by any tag directory entries.
CIccMemIO * CIccProfile::GetTagIO (icSignature sig)
Name: CIccProfile::GetTagIO
Purpose: Finds the tag directory entry with the given signature and returns a CIccIO object that can be used to read the tag data stored in the profile. This only works if the profile is still connected to the file IO object.
Args: sig - tag signature to find in profile
Return: A CIccIO object that can be used to read the tag data from the file. Note: the caller is responsible for deleting the returned CIccIO object.
References CIccMemIO::Alloc(), CIccMemIO, CIccMemIO::GetData(), CIccMemIO::GetLength(), icSeekSet, icTag::offset, CIccMemIO::Seek(), icTag::size, and IccTagEntry::TagInfo.
void CIccProfile::InitHeader ()
Name: CIccProfile::InitHeader
Purpose: Initializes the data to be written in the profile header.
References icDtoF(), icMagicNumber, icPerceptual, icSigLabData, icSigSampleICC, and icVersionNumberV4.
bool CIccProfile::IsTagPresent (icSignature sig) const inline
bool CIccProfile::IsTypeValid (icTagSignature tagSig, icTagTypeSignature typeSig) const protected
Name: CIccProfile::IsTypeValid
Purpose: Check if tags have allowed tag types.
Return: true if valid, else false.
References icSigAToB0Tag, icSigAToB1Tag, icSigAToB2Tag, icSigBlueMatrixColumnTag, icSigBlueTRCTag, icSigBToA0Tag, icSigBToA1Tag, icSigBToA2Tag, icSigCalibrationDateTimeTag, icSigCharTargetTag, icSigChromaticAdaptationTag, icSigChromaticityTag, icSigChromaticityType, icSigColorantOrderTag, icSigColorantOrderType, icSigColorantTableOutTag, icSigColorantTableTag, icSigColorantTableType, icSigCopyrightTag, icSigCurveType, icSigDateTimeType, icSigDeviceMfgDescTag, icSigDeviceModelDescTag, icSigGamutTag, icSigGrayTRCTag, icSigGreenMatrixColumnTag, icSigGreenTRCTag, icSigLuminanceTag, icSigLut16Type, icSigLut8Type, icSigLutAtoBType, icSigLutBtoAType, icSigMeasurementTag, icSigMeasurementType, icSigMediaBlackPointTag, icSigMediaWhitePointTag, icSigMultiLocalizedUnicodeType, icSigNamedColor2Tag, icSigNamedColor2Type, icSigOutputResponseTag, icSigParametricCurveType, icSigPerceptualRenderingIntentGamutTag, icSigPreview0Tag, icSigPreview1Tag, icSigPreview2Tag, icSigProfileDescriptionTag, icSigProfileSequenceDescTag, icSigProfileSequenceDescType, icSigRedMatrixColumnTag, icSigRedTRCTag, icSigResponseCurveSet16Type, icSigS15Fixed16ArrayType, icSigSaturationRenderingIntentGamutTag, icSigSignatureType, icSigTechnologyTag, icSigTextDescriptionType, icSigTextType, icSigViewingCondDescTag, icSigViewingConditionsTag, icSigViewingConditionsType, and icSigXYZType.
bool CIccProfile::LoadTag (IccTagEntry * pTagEntry, CIccIO * pIO) protected
Name: CIccProfile::LoadTag
Purpose: This will load from the indicated IO object and associate a tag object to a tag directory entry. Nothing happens if tag directory entry is associated with a tag object.
Args: pTagEntry - pointer to tag directory entry, pIO - pointer to IO object to read tag object data from
Return: true - tag directory object associated with tag directory entry, false - failure
References CIccTag::Create(), icSeekSet, icSigAToB0Tag, icSigAToB1Tag, icSigAToB2Tag, icSigBToA0Tag, icSigBToA1Tag, icSigBToA2Tag, icSigGamutData, icSigGamutTag, icSigNamedColor2Tag, CIccTag::IsMBBType(), icTag::offset, IccTagEntry::pTag, IccTagPtr::ptr, CIccTag::Read(), CIccIO::Read32(), CIccIO::Seek(), icTag::sig, icTag::size, and IccTagEntry::TagInfo.
CIccProfile & CIccProfile::operator= (const CIccProfile & Profile)
Name: CIccProfile::operator=
Purpose: Copy Operator. The copy operator makes the copy of the CIccProfile object in it's present state. It DOES NOT make a copy of the m_pAttachIO member variable. Any operation with the IO object should be done before making a copy.
Args: Profile = CIccProfile object which is to be copied.
References m_Header, m_Tags, m_TagVals, CIccTag::NewCopy(), IccTagEntry::pTag, IccTagPtr::ptr, and IccTagEntry::TagInfo.
bool CIccProfile::Read (CIccIO * pIO)
Name: CIccProfile::Read
Purpose: This will read the entire ICC profile from the IO object into the CIccProfile object
Args: pIO - pointer to IO object to read ICC profile from
Return: true - the IO object (file) is an ICC profile, and the CIccProfile object now contains all its data, false - the IO object (file) is not an ICC profile.
Referenced by ReadIccProfile().
bool CIccProfile::ReadBasic (CIccIO * pIO) protected
Name: CIccProfile::ReadBasic
Purpose: Read in ICC header and tag directory entries.
Args: pIO - pointer to IO object to read data with
Return: true - valid ICC header and tag directory, false - failure
References icMagicNumber, icSeekSet, icTag::offset, IccTagEntry::pTag, CIccIO::Read16(), CIccIO::Read32(), CIccIO::Read64(), CIccIO::Read8(), CIccIO::Seek(), icTag::sig, icTag::size, and IccTagEntry::TagInfo.
bool CIccProfile::ReadTags (CIccProfile * pProfile)
Name: CIccProfile::ReadTags
Purpose: This will read the all the tags from the IO object into the CIccProfile object. The IO object must have been attached before calling this function.
Return: true - CIccProfile object now contains all tag data, false - No IO object attached or tags cannot be read.
References icSeekSet, m_pAttachIO, CIccIO::Seek(), and CIccIO::Tell().
Referenced by CIccXform::Begin().
icValidateStatus CIccProfile::ReadValidate (CIccIO * pIO, std::string & sReport)
Name: CIccProfile::ReadValidate
Purpose: This will read the entire ICC profile from the IO object into the CIccProfile object
Args: pIO - pointer to IO object to read ICC profile from sReport - string to put validation report info into. String should be initialized before calling
Return: icValidateOK if file can be read, bad status otherwise.
References CalcProfileID(), CIccInfo::GetTagSigName(), icMaxStatus(), icValidateCriticalError, icValidateCriticalErrorMsg, icValidateNonCompliant, icValidateNonCompliantMsg, icValidateOK, icProfileID::ID8, and CIccInfo::IsProfileIDCalculated().
Referenced by ValidateIccProfile().
icValidateStatus CIccProfile::Validate (std::string & sReport) const
Name: CIccProfile::Validate
Purpose: Check the data integrity of the profile, and conformance to the ICC specification
Args: sReport = String to put report into
Return: icValidateOK if profile is valid, warning/error level otherwise
References icMaxStatus(), icValidateOK, and icValidateWarning.
Referenced by ValidateIccProfile().
bool CIccProfile::Write (CIccIO * pIO, icProfileIDSaveMethod nWriteId = icVersionBasedID)
Name: CIccProfile::Write
Purpose: Write the data associated with the CIccProfile object to an IO IO object.
Args: pIO - pointer to IO object to write data to
Return: true - success, false - failure
References CIccIO::Align32(), CalcProfileID(), CIccIO::GetLength(), icAlwaysWriteID, icNeverWriteID, icSeekSet, icVersionBasedID, icVersionNumberV4, CIccIO::Seek(), CIccIO::Write16(), CIccIO::Write32(), CIccIO::Write64(), and CIccIO::Write8().
Referenced by SaveIccProfile().
Member Data Documentation
icHeader CIccProfile::m_Header
Referenced by CIccCmm::AddXform(), CIccNamedColorCmm::AddXform(), CIccApplyBPC::CalcFactors(), CIccProfile(), CIccProfileIdDesc::CIccProfileIdDesc(), CIccXform::Create(), CIccXformMpe::Create(), CIccEvalCompare::EvaluateProfile(), CIccPRMG::EvaluateProfile(), operator=(), CIccMatrix::Validate(), CIccMBB::Validate(), CIccTagNamedColor2::Validate(), CIccTagLutAtoB::Validate(), CIccTagLutBtoA::Validate(), CIccTagLut8::Validate(), CIccTagLut16::Validate(), CIccTagColorantOrder::Validate(), CIccTagColorantTable::Validate(), and CIccTagResponseCurveSet16::Validate().
CIccIO* CIccProfile::m_pAttachIO protected
Referenced by ReadTags().
TagEntryList* CIccProfile::m_Tags
Referenced by CIccProfile(), and operator=().
TagPtrList* CIccProfile::m_TagVals protected
Referenced by CIccProfile(), and operator=().
The documentation for this class was generated from the following files:
IccProfile.h
IccProfile.cpp