CIccTagProfileSeqDesc Class Reference
CIccTagProfileSeqDesc Class Reference
#include <IccTagBasic.h>
Public Member Functions
CIccTagProfileSeqDesc ()
CIccTagProfileSeqDesc (const CIccTagProfileSeqDesc &ITPSD)
CIccTagProfileSeqDesc & operator= (const CIccTagProfileSeqDesc &ProfSeqDescTag)
virtual CIccTag * NewCopy () const
virtual ~CIccTagProfileSeqDesc ()
virtual icTagTypeSignature GetType () const
virtual const icChar * GetClassName () const
virtual void Describe (std::string &sDescription)
virtual bool Read (icUInt32Number size, CIccIO *pIO)
virtual bool Write (CIccIO *pIO)
virtual icValidateStatus Validate (icTagSignature sig, std::string &sReport, const CIccProfile *pProfile=NULL) const
Public Member Functions inherited from CIccTag
CIccTag ()
virtual ~CIccTag ()
virtual bool IsArrayType ()
virtual bool IsMBBType ()
virtual IIccExtensionTag * GetExtension ()
virtual bool IsSupported ()
Public Attributes
CIccProfileSeqDesc * m_Descriptions
Public Attributes inherited from CIccTag
icUInt32Number m_nReserved
Additional Inherited Members
Static Public Member Functions inherited from CIccTag
static CIccTag * Create (icTagTypeSignature sig)
Detailed Description
Class: CIccTagProfileSeqDesc
Purpose: Profile Sequence description tag
Constructor & Destructor Documentation
CIccTagProfileSeqDesc::CIccTagProfileSeqDesc ()
Name: CIccTagProfileSeqDesc::CIccTagProfileSeqDesc
Purpose: Constructor
CIccTagProfileSeqDesc::CIccTagProfileSeqDesc (const CIccTagProfileSeqDesc & ITPSD)
Name: CIccTagProfileSeqDesc::CIccTagProfileSeqDesc
Purpose: Copy Constructor
Args: ITPSD = The CIccTagProfileSeqDesc object to be copied
References m_Descriptions.
CIccTagProfileSeqDesc::~CIccTagProfileSeqDesc () virtual
Name: CIccTagProfileSeqDesc::~CIccTagProfileSeqDesc
Purpose: Destructor
Member Function Documentation
void CIccTagProfileSeqDesc::Describe (std::string & sDescription) virtual
Name: CIccTagProfileSeqDesc::Describe
Purpose: Dump data associated with the tag to a string
Args: sDescription - string to concatenate tag dump to
Reimplemented from CIccTag.
References icGetSig().
virtual const icChar* CIccTagProfileSeqDesc::GetClassName () const inline virtual
Reimplemented from CIccTag.
virtual icTagTypeSignature CIccTagProfileSeqDesc::GetType () const inline virtual
Function: GetType()
Purpose: Get Tag Type. Each derived tag will implement it's own GetType() function.
Reimplemented from CIccTag.
References icSigProfileSequenceDescType.
virtual CIccTag* CIccTagProfileSeqDesc::NewCopy () const inline virtual
Function: NewCopy(sDescription) Each derived tag will implement it's own NewCopy() function.
Parameter(s): none
Returns a new CIccTag object that is a copy of this object.
Reimplemented from CIccTag.
CIccTagProfileSeqDesc & CIccTagProfileSeqDesc::operator= (const CIccTagProfileSeqDesc & ProfSeqDescTag)
Name: CIccTagProfileSeqDesc::operator=
Purpose: Copy Operator
Args: ProfSeqDescTag = The CIccTagProfileSeqDesc object to be copied
References m_Descriptions.
bool CIccTagProfileSeqDesc::Read (icUInt32Number size, CIccIO * pIO) virtual
Name: CIccTagProfileSeqDesc::Read
Purpose: Read in the tag contents into a data block
Args: size - # of bytes in tag, pIO - IO object to read tag from
Return: true = successful, false = failure
Reimplemented from CIccTag.
References CIccProfileDescStruct::m_attributes, CIccProfileDescStruct::m_deviceMfg, CIccProfileDescStruct::m_deviceMfgDesc, CIccProfileDescStruct::m_deviceModel, CIccProfileDescStruct::m_deviceModelDesc, CIccProfileDescStruct::m_technology, CIccProfileDescText::Read(), CIccIO::Read32(), CIccIO::Read64(), and CIccIO::Tell().
icValidateStatus CIccTagProfileSeqDesc::Validate (icTagSignature sig, std::string & sReport, const CIccProfile * pProfile = NULL) const virtual
Name: CIccTagProfileSeqDesc::Validate
Purpose: Check tag data validity.
Args: sig = signature of tag being validated, sReport = String to add report information to
Return: icValidateStatusOK if valid, or other error status.
Reimplemented from CIccTag.
References CIccInfo::GetSigName(), icMaxStatus(), icSigAMDisplay, icSigCRTDisplay, icSigDigitalCamera, icSigDyeSublimationPrinter, icSigElectrophotographicPrinter, icSigElectrostaticPrinter, icSigFilmScanner, icSigFilmWriter, icSigFlexography, icSigGravure, icSigInkJetPrinter, icSigOffsetLithography, icSigPhotoCD, icSigPhotographicPaperPrinter, icSigPhotoImageSetter, icSigPMDisplay, icSigProjectionTelevision, icSigReflectiveScanner, icSigSilkscreen, icSigThermalWaxPrinter, icSigVideoCamera, icSigVideoMonitor, icValidateNonCompliant, icValidateNonCompliantMsg, and CIccTag::Validate().
bool CIccTagProfileSeqDesc::Write (CIccIO * pIO) virtual
Name: CIccTagProfileSeqDesc::Write
Purpose: Write the tag to a file
Args: pIO - The IO object to write tag to.
Return: true = succesful, false = failure
Reimplemented from CIccTag.
References CIccIO::Write32(), and CIccIO::Write64().
Member Data Documentation
CIccProfileSeqDesc* CIccTagProfileSeqDesc::m_Descriptions
Referenced by CIccTagProfileSeqDesc(), and operator=().
The documentation for this class was generated from the following files:
IccTagBasic.h
IccTagBasic.cpp