CIccDictEntry Class Reference
CIccDictEntry Class Reference
#include <IccTagDict.h>
Public Member Functions
CIccDictEntry ()
CIccDictEntry (const CIccDictEntry &IDE)
CIccDictEntry & operator= (const CIccDictEntry &IDE)
virtual ~CIccDictEntry ()
void Describe (std::string &sDescription)
icUInt32Number PosRecSize ()
const CIccUTF16String & GetValue ()
bool IsValueSet ()
CIccTagMultiLocalizedUnicode * GetNameLocalized ()
CIccTagMultiLocalizedUnicode * GetValueLocalized ()
void UnsetValue ()
bool SetValue (const CIccUTF16String &sValue)
bool SetNameLocalized (CIccTagMultiLocalizedUnicode *pNameLocalized)
bool SetValueLocalized (CIccTagMultiLocalizedUnicode *pValueLocalized)
Public Attributes
CIccUTF16String m_sName
Protected Attributes
CIccUTF16String m_sValue
bool m_bValueSet
CIccTagMultiLocalizedUnicode * m_pNameLocalized
CIccTagMultiLocalizedUnicode * m_pValueLocalized
Detailed Description
Data Class: CIccDictEntry
Purpose: Implementation of a dictionary entry with optional localization of name and value
Constructor & Destructor Documentation
CIccDictEntry::CIccDictEntry ()
Name: CIccDictEntry::CIccDictEntry
Purpose:
Args:
Return:
References m_bValueSet, m_pNameLocalized, and m_pValueLocalized.
CIccDictEntry::CIccDictEntry (const CIccDictEntry & IDE)
Name: CIccDictEntry::CIccDictEntry
Purpose:
Args:
Return:
References m_bValueSet, m_pNameLocalized, m_pValueLocalized, m_sName, m_sValue, and CIccTagMultiLocalizedUnicode::NewCopy().
CIccDictEntry::~CIccDictEntry () virtual
Name: CIccDictEntry::~CIccDictEntry
Purpose:
Args:
Return:
References m_pNameLocalized, and m_pValueLocalized.
Member Function Documentation
void CIccDictEntry::Describe (std::string & sDescription)
Name: CIccDictEntry::Describe
Purpose:
Args:
Return:
References CIccTagMultiLocalizedUnicode::Describe(), m_pNameLocalized, m_pValueLocalized, m_sName, m_sValue, and CIccUTF16String::ToUtf8().
CIccTagMultiLocalizedUnicode* CIccDictEntry::GetNameLocalized () inline
Referenced by CIccTagDict::GetNameLocalized().
const CIccUTF16String& CIccDictEntry::GetValue () inline
Referenced by CIccTagDict::GetValue(), and CIccTagDict::Set().
CIccTagMultiLocalizedUnicode* CIccDictEntry::GetValueLocalized () inline
Referenced by CIccTagDict::GetValueLocalized().
bool CIccDictEntry::IsValueSet () inline
Referenced by CIccTagDict::GetValue(), and CIccTagDict::Set().
CIccDictEntry & CIccDictEntry::operator= (const CIccDictEntry & IDE)
Name: CIccDictEntry::operator=
Purpose:
Args:
Return:
References m_bValueSet, m_pNameLocalized, m_pValueLocalized, m_sName, m_sValue, and CIccTagMultiLocalizedUnicode::NewCopy().
icUInt32Number CIccDictEntry::PosRecSize ()
Name: CIccDictEntry::PosRecSize
Purpose:
Args:
Return:
References m_pNameLocalized, and m_pValueLocalized.
Referenced by CIccTagDict::MaxPosRecSize().
bool CIccDictEntry::SetNameLocalized (CIccTagMultiLocalizedUnicode * pNameLocalized)
Name: CIccDictEntry::SetNameLocalized
Purpose:
Args:
Return:
References m_pNameLocalized.
Referenced by CIccTagDict::Read(), and CIccTagDict::SetNameLocalized().
bool CIccDictEntry::SetValue (const CIccUTF16String & sValue)
References CIccUTF16String::Empty(), m_bValueSet, and m_sValue.
Referenced by CIccTagDict::Read(), and CIccTagDict::Set().
bool CIccDictEntry::SetValueLocalized (CIccTagMultiLocalizedUnicode * pValueLocalized)
Name: CIccDictEntry::SetValueLocalized
Purpose:
Args:
Return:
References m_pValueLocalized.
Referenced by CIccTagDict::Read(), and CIccTagDict::SetValueLocalized().
void CIccDictEntry::UnsetValue () inline
Referenced by CIccTagDict::Set().
Member Data Documentation
bool CIccDictEntry::m_bValueSet protected
Referenced by CIccDictEntry(), operator=(), and SetValue().
CIccTagMultiLocalizedUnicode* CIccDictEntry::m_pNameLocalized protected
Referenced by CIccDictEntry(), Describe(), operator=(), PosRecSize(), SetNameLocalized(), and ~CIccDictEntry().
CIccTagMultiLocalizedUnicode* CIccDictEntry::m_pValueLocalized protected
Referenced by CIccDictEntry(), Describe(), operator=(), PosRecSize(), SetValueLocalized(), and ~CIccDictEntry().
CIccUTF16String CIccDictEntry::m_sName
Referenced by CIccDictEntry(), Describe(), operator=(), CIccTagDict::Read(), CIccTagDict::Set(), CIccTagDict::SetNameLocalized(), and CIccTagDict::SetValueLocalized().
CIccUTF16String CIccDictEntry::m_sValue protected
Referenced by CIccDictEntry(), Describe(), operator=(), and SetValue().
The documentation for this class was generated from the following files:
IccTagDict.h
IccTagDict.cpp