md5.h File Reference
md5.h File Reference
#include "IccProfLibConf.h"
Classes
struct MD5_CTX
Typedefs
typedef unsigned char * POINTER
typedef unsigned short int UINT2
typedef ICCUINT32 UINT4
Functions
void ICCPROFLIB_API icMD5Init (MD5_CTX *)
void ICCPROFLIB_API icMD5Update (MD5_CTX *, unsigned char *, unsigned int)
void ICCPROFLIB_API icMD5Final (unsigned char *, MD5_CTX *)
Detailed Description
md5.H - header file for md5.cpp
Copyright (C) 1991-2, RSA Data Security, Inc. Created 1991. All rights reserved.
License to copy and use this software is granted provided that it is identified as the "RSA Data Security, Inc. MD5 Message-Digest Algorithm" in all material mentioning or referencing this software or this function.
License is also granted to make and use derivative works provided that such works are identified as "derived from the RSA Data Security, Inc. MD5 Message-Digest Algorithm" in all material mentioning or referencing the derived work.
RSA Data Security, Inc. makes no representations concerning either the merchantability of this software or the suitability of this software for any particular purpose. It is provided "as is" without express or implied warranty of any kind.
These notices must be retained in any copies of any part of this documentation and/or software.
Typedef Documentation
typedef unsigned char* POINTER
POINTER defines a generic pointer type
typedef unsigned short int UINT2
UINT2 defines a two byte word
typedef ICCUINT32 UINT4
UINT4 defines a four byte word
Function Documentation
void ICCPROFLIB_API icMD5Final (unsigned char * digest, MD5_CTX * context)
MD5 finalization. Ends an MD5 message-digest operation, writing the the message digest and zeroizing the context.
References MD5_CTX::count, icMD5Update(), and MD5_CTX::state.
Referenced by CalcProfileID().
void ICCPROFLIB_API icMD5Init (MD5_CTX * context)
MD5 initialization. Begins an MD5 operation, writing a new context.
References MD5_CTX::count, and MD5_CTX::state.
Referenced by CalcProfileID().
void ICCPROFLIB_API icMD5Update (MD5_CTX * context, unsigned char * input, unsigned int inputLen)
MD5 block update operation. Continues an MD5 message-digest operation, processing another message block, and updating the context.
References MD5_CTX::buffer, MD5_CTX::count, and MD5_CTX::state.
Referenced by CalcProfileID(), and icMD5Final().