ExternalProject_Add(
  OpenTimelineIO
  GIT_REPOSITORY "https://github.com/AcademySoftwareFoundation/OpenTimelineIO.git"
  GIT_TAG main
  GIT_PROGRESS 1
  CMAKE_ARGS
  -DCMAKE_INSTALL_PREFIX=${CMAKE_INSTALL_PREFIX}
  -DCMAKE_PREFIX_PATH=${CMAKE_INSTALL_PREFIX}
  -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
  -DCMAKE_C_FLAGS=${CMAKE_C_FLAGS}
  -DCMAKE_CXX_FLAGS=${CMAKE_CXX_FLAGS}
   ${MRV_EXTERNAL_ARGS}
  -DBUILD_TESTING=FALSE
  -DPYTHON=FALSE
  -DDOCS=FALSE
  )


set( OpenTimelineIO "OpenTimelineIO" )
