
ExternalProject_Add(
  Imath
  GIT_REPOSITORY "https://github.com/AcademySoftwareFoundation/Imath.git"
  GIT_TAG v3.1.5
  GIT_PROGRESS 1
  CMAKE_ARGS
  -DCMAKE_INSTALL_PREFIX=${CMAKE_INSTALL_PREFIX}
  -DCMAKE_PREFIX_PATH=${CMAKE_INSTALL_PREFIX}
  -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
  -DCMAKE_C_FLAGS=${CMAKE_C_FLAGS}
  -DCMAKE_CXX_FLAGS=${CMAKE_CXX_FLAGS}
  -DBUILD_SHARED_LIBS=TRUE
  -DBUILD_TESTING=FALSE
  -DPYILMBASE_ENABLE=FALSE
  -DPYTHON=FALSE
  -DDOCS=FALSE
  )
