ExternalProject_Add(
  OTIO
  GIT_REPOSITORY "https://github.com/AcademySoftwareFoundation/OpenTimelineIO.git"
  GIT_TAG main
  GIT_PROGRESS 1
  CMAKE_ARGS
  -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
  -DCMAKE_INSTALL_PREFIX=${CMAKE_INSTALL_PREFIX}
  -DCMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH}
  -DBUILD_SHARED_LIBS=ON
  -DBoost_ROOT=${CMAKE_PREFIX_PATH}
  -DUSE_PYTHON=OFF)

set( OTIO "OTIO" )
