set( Imath_TAG "3ad5d4da02795dbf37b44c5bbd2f919a7c01a19a" )

set( table ON )
if( WIN32 )
    set( CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -DIMATH_DLL -DIMATH_EXPORTS" )
    set( table OFF )
endif()

ExternalProject_Add(
  Imath
  GIT_REPOSITORY "https://github.com/AcademySoftwareFoundation/Imath.git"
  GIT_TAG ${Imath_TAG}
  GIT_PROGRESS 1
  DEPENDS ${OTIO} ${OPENEXR}
  CMAKE_ARGS
  -DCMAKE_INSTALL_PREFIX=${CMAKE_INSTALL_PREFIX}
  -DCMAKE_PREFIX_PATH=${CMAKE_INSTALL_PREFIX}
  -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
  -DCMAKE_C_FLAGS=${CMAKE_C_FLAGS}
  -DCMAKE_CXX_FLAGS=${CMAKE_CXX_FLAGS}
  -DOPENEXR_FORCE_INTERNAL_IMATH=ON
  -DIMATH_HALF_USE_LOOKUP_TABLE=${table}
   ${MRV_EXTERNAL_ARGS}
  -DBUILD_TESTING=FALSE
  -DPYILMBASE_ENABLE=FALSE
  -DPYTHON=FALSE
  -DDOCS=FALSE
  )
