
ExternalProject_Add(
  LibOpus
  GIT_REPOSITORY "https://github.com/xiph/opus.git"
  GIT_TAG master
  CMAKE_ARGS
  -DCMAKE_MODULE_PATH=${CMAKE_MODULE_PATH}
  -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
  -DCMAKE_INSTALL_PREFIX=${CMAKE_INSTALL_PREFIX}
  -DCMAKE_PREFIX_PATH=${CMAKE_INSTALL_PREFIX}
  -DCMAKE_C_FLAGS=${CMAKE_C_FLAGS}
  -DCMAKE_CXX_FLAGS=${CMAKE_CXX_flags}
  -DBUILD_SHARED_LIBS=ON
  )

set( LibOpus "LibOpus" )
