// generated by Fast Light User Interface Designer (fluid) version 1,0400

#include <vector>
#include <string>

#include "FL/Fl_Box.H"

#include "gui/mrvMedia.h"
#include "File_Chooser.h"


static const char* kModule = "filereq";

class Fl_Thumbnail : public Fl_Group
{
    static const int VMARGIN = 6;
    static const int H2 = 16;
    Fl_Box* image;
    Fl_Box* label;

    mrv::media _elem;
public:

    Fl_Thumbnail( int X, int Y, int W, int H, mrv::media m ) :
        Fl_Group( X, Y, W, H ),
        image( NULL ),
        _elem( m )
        {
            label = new Fl_Box( X, Y + H, W, H2 );
            label->box( FL_FLAT_BOX );
            label->color( 0xffff00ff );
            label->align( Fl_Align( FL_ALIGN_CENTER ) );
            mrv::CMedia* img = m->image();
            if ( img ) label->copy_label( img->name().c_str() );
        }

    void create_thumbnail()
        {
            _elem->create_thumbnail( w(), h()-H2 );

            Fl_Image* b = NULL;
            if ( _elem->thumbnail() )
            {
                b = _elem->thumbnail();
            }
            else
            {
                uchar* d = new uchar[64*64];
                memset( d, 0, 64*64 );
                Fl_RGB_Image* rgb = new Fl_RGB_Image( d, 64, 64, 1 );
                rgb->alloc_array = 1;
                b = rgb;
            }
            if ( !b || b->w() < 1 )
            {
                LOG_ERROR( _("Empty image in thumbnail") );
            }
            if ( !image )
            {
                image = new Fl_Box( x(), y()+VMARGIN, b->w(), b->h() );
                label->size( b->w(), label->h() );
            }
            if ( b && image ) image->image( b );
        }
};


Fl_Group *uiPaths=(Fl_Group *)0;

MyPack *uiThumbnails=(MyPack *)0;

Fl_Double_Window* make_window() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(855, 770);
    w = o; if (w) {/* empty */}
    { uiPaths = new Fl_Group(10, 10, 280, 750);
      uiPaths->end();
    } // Fl_Group* uiPaths
    { uiThumbnails = new MyPack(295, 10, 555, 750);
        uiThumbnails->type(0);
        const char* file = "/media/gga/Datos/movies/avatar640/avatar640.0001.tif";
        mrv::CMedia* img = mrv::CMedia::guess_image( file, NULL, 0, false,
                                                     AV_NOPTS_VALUE,
                                                     AV_NOPTS_VALUE, true );

        mrv::media m( new mrv::gui::media( img ) );
        Fl_Thumbnail* t1 = new Fl_Thumbnail( 300, 15, 320, 240, m );
        t1->create_thumbnail();
        mrv::media m2( new mrv::gui::media( img ) );
        Fl_Thumbnail* t2 = new Fl_Thumbnail( 320, 15, 320, 240, m2 );
        t2->create_thumbnail();
      uiThumbnails->end();
    } // Fl_Group* uiThumbnails
    o->end();
  } // Fl_Double_Window* o
  return w;
}

const char* _newflu_file_chooser( const char *message, const char *pattern,
                                  const char *filename, int type,
                                  FluStringVector& filelist,
                                  const bool compact_files )
{
    Fl_Double_Window* w = make_window();
    w->set_modal();
    w->show();
    return "";
}
