CIccApplyTagMpe Class Reference
CIccApplyTagMpe Class Reference
#include <IccTagMPE.h>
Public Member Functions
CIccApplyTagMpe (CIccTagMultiProcessElement *pTag)
virtual ~CIccApplyTagMpe ()
CIccTagMultiProcessElement * GetTag ()
virtual bool AppendElem (CIccMultiProcessElement *pElem)
CIccDblPixelBuffer * GetBuf ()
CIccApplyMpeList * GetList ()
CIccApplyMpeIter begin ()
CIccApplyMpeIter end ()
Protected Attributes
CIccTagMultiProcessElement * m_pTag
CIccApplyMpeList * m_list
CIccDblPixelBuffer m_applyBuf
Detailed Description
Class: CIccTagMultiProcessElement
Purpose: Apply storage for MPE general purpose processing tags
Constructor & Destructor Documentation
CIccApplyTagMpe::CIccApplyTagMpe (CIccTagMultiProcessElement * pTag)
Name: CIccApplyTagMpe::CIccApplyTagMpe
Purpose:
Args:
Return:
CIccApplyTagMpe::~CIccApplyTagMpe () virtual
Name: CIccApplyTagMpe::~CIccApplyTagMpe
Purpose:
Args:
Return:
Member Function Documentation
bool CIccApplyTagMpe::AppendElem (CIccMultiProcessElement * pElem) virtual
Name: CIccApplyTagMpe::CIccApplyTagMpe
Purpose:
Args:
Return:
References CIccMultiProcessElement::GetNewApply(), and CIccApplyMpePtr::ptr.
Referenced by CIccTagMultiProcessElement::GetNewApply().
CIccApplyMpeIter CIccApplyTagMpe::begin () inline
Referenced by CIccTagMultiProcessElement::Apply().
CIccApplyMpeIter CIccApplyTagMpe::end () inline
Referenced by CIccTagMultiProcessElement::Apply().
CIccDblPixelBuffer* CIccApplyTagMpe::GetBuf () inline
Referenced by CIccTagMultiProcessElement::Apply(), and CIccTagMultiProcessElement::GetNewApply().
CIccApplyMpeList* CIccApplyTagMpe::GetList () inline
Referenced by CIccTagMultiProcessElement::Apply().
CIccTagMultiProcessElement* CIccApplyTagMpe::GetTag () inline
Member Data Documentation
CIccDblPixelBuffer CIccApplyTagMpe::m_applyBuf protected
CIccApplyMpeList* CIccApplyTagMpe::m_list protected
CIccTagMultiProcessElement* CIccApplyTagMpe::m_pTag protected
The documentation for this class was generated from the following files:
IccTagMPE.h
IccTagMPE.cpp