CIccDblPixelBuffer Class Reference
CIccDblPixelBuffer Class Reference
#include <IccTagMPE.h>
Public Member Functions
CIccDblPixelBuffer ()
CIccDblPixelBuffer (const CIccDblPixelBuffer &buf)
CIccDblPixelBuffer & operator= (const CIccDblPixelBuffer &buf)
virtual ~CIccDblPixelBuffer ()
void Clean ()
void Reset ()
void UpdateChannels (icUInt16Number nNumChannels)
bool Begin ()
icUInt16Number GetMaxChannels ()
icFloatNumber * GetSrcBuf ()
icFloatNumber * GetDstBuf ()
void Switch ()
icUInt16Number GetAvailChannels ()
Protected Attributes
icUInt16Number m_nMaxChannels
icUInt16Number m_nLastNumChannels
icFloatNumber * m_pixelBuf1
icFloatNumber * m_pixelBuf2
Detailed Description
Class: CIccDblPixelBuffer
Purpose: The general purpose pixel storage buffer for pixel apply
Constructor & Destructor Documentation
CIccDblPixelBuffer::CIccDblPixelBuffer ()
Name: CIccDblPixelBuffer::CIccDblPixelBuffer
Purpose:
Args:
Return:
CIccDblPixelBuffer::CIccDblPixelBuffer (const CIccDblPixelBuffer & buf)
Name: CIccDblPixelBuffer::CIccDblPixelBuffer
Purpose:
Args:
Return:
References m_nMaxChannels, m_pixelBuf1, and m_pixelBuf2.
CIccDblPixelBuffer::~CIccDblPixelBuffer () virtual
Name: CIccDblPixelBuffer::~CIccDblPixelBuffer
Purpose:
Args:
Return:
Member Function Documentation
bool CIccDblPixelBuffer::Begin ()
Name: CIccDblPixelBuffer::CIccDblPixelBuffer
Purpose:
Args:
Return:
Referenced by CIccTagMultiProcessElement::GetNewApply().
void CIccDblPixelBuffer::Clean ()
Name: CIccDblPixelBuffer::CIccDblPixelBuffer
Purpose:
Args:
Return:
icUInt16Number CIccDblPixelBuffer::GetAvailChannels () inline
icFloatNumber* CIccDblPixelBuffer::GetDstBuf () inline
Referenced by CIccTagMultiProcessElement::Apply().
icUInt16Number CIccDblPixelBuffer::GetMaxChannels () inline
icFloatNumber* CIccDblPixelBuffer::GetSrcBuf () inline
Referenced by CIccTagMultiProcessElement::Apply().
CIccDblPixelBuffer & CIccDblPixelBuffer::operator= (const CIccDblPixelBuffer & buf)
Name: CIccDblPixelBuffer::CIccDblPixelBuffer
Purpose:
Args:
Return:
References m_nMaxChannels, m_pixelBuf1, and m_pixelBuf2.
void CIccDblPixelBuffer::Reset () inline
void CIccDblPixelBuffer::Switch () inline
Referenced by CIccTagMultiProcessElement::Apply().
void CIccDblPixelBuffer::UpdateChannels (icUInt16Number nNumChannels) inline
Referenced by CIccTagMultiProcessElement::GetNewApply().
Member Data Documentation
icUInt16Number CIccDblPixelBuffer::m_nLastNumChannels protected
icUInt16Number CIccDblPixelBuffer::m_nMaxChannels protected
Referenced by CIccDblPixelBuffer(), and operator=().
icFloatNumber* CIccDblPixelBuffer::m_pixelBuf1 protected
Referenced by CIccDblPixelBuffer(), and operator=().
icFloatNumber* CIccDblPixelBuffer::m_pixelBuf2 protected
Referenced by CIccDblPixelBuffer(), and operator=().
The documentation for this class was generated from the following files:
IccTagMPE.h
IccTagMPE.cpp