CIccEvalCompare Class Reference
CIccEvalCompare Class Reference abstract
#include <IccEval.h>
Public Member Functions
virtual void Compare (icFloatNumber *pPixel, icFloatNumber *deviceLab, icFloatNumber *destLab1, icFloatNumber *destLab2)=0
icStatusCMM ICCPROFLIB_API EvaluateProfile (CIccProfile *pProfile, icUInt8Number nGran=0, icRenderingIntent nIntent=icUnknownIntent, icXformInterp nInterp=icInterpLinear, bool buseMpeTags=true)
icStatusCMM ICCPROFLIB_API EvaluateProfile (const icChar *szProfilePath, icUInt8Number nGran=0, icRenderingIntent nIntent=icUnknownIntent, icXformInterp nInterp=icInterpLinear, bool buseMpeTags=true)
Member Function Documentation
virtual void CIccEvalCompare::Compare (icFloatNumber * pPixel, icFloatNumber * deviceLab, icFloatNumber * destLab1, icFloatNumber * destLab2) pure virtual
icStatusCMM CIccEvalCompare::EvaluateProfile (CIccProfile * pProfile, icUInt8Number nGran = 0, icRenderingIntent nIntent = icUnknownIntent, icXformInterp nInterp = icInterpLinear, bool buseMpeTags = true)
References CIccCmm::AddXform(), CIccCmm::Apply(), CIccCmm::Begin(), icHeader::colorSpace, icHeader::deviceClass, CIccProfile::FindTag(), CIccMBB::GetCLUT(), CIccCLUT::GridPoints(), icAbsoluteColorimetric, icCmmStatCantOpenProfile, icCmmStatInvalidProfile, icCmmStatOk, icGetSpaceSamples(), icLabFromPcs(), icMin(), icRelativeColorimetric, icSigAToB0Tag, icSigColorSpaceClass, icSigDisplayClass, icSigInputClass, icSigLabData, icSigOutputClass, icSigUnknownData, icXformLutColor, and CIccProfile::m_Header.
icStatusCMM CIccEvalCompare::EvaluateProfile (const icChar * szProfilePath, icUInt8Number nGran = 0, icRenderingIntent nIntent = icUnknownIntent, icXformInterp nInterp = icInterpLinear, bool buseMpeTags = true)
References icCmmStatCantOpenProfile, and ReadIccProfile().
The documentation for this class was generated from the following files:
IccEval.h
IccEval.cpp