CIccTagNamedColor2 Class Reference
CIccTagNamedColor2 Class Reference
#include <IccTagBasic.h>
Public Member Functions
CIccTagNamedColor2 (int nSize=1, int nDeviceCoords=0)
CIccTagNamedColor2 (const CIccTagNamedColor2 &ITNC)
CIccTagNamedColor2 & operator= (const CIccTagNamedColor2 &NamedColor2Tag)
virtual CIccTag * NewCopy () const
virtual ~CIccTagNamedColor2 ()
virtual icTagTypeSignature GetType () const
virtual const icChar * GetClassName () const
virtual bool UseLegacyPCS () const
virtual void Describe (std::string &sDescription)
virtual bool Read (icUInt32Number size, CIccIO *pIO)
virtual bool Write (CIccIO *pIO)
const icChar * GetPrefix () const
void SetPrefix (const icChar *szPrefix)
const icChar * GetSufix () const
void SetSufix (const icChar *szSufix)
icUInt32Number GetVendorFlags () const
void SetVendorFlags (icUInt32Number nVendorFlags)
icInt32Number FindColor (const icChar *szColor) const
icInt32Number FindRootColor (const icChar *szRootColor) const
icInt32Number FindDeviceColor (icFloatNumber *pDevColor) const
icInt32Number FindPCSColor (icFloatNumber *pPCS, icFloatNumber dMinDE=1000.0)
bool InitFindCachedPCSColor ()
icInt32Number FindCachedPCSColor (icFloatNumber *pPCS, icFloatNumber dMinDE=1000.0) const
void ResetPCSCache ()
Call ResetPCSCache() if entry values change between calls to FindPCSColor()
bool GetColorName (std::string &sColorName, icInt32Number index) const
SIccNamedColorEntry & operator[] (icUInt32Number index) const
SIccNamedColorEntry * GetEntry (icUInt32Number index) const
icUInt32Number GetSize () const
icUInt32Number GetDeviceCoords () const
void SetSize (icUInt32Number nSize, icInt32Number nDeviceCoords=-1)
virtual void SetColorSpaces (icColorSpaceSignature csPCS, icColorSpaceSignature csDevice)
icColorSpaceSignature GetPCS () const
icColorSpaceSignature GetDeviceSpace () const
icFloatNumber NegClip (icFloatNumber v) const
icFloatNumber UnitClip (icFloatNumber v) const
void Lab2ToLab4 (icFloatNumber *Dst, const icFloatNumber *Src) const
void Lab4ToLab2 (icFloatNumber *Dst, const icFloatNumber *Src) const
virtual icValidateStatus Validate (icTagSignature sig, std::string &sReport, const CIccProfile *pProfile=NULL) const
Public Member Functions inherited from CIccTag
CIccTag ()
virtual ~CIccTag ()
virtual bool IsArrayType ()
virtual bool IsMBBType ()
virtual IIccExtensionTag * GetExtension ()
virtual bool IsSupported ()
Protected Attributes
icChar m_szPrefix [32]
icChar m_szSufix [32]
SIccNamedColorEntry * m_NamedColor
SIccNamedLabEntry * m_NamedLab
icUInt32Number m_nColorEntrySize
For quick response of repeated FindPCSColor.
icUInt32Number m_nVendorFlags
icUInt32Number m_nDeviceCoords
icUInt32Number m_nSize
icColorSpaceSignature m_csPCS
icColorSpaceSignature m_csDevice
Additional Inherited Members
Static Public Member Functions inherited from CIccTag
static CIccTag * Create (icTagTypeSignature sig)
Public Attributes inherited from CIccTag
icUInt32Number m_nReserved
Detailed Description
Class: CIccTagNamedColor2
Purpose: the NamedColor2 tag - an array of Named Colors
Constructor & Destructor Documentation
CIccTagNamedColor2::CIccTagNamedColor2 (int nSize = 1, int nDeviceCoords = 0)
Name: CIccTagNamedColor2::CIccTagNamedColor2
Purpose: Constructor
Args: nSize = number of named color entries, nDeviceCoords = number of device channels
References icSigUnknownData.
CIccTagNamedColor2::CIccTagNamedColor2 (const CIccTagNamedColor2 & ITNC)
Name: CIccTagNamedColor2::CIccTagNamedColor2
Purpose: Copy Constructor
Args: ITNC = The CIccTagNamedColor2 object to be copied
References m_csDevice, m_csPCS, m_NamedColor, m_nColorEntrySize, m_nDeviceCoords, m_nSize, m_nVendorFlags, m_szPrefix, and m_szSufix.
CIccTagNamedColor2::~CIccTagNamedColor2 () virtual
Name: CIccTagNamedColor2::~CIccTagNamedColor2
Purpose: Destructor
Member Function Documentation
void CIccTagNamedColor2::Describe (std::string & sDescription) virtual
Name: CIccTagNamedColor2::Describe
Purpose: Dump data associated with the tag to a string
Args: sDescription - string to concatenate tag dump to
Reimplemented from CIccTag.
References SIccNamedColorEntry::deviceCoords, icColorIndexName(), icColorValue(), icSigLabData, SIccNamedColorEntry::pcsCoords, and SIccNamedColorEntry::rootName.
icInt32Number CIccTagNamedColor2::FindCachedPCSColor (icFloatNumber * pPCS, icFloatNumber dMinDE = 1000.0) const
Name: CIccTagNamedColor2::FindPCSColor
Purpose: Find the PCS color within the specified deltaE
Args: pPCS = PCS co-ordinates, dMinDE = the minimum deltaE (tolerance)
Return: Index of the named color array where the PCS color was found, if the color was not found within the tolerance -1 is returned
References icDeltaE(), icLabFromPcs(), icSigLabData, icXyzFromPcs(), and icXYZtoLab().
Referenced by CIccXformNamedColor::Apply().
icInt32Number CIccTagNamedColor2::FindColor (const icChar * szColor) const
Name: CIccTagNamedColor2::FindColor
Purpose: Find the color with given name
Args: szColor = the color name
Return: Index of the named color array where the color name was found, if the color was not found -1 is returned
Referenced by CIccXformNamedColor::Apply().
icInt32Number CIccTagNamedColor2::FindDeviceColor (icFloatNumber * pDevColor) const
Name: CIccTagNamedColor2::FindDeviceColor
Purpose: Find the device color
Args: pDevColor = device color co-ordinates
Return: Index of the named color array where the closest device color was found, if device representation is absent -1 is returned.
Referenced by CIccXformNamedColor::Apply().
icInt32Number CIccTagNamedColor2::FindPCSColor (icFloatNumber * pPCS, icFloatNumber dMinDE = 1000.0)
Name: CIccTagNamedColor2::FindPCSColor
Purpose: Find the PCS color within the specified deltaE
Args: pPCS = PCS co-ordinates, dMinDE = the minimum deltaE (tolerance)
Return: Index of the named color array where the PCS color was found, if the color was not found within the tolerance -1 is returned
icInt32Number CIccTagNamedColor2::FindRootColor (const icChar * szRootColor) const
Name: CIccTagNamedColor2::FindRootColor
Purpose: Find the root color name
Args: szRootColor = string containing the root color name to be found
Return: Index of the named color array where the root color name was found, if the color was not found -1 is returned
References stricmp.
virtual const icChar* CIccTagNamedColor2::GetClassName () const inline virtual
Reimplemented from CIccTag.
bool CIccTagNamedColor2::GetColorName (std::string & sColorName, icInt32Number index) const
Name: CIccTagNamedColor2::GetColorName
Purpose: Extracts the color name from the named color array
Args: sColorName = string where color name will be stored, index = array index of the color name
Return: true = if the index is within range, false = index out of range
Referenced by CIccXformNamedColor::Apply().
icUInt32Number CIccTagNamedColor2::GetDeviceCoords () const inline
Referenced by CIccXformNamedColor::Apply().
icColorSpaceSignature CIccTagNamedColor2::GetDeviceSpace () const inline
SIccNamedColorEntry* CIccTagNamedColor2::GetEntry (icUInt32Number index) const inline
Referenced by CIccXformNamedColor::Apply().
icColorSpaceSignature CIccTagNamedColor2::GetPCS () const inline
const icChar* CIccTagNamedColor2::GetPrefix () const inline
icUInt32Number CIccTagNamedColor2::GetSize () const inline
const icChar* CIccTagNamedColor2::GetSufix () const inline
virtual icTagTypeSignature CIccTagNamedColor2::GetType () const inline virtual
Function: GetType()
Purpose: Get Tag Type. Each derived tag will implement it's own GetType() function.
Reimplemented from CIccTag.
References icSigNamedColor2Type.
icUInt32Number CIccTagNamedColor2::GetVendorFlags () const inline
bool CIccTagNamedColor2::InitFindCachedPCSColor ()
Name: CIccTagNamedColor2::InitFindPCSColor
Purpose: Initialization needed for using FindPCSColor
Return: true if successfull, false if failure
References icLabFromPcs(), icSigLabData, icXyzFromPcs(), icXYZtoLab(), and SIccNamedLabEntry::lab.
void CIccTagNamedColor2::Lab2ToLab4 (icFloatNumber * Dst, const icFloatNumber * Src) const
Name: CIccTagNamedColor2::Lab2ToLab4
Purpose: Convert version 2 Lab to version 4 Lab
Args: Dst = array to store version 4 Lab coordinates, Src = array containing version 2 Lab coordinates
void CIccTagNamedColor2::Lab4ToLab2 (icFloatNumber * Dst, const icFloatNumber * Src) const
Name: CIccTagNamedColor2::Lab4ToLab2
Purpose: Convert version 4 Lab to version 2 Lab
Args: Dst = array to store version 2 Lab coordinates, Src = array containing version 4 Lab coordinates
icFloatNumber CIccTagNamedColor2::NegClip (icFloatNumber v) const
Name: CIccTagNamedColor2::NegClip
Purpose: Negative numbers are clipped to zero
Args: v = number to be clipped
Return: Clipped number
virtual CIccTag* CIccTagNamedColor2::NewCopy () const inline virtual
Function: NewCopy(sDescription) Each derived tag will implement it's own NewCopy() function.
Parameter(s): none
Returns a new CIccTag object that is a copy of this object.
Reimplemented from CIccTag.
CIccTagNamedColor2 & CIccTagNamedColor2::operator= (const CIccTagNamedColor2 & NamedColor2Tag)
Name: CIccTagNamedColor2::operator=
Purpose: Copy Operator
Args: NamedColor2Tag = The CIccTagNamedColor2 object to be copied
References m_csDevice, m_csPCS, m_NamedColor, m_nColorEntrySize, m_nDeviceCoords, m_nSize, m_nVendorFlags, m_szPrefix, and m_szSufix.
SIccNamedColorEntry& CIccTagNamedColor2::operator[] (icUInt32Number index) const inline
bool CIccTagNamedColor2::Read (icUInt32Number size, CIccIO * pIO) virtual
Name: CIccTagNamedColor2::Read
Purpose: Read in the tag contents into a data block
Args: size - # of bytes in tag, pIO - IO object to read tag from
Return: true = successful, false = failure
Reimplemented from CIccTag.
References SIccNamedColorEntry::deviceCoords, SIccNamedColorEntry::pcsCoords, CIccIO::Read16Float(), CIccIO::Read32(), CIccIO::Read8(), and SIccNamedColorEntry::rootName.
void CIccTagNamedColor2::ResetPCSCache ()
Call ResetPCSCache() if entry values change between calls to FindPCSColor()
Name: CIccTagNamedColor2::ResetPCSCache
Purpose: This function is called if entry values change between calls to FindPCSColor()
void CIccTagNamedColor2::SetColorSpaces (icColorSpaceSignature csPCS, icColorSpaceSignature csDevice) virtual
Name: CIccTagNamedColor2::SetColorSpaces
Purpose: Set the device and PCS color space of the tag
Args: csPCS = PCS color space signature, csDevice = Device color space signature
void CIccTagNamedColor2::SetPrefix (const icChar * szPrefix)
Name: CIccTagNamedColor2::SetPrefix
Purpose: Set contents of suffix member field
Args: szPrefix - string to set prefix to
void CIccTagNamedColor2::SetSize (icUInt32Number nSize, icInt32Number nDeviceCoords = -1)
Name: CIccTagNamedColor2::SetSize
Purpose: Sets the size of the named color array.
Args: nSize - number of named color entries, nDeviceCoords - number of device channels
References __min, SIccNamedColorEntry::deviceCoords, SIccNamedColorEntry::pcsCoords, and SIccNamedColorEntry::rootName.
void CIccTagNamedColor2::SetSufix (const icChar * szSufix)
Name: CIccTagNamedColor2::SetSufix
Purpose: Set contents of suffix member field
Args: szPrefix - string to set prefix to
void CIccTagNamedColor2::SetVendorFlags (icUInt32Number nVendorFlags) inline
icFloatNumber CIccTagNamedColor2::UnitClip (icFloatNumber v) const
Name: CIccTagNamedColor2::UnitClip
Purpose: Clip number so that its between 0-1
Args: v = number to be clipped
Return: Clipped number
virtual bool CIccTagNamedColor2::UseLegacyPCS () const inline virtual
icValidateStatus CIccTagNamedColor2::Validate (icTagSignature sig, std::string & sReport, const CIccProfile * pProfile = NULL) const virtual
Name: CIccTagNamedColor2::Validate
Purpose: Check tag data validity.
Args: sig = signature of tag being validated, sReport = String to add report information to
Return: icValidateStatusOK if valid, or other error status.
Reimplemented from CIccTag.
References icHeader::colorSpace, CIccInfo::GetSigName(), icGetSpaceSamples(), icMaxStatus(), icValidateNonCompliant, icValidateNonCompliantMsg, icValidateWarning, icValidateWarningMsg, CIccProfile::m_Header, and CIccTag::Validate().
bool CIccTagNamedColor2::Write (CIccIO * pIO) virtual
Name: CIccTagNamedColor2::Write
Purpose: Write the tag to a file
Args: pIO - The IO object to write tag to.
Return: true = succesful, false = failure
Reimplemented from CIccTag.
References SIccNamedColorEntry::deviceCoords, SIccNamedColorEntry::pcsCoords, SIccNamedColorEntry::rootName, CIccIO::Write16Float(), CIccIO::Write32(), and CIccIO::Write8().
Member Data Documentation
icColorSpaceSignature CIccTagNamedColor2::m_csDevice protected
Referenced by CIccTagNamedColor2(), and operator=().
icColorSpaceSignature CIccTagNamedColor2::m_csPCS protected
Referenced by CIccTagNamedColor2(), and operator=().
SIccNamedColorEntry* CIccTagNamedColor2::m_NamedColor protected
Referenced by CIccTagNamedColor2(), and operator=().
SIccNamedLabEntry* CIccTagNamedColor2::m_NamedLab protected
icUInt32Number CIccTagNamedColor2::m_nColorEntrySize protected
For quick response of repeated FindPCSColor.
Referenced by CIccTagNamedColor2(), and operator=().
icUInt32Number CIccTagNamedColor2::m_nDeviceCoords protected
Referenced by CIccTagNamedColor2(), and operator=().
icUInt32Number CIccTagNamedColor2::m_nSize protected
Referenced by CIccTagNamedColor2(), and operator=().
icUInt32Number CIccTagNamedColor2::m_nVendorFlags protected
Referenced by CIccTagNamedColor2(), and operator=().
icChar CIccTagNamedColor2::m_szPrefix[32] protected
Referenced by CIccTagNamedColor2(), and operator=().
icChar CIccTagNamedColor2::m_szSufix[32] protected
Referenced by CIccTagNamedColor2(), and operator=().
The documentation for this class was generated from the following files:
IccTagBasic.h
IccTagBasic.cpp