CIccMpeUnknown Class Reference
CIccMpeUnknown Class Reference
#include <IccTagMPE.h>
Public Member Functions
CIccMpeUnknown ()
CIccMpeUnknown (const CIccMpeUnknown &elem)
CIccMpeUnknown & operator= (const CIccMpeUnknown &elem)
virtual CIccMultiProcessElement * NewCopy () const
virtual ~CIccMpeUnknown ()
virtual icElemTypeSignature GetType () const
virtual const icChar * GetClassName () const
virtual bool IsSupported ()
virtual void Describe (std::string &sDescription)
void SetType (icElemTypeSignature sig)
void SetChannels (icUInt16Number nInputChannels, icUInt16Number nOutputChannels)
bool SetDataSize (icUInt32Number nSize, bool bZeroData=true)
icUInt8Number * GetData ()
virtual bool Read (icUInt32Number nSize, CIccIO *pIO)
virtual bool Write (CIccIO *pIO)
virtual bool Begin (icElemInterp nIterp=icElemInterpLinear, CIccTagMultiProcessElement *pMPE=NULL)
virtual CIccApplyMpe * GetNewApply ()
virtual void Apply (CIccApplyMpe *pApply, icFloatNumber *pDestPixel, const icFloatNumber *pSrcPixel) const
virtual icValidateStatus Validate (icTagSignature sig, std::string &sReport, const CIccTagMultiProcessElement *pMPE=NULL) const
Public Member Functions inherited from CIccMultiProcessElement
CIccMultiProcessElement ()
virtual ~CIccMultiProcessElement ()
virtual icUInt16Number NumInputChannels () const
virtual icUInt16Number NumOutputChannels () const
virtual CIccApplyMpe * GetNewApply (CIccApplyTagMpe *pApplyTag)
virtual bool IsAcs ()
virtual icAcsSignature GetBAcsSig ()
virtual icAcsSignature GetEAcsSig ()
virtual IIccExtensionMpe * GetExtension ()
Protected Attributes
icElemTypeSignature m_sig
icUInt32Number m_nReserved
icUInt16Number m_nInputChannels
icUInt16Number m_nOutputChannels
icUInt32Number m_nSize
icUInt8Number * m_pData
Protected Attributes inherited from CIccMultiProcessElement
icUInt16Number m_nInputChannels
icUInt16Number m_nOutputChannels
Additional Inherited Members
Static Public Member Functions inherited from CIccMultiProcessElement
static CIccMultiProcessElement * Create (icElemTypeSignature sig)
Public Attributes inherited from CIccMultiProcessElement
icUInt32Number m_nReserved
Detailed Description
Class: CIccMpeUnknown
Purpose: Base Class for Process Elements
Constructor & Destructor Documentation
CIccMpeUnknown::CIccMpeUnknown ()
Name: CIccMpeUnknown::CIccMpeUnknown
Purpose:
Args:
Return:
References icSigUnknownElemType.
CIccMpeUnknown::CIccMpeUnknown (const CIccMpeUnknown & elem)
Name: CIccMpeUnknown::CIccMpeUnknown
Purpose:
Args:
Return:
References m_nInputChannels, m_nOutputChannels, m_nReserved, m_nSize, m_pData, and m_sig.
CIccMpeUnknown::~CIccMpeUnknown () virtual
Name: CIccMpeUnknown::~CIccMpeUnknown
Purpose:
Args:
Return:
Member Function Documentation
virtual void CIccMpeUnknown::Apply (CIccApplyMpe * pApply, icFloatNumber * pDestPixel, const icFloatNumber * pSrcPixel) const inline virtual
Implements CIccMultiProcessElement.
virtual bool CIccMpeUnknown::Begin (icElemInterp nIterp = icElemInterpLinear, CIccTagMultiProcessElement * pMPE = NULL) inline virtual
Implements CIccMultiProcessElement.
void CIccMpeUnknown::Describe (std::string & sDescription) virtual
Name: CIccMpeUnknown::Describe
Purpose:
Args:
Return:
Implements CIccMultiProcessElement.
References icGetSig(), and icMemDump().
virtual const icChar* CIccMpeUnknown::GetClassName () const inline virtual
Implements CIccMultiProcessElement.
icUInt8Number* CIccMpeUnknown::GetData () inline
virtual CIccApplyMpe* CIccMpeUnknown::GetNewApply () inline virtual
virtual icElemTypeSignature CIccMpeUnknown::GetType () const inline virtual
Implements CIccMultiProcessElement.
virtual bool CIccMpeUnknown::IsSupported () inline virtual
Reimplemented from CIccMultiProcessElement.
virtual CIccMultiProcessElement* CIccMpeUnknown::NewCopy () const inline virtual
Implements CIccMultiProcessElement.
CIccMpeUnknown & CIccMpeUnknown::operator= (const CIccMpeUnknown & elem)
Name: CIccMpeUnknown::operator=
Purpose:
Args:
Return:
References m_nInputChannels, m_nOutputChannels, m_nReserved, m_nSize, m_pData, and m_sig.
bool CIccMpeUnknown::Read (icUInt32Number nSize, CIccIO * pIO) virtual
Name: CIccMpeUnknown::Read
Purpose:
Args:
Return:
Implements CIccMultiProcessElement.
References CIccIO::Read16(), CIccIO::Read32(), and CIccIO::Read8().
void CIccMpeUnknown::SetChannels (icUInt16Number nInputChannels, icUInt16Number nOutputChannels)
Name: CIccMpeUnknown::Describe
Purpose:
Args:
Return:
bool CIccMpeUnknown::SetDataSize (icUInt32Number nSize, bool bZeroData = true)
Name: CIccMpeUnknown::SetDataSize
Purpose:
Args:
Return:
void CIccMpeUnknown::SetType (icElemTypeSignature sig)
Name: CIccMpeUnknown::SetType
Purpose:
Args:
Return:
icValidateStatus CIccMpeUnknown::Validate (icTagSignature sig, std::string & sReport, const CIccTagMultiProcessElement * pMPE = NULL) const virtual
Name: CIccMpeUnknown::Validate
Purpose:
Args:
Return:
Implements CIccMultiProcessElement.
References CIccInfo::GetSigName(), icGetSig(), icValidateCriticalError, and icValidateCriticalErrorMsg.
bool CIccMpeUnknown::Write (CIccIO * pIO) virtual
Name: CIccMpeUnknown::Write
Purpose:
Args:
Return:
Implements CIccMultiProcessElement.
References CIccIO::Write16(), CIccIO::Write32(), and CIccIO::Write8().
Member Data Documentation
icUInt16Number CIccMpeUnknown::m_nInputChannels protected
Referenced by CIccMpeUnknown(), and operator=().
icUInt16Number CIccMpeUnknown::m_nOutputChannels protected
Referenced by CIccMpeUnknown(), and operator=().
icUInt32Number CIccMpeUnknown::m_nReserved protected
Referenced by CIccMpeUnknown(), and operator=().
icUInt32Number CIccMpeUnknown::m_nSize protected
Referenced by CIccMpeUnknown(), and operator=().
icUInt8Number* CIccMpeUnknown::m_pData protected
Referenced by CIccMpeUnknown(), and operator=().
icElemTypeSignature CIccMpeUnknown::m_sig protected
Referenced by CIccMpeUnknown(), and operator=().
The documentation for this class was generated from the following files:
IccTagMPE.h
IccTagMPE.cpp