CIccXform Class Reference
CIccXform Class Reference abstract
#include <IccCmm.h>
Public Member Functions
CIccXform ()
virtual ~CIccXform ()
virtual icXformType GetXformType () const =0
virtual icStatusCMM Begin ()
virtual CIccApplyXform * GetNewApply (icStatusCMM &status)
virtual void Apply (CIccApplyXform *pXform, icFloatNumber *DstPixel, const icFloatNumber *SrcPixel) const =0
virtual bool RemoveIO ()
virtual icColorSpaceSignature GetSrcSpace () const
Returns the source color space of the transform.
virtual icColorSpaceSignature GetDstSpace () const
Returns the destination color space of the transform.
virtual bool UseLegacyPCS () const
Checks if version 2 PCS is to be used.
virtual bool IsVersion2 () const
Checks if the profile is version 2.
bool IsInput () const
Checks if the profile is to be used as input profile.
void SetParams (CIccProfile *pProfile, bool bInput, icRenderingIntent nIntent, icXformInterp nInterp, CIccCreateXformHintManager *pHintManager=NULL)
The following function is for Overridden create function.
virtual LPIccCurve * ExtractInputCurves ()=0
Use these functions to extract the input/output curves from the xform.
virtual LPIccCurve * ExtractOutputCurves ()=0
virtual bool NoClipPCS () const
const CIccProfile * GetProfile () const
Returns the profile pointer. Profile is still owned by the Xform.
icRenderingIntent GetIntent () const
Returns the rendering intent being used by the Xform.
Static Public Member Functions
static CIccXform * Create (CIccProfile *pProfile, bool bInput=true, icRenderingIntent nIntent=icUnknownIntent, icXformInterp nInterp=icInterpLinear, icXformLutType nLutType=icXformLutColor, bool bUseMpeTags=true, CIccCreateXformHintManager *pHintManager=NULL)
Note: The returned CIccXform will own the profile.
static CIccXform * Create (CIccProfile &pProfile, bool bInput=true, icRenderingIntent nIntent=icUnknownIntent, icXformInterp nInterp=icInterpLinear, icXformLutType nLutType=icXformLutColor, bool bUseMpeTags=true, CIccCreateXformHintManager *pHintManager=NULL)
Protected Member Functions
const icFloatNumber * CheckSrcAbs (CIccApplyXform *pApply, const icFloatNumber *Pixel) const
void CheckDstAbs (icFloatNumber *Pixel) const
void AdjustPCS (icFloatNumber *DstPixel, const icFloatNumber *SrcPixel) const
virtual bool HasPerceptualHandling ()
Protected Attributes
CIccProfile * m_pProfile
bool m_bInput
icRenderingIntent m_nIntent
icXYZNumber m_MediaXYZ
icXformInterp m_nInterp
IIccAdjustPCSXform * m_pAdjustPCS
bool m_bAdjustPCS
icFloatNumber m_PCSScale [3]
icFloatNumber m_PCSOffset [3]
Detailed Description
Type: Class
Purpose: This is the base CMM xform object. A general static creation function, base behavior, and data are defined. The Create() function will assign a profile to the class. The CIccProfile object will then be owned by the xform object and later deleted when the IccXform is deleted.
Constructor & Destructor Documentation
CIccXform::CIccXform ()
Name: CIccXform::CIccXform
Purpose: Constructor
References icUnknownIntent.
CIccXform::~CIccXform () virtual
Name: CIccXform::~CIccXform
Purpose: Destructor
Member Function Documentation
void CIccXform::AdjustPCS (icFloatNumber * DstPixel, const icFloatNumber * SrcPixel) const protected
Name: CIccXform::AdjustPCS
Purpose: This function will take care of any PCS adjustments needed by the xform (the PCS is always version 4 relative).
Args: DstPixel = Destination pixel where the result is stored, SrcPixel = Source pixel which is to be applied.
References icSigLabData, CIccPCS::Lab2ToXyz(), CIccPCS::LabToXyz(), CIccPCS::NegClip(), CIccPCS::XyzToLab(), and CIccPCS::XyzToLab2().
virtual void CIccXform::Apply (CIccApplyXform * pXform, icFloatNumber * DstPixel, const icFloatNumber * SrcPixel) const pure virtual
Implemented in CIccXformMpe, CIccXformNamedColor, CIccXformNDLut, CIccXform4DLut, CIccXform3DLut, CIccXformMatrixTRC, and CIccXformMonochrome.
Referenced by CIccApplyCmm::Apply(), and CIccApplyNamedColorCmm::Apply().
icStatusCMM CIccXform::Begin () virtual
Name: CIccXform::Begin
Purpose: This function will be called before the xform is applied. Derived objects should also call this base class function to initialize for Absolute Colorimetric Intent handling which is performed through the use of the CheckSrcAbs and CheckDstAbs functions.
Reimplemented in CIccXformMpe, CIccXformNamedColor, CIccXformNDLut, CIccXform4DLut, CIccXform3DLut, CIccXformMatrixTRC, and CIccXformMonochrome.
References CIccTag::GetType(), icAbsoluteColorimetric, icCmmStatIncorrectApply, icCmmStatInvalidProfile, icCmmStatOk, icPerceptual, icPerceptualRefBlackX, icPerceptualRefBlackY, icPerceptualRefBlackZ, icPerceptualRefWhiteX, icPerceptualRefWhiteY, icPerceptualRefWhiteZ, icSigAbstractClass, icSigMediaWhitePointTag, icSigXYZType, IsSpacePCS, and CIccProfile::ReadTags().
Referenced by CIccXformMonochrome::Begin(), CIccXformMatrixTRC::Begin(), CIccXform3DLut::Begin(), CIccXform4DLut::Begin(), CIccXformNDLut::Begin(), CIccXformNamedColor::Begin(), and CIccXformMpe::Begin().
void CIccXform::CheckDstAbs (icFloatNumber * Pixel) const protected
Name: CIccXform::CheckDstAbs
Purpose: This function will be called by a derived CIccXform object's Apply() function AFTER the actual xform is performed to take care of Absolute to Relative adjustments needed by the xform (IE the PCS is always version 4 relative).
Args: Pixel = source pixel data which will be modified
const icFloatNumber * CIccXform::CheckSrcAbs (CIccApplyXform * pApply, const icFloatNumber * Pixel) const protected
Name: CIccXform::CheckSrcAbs
Purpose: This function will be called by a derived CIccXform object's Apply() function BEFORE the actual xform is performed to take care of Absolute to Relative adjustments needed by the xform (IE the PCS is always version 4 relative).
Args: Pixel = src pixel data (will not be modified)
Return: returns Pixel or adjusted pixel data.
References CIccApplyXform::m_AbsLab.
CIccXform * CIccXform::Create (CIccProfile * pProfile, bool bInput = true, icRenderingIntent nIntent = icUnknownIntent, icXformInterp nInterp = icInterpLinear, icXformLutType nLutType = icXformLutColor, bool bUseMpeTags = true, CIccCreateXformHintManager * pHintManager = NULL) static
Note: The returned CIccXform will own the profile.
Name: CIccXform::Create
Purpose: This is a static Creation function that creates derived CIccXform objects and initializes them.
Args: pProfile = pointer to a CIccProfile object that will be owned by the transform. This object will be destroyed when the returned CIccXform object is destroyed. The means that the CIccProfile object needs to be allocated on the heap. bInput = flag to indicate whether to use the input or output side of the profile, nIntent = the rendering intent to apply to the profile, nInterp = the interpolation algorithm to use for N-D luts. nLutType = selection of which transform lut to use bUseMpeTags = flag to indicate the use MPE flags if available pHintManager = pointer to object that contains xform creation hints
Return: A suitable pXform object
References CIccCreateXformHintManager::AddHint(), icHeader::colorSpace, CIccXformCreator::CreateXform(), CIccCreateNamedColorXformHint::csDevice, CIccCreateNamedColorXformHint::csPcs, CIccCreateXformHintManager::DeleteHint(), icHeader::deviceClass, CIccProfile::FindTag(), CIccTag::GetType(), icAbsoluteColorimetric, icPerceptual, icRelativeColorimetric, icSig3colorData, icSig4colorData, icSigAToB0Tag, icSigBToA0Tag, icSigBToD0Tag, icSigBToD1Tag, icSigCmyData, icSigCmykData, icSigDToB0Tag, icSigDToB1Tag, icSigGamutTag, icSigGrayData, icSigHlsData, icSigHsvData, icSigLabData, icSigLinkClass, icSigLuvData, icSigMultiProcessElementType, icSigNamedColor2Tag, icSigPreview0Tag, icSigRgbData, icSigXYZData, icSigYCbCrData, icSigYxyData, icUnknownIntent, icXformLutColor, icXformLutGamut, icXformLutNamedColor, icXformLutPreview, icXformType3DLut, icXformType4DLut, icXformTypeMatrixTRC, icXformTypeMonochrome, icXformTypeMpe, icXformTypeNamedColor, icXformTypeNDLut, CIccTag::IsSupported(), CIccProfile::m_Header, icHeader::pcs, and SetParams().
Referenced by CIccCmm::AddXform(), and CIccNamedColorCmm::AddXform().
CIccXform * CIccXform::Create (CIccProfile & Profile, bool bInput = true, icRenderingIntent nIntent = icUnknownIntent, icXformInterp nInterp = icInterpLinear, icXformLutType nLutType = icXformLutColor, bool bUseMpeTags = true, CIccCreateXformHintManager * pHintManager = NULL) static
Note: Provide an interface to work profile references. The IccProfile is copied, and the copy's ownership is turned over to the Returned CIccXform object.
Name: CIccXform::Create
Purpose: This is a static Creation function that creates derived CIccXform objects and initializes them.
Args: Profile = reference to a CIccProfile object that will be used to create the transform. A copy of the CIccProfile object will be created and passed to the pointer based Create(). The copied object will be destroyed when the returned CIccXform object is destroyed. bInput = flag to indicate whether to use the input or output side of the profile, nIntent = the rendering intent to apply to the profile, nInterp = the interpolation algorithm to use for N-D luts. nLutType = selection of which transform lut to use bUseMpeTags = flag to indicate the use MPE flags if available pHint = pointer to object passed to CIccXform creation functionality
Return: A suitable pXform object
References CIccProfile.
virtual LPIccCurve* CIccXform::ExtractInputCurves () pure virtual
Use these functions to extract the input/output curves from the xform.
Implemented in CIccXformMpe, CIccXformNamedColor, CIccXformNDLut, CIccXform4DLut, CIccXform3DLut, CIccXformMatrixTRC, and CIccXformMonochrome.
virtual LPIccCurve* CIccXform::ExtractOutputCurves () pure virtual
Implemented in CIccXformMpe, CIccXformNamedColor, CIccXformNDLut, CIccXform4DLut, CIccXform3DLut, CIccXformMatrixTRC, and CIccXformMonochrome.
icColorSpaceSignature CIccXform::GetDstSpace () const virtual
Returns the destination color space of the transform.
Name: CIccXformMatrixTRC::GetDstSpace
Purpose: Return the color space that is output by the transform. If a device space is either XYZ/Lab it is changed to dXYZ/dLab to avoid confusion with PCS encoding of these spaces. Device encoding of XYZ and Lab spaces left to the device.
Reimplemented in CIccXformNamedColor.
References icSigAbstractClass, icSigDevLabData, icSigDevXYZData, icSigLabData, and icSigXYZData.
Referenced by CIccPCS::Check().
icRenderingIntent CIccXform::GetIntent () const inline
Returns the rendering intent being used by the Xform.
Referenced by CIccApplyBPC::CalcFactors().
CIccApplyXform * CIccXform::GetNewApply (icStatusCMM & status) virtual
Name: CIccXform::GetNewApply
Purpose: This Factory function allocates data specific for the application of the xform. This allows multiple threads to simultaneously use the same xform.
Reimplemented in CIccXformMpe.
References icCmmStatAllocErr, and icCmmStatOk.
const CIccProfile* CIccXform::GetProfile () const inline
Returns the profile pointer. Profile is still owned by the Xform.
icColorSpaceSignature CIccXform::GetSrcSpace () const virtual
Returns the source color space of the transform.
Name: CIccXformMatrixTRC::GetSrcSpace
Purpose: Return the color space that is input to the transform. If a device space is either XYZ/Lab it is changed to dXYZ/dLab to avoid confusion with PCS encoding of these spaces. Device encoding of XYZ and Lab spaces left to the device.
Reimplemented in CIccXformNamedColor.
References icSigAbstractClass, icSigDevLabData, icSigDevXYZData, icSigLabData, and icSigXYZData.
Referenced by CIccPCS::Check().
virtual icXformType CIccXform::GetXformType () const pure virtual
Implemented in CIccXformMpe, CIccXformNamedColor, CIccXformNDLut, CIccXform4DLut, CIccXform3DLut, CIccXformMatrixTRC, and CIccXformMonochrome.
Referenced by CIccApplyNamedColorCmm::Apply(), and CIccNamedColorCmm::SetLastXformDest().
virtual bool CIccXform::HasPerceptualHandling () inline protected virtual
Reimplemented in CIccXformNamedColor, CIccXformMatrixTRC, and CIccXformMonochrome.
bool CIccXform::IsInput () const inline
Checks if the profile is to be used as input profile.
Referenced by CIccApplyBPC::CalcFactors().
virtual bool CIccXform::IsVersion2 () const inline virtual
Checks if the profile is version 2.
References icVersionNumberV4.
virtual bool CIccXform::NoClipPCS () const inline virtual
Reimplemented in CIccXformMpe.
Referenced by CIccApplyCmm::Apply(), and CIccPCS::Check().
virtual bool CIccXform::RemoveIO () inline virtual
void CIccXform::SetParams (CIccProfile * pProfile, bool bInput, icRenderingIntent nIntent, icXformInterp nInterp, CIccCreateXformHintManager * pHintManager = NULL)
The following function is for Overridden create function.
Name: CIccXform::SetParams
Purpose: This is an accessor function to set private values.
Args: pProfile = pointer to profile associated with transform bInput = indicates whether profile is input profile nIntent = rendering intent to apply to the profile nInterp = the interpolation algorithm to use for N-D luts
References CIccCreateXformHintManager::GetHint(), and CIccCreateAdjustPCSXformHint::GetNewAdjustPCSXform().
Referenced by Create(), and CIccXformMpe::Create().
virtual bool CIccXform::UseLegacyPCS () const inline virtual
Checks if version 2 PCS is to be used.
Reimplemented in CIccXformMpe, CIccXformNamedColor, CIccXformNDLut, CIccXform4DLut, and CIccXform3DLut.
Referenced by CIccPCS::Check().
Member Data Documentation
bool CIccXform::m_bAdjustPCS protected
bool CIccXform::m_bInput protected
icXYZNumber CIccXform::m_MediaXYZ protected
icRenderingIntent CIccXform::m_nIntent protected
icXformInterp CIccXform::m_nInterp protected
IIccAdjustPCSXform* CIccXform::m_pAdjustPCS protected
icFloatNumber CIccXform::m_PCSOffset[3] protected
icFloatNumber CIccXform::m_PCSScale[3] protected
CIccProfile* CIccXform::m_pProfile protected
The documentation for this class was generated from the following files:
IccCmm.h
IccCmm.cpp