CIccSampledCurveSegment Class Reference
CIccSampledCurveSegment Class Reference
#include <IccMpeBasic.h>
Public Member Functions
CIccSampledCurveSegment (icFloatNumber start, icFloatNumber end)
CIccSampledCurveSegment (const CIccSampledCurveSegment &ITPC)
CIccSampledCurveSegment & operator= (const CIccSampledCurveSegment &ParamCurveTag)
virtual CIccCurveSegment * NewCopy () const
virtual ~CIccSampledCurveSegment ()
virtual icCurveSegSignature GetType () const
virtual const icChar * GetClassName () const
virtual bool SetSize (icUInt32Number nSize, bool bZeroAlloc=true)
virtual icUInt32Number GetSize ()
virtual icFloatNumber * GetSamples ()
virtual void Describe (std::string &sDescription)
virtual bool Read (icUInt32Number size, CIccIO *pIO)
virtual bool Write (CIccIO *pIO)
virtual bool Begin (CIccCurveSegment *pPrevSeg)
virtual icFloatNumber Apply (icFloatNumber v) const
virtual icValidateStatus Validate (icTagSignature sig, std::string &sReport, const CIccTagMultiProcessElement *pMPE=NULL) const
Public Member Functions inherited from CIccCurveSegment
virtual ~CIccCurveSegment ()
icFloatNumber StartPoint ()
icFloatNumber EndPoint ()
Protected Attributes
icUInt32Number m_nCount
icFloatNumber * m_pSamples
icFloatNumber m_range
icFloatNumber m_last
Protected Attributes inherited from CIccCurveSegment
icFloatNumber m_startPoint
icFloatNumber m_endPoint
icUInt32Number m_nReserved
Additional Inherited Members
Static Public Member Functions inherited from CIccCurveSegment
static CIccCurveSegment * Create (icCurveSegSignature sig, icFloatNumber start, icFloatNumber end)
Detailed Description
Class: CIccSampledCurveSegment
Purpose: The sampled curve segment
Constructor & Destructor Documentation
CIccSampledCurveSegment::CIccSampledCurveSegment (icFloatNumber start, icFloatNumber end)
Name: CIccSampledCurveSegment::CIccSampledCurveSegment
Purpose:
Args:
Return:
CIccSampledCurveSegment::CIccSampledCurveSegment (const CIccSampledCurveSegment & curve)
Name: CIccSampledCurveSegment::CIccSampledCurveSegment
Purpose:
Args:
Return:
References CIccCurveSegment::m_endPoint, m_nCount, CIccCurveSegment::m_nReserved, m_pSamples, and CIccCurveSegment::m_startPoint.
CIccSampledCurveSegment::~CIccSampledCurveSegment () virtual
Name: CIccSampledCurveSegment::~CIccSampledCurveSegment
Purpose:
Args:
Return:
Member Function Documentation
icFloatNumber CIccSampledCurveSegment::Apply (icFloatNumber v) const virtual
Name: CIccSampledCurveSegment::Apply
Purpose:
Args:
Return:
Implements CIccCurveSegment.
bool CIccSampledCurveSegment::Begin (CIccCurveSegment * pPrevSeg = NULL) virtual
Name: CIccSampledCurveSegment::Begin
Purpose:
Args:
Return:
Implements CIccCurveSegment.
void CIccSampledCurveSegment::Describe (std::string & sDescription) virtual
Name: CIccSampledCurveSegment::Describe
Purpose:
Args:
Return:
Implements CIccCurveSegment.
References icMaxFloat32Number, and icMinFloat32Number.
virtual const icChar* CIccSampledCurveSegment::GetClassName () const inline virtual
Implements CIccCurveSegment.
virtual icFloatNumber* CIccSampledCurveSegment::GetSamples () inline virtual
virtual icUInt32Number CIccSampledCurveSegment::GetSize () inline virtual
virtual icCurveSegSignature CIccSampledCurveSegment::GetType () const inline virtual
Implements CIccCurveSegment.
References icSigSampledCurveSeg.
virtual CIccCurveSegment* CIccSampledCurveSegment::NewCopy () const inline virtual
Implements CIccCurveSegment.
CIccSampledCurveSegment & CIccSampledCurveSegment::operator= (const CIccSampledCurveSegment & curve)
Name: &CIccSampledCurveSegment::operator=
Purpose:
Args:
Return:
References CIccCurveSegment::m_endPoint, m_nCount, CIccCurveSegment::m_nReserved, m_pSamples, and CIccCurveSegment::m_startPoint.
bool CIccSampledCurveSegment::Read (icUInt32Number size, CIccIO * pIO) virtual
Name: CIccSampledCurveSegment::Read
Purpose:
Args:
Return:
Implements CIccCurveSegment.
References CIccIO::Read32(), and CIccIO::ReadFloat32Float().
bool CIccSampledCurveSegment::SetSize (icUInt32Number nCount, bool bZeroAlloc = true) virtual
Name: CIccSampledCurveSegment::SetSize
Purpose: Sets size of sampled lookup table. Previous data (if exists) is lost.
Args: nCount = number of elements in lut (must be >= 2). Note: the m_pSample[0] is initialized from the the previous segment. It is not saved as part of Write(), or loaded as part of Read(). It will be initialized during the call to Begin(), The actual count of elements written to the file will be nCount-1 bZeroAlloc = flag to decide if memory should be set to zero.
Return: true if allocation successful.
icValidateStatus CIccSampledCurveSegment::Validate (icTagSignature sig, std::string & sReport, const CIccTagMultiProcessElement * pMPE = NULL) const virtual
Name: CIccSampledCurveSegment::Validate
Purpose:
Args:
Return:
Implements CIccCurveSegment.
References CIccInfo::GetSigName(), icMaxStatus(), icValidateCriticalError, icValidateCriticalErrorMsg, icValidateOK, icValidateWarning, and icValidateWarningMsg.
bool CIccSampledCurveSegment::Write (CIccIO * pIO) virtual
Name: CIccSampledCurveSegment::Write
Purpose:
Args:
Return:
Implements CIccCurveSegment.
References CIccIO::Write32(), and CIccIO::WriteFloat32Float().
Member Data Documentation
icFloatNumber CIccSampledCurveSegment::m_last protected
icUInt32Number CIccSampledCurveSegment::m_nCount protected
Referenced by CIccSampledCurveSegment(), and operator=().
icFloatNumber* CIccSampledCurveSegment::m_pSamples protected
Referenced by CIccSampledCurveSegment(), and operator=().
icFloatNumber CIccSampledCurveSegment::m_range protected
The documentation for this class was generated from the following files:
IccMpeBasic.h
IccMpeBasic.cpp