CIccApplyBPC Class Reference
CIccApplyBPC Class Reference
#include <IccApplyBPC.h>
Public Member Functions
virtual bool CalcFactors (const CIccProfile *pProfile, const CIccXform *pXfm, icFloatNumber *Scale, icFloatNumber *Offset) const
Public Member Functions inherited from IIccAdjustPCSXform
virtual ~IIccAdjustPCSXform ()
Detailed Description
Type: Class
Purpose: This is the hint for applying black point compensation. Also does the calculations to setup actual application of BPC.
Member Function Documentation
bool CIccApplyBPC::CalcFactors (const CIccProfile * pProfile, const CIccXform * pXform, icFloatNumber * Scale, icFloatNumber * Offset) const virtual
Name: CIccApplyBPC::CalculateFactors
Purpose: This function does the suitable calculations to setup black point compensation.
Args: pXform = pointer to the Xform object that calls this function
Return: true = all calculations done false = an error occurred
Implements IIccAdjustPCSXform.
References icHeader::deviceClass, CIccXform::GetIntent(), icAbsoluteColorimetric, icPerceptualRefBlackY, icPerceptualRefWhiteX, icPerceptualRefWhiteY, icPerceptualRefWhiteZ, icSigAbstractClass, icSigLinkClass, icSigNamedColorClass, icXyzToPcs(), CIccXform::IsInput(), and CIccProfile::m_Header.
The documentation for this class was generated from the following files:
IccApplyBPC.h
IccApplyBPC.cpp