CIccTagDateTime Class Reference
CIccTagDateTime Class Reference
#include <IccTagBasic.h>
Public Member Functions
CIccTagDateTime ()
CIccTagDateTime (const CIccTagDateTime &ITDT)
CIccTagDateTime & operator= (const CIccTagDateTime &DateTimeTag)
virtual CIccTag * NewCopy () const
virtual ~CIccTagDateTime ()
virtual icTagTypeSignature GetType () const
virtual const icChar * GetClassName () const
virtual bool Read (icUInt32Number size, CIccIO *pIO)
virtual bool Write (CIccIO *pIO)
virtual void Describe (std::string &sDescription)
void SetDateTime (icDateTimeNumber nDateTime)
virtual icValidateStatus Validate (icTagSignature sig, std::string &sReport, const CIccProfile *pProfile=NULL) const
Public Member Functions inherited from CIccTag
CIccTag ()
virtual ~CIccTag ()
virtual bool IsArrayType ()
virtual bool IsMBBType ()
virtual IIccExtensionTag * GetExtension ()
virtual bool IsSupported ()
Protected Attributes
icDateTimeNumber m_DateTime
Additional Inherited Members
Static Public Member Functions inherited from CIccTag
static CIccTag * Create (icTagTypeSignature sig)
Public Attributes inherited from CIccTag
icUInt32Number m_nReserved
Detailed Description
Class: CIccTagDateTime
Purpose: The date time tag type
Constructor & Destructor Documentation
CIccTagDateTime::CIccTagDateTime ()
Name: CIccTagDateTime::CIccTagDateTime
Purpose: Constructor
CIccTagDateTime::CIccTagDateTime (const CIccTagDateTime & ITDT)
Name: CIccTagDateTime::CIccTagDateTime
Purpose: Copy Constructor
Args: ITDT = The CIccTagDateTime object to be copied
References m_DateTime.
CIccTagDateTime::~CIccTagDateTime () virtual
Name: CIccTagDateTime::~CIccTagDateTime
Purpose: Destructor
Member Function Documentation
void CIccTagDateTime::Describe (std::string & sDescription) virtual
Name: CIccTagDateTime::Describe
Purpose: Dump data associated with the tag to a string
Args: sDescription - string to concatenate tag dump to
Reimplemented from CIccTag.
virtual const icChar* CIccTagDateTime::GetClassName () const inline virtual
Reimplemented from CIccTag.
virtual icTagTypeSignature CIccTagDateTime::GetType () const inline virtual
Function: GetType()
Purpose: Get Tag Type. Each derived tag will implement it's own GetType() function.
Reimplemented from CIccTag.
References icSigDateTimeType.
virtual CIccTag* CIccTagDateTime::NewCopy () const inline virtual
Function: NewCopy(sDescription) Each derived tag will implement it's own NewCopy() function.
Parameter(s): none
Returns a new CIccTag object that is a copy of this object.
Reimplemented from CIccTag.
CIccTagDateTime & CIccTagDateTime::operator= (const CIccTagDateTime & DateTimeTag)
Name: CIccTagDateTime::operator=
Purpose: Copy Operator
Args: DateTimeTag = The CIccTagDateTime object to be copied
References m_DateTime.
bool CIccTagDateTime::Read (icUInt32Number size, CIccIO * pIO) virtual
Name: CIccTagDateTime::Read
Purpose: Read in the tag contents into a data block
Args: size - # of bytes in tag, pIO - IO object to read tag from
Return: true = successful, false = failure
Reimplemented from CIccTag.
References CIccIO::Read16(), and CIccIO::Read32().
void CIccTagDateTime::SetDateTime (icDateTimeNumber nDateTime) inline
icValidateStatus CIccTagDateTime::Validate (icTagSignature sig, std::string & sReport, const CIccProfile * pProfile = NULL) const virtual
Name: CIccTagDateTime::Validate
Purpose: Check tag data validity.
Args: sig = signature of tag being validated, sReport = String to add report information to
Return: icValidateStatusOK if valid, or other error status.
Reimplemented from CIccTag.
References CIccInfo::CheckData(), icMaxStatus(), and CIccTag::Validate().
bool CIccTagDateTime::Write (CIccIO * pIO) virtual
Name: CIccTagDateTime::Write
Purpose: Write the tag to a file
Args: pIO - The IO object to write tag to.
Return: true = succesful, false = failure
Reimplemented from CIccTag.
References CIccIO::Write16(), and CIccIO::Write32().
Member Data Documentation
icDateTimeNumber CIccTagDateTime::m_DateTime protected
Referenced by CIccTagDateTime(), and operator=().
The documentation for this class was generated from the following files:
IccTagBasic.h
IccTagBasic.cpp