CIccTagLut8 Class Reference
CIccTagLut8 Class Reference
#include <IccTagLut.h>
Public Member Functions
CIccTagLut8 ()
CIccTagLut8 (const CIccTagLut8 &ITL)
CIccTagLut8 & operator= (const CIccTagLut8 &ITL)
virtual CIccTag * NewCopy () const
virtual ~CIccTagLut8 ()
virtual icTagTypeSignature GetType () const
virtual icUInt8Number GetPrecision ()
bool Read (icUInt32Number size, CIccIO *pIO)
bool Write (CIccIO *pIO)
virtual void SetColorSpaces (icColorSpaceSignature csInput, icColorSpaceSignature csOutput)
virtual icValidateStatus Validate (icTagSignature sig, std::string &sReport, const CIccProfile *pProfile=NULL) const
Public Member Functions inherited from CIccMBB
CIccMBB ()
CIccMBB (const CIccMBB &IMBB)
CIccMBB & operator= (const CIccMBB &IMBB)
virtual ~CIccMBB ()
virtual bool IsMBBType ()
virtual bool IsInputMatrix ()
virtual bool UseLegacyPCS () const
bool IsInputB ()
bool SwapMBCurves ()
void Cleanup ()
void Init (icUInt8Number nInputChannels, icUInt8Number nOutputChannels)
icUInt8Number InputChannels () const
icUInt8Number OutputChannels () const
virtual void Describe (std::string &sDescription)
LPIccCurve * NewCurvesA ()
CIccCLUT * NewCLUT (icUInt8Number nGridPoints, icUInt8Number nPrecision=2)
CIccCLUT * NewCLUT (icUInt8Number *pGridPoints, icUInt8Number nPrecision=2)
CIccMatrix * NewMatrix ()
LPIccCurve * NewCurvesM ()
LPIccCurve * NewCurvesB ()
CIccMatrix * GetMatrix () const
CIccCLUT * GetCLUT () const
LPIccCurve * GetCurvesA () const
LPIccCurve * GetCurvesB () const
LPIccCurve * GetCurvesM () const
CIccCLUT * SetCLUT (CIccCLUT *clut)
Public Member Functions inherited from CIccTag
CIccTag ()
virtual ~CIccTag ()
virtual bool IsArrayType ()
virtual const icChar * GetClassName () const
virtual IIccExtensionTag * GetExtension ()
virtual bool IsSupported ()
Protected Attributes
icUInt8Number m_nReservedByte
icS15Fixed16Number m_XYZMatrix [9]
Protected Attributes inherited from CIccMBB
bool m_bInputMatrix
bool m_bUseMCurvesAsBCurves
icUInt8Number m_nInput
icUInt8Number m_nOutput
icColorSpaceSignature m_csInput
icColorSpaceSignature m_csOutput
LPIccCurve * m_CurvesA
CIccCLUT * m_CLUT
CIccMatrix * m_Matrix
LPIccCurve * m_CurvesM
LPIccCurve * m_CurvesB
Additional Inherited Members
Static Public Member Functions inherited from CIccTag
static CIccTag * Create (icTagTypeSignature sig)
Public Attributes inherited from CIccTag
icUInt32Number m_nReserved
Detailed Description
Class: CIccTagLut8
Purpose: The Lut8 tag type
Constructor & Destructor Documentation
CIccTagLut8::CIccTagLut8 ()
Name: CIccTagLut8::CIccTagLut8
Purpose: Constructor
References icDtoF(), m_nReservedByte, and m_XYZMatrix.
CIccTagLut8::CIccTagLut8 (const CIccTagLut8 & ITL)
Name: CIccTagLut8::CIccTagLut8
Purpose: Copy Constructor
Args: ITL = The CIccTagLut8 object to be copied
References m_nReservedByte, and m_XYZMatrix.
CIccTagLut8::~CIccTagLut8 () virtual
Name: CIccTagLut8::~CIccTagLut8
Purpose: Destructor
Member Function Documentation
virtual icUInt8Number CIccTagLut8::GetPrecision () inline virtual
Reimplemented from CIccMBB.
virtual icTagTypeSignature CIccTagLut8::GetType () const inline virtual
Function: GetType()
Purpose: Get Tag Type. Each derived tag will implement it's own GetType() function.
Reimplemented from CIccTag.
References icSigLut8Type.
Referenced by Read(), Validate(), and Write().
virtual CIccTag* CIccTagLut8::NewCopy () const inline virtual
Function: NewCopy(sDescription) Each derived tag will implement it's own NewCopy() function.
Parameter(s): none
Returns a new CIccTag object that is a copy of this object.
Reimplemented from CIccMBB.
CIccTagLut8 & CIccTagLut8::operator= (const CIccTagLut8 & ITL)
Name: CIccTagLut8::operator=
Purpose: Copy Operator
Args: ITL = The CIccTagLut8 object to be copied
References m_XYZMatrix, and CIccMBB::operator=().
bool CIccTagLut8::Read (icUInt32Number size, CIccIO * pIO) virtual
Name: CIccTagLut8::Read
Purpose: Read in the tag contents into a data block
Args: size - # of bytes in tag, pIO - IO object to read tag from
Return: true = successful, false = failure
Reimplemented from CIccTag.
References CIccTag::Create(), GetType(), icSigCurveType, CIccCLUT::Init(), CIccMBB::m_CLUT, CIccMBB::m_nInput, CIccMBB::m_nOutput, CIccTag::m_nReserved, m_nReservedByte, m_XYZMatrix, CIccMBB::NewCurvesA(), CIccMBB::NewCurvesB(), CIccIO::Read32(), CIccIO::Read8(), CIccIO::Read8Float(), CIccCLUT::ReadData(), CIccTagCurve::SetSize(), and CIccIO::Tell().
void CIccTagLut8::SetColorSpaces (icColorSpaceSignature csInput, icColorSpaceSignature csOutput) virtual
Name: CIccTagLut8::SetColorSpaces
Purpose: Sets the input and output color spaces
Args: csInput = input color space signature, csOutput = output color space signature
Reimplemented from CIccMBB.
References CIccTag::Create(), icDtoF(), icFtoD(), icSigCurveType, icSigXYZData, CIccMBB::IsInputMatrix(), CIccMatrix::m_bUseConstants, CIccMBB::m_bUseMCurvesAsBCurves, CIccMBB::m_CurvesB, CIccMBB::m_CurvesM, CIccMatrix::m_e, CIccMBB::m_Matrix, CIccMBB::m_nInput, m_XYZMatrix, CIccMBB::NewCurvesB(), CIccMBB::NewMatrix(), CIccMBB::SetColorSpaces(), and CIccTagCurve::SetSize().
icValidateStatus CIccTagLut8::Validate (icTagSignature sig, std::string & sReport, const CIccProfile * pProfile = NULL) const virtual
Name: CIccTagLut8::Validate
Purpose: Check tag data validity.
Args: sig = signature of tag being validated, sReport = String to add report information to
Return: icValidateStatusOK if valid, or other error status.
Reimplemented from CIccMBB.
References icHeader::colorSpace, CIccInfo::GetSigName(), CIccTagCurve::GetSize(), GetType(), icGetSpaceSamples(), icMaxStatus(), icSigAToB0Tag, icSigAToB1Tag, icSigAToB2Tag, icSigBToA0Tag, icSigBToA1Tag, icSigBToA2Tag, icSigCurveType, icSigGamutTag, icValidateCriticalError, icValidateCriticalErrorMsg, icValidateWarning, icValidateWarningMsg, CIccMBB::m_CurvesA, CIccMBB::m_CurvesB, CIccProfile::m_Header, CIccMBB::m_Matrix, m_XYZMatrix, icHeader::pcs, CIccMatrix::Validate(), and CIccMBB::Validate().
bool CIccTagLut8::Write (CIccIO * pIO) virtual
Name: CIccTagLut8::Write
Purpose: Write the tag to a file
Args: pIO - The IO object to write tag to.
Return: true = succesful, false = failure
Reimplemented from CIccTag.
References CIccTagCurve::Apply(), F, CIccTagCurve::GetSize(), GetType(), CIccCLUT::GridPoints(), icDtoF(), icSigCurveType, CIccMBB::m_bUseMCurvesAsBCurves, CIccMBB::m_CLUT, CIccMBB::m_CurvesA, CIccMBB::m_CurvesB, CIccMBB::m_CurvesM, CIccMatrix::m_e, CIccMBB::m_Matrix, CIccMBB::m_nInput, CIccMBB::m_nOutput, CIccTag::m_nReserved, m_nReservedByte, CIccIO::Write32(), CIccIO::Write8(), CIccIO::Write8Float(), and CIccCLUT::WriteData().
Member Data Documentation
icUInt8Number CIccTagLut8::m_nReservedByte protected
Referenced by CIccTagLut8(), Read(), and Write().
icS15Fixed16Number CIccTagLut8::m_XYZMatrix[9] protected
Referenced by CIccTagLut8(), operator=(), Read(), SetColorSpaces(), and Validate().
The documentation for this class was generated from the following files:
IccTagLut.h
IccTagLut.cpp