CIccTagResponseCurveSet16 Class Reference
CIccTagResponseCurveSet16 Class Reference
#include <IccTagBasic.h>
Public Member Functions
CIccTagResponseCurveSet16 ()
CIccTagResponseCurveSet16 (const CIccTagResponseCurveSet16 &ITRCS)
CIccTagResponseCurveSet16 & operator= (const CIccTagResponseCurveSet16 &RespCurveSet16Tag)
virtual CIccTag * NewCopy () const
virtual ~CIccTagResponseCurveSet16 ()
virtual icTagTypeSignature GetType () const
virtual const icChar * GetClassName () const
virtual bool Read (icUInt32Number size, CIccIO *pIO)
virtual bool Write (CIccIO *pIO)
virtual void Describe (std::string &sDescription)
void SetNumChannels (icUInt16Number nChannels)
icUInt16Number GetNumChannels () const
CIccResponseCurveStruct * NewResponseCurves (icMeasurementUnitSig sig)
CIccResponseCurveStruct * GetResponseCurves (icMeasurementUnitSig sig)
CIccResponseCurveStruct * GetFirstCurves ()
CIccResponseCurveStruct * GetNextCurves ()
icUInt16Number GetNumResponseCurveTypes () const
virtual icValidateStatus Validate (icTagSignature sig, std::string &sReport, const CIccProfile *pProfile=NULL) const
Public Member Functions inherited from CIccTag
CIccTag ()
virtual ~CIccTag ()
virtual bool IsArrayType ()
virtual bool IsMBBType ()
virtual IIccExtensionTag * GetExtension ()
virtual bool IsSupported ()
Protected Attributes
CIccResponseCurveSet * m_ResponseCurves
icUInt16Number m_nChannels
CIccResponseCurveSetIter * m_Curve
Additional Inherited Members
Static Public Member Functions inherited from CIccTag
static CIccTag * Create (icTagTypeSignature sig)
Public Attributes inherited from CIccTag
icUInt32Number m_nReserved
Detailed Description
Class: CIccTagResponseCurveSet16
Purpose: The responseCurveSet16 Tag type
Constructor & Destructor Documentation
CIccTagResponseCurveSet16::CIccTagResponseCurveSet16 ()
Name: CIccTagResponseCurveSet16::CIccTagResponseCurveSet16
Purpose: Constructor
CIccTagResponseCurveSet16::CIccTagResponseCurveSet16 (const CIccTagResponseCurveSet16 & ITRCS)
Name: CIccTagResponseCurveSet16::CIccTagResponseCurveSet16
Purpose: Copy Constructor
Args: ITRCS = The CIccTagResponseCurveSet16 object to be copied
References m_Curve, m_nChannels, and m_ResponseCurves.
CIccTagResponseCurveSet16::~CIccTagResponseCurveSet16 () virtual
Name: CIccTagResponseCurveSet16::~CIccTagResponseCurveSet16
Purpose: Destructor
Member Function Documentation
void CIccTagResponseCurveSet16::Describe (std::string & sDescription) virtual
Name: CIccTagResponseCurveSet16::Describe
Purpose: Dump data associated with the tag to a string
Args: sDescription - string to concatenate tag dump to
Reimplemented from CIccTag.
virtual const icChar* CIccTagResponseCurveSet16::GetClassName () const inline virtual
Reimplemented from CIccTag.
CIccResponseCurveStruct * CIccTagResponseCurveSet16::GetFirstCurves ()
Name: CIccTagResponseCurveSet16::GetFirstCurves
Purpose: Returns pointer to the first set of response curves in the list.
References CIccResponseCurveStruct::GetThis().
CIccResponseCurveStruct * CIccTagResponseCurveSet16::GetNextCurves ()
Name: CIccTagResponseCurveSet16::GetNextCurves
Purpose: Serves as an iterator for the list containing response curves. GetFirstCurves() must be called before calling this function.
References CIccResponseCurveStruct::GetThis().
icUInt16Number CIccTagResponseCurveSet16::GetNumChannels () const inline
icUInt16Number CIccTagResponseCurveSet16::GetNumResponseCurveTypes () const
Name: CIccTagResponseCurveSet16::GetNumResponseCurveTypes
Purpose: Get the number of response curve types.
CIccResponseCurveStruct * CIccTagResponseCurveSet16::GetResponseCurves (icMeasurementUnitSig sig)
Name: CIccTagResponseCurveSet16::GetResponseCurves
Purpose: Returns pointer to the requested set of response curves
Args: sig = measurement unit signature of the response curve set desired
virtual icTagTypeSignature CIccTagResponseCurveSet16::GetType () const inline virtual
Function: GetType()
Purpose: Get Tag Type. Each derived tag will implement it's own GetType() function.
Reimplemented from CIccTag.
References icSigResponseCurveSet16Type.
virtual CIccTag* CIccTagResponseCurveSet16::NewCopy () const inline virtual
Function: NewCopy(sDescription) Each derived tag will implement it's own NewCopy() function.
Parameter(s): none
Returns a new CIccTag object that is a copy of this object.
Reimplemented from CIccTag.
CIccResponseCurveStruct * CIccTagResponseCurveSet16::NewResponseCurves (icMeasurementUnitSig sig)
Name: CIccTagResponseCurveSet16::NewResponseCurves
Purpose: Creates and adds a new set of response curves to the list. SetNumChannels() must be called before calling this function.
Args: sig = measurement unit signature
CIccTagResponseCurveSet16 & CIccTagResponseCurveSet16::operator= (const CIccTagResponseCurveSet16 & RespCurveSet16Tag)
Name: CIccTagResponseCurveSet16::operator=
Purpose: Copy Operator
Args: RespCurveSet16Tag = The CIccTagResponseCurveSet16 object to be copied
References m_Curve, m_nChannels, and m_ResponseCurves.
bool CIccTagResponseCurveSet16::Read (icUInt32Number size, CIccIO * pIO) virtual
Name: CIccTagResponseCurveSet16::Read
Purpose: Read in the tag contents into a data block
Args: size - # of bytes in tag, pIO - IO object to read tag from
Return: true = successful, false = failure
Reimplemented from CIccTag.
References CIccResponseCurveStruct::Read(), CIccIO::Read16(), and CIccIO::Read32().
void CIccTagResponseCurveSet16::SetNumChannels (icUInt16Number nChannels)
Name: CIccTagResponseCurveSet16::SetNumChannels
Purpose: Sets the number of channels. This will delete any prior Response curves from the set.
Args: nChannels = number of channels
icValidateStatus CIccTagResponseCurveSet16::Validate (icTagSignature sig, std::string & sReport, const CIccProfile * pProfile = NULL) const virtual
Name: CIccTagResponseCurveSet16::Validate
Purpose: Check tag data validity.
Args: sig = signature of tag being validated, sReport = String to add report information to
Return: icValidateStatusOK if valid, or other error status.
Reimplemented from CIccTag.
References icHeader::colorSpace, CIccInfo::GetSigName(), icGetSpaceSamples(), icMaxStatus(), icValidateWarning, icValidateWarningMsg, CIccProfile::m_Header, and CIccTag::Validate().
bool CIccTagResponseCurveSet16::Write (CIccIO * pIO) virtual
Name: CIccTagResponseCurveSet16::Write
Purpose: Write the tag to a file
Args: pIO - The IO object to write tag to.
Return: true = succesful, false = failure
Reimplemented from CIccTag.
References CIccIO::GetLength(), icSeekSet, CIccIO::Seek(), CIccIO::Write16(), and CIccIO::Write32().
Member Data Documentation
CIccResponseCurveSetIter* CIccTagResponseCurveSet16::m_Curve protected
Referenced by CIccTagResponseCurveSet16(), and operator=().
icUInt16Number CIccTagResponseCurveSet16::m_nChannels protected
Referenced by CIccTagResponseCurveSet16(), and operator=().
CIccResponseCurveSet* CIccTagResponseCurveSet16::m_ResponseCurves protected
Referenced by CIccTagResponseCurveSet16(), and operator=().
The documentation for this class was generated from the following files:
IccTagBasic.h
IccTagBasic.cpp