CIccUTF16String Class Reference
CIccUTF16String Class Reference
#include <IccUtil.h>
Public Member Functions
CIccUTF16String ()
CIccUTF16String (const icUInt16Number *uzStr)
CIccUTF16String (const char *szStr)
CIccUTF16String (const CIccUTF16String &str)
virtual ~CIccUTF16String ()
void Clear ()
bool Empty () const
size_t Size () const
void Resize (size_t len)
CIccUTF16String & operator= (const CIccUTF16String &wstr)
CIccUTF16String & operator= (const char *szStr)
CIccUTF16String & operator= (const icUInt16Number *uzStr)
bool operator== (const CIccUTF16String &str) const
icUInt16Number operator[] (size_t nIndex) const
const icUInt16Number * c_str () const
void FromUtf8 (const char *szStr, size_t sizeSrc=0)
const char * ToUtf8 (std::string &buf) const
void FromWString (const std::wstring &buf)
const wchar_t * ToWString (std::wstring &buf) const
Static Public Member Functions
static size_t WStrlen (const icUInt16Number *uzStr)
Static Protected Member Functions
static size_t AllocSize (size_t n)
Protected Attributes
size_t m_alloc
size_t m_len
icUInt16Number * m_str
Detailed Description
Type: Class
Purpose: This is a UTF16 string class that provides conversions
Constructor & Destructor Documentation
CIccUTF16String::CIccUTF16String ()
CIccUTF16String::CIccUTF16String (const icUInt16Number * uzStr)
CIccUTF16String::CIccUTF16String (const char * szStr)
References icConvertUTF8toUTF16(), and lenientConversion.
CIccUTF16String::CIccUTF16String (const CIccUTF16String & str)
References m_alloc, m_len, and m_str.
CIccUTF16String::~CIccUTF16String () virtual
Member Function Documentation
static size_t CIccUTF16String::AllocSize (size_t n) inline static protected
const icUInt16Number* CIccUTF16String::c_str () const inline
Referenced by icUtf8ToUtf16(), and CIccTagDict::Write().
void CIccUTF16String::Clear ()
Referenced by CIccTagDict::Read().
bool CIccUTF16String::Empty () const inline
Referenced by CIccTagDict::Set(), and CIccDictEntry::SetValue().
void CIccUTF16String::FromUtf8 (const char * szStr, size_t sizeSrc = 0)
References icConvertUTF8toUTF16(), and lenientConversion.
Referenced by icUtf8ToUtf16().
void CIccUTF16String::FromWString (const std::wstring & buf)
References icConvertUTF32toUTF16(), and lenientConversion.
CIccUTF16String & CIccUTF16String::operator= (const CIccUTF16String & wstr)
References m_alloc, m_len, and m_str.
CIccUTF16String & CIccUTF16String::operator= (const char * szStr)
CIccUTF16String & CIccUTF16String::operator= (const icUInt16Number * uzStr)
bool CIccUTF16String::operator== (const CIccUTF16String & str) const
References m_len, and m_str.
icUInt16Number CIccUTF16String::operator[] (size_t nIndex) const inline
void CIccUTF16String::Resize (size_t len)
size_t CIccUTF16String::Size () const inline
Referenced by CIccTagDict::Write().
const char * CIccUTF16String::ToUtf8 (std::string & buf) const
References icUtf16ToUtf8().
Referenced by CIccDictEntry::Describe().
const wchar_t * CIccUTF16String::ToWString (std::wstring & buf) const
References icConvertUTF16toUTF32(), and lenientConversion.
size_t CIccUTF16String::WStrlen (const icUInt16Number * uzStr) static
Referenced by icUtf16ToUtf8().
Member Data Documentation
size_t CIccUTF16String::m_alloc protected
Referenced by CIccUTF16String(), and operator=().
size_t CIccUTF16String::m_len protected
Referenced by CIccUTF16String(), operator=(), and operator==().
icUInt16Number* CIccUTF16String::m_str protected
Referenced by CIccUTF16String(), operator=(), and operator==().
The documentation for this class was generated from the following files:
IccUtil.h
IccUtil.cpp