CIccMultiProcessElement Class Reference
CIccMultiProcessElement Class Reference abstract
#include <IccTagMPE.h>
Public Member Functions
CIccMultiProcessElement ()
virtual ~CIccMultiProcessElement ()
virtual CIccMultiProcessElement * NewCopy () const =0
virtual icElemTypeSignature GetType () const =0
virtual const icChar * GetClassName () const =0
virtual icUInt16Number NumInputChannels () const
virtual icUInt16Number NumOutputChannels () const
virtual bool IsSupported ()
virtual void Describe (std::string &sDescription)=0
virtual bool Read (icUInt32Number size, CIccIO *pIO)=0
virtual bool Write (CIccIO *pIO)=0
virtual bool Begin (icElemInterp nIterp=icElemInterpLinear, CIccTagMultiProcessElement *pMPE=NULL)=0
virtual CIccApplyMpe * GetNewApply (CIccApplyTagMpe *pApplyTag)
virtual void Apply (CIccApplyMpe *pApply, icFloatNumber *pDestPixel, const icFloatNumber *pSrcPixel) const =0
virtual icValidateStatus Validate (icTagSignature sig, std::string &sReport, const CIccTagMultiProcessElement *pMPE=NULL) const =0
virtual bool IsAcs ()
virtual icAcsSignature GetBAcsSig ()
virtual icAcsSignature GetEAcsSig ()
virtual IIccExtensionMpe * GetExtension ()
Static Public Member Functions
static CIccMultiProcessElement * Create (icElemTypeSignature sig)
Public Attributes
icUInt32Number m_nReserved
Protected Attributes
icUInt16Number m_nInputChannels
icUInt16Number m_nOutputChannels
Detailed Description
Class: CIccMultiProcessElement
Purpose: Base Class for Multi Process Elements
Constructor & Destructor Documentation
CIccMultiProcessElement::CIccMultiProcessElement () inline
virtual CIccMultiProcessElement::~CIccMultiProcessElement () inline virtual
Member Function Documentation
virtual void CIccMultiProcessElement::Apply (CIccApplyMpe * pApply, icFloatNumber * pDestPixel, const icFloatNumber * pSrcPixel) const pure virtual
Implemented in CIccMpeCLUT, CIccMpeMatrix, CIccMpeCurveSet, CIccMpeUnknown, and CIccMpeAcs.
Referenced by CIccTagMultiProcessElement::Apply().
virtual bool CIccMultiProcessElement::Begin (icElemInterp nIterp = icElemInterpLinear, CIccTagMultiProcessElement * pMPE = NULL) pure virtual
Implemented in CIccMpeCLUT, CIccMpeMatrix, CIccMpeCurveSet, CIccMpeUnknown, and CIccMpeAcs.
Referenced by CIccTagMultiProcessElement::Begin().
CIccMultiProcessElement * CIccMultiProcessElement::Create (icElemTypeSignature sig) static
Name: CIccMultiProcessElement::Create
Purpose:
Args:
Return:
References CIccMpeCreator::CreateElement().
Referenced by CIccTagMultiProcessElement::Read().
virtual void CIccMultiProcessElement::Describe (std::string & sDescription) pure virtual
Implemented in CIccMpeCLUT, CIccMpeMatrix, CIccMpeCurveSet, CIccMpeUnknown, and CIccMpeAcs.
virtual icAcsSignature CIccMultiProcessElement::GetBAcsSig () inline virtual
Reimplemented in CIccMpeBAcs.
References icSigAcsZero.
virtual const icChar* CIccMultiProcessElement::GetClassName () const pure virtual
Implemented in CIccMpeCLUT, CIccMpeMatrix, CIccMpeCurveSet, CIccMpeUnknown, CIccMpeEAcs, and CIccMpeBAcs.
Referenced by CIccTagMultiProcessElement::Validate().
virtual icAcsSignature CIccMultiProcessElement::GetEAcsSig () inline virtual
Reimplemented in CIccMpeEAcs.
References icSigAcsZero.
virtual IIccExtensionMpe* CIccMultiProcessElement::GetExtension () inline virtual
CIccApplyMpe * CIccMultiProcessElement::GetNewApply (CIccApplyTagMpe * pApplyTag) virtual
Name: CIccMultiProcessElement::GetNewApply()
Purpose:
Args:
Return:
Referenced by CIccApplyTagMpe::AppendElem().
virtual icElemTypeSignature CIccMultiProcessElement::GetType () const pure virtual
Implemented in CIccMpeCLUT, CIccMpeMatrix, CIccMpeCurveSet, CIccMpeUnknown, CIccMpeEAcs, and CIccMpeBAcs.
virtual bool CIccMultiProcessElement::IsAcs () inline virtual
Reimplemented in CIccMpeAcs.
Referenced by CIccTagMultiProcessElement::Apply().
virtual bool CIccMultiProcessElement::IsSupported () inline virtual
Reimplemented in CIccMpeUnknown.
virtual CIccMultiProcessElement* CIccMultiProcessElement::NewCopy () const pure virtual
Implemented in CIccMpeCLUT, CIccMpeMatrix, CIccMpeCurveSet, CIccMpeUnknown, CIccMpeEAcs, and CIccMpeBAcs.
Referenced by CIccTagMultiProcessElement::CIccTagMultiProcessElement(), and CIccTagMultiProcessElement::operator=().
virtual icUInt16Number CIccMultiProcessElement::NumInputChannels () const inline virtual
virtual icUInt16Number CIccMultiProcessElement::NumOutputChannels () const inline virtual
Referenced by CIccTagMultiProcessElement::Begin(), and CIccTagMultiProcessElement::Validate().
virtual bool CIccMultiProcessElement::Read (icUInt32Number size, CIccIO * pIO) pure virtual
Implemented in CIccMpeCLUT, CIccMpeMatrix, CIccMpeCurveSet, CIccMpeUnknown, and CIccMpeAcs.
Referenced by CIccTagMultiProcessElement::Read().
icValidateStatus CIccMultiProcessElement::Validate (icTagSignature sig, std::string & sReport, const CIccTagMultiProcessElement * pMPE = NULL) const pure virtual
Name: CIccProcessElement::Validate
Purpose:
Args:
Return:
Implemented in CIccMpeCLUT, CIccMpeMatrix, CIccMpeCurveSet, CIccMpeUnknown, and CIccMpeAcs.
References CIccInfo::GetSigName(), icValidateNonCompliant, icValidateNonCompliantMsg, and icValidateOK.
Referenced by CIccMpeAcs::Validate(), CIccMpeCurveSet::Validate(), CIccMpeMatrix::Validate(), CIccTagMultiProcessElement::Validate(), and CIccMpeCLUT::Validate().
virtual bool CIccMultiProcessElement::Write (CIccIO * pIO) pure virtual
Implemented in CIccMpeCLUT, CIccMpeMatrix, CIccMpeCurveSet, CIccMpeUnknown, and CIccMpeAcs.
Member Data Documentation
icUInt16Number CIccMultiProcessElement::m_nInputChannels protected
Referenced by CIccMpeBAcs::CIccMpeBAcs(), CIccMpeCLUT::CIccMpeCLUT(), CIccMpeCurveSet::CIccMpeCurveSet(), CIccMpeEAcs::CIccMpeEAcs(), CIccMpeMatrix::CIccMpeMatrix(), CIccMpeBAcs::operator=(), CIccMpeEAcs::operator=(), CIccMpeCurveSet::operator=(), CIccMpeMatrix::operator=(), and CIccMpeCLUT::operator=().
icUInt16Number CIccMultiProcessElement::m_nOutputChannels protected
Referenced by CIccMpeBAcs::CIccMpeBAcs(), CIccMpeCLUT::CIccMpeCLUT(), CIccMpeEAcs::CIccMpeEAcs(), CIccMpeMatrix::CIccMpeMatrix(), CIccMpeBAcs::operator=(), CIccMpeEAcs::operator=(), CIccMpeMatrix::operator=(), and CIccMpeCLUT::operator=().
icUInt32Number CIccMultiProcessElement::m_nReserved
Referenced by CIccMpeBAcs::CIccMpeBAcs(), CIccMpeCLUT::CIccMpeCLUT(), CIccMpeCurveSet::CIccMpeCurveSet(), CIccMpeEAcs::CIccMpeEAcs(), CIccMpeMatrix::CIccMpeMatrix(), CIccMpeBAcs::operator=(), CIccMpeEAcs::operator=(), CIccMpeMatrix::operator=(), and CIccMpeCLUT::operator=().
The documentation for this class was generated from the following files:
IccTagMPE.h
IccTagMPE.cpp