CIccTagParametricCurve Class Reference
CIccTagParametricCurve Class Reference
#include <IccTagLut.h>
Public Member Functions
CIccTagParametricCurve ()
CIccTagParametricCurve (const CIccTagParametricCurve &ITPC)
CIccTagParametricCurve & operator= (const CIccTagParametricCurve &ParamCurveTag)
virtual CIccTag * NewCopy () const
virtual ~CIccTagParametricCurve ()
virtual icTagTypeSignature GetType () const
virtual const icChar * GetClassName () const
virtual void Describe (std::string &sDescription)
virtual void DumpLut (std::string &sDescription, const icChar *szName, icColorSpaceSignature csSig, int nIndex)
virtual bool Read (icUInt32Number size, CIccIO *pIO)
virtual bool Write (CIccIO *pIO)
bool SetFunctionType (icUInt16Number nFunctionType)
icUInt16Number GetFunctionType () const
icUInt16Number GetNumParam () const
icFloatNumber * GetParams () const
icFloatNumber Param (int index) const
icFloatNumber & operator[] (int index)
virtual icFloatNumber Apply (icFloatNumber v)
virtual icValidateStatus Validate (icTagSignature sig, std::string &sReport, const CIccProfile *pProfile=NULL) const
virtual bool IsIdentity ()
Public Member Functions inherited from CIccCurve
CIccCurve ()
virtual ~CIccCurve ()
virtual void Begin ()
icFloatNumber Find (icFloatNumber v)
Public Member Functions inherited from CIccTag
CIccTag ()
virtual ~CIccTag ()
virtual bool IsArrayType ()
virtual bool IsMBBType ()
virtual IIccExtensionTag * GetExtension ()
virtual bool IsSupported ()
Public Attributes
icUInt16Number m_nReserved2
Public Attributes inherited from CIccTag
icUInt32Number m_nReserved
Protected Member Functions
icFloatNumber DoApply (icFloatNumber v) const
Protected Member Functions inherited from CIccCurve
icFloatNumber Find (icFloatNumber v, icFloatNumber p0, icFloatNumber v0, icFloatNumber p1, icFloatNumber v1)
Protected Attributes
icUInt16Number m_nFunctionType
icUInt16Number m_nNumParam
icFloatNumber * m_dParam
Additional Inherited Members
Static Public Member Functions inherited from CIccTag
static CIccTag * Create (icTagTypeSignature sig)
Detailed Description
Class: CIccTagParametricCurve
Purpose: The parametric curve type tag
Constructor & Destructor Documentation
CIccTagParametricCurve::CIccTagParametricCurve ()
Name: CIccTagParametricCurve::CIccTagParametricCurve
Purpose: Constructor
CIccTagParametricCurve::CIccTagParametricCurve (const CIccTagParametricCurve & ITPC)
Name: CIccTagParametricCurve::CIccTagParametricCurve
Purpose: Copy Constructor
Args: ITPC = The CIccTagParametricCurve object to be copied
References m_dParam, m_nFunctionType, and m_nNumParam.
CIccTagParametricCurve::~CIccTagParametricCurve () virtual
Name: CIccTagParametricCurve::~CIccTagParametricCurve
Purpose: Destructor
Member Function Documentation
virtual icFloatNumber CIccTagParametricCurve::Apply (icFloatNumber v) inline virtual
Reimplemented from CIccCurve.
void CIccTagParametricCurve::Describe (std::string & sDescription) virtual
Name: CIccTagParametricCurve::Describe
Purpose: Dump data associated with the tag to a string
Args: sDescription - string to concatenate tag dump to
Reimplemented from CIccTag.
icFloatNumber CIccTagParametricCurve::DoApply (icFloatNumber X) const protected
Name: CIccTagParametricCurve::Apply
Purpose: Applies the curve to the value passed.
Args: x = value to be passed through the curve.
Return: The value modified by the curve.
void CIccTagParametricCurve::DumpLut (std::string & sDescription, const icChar * szName, icColorSpaceSignature csSig, int nIndex) virtual
Name: CIccTagParametricCurve::DumpLut
Purpose: Dump data associated with the tag to a string. Basically has the same function as Describe()
Args: sDescription = string to concatenate tag dump to, szName = name of the curve to be printed, csSig = color space signature of the curve data, nIndex = the channel number of color space
Reimplemented from CIccCurve.
virtual const icChar* CIccTagParametricCurve::GetClassName () const inline virtual
Reimplemented from CIccTag.
icUInt16Number CIccTagParametricCurve::GetFunctionType () const inline
icUInt16Number CIccTagParametricCurve::GetNumParam () const inline
icFloatNumber* CIccTagParametricCurve::GetParams () const inline
virtual icTagTypeSignature CIccTagParametricCurve::GetType () const inline virtual
Function: GetType()
Purpose: Get Tag Type. Each derived tag will implement it's own GetType() function.
Reimplemented from CIccTag.
References icSigParametricCurveType.
bool CIccTagParametricCurve::IsIdentity () virtual
Name: CIccTagParametricCurve::IsIdentity
Purpose: Checks if this is an identity curve.
Return: true if the curve is an identity
Reimplemented from CIccCurve.
virtual CIccTag* CIccTagParametricCurve::NewCopy () const inline virtual
Function: NewCopy(sDescription) Each derived tag will implement it's own NewCopy() function.
Parameter(s): none
Returns a new CIccTag object that is a copy of this object.
Reimplemented from CIccCurve.
CIccTagParametricCurve & CIccTagParametricCurve::operator= (const CIccTagParametricCurve & ParamCurveTag)
Name: CIccTagParametricCurve::operator=
Purpose: Copy Operator
Args: ParamCurveTag = The CIccTagParametricCurve object to be copied
References m_dParam, m_nFunctionType, and m_nNumParam.
icFloatNumber& CIccTagParametricCurve::operator[] (int index) inline
icFloatNumber CIccTagParametricCurve::Param (int index) const inline
bool CIccTagParametricCurve::Read (icUInt32Number size, CIccIO * pIO) virtual
Name: CIccTagParametricCurve::Read
Purpose: Read in the tag contents into a data block
Args: size - # of bytes in tag, pIO - IO object to read tag from
Return: true = successful, false = failure
Reimplemented from CIccTag.
References icFtoD(), CIccIO::Read16(), and CIccIO::Read32().
bool CIccTagParametricCurve::SetFunctionType (icUInt16Number nFunctionType)
Name: CIccTagParametricCurve::SetFunctionType
Purpose: Sets the type of the function the Parametric curve represents
Args: nFunctionType = the type of the function encoded as 0-4
Return: always true!!
icValidateStatus CIccTagParametricCurve::Validate (icTagSignature sig, std::string & sReport, const CIccProfile * pProfile = NULL) const virtual
Name: CIccTagParametricCurve::Validate
Purpose: Check tag data validity.
Args: sig = signature of tag being validated, sReport = String to add report information to
Return: icValidateStatusOK if valid, or other error status.
Reimplemented from CIccTag.
References CIccInfo::GetSigName(), icMaxStatus(), icSigBlueTRCTag, icSigGrayTRCTag, icSigGreenTRCTag, icSigRedTRCTag, icValidateCriticalError, icValidateCriticalErrorMsg, icValidateNonCompliant, icValidateNonCompliantMsg, icValidateWarning, icValidateWarningMsg, and CIccTag::Validate().
bool CIccTagParametricCurve::Write (CIccIO * pIO) virtual
Name: CIccTagParametricCurve::Write
Purpose: Write the tag to a file
Args: pIO - The IO object to write tag to.
Return: true = succesful, false = failure
Reimplemented from CIccTag.
References CIccIO::Align32(), icDtoF(), CIccIO::Write16(), and CIccIO::Write32().
Member Data Documentation
icFloatNumber* CIccTagParametricCurve::m_dParam protected
Referenced by CIccTagParametricCurve(), and operator=().
icUInt16Number CIccTagParametricCurve::m_nFunctionType protected
Referenced by CIccTagParametricCurve(), and operator=().
icUInt16Number CIccTagParametricCurve::m_nNumParam protected
Referenced by CIccTagParametricCurve(), and operator=().
icUInt16Number CIccTagParametricCurve::m_nReserved2
The documentation for this class was generated from the following files:
IccTagLut.h
IccTagLut.cpp