CIccPCS Class Reference
CIccPCS Class Reference
#include <IccCmm.h>
Public Member Functions
CIccPCS ()
virtual ~CIccPCS ()
void Reset (icColorSpaceSignature StartSpace, bool bUseLegacyPCS=false)
virtual const icFloatNumber * Check (const icFloatNumber *SrcPixel, const CIccXform *pXform)
void CheckLast (icFloatNumber *SrcPixel, icColorSpaceSignature Space, bool bNoClip=false)
Static Public Member Functions
static void LabToXyz (icFloatNumber *Dst, const icFloatNumber *Src, bool bNoClip=false)
static void XyzToLab (icFloatNumber *Dst, const icFloatNumber *Src, bool bNoClip=false)
static void Lab2ToXyz (icFloatNumber *Dst, const icFloatNumber *Src, bool bNoClip=false)
static void XyzToLab2 (icFloatNumber *Dst, const icFloatNumber *Src, bool bNoClip=false)
static icFloatNumber NegClip (icFloatNumber v)
static icFloatNumber UnitClip (icFloatNumber v)
static void Lab2ToLab4 (icFloatNumber *Dst, const icFloatNumber *Src, bool bNoclip=false)
static void Lab4ToLab2 (icFloatNumber *Dst, const icFloatNumber *Src)
Protected Attributes
bool m_bIsV2Lab
icColorSpaceSignature m_Space
icFloatNumber m_Convert [3]
Detailed Description
Type: Class
Purpose: Independant PCS class to do PCS based calculations. This is a class for managing PCS colorspace transformations. There are two important categories V2 <-> V4, and Lab <-> XYZ.
Constructor & Destructor Documentation
CIccPCS::CIccPCS ()
Class CIccPCS Constructor
Purpose: This is a class constructor.
References icSigUnknownData.
virtual CIccPCS::~CIccPCS () inline virtual
Member Function Documentation
const icFloatNumber * CIccPCS::Check (const icFloatNumber * SrcPixel, const CIccXform * pXform) virtual
Name: CIccPCS::Check
Purpose: This is called before the apply of each profile's xform to adjust the PCS to the xform's needed PCS.
Args: SrcPixel = source pixel data (this may need adjusting), pXform = the xform that who's Apply function will shortly be called
Return: SrcPixel or ptr to adjusted pixel data (we dont want to modify the source data).
References CIccXform::GetDstSpace(), CIccXform::GetSrcSpace(), icSigLabData, icSigXYZData, CIccXform::NoClipPCS(), and CIccXform::UseLegacyPCS().
Referenced by CIccApplyCmm::Apply(), and CIccApplyNamedColorCmm::Apply().
void CIccPCS::CheckLast (icFloatNumber * Pixel, icColorSpaceSignature DestSpace, bool bNoClip = false)
Name: CIccPCS::CheckLast
Purpose: Called after all xforms are applied to adjust PCS to final space if needed Note: space will always be V4.
Args: Pixel = Pixel data, DestSpace = destination color space bNoClip = indicates whether PCS should be clipped
References icSigLabData, and icSigXYZData.
Referenced by CIccApplyCmm::Apply(), and CIccApplyNamedColorCmm::Apply().
void CIccPCS::Lab2ToLab4 (icFloatNumber * Dst, const icFloatNumber * Src, bool bNoClip = false) static
Name: CIccPCS::Lab2ToLab4
Purpose: Convert version 2 Lab to version 4 Lab
Referenced by CIccCmm::ToInternalEncoding().
void CIccPCS::Lab2ToXyz (icFloatNumber * Dst, const icFloatNumber * Src, bool bNoClip = false) static
Name: CIccPCS::Lab2ToXyz
Purpose: Convert version 2 Lab to XYZ
Referenced by CIccXform::AdjustPCS().
void CIccPCS::Lab4ToLab2 (icFloatNumber * Dst, const icFloatNumber * Src) static
Name: CIccPCS::Lab4ToLab2
Purpose: Convert version 4 Lab to version 2 Lab
Referenced by CIccCmm::FromInternalEncoding().
void CIccPCS::LabToXyz (icFloatNumber * Dst, const icFloatNumber * Src, bool bNoClip = false) static
Name: CIccPCS::LabToXyz
Purpose: Convert Lab to XYZ
References icLabFromPcs(), icLabtoXYZ(), and icXyzToPcs().
Referenced by CIccXform::AdjustPCS().
icFloatNumber CIccPCS::NegClip (icFloatNumber v) static
Name: CIccPCS::NegClip
Purpose: Convert a double to an icUInt16Number with clipping of negative numbers
Referenced by CIccXform::AdjustPCS().
void CIccPCS::Reset (icColorSpaceSignature StartSpace, bool bUseLegacyPCS = false)
Name: CIccPCS::Reset
Purpose: This is called with the initial color space and a bool argument which is true if the PCS is version 2.
Args: Startpsace = Starting Colorspace bUseLegacyPCS = legacy PCS flag
References IsSpacePCS.
Referenced by CIccApplyCmm::Apply(), and CIccApplyNamedColorCmm::Apply().
icFloatNumber CIccPCS::UnitClip (icFloatNumber v) static
Name: CIccPCS::UnitClip
Purpose: Convert a double to an icUInt16Number with clipping
void CIccPCS::XyzToLab (icFloatNumber * Dst, const icFloatNumber * Src, bool bNoClip = false) static
Name: CIccPCS::XyzToLab
Purpose: Convert XYZ to Lab
References icLabToPcs(), icXyzFromPcs(), and icXYZtoLab().
Referenced by CIccXform::AdjustPCS(), and CIccXformMonochrome::Apply().
void CIccPCS::XyzToLab2 (icFloatNumber * Dst, const icFloatNumber * Src, bool bNoClip = false) static
Name: CIccPCS::XyzToLab2
Purpose: Convert XYZ to version 2 Lab
Referenced by CIccXform::AdjustPCS(), and CIccXformMonochrome::Apply().
Member Data Documentation
bool CIccPCS::m_bIsV2Lab protected
icFloatNumber CIccPCS::m_Convert[3] protected
icColorSpaceSignature CIccPCS::m_Space protected
The documentation for this class was generated from the following files:
IccCmm.h
IccCmm.cpp