CIccLocalizedUnicode Class Reference
CIccLocalizedUnicode Class Reference
#include <IccTagBasic.h>
Public Member Functions
CIccLocalizedUnicode ()
CIccLocalizedUnicode (const CIccLocalizedUnicode &ILU)
CIccLocalizedUnicode & operator= (const CIccLocalizedUnicode &UnicodeText)
virtual ~CIccLocalizedUnicode ()
icUInt32Number GetLength () const
icUInt16Number * GetBuf () const
icUInt32Number GetAnsiSize ()
const icChar * GetAnsi (icChar *szBuf, icUInt32Number nBufSize)
void SetSize (icUInt32Number)
void SetText (const icChar *szText, icLanguageCode nLanguageCode=icLanguageCodeEnglish, icCountryCode nRegionCode=icCountryCodeUSA)
void SetText (const icUInt16Number *sszUnicode16Text, icLanguageCode nLanguageCode=icLanguageCodeEnglish, icCountryCode nRegionCode=icCountryCodeUSA)
void SetText (const icUInt32Number *sszUnicode32Text, icLanguageCode nLanguageCode=icLanguageCodeEnglish, icCountryCode nRegionCode=icCountryCodeUSA)
const icChar * operator= (const icChar *szText)
const icUInt16Number * operator= (const icUInt16Number *sszText)
const icUInt32Number * operator= (const icUInt32Number *sszText)
Public Attributes
icLanguageCode m_nLanguageCode
icCountryCode m_nCountryCode
Protected Attributes
icUInt32Number m_nLength
icUInt16Number * m_pBuf
Detailed Description
Data Class: CIccLocalizedUnicode
Purpose: Implementation of a unicode string with language and region identifiers.
Constructor & Destructor Documentation
CIccLocalizedUnicode::CIccLocalizedUnicode ()
Name: CIccLocalizedUnicode::CIccLocalizedUnicode
Purpose: Constructor
CIccLocalizedUnicode::CIccLocalizedUnicode (const CIccLocalizedUnicode & ILU)
Name: CIccLocalizedUnicode::CIccLocalizedUnicode
Purpose: Copy Constructor
Args: ILU = The CIccLocalizedUnicode object to be copied
References GetBuf(), GetLength(), m_nCountryCode, and m_nLanguageCode.
CIccLocalizedUnicode::~CIccLocalizedUnicode () virtual
Name: CIccLocalizedUnicode::~CIccLocalizedUnicode
Purpose: Destructor
Member Function Documentation
const icChar * CIccLocalizedUnicode::GetAnsi (icChar * szBuf, icUInt32Number nBufSize)
Name: CIccLocalizedUnicode::GetAnsi
Purpose: Extracts the ANSI data buffer
Args: szBuf = pointer where the returned string buffer is to be stored nBufSize = size of the buffer to be extracted
Return: Pointer to the ANSI data string
icUInt32Number CIccLocalizedUnicode::GetAnsiSize ()
Name: CIccLocalizedUnicode::GetAnsiSize
Purpose: Returns the size of the ANSI data buffer
icUInt16Number* CIccLocalizedUnicode::GetBuf () const inline
Referenced by CIccLocalizedUnicode(), operator=(), and CIccTagMultiLocalizedUnicode::Read().
icUInt32Number CIccLocalizedUnicode::GetLength () const inline
Referenced by CIccLocalizedUnicode(), and operator=().
CIccLocalizedUnicode & CIccLocalizedUnicode::operator= (const CIccLocalizedUnicode & UnicodeText)
Name: CIccLocalizedUnicode::operator=
Purpose: Copy Operator
Args: UnicodeText = The CIccLocalizedUnicode object to be copied
References GetBuf(), GetLength(), m_nCountryCode, and m_nLanguageCode.
const icChar* CIccLocalizedUnicode::operator= (const icChar * szText) inline
const icUInt16Number* CIccLocalizedUnicode::operator= (const icUInt16Number * sszText) inline
const icUInt32Number* CIccLocalizedUnicode::operator= (const icUInt32Number * sszText) inline
void CIccLocalizedUnicode::SetSize (icUInt32Number nSize)
Name: CIccLocalizedUnicode::SetSize
Purpose: Sets the size of the string buffer.
Args: nSize - length of the string
Referenced by CIccTagMultiLocalizedUnicode::Read().
void CIccLocalizedUnicode::SetText (const icChar * szText, icLanguageCode nLanguageCode = icLanguageCodeEnglish, icCountryCode nRegionCode = icCountryCodeUSA)
Name: CIccLocalizedUnicode::SetText
Purpose: Allows text data associated with the tag to be set.
Args: szText = zero terminated string to put in tag, nLanguageCode = the language code type as defined by icLanguageCode, nRegionCode = the region code type as defined by icCountryCode
Referenced by CIccTagMultiLocalizedUnicode::SetText().
void CIccLocalizedUnicode::SetText (const icUInt16Number * sszUnicode16Text, icLanguageCode nLanguageCode = icLanguageCodeEnglish, icCountryCode nRegionCode = icCountryCodeUSA)
Name: CIccLocalizedUnicode::SetText
Purpose: Allows text data associated with the tag to be set.
Args: sszUnicode16Text = Unicode16 text to be set, nLanguageCode = the language code type as defined by icLanguageCode, nRegionCode = the region code type as defined by icCountryCode
void CIccLocalizedUnicode::SetText (const icUInt32Number * sszUnicode32Text, icLanguageCode nLanguageCode = icLanguageCodeEnglish, icCountryCode nRegionCode = icCountryCodeUSA)
Name: CIccLocalizedUnicode::SetText
Purpose: Allows text data associated with the tag to be set.
Args: sszUnicode32Text = Unicode32 text to be set, nLanguageCode = the language code type as defined by icLanguageCode, nRegionCode = the region code type as defined by icCountryCode
References icConvertUTF32toUTF16(), and lenientConversion.
Member Data Documentation
icCountryCode CIccLocalizedUnicode::m_nCountryCode
Referenced by CIccLocalizedUnicode(), operator=(), and CIccTagMultiLocalizedUnicode::Read().
icLanguageCode CIccLocalizedUnicode::m_nLanguageCode
Referenced by CIccLocalizedUnicode(), operator=(), and CIccTagMultiLocalizedUnicode::Read().
icUInt32Number CIccLocalizedUnicode::m_nLength protected
icUInt16Number* CIccLocalizedUnicode::m_pBuf protected
The documentation for this class was generated from the following files:
IccTagBasic.h
IccTagBasic.cpp