CIccTagLutAtoB Class Reference
CIccTagLutAtoB Class Reference
#include <IccTagLut.h>
Public Member Functions
CIccTagLutAtoB ()
CIccTagLutAtoB (const CIccTagLutAtoB &ITLA2B)
CIccTagLutAtoB & operator= (const CIccTagLutAtoB &ITLA2B)
virtual CIccTag * NewCopy () const
virtual ~CIccTagLutAtoB ()
virtual icTagTypeSignature GetType () const
bool Read (icUInt32Number size, CIccIO *pIO)
bool Write (CIccIO *pIO)
virtual icValidateStatus Validate (icTagSignature sig, std::string &sReport, const CIccProfile *pProfile=NULL) const
Public Member Functions inherited from CIccMBB
CIccMBB ()
CIccMBB (const CIccMBB &IMBB)
CIccMBB & operator= (const CIccMBB &IMBB)
virtual ~CIccMBB ()
virtual bool IsMBBType ()
virtual icUInt8Number GetPrecision ()
virtual bool IsInputMatrix ()
virtual bool UseLegacyPCS () const
bool IsInputB ()
bool SwapMBCurves ()
void Cleanup ()
void Init (icUInt8Number nInputChannels, icUInt8Number nOutputChannels)
icUInt8Number InputChannels () const
icUInt8Number OutputChannels () const
virtual void Describe (std::string &sDescription)
virtual void SetColorSpaces (icColorSpaceSignature csInput, icColorSpaceSignature csOutput)
LPIccCurve * NewCurvesA ()
CIccCLUT * NewCLUT (icUInt8Number nGridPoints, icUInt8Number nPrecision=2)
CIccCLUT * NewCLUT (icUInt8Number *pGridPoints, icUInt8Number nPrecision=2)
CIccMatrix * NewMatrix ()
LPIccCurve * NewCurvesM ()
LPIccCurve * NewCurvesB ()
CIccMatrix * GetMatrix () const
CIccCLUT * GetCLUT () const
LPIccCurve * GetCurvesA () const
LPIccCurve * GetCurvesB () const
LPIccCurve * GetCurvesM () const
CIccCLUT * SetCLUT (CIccCLUT *clut)
Public Member Functions inherited from CIccTag
CIccTag ()
virtual ~CIccTag ()
virtual bool IsArrayType ()
virtual const icChar * GetClassName () const
virtual IIccExtensionTag * GetExtension ()
virtual bool IsSupported ()
Protected Attributes
icUInt16Number m_nReservedWord
Protected Attributes inherited from CIccMBB
bool m_bInputMatrix
bool m_bUseMCurvesAsBCurves
icUInt8Number m_nInput
icUInt8Number m_nOutput
icColorSpaceSignature m_csInput
icColorSpaceSignature m_csOutput
LPIccCurve * m_CurvesA
CIccCLUT * m_CLUT
CIccMatrix * m_Matrix
LPIccCurve * m_CurvesM
LPIccCurve * m_CurvesB
Additional Inherited Members
Static Public Member Functions inherited from CIccTag
static CIccTag * Create (icTagTypeSignature sig)
Public Attributes inherited from CIccTag
icUInt32Number m_nReserved
Detailed Description
Class: CIccTagLutAtoB
Purpose: The LutA2B tag type
Constructor & Destructor Documentation
CIccTagLutAtoB::CIccTagLutAtoB ()
Name: CIccTagLutAtoB::CIccTagLutAtoB
Purpose: Constructor
CIccTagLutAtoB::CIccTagLutAtoB (const CIccTagLutAtoB & ITLA2B)
Name: CIccTagLutAtoB::CIccTagLutAtoB
Purpose: Copy Constructor
Args: ITLA2B = The CIccTagLutAtoB object to be copied
References m_nReservedWord.
CIccTagLutAtoB::~CIccTagLutAtoB () virtual
Name: CIccTagLutAtoB::~CIccTagLutAtoB
Purpose: Destructor
Member Function Documentation
virtual icTagTypeSignature CIccTagLutAtoB::GetType () const inline virtual
Function: GetType()
Purpose: Get Tag Type. Each derived tag will implement it's own GetType() function.
Reimplemented from CIccTag.
Reimplemented in CIccTagLutBtoA.
References icSigLutAtoBType.
Referenced by Read(), and Write().
virtual CIccTag* CIccTagLutAtoB::NewCopy () const inline virtual
Function: NewCopy(sDescription) Each derived tag will implement it's own NewCopy() function.
Parameter(s): none
Returns a new CIccTag object that is a copy of this object.
Reimplemented from CIccMBB.
Reimplemented in CIccTagLutBtoA.
CIccTagLutAtoB & CIccTagLutAtoB::operator= (const CIccTagLutAtoB & ITLA2B)
Name: CIccTagLutAtoB::operator=
Purpose: Copy Operator
Args: ITLA2B = The CIccTagLutAtoB object to be copied
References CIccMBB::operator=().
bool CIccTagLutAtoB::Read (icUInt32Number size, CIccIO * pIO) virtual
Name: CIccTagLutAtoB::Read
Purpose: Read in the tag contents into a data block
Args: size - # of bytes in tag, pIO - IO object to read tag from
Return: true = successful, false = failure
Reimplemented from CIccTag.
References CIccTag::Create(), GetType(), icFtoD(), icSeekSet, icSigCurveType, icSigParametricCurveType, CIccMBB::IsInputB(), CIccMBB::IsInputMatrix(), CIccMBB::m_CLUT, CIccMatrix::m_e, CIccMBB::m_Matrix, CIccMBB::m_nInput, CIccMBB::m_nOutput, CIccTag::m_nReserved, m_nReservedWord, CIccMBB::NewCurvesA(), CIccMBB::NewCurvesB(), CIccMBB::NewCurvesM(), CIccCLUT::Read(), CIccIO::Read16(), CIccIO::Read32(), CIccIO::Read8(), CIccIO::Seek(), CIccIO::Sync32(), and CIccIO::Tell().
icValidateStatus CIccTagLutAtoB::Validate (icTagSignature sig, std::string & sReport, const CIccProfile * pProfile = NULL) const virtual
Name: CIccTagLutAtoB::Validate
Purpose: Check tag data validity.
Args: sig = signature of tag being validated, sReport = String to add report information to
Return: icValidateStatusOK if valid, or other error status.
Reimplemented from CIccMBB.
Reimplemented in CIccTagLutBtoA.
References icHeader::colorSpace, CIccInfo::GetSigName(), icGetSpaceSamples(), icMaxStatus(), icSigAToB0Tag, icSigAToB1Tag, icSigAToB2Tag, icValidateCriticalError, icValidateCriticalErrorMsg, icValidateNonCompliant, icValidateNonCompliantMsg, CIccMBB::m_CLUT, CIccMBB::m_CurvesA, CIccMBB::m_CurvesB, CIccMBB::m_CurvesM, CIccProfile::m_Header, icHeader::pcs, and CIccMBB::Validate().
bool CIccTagLutAtoB::Write (CIccIO * pIO) virtual
Name: CIccTagLutAtoB::Write
Purpose: Write the tag to a file
Args: pIO - The IO object to write tag to.
Return: true = succesful, false = failure
Reimplemented from CIccTag.
References CIccIO::Align32(), GetType(), icDtoF(), icSeekSet, CIccMBB::IsInputB(), CIccMBB::IsInputMatrix(), CIccMBB::m_CLUT, CIccMBB::m_CurvesA, CIccMBB::m_CurvesB, CIccMBB::m_CurvesM, CIccMatrix::m_e, CIccMBB::m_Matrix, CIccMBB::m_nInput, CIccMBB::m_nOutput, CIccTag::m_nReserved, m_nReservedWord, CIccIO::Seek(), CIccIO::Tell(), CIccCLUT::Write(), CIccIO::Write16(), CIccIO::Write32(), and CIccIO::Write8().
Member Data Documentation
icUInt16Number CIccTagLutAtoB::m_nReservedWord protected
Referenced by CIccTagLutAtoB(), Read(), and Write().
The documentation for this class was generated from the following files:
IccTagLut.h
IccTagLut.cpp