CIccTagCurve Class Reference
CIccTagCurve Class Reference
#include <IccTagLut.h>
Public Member Functions
CIccTagCurve (int nSize=0)
CIccTagCurve (const CIccTagCurve &ITCurve)
CIccTagCurve & operator= (const CIccTagCurve &CurveTag)
virtual CIccTag * NewCopy () const
virtual ~CIccTagCurve ()
virtual icTagTypeSignature GetType () const
virtual const icChar * GetClassName () const
virtual void Describe (std::string &sDescription)
virtual void DumpLut (std::string &sDescription, const icChar *szName, icColorSpaceSignature csSig, int nIndex)
virtual bool Read (icUInt32Number size, CIccIO *pIO)
virtual bool Write (CIccIO *pIO)
icFloatNumber & operator[] (icUInt32Number index)
icFloatNumber * GetData (icUInt32Number index)
icUInt32Number GetSize () const
void SetSize (icUInt32Number nSize, icTagCurveSizeInit nSizeOpt=icInitZero)
void SetGamma (icFloatNumber gamma)
virtual void Begin ()
virtual icFloatNumber Apply (icFloatNumber v)
virtual icValidateStatus Validate (icTagSignature sig, std::string &sReport, const CIccProfile *pProfile=NULL) const
virtual bool IsIdentity ()
Public Member Functions inherited from CIccCurve
CIccCurve ()
virtual ~CIccCurve ()
icFloatNumber Find (icFloatNumber v)
Public Member Functions inherited from CIccTag
CIccTag ()
virtual ~CIccTag ()
virtual bool IsArrayType ()
virtual bool IsMBBType ()
virtual IIccExtensionTag * GetExtension ()
virtual bool IsSupported ()
Protected Attributes
icFloatNumber * m_Curve
icUInt32Number m_nSize
icUInt16Number m_nMaxIndex
Additional Inherited Members
Static Public Member Functions inherited from CIccTag
static CIccTag * Create (icTagTypeSignature sig)
Public Attributes inherited from CIccTag
icUInt32Number m_nReserved
Protected Member Functions inherited from CIccCurve
icFloatNumber Find (icFloatNumber v, icFloatNumber p0, icFloatNumber v0, icFloatNumber p1, icFloatNumber v1)
Detailed Description
Class: CIccTagCurve
Purpose: The curveType tag
Constructor & Destructor Documentation
CIccTagCurve::CIccTagCurve (int nSize = 0)
Name: CIccTagCurve::CIccTagCurve
Purpose: Constructor
CIccTagCurve::CIccTagCurve (const CIccTagCurve & ITCurve)
Name: CIccTagCurve::CIccTagCurve
Purpose: Copy Constructor
Args: ITCurve = The CIccTagCurve object to be copied
References m_Curve, m_nMaxIndex, and m_nSize.
CIccTagCurve::~CIccTagCurve () virtual
Name: CIccTagCurve::~CIccTagCurve
Purpose: Destructor
Member Function Documentation
icFloatNumber CIccTagCurve::Apply (icFloatNumber v) virtual
Name: CIccTagCurve::Apply
Purpose: Applies the curve to the value passed.
Args: v = value to be passed through the curve.
Return: The value modified by the curve.
Reimplemented from CIccCurve.
Referenced by CIccTagLut8::Write().
virtual void CIccTagCurve::Begin () inline virtual
Reimplemented from CIccCurve.
void CIccTagCurve::Describe (std::string & sDescription) virtual
Name: CIccTagCurve::Describe
Purpose: Dump data associated with the tag to a string
Args: sDescription - string to concatenate tag dump to
Reimplemented from CIccTag.
References icColorValue(), and icSigMCH1Data.
void CIccTagCurve::DumpLut (std::string & sDescription, const icChar * szName, icColorSpaceSignature csSig, int nIndex) virtual
Name: CIccTagCurve::DumpLut
Purpose: Dump data associated with the tag to a string. Basically has the same function as Describe()
Args: sDescription = string to concatenate tag dump to, szName = name of the curve to be printed, csSig = color space signature of the LUT data, nIndex = the channel number of color space
Reimplemented from CIccCurve.
References icColorValue().
virtual const icChar* CIccTagCurve::GetClassName () const inline virtual
Reimplemented from CIccTag.
icFloatNumber* CIccTagCurve::GetData (icUInt32Number index) inline
icUInt32Number CIccTagCurve::GetSize () const inline
Referenced by CIccTagLut8::Validate(), CIccTagLut16::Validate(), and CIccTagLut8::Write().
virtual icTagTypeSignature CIccTagCurve::GetType () const inline virtual
Function: GetType()
Purpose: Get Tag Type. Each derived tag will implement it's own GetType() function.
Reimplemented from CIccTag.
References icSigCurveType.
bool CIccTagCurve::IsIdentity () virtual
Name: CIccTagCurve::IsIdentity
Purpose: Checks if this is an identity curve.
Return: true if the curve is an identity
Reimplemented from CIccCurve.
virtual CIccTag* CIccTagCurve::NewCopy () const inline virtual
Function: NewCopy(sDescription) Each derived tag will implement it's own NewCopy() function.
Parameter(s): none
Returns a new CIccTag object that is a copy of this object.
Reimplemented from CIccCurve.
CIccTagCurve & CIccTagCurve::operator= (const CIccTagCurve & CurveTag)
Name: CIccTagCurve::operator=
Purpose: Copy Operator
Args: CurveTag = The CIccTagCurve object to be copied
References m_Curve, m_nMaxIndex, and m_nSize.
icFloatNumber& CIccTagCurve::operator[] (icUInt32Number index) inline
bool CIccTagCurve::Read (icUInt32Number size, CIccIO * pIO) virtual
Name: CIccTagCurve::Read
Purpose: Read in the tag contents into a data block
Args: size - # of bytes in tag, pIO - IO object to read tag from
Return: true = successful, false = failure
Reimplemented from CIccTag.
References icInitNone, CIccIO::Read16Float(), and CIccIO::Read32().
void CIccTagCurve::SetGamma (icFloatNumber gamma)
Name: sampleICC::CIccTagCurve::SetGamma
Purpose: Set the curve with a single gamma value.
Args: gamma - gamma value to use
References icInitNone.
void CIccTagCurve::SetSize (icUInt32Number nSize, icTagCurveSizeInit nSizeOpt = icInitZero)
Name: CIccTagCurve::SetSize
Purpose: Sets the size of the curve array.
Args: nSize - number of entries in the curve, nSizeOpt - flag to zero newly formed values
References icInitIdentity, icInitNone, and icInitZero.
Referenced by CIccTagLut8::Read(), CIccTagLut16::Read(), CIccTagLut8::SetColorSpaces(), and CIccTagLut16::SetColorSpaces().
icValidateStatus CIccTagCurve::Validate (icTagSignature sig, std::string & sReport, const CIccProfile * pProfile = NULL) const virtual
Name: CIccTagCurve::Validate
Purpose: Check tag data validity.
Args: sig = signature of tag being validated, sReport = String to add report information to
Return: icValidateStatusOK if valid, or other error status.
Reimplemented from CIccTag.
References CIccInfo::GetSigName(), icMaxStatus(), icSigBlueTRCTag, icSigGrayTRCTag, icSigGreenTRCTag, icSigRedTRCTag, icValidateWarning, icValidateWarningMsg, and CIccTag::Validate().
bool CIccTagCurve::Write (CIccIO * pIO) virtual
Name: CIccTagCurve::Write
Purpose: Write the tag to a file
Args: pIO - The IO object to write tag to.
Return: true = succesful, false = failure
Reimplemented from CIccTag.
References CIccIO::Align32(), CIccIO::Write16Float(), and CIccIO::Write32().
Member Data Documentation
icFloatNumber* CIccTagCurve::m_Curve protected
Referenced by CIccTagCurve(), and operator=().
icUInt16Number CIccTagCurve::m_nMaxIndex protected
Referenced by CIccTagCurve(), and operator=().
icUInt32Number CIccTagCurve::m_nSize protected
Referenced by CIccTagCurve(), and operator=().
The documentation for this class was generated from the following files:
IccTagLut.h
IccTagLut.cpp