CIccMpeCLUT Class Reference
CIccMpeCLUT Class Reference
#include <IccMpeBasic.h>
Public Member Functions
CIccMpeCLUT ()
CIccMpeCLUT (const CIccMpeCLUT &clut)
CIccMpeCLUT & operator= (const CIccMpeCLUT &clut)
virtual CIccMultiProcessElement * NewCopy () const
virtual ~CIccMpeCLUT ()
virtual icElemTypeSignature GetType () const
virtual const icChar * GetClassName () const
virtual void Describe (std::string &sDescription)
virtual bool Read (icUInt32Number size, CIccIO *pIO)
virtual bool Write (CIccIO *pIO)
virtual bool Begin (icElemInterp nInterp, CIccTagMultiProcessElement *pMPE)
virtual void Apply (CIccApplyMpe *pApply, icFloatNumber *dstPixel, const icFloatNumber *srcPixel) const
virtual icValidateStatus Validate (icTagSignature sig, std::string &sReport, const CIccTagMultiProcessElement *pMPE=NULL) const
CIccCLUT * GetCLUT ()
void SetCLUT (CIccCLUT *pCLUT)
Public Member Functions inherited from CIccMultiProcessElement
CIccMultiProcessElement ()
virtual ~CIccMultiProcessElement ()
virtual icUInt16Number NumInputChannels () const
virtual icUInt16Number NumOutputChannels () const
virtual bool IsSupported ()
virtual CIccApplyMpe * GetNewApply (CIccApplyTagMpe *pApplyTag)
virtual bool IsAcs ()
virtual icAcsSignature GetBAcsSig ()
virtual icAcsSignature GetEAcsSig ()
virtual IIccExtensionMpe * GetExtension ()
Protected Attributes
CIccCLUT * m_pCLUT
icCLUTElemType m_interpType
Protected Attributes inherited from CIccMultiProcessElement
icUInt16Number m_nInputChannels
icUInt16Number m_nOutputChannels
Additional Inherited Members
Static Public Member Functions inherited from CIccMultiProcessElement
static CIccMultiProcessElement * Create (icElemTypeSignature sig)
Public Attributes inherited from CIccMultiProcessElement
icUInt32Number m_nReserved
Detailed Description
Class: CIccMpeCLUT
Purpose: The sampled float curve segment tag
Constructor & Destructor Documentation
CIccMpeCLUT::CIccMpeCLUT ()
Name: CIccMpeCLUT::CIccMpeCLUT
Purpose:
Args:
Return:
CIccMpeCLUT::CIccMpeCLUT (const CIccMpeCLUT & clut)
Name: CIccMpeCLUT::CIccMpeCLUT
Purpose:
Args:
Return:
References CIccMultiProcessElement::m_nInputChannels, CIccMultiProcessElement::m_nOutputChannels, CIccMultiProcessElement::m_nReserved, and m_pCLUT.
CIccMpeCLUT::~CIccMpeCLUT () virtual
Name: CIccMpeCLUT::~CIccMpeCLUT
Purpose:
Args:
Return:
Member Function Documentation
void CIccMpeCLUT::Apply (CIccApplyMpe * pApply, icFloatNumber * dstPixel, const icFloatNumber * srcPixel) const virtual
Name: CIccMpeCLUT::Apply
Purpose:
Args:
Return:
Implements CIccMultiProcessElement.
References ic3dInterp, ic3dInterpTetra, ic4dInterp, ic5dInterp, ic6dInterp, icNdInterp, CIccCLUT::Interp3d(), CIccCLUT::Interp3dTetra(), CIccCLUT::Interp4d(), CIccCLUT::Interp5d(), CIccCLUT::Interp6d(), and CIccCLUT::InterpND().
bool CIccMpeCLUT::Begin (icElemInterp nInterp, CIccTagMultiProcessElement * pMPE) virtual
Name: CIccMpeCLUT::Begin
Purpose:
Args:
Return:
Implements CIccMultiProcessElement.
References ic3dInterp, ic3dInterpTetra, ic4dInterp, ic5dInterp, ic6dInterp, icElemInterpTetra, and icNdInterp.
void CIccMpeCLUT::Describe (std::string & sDescription) virtual
Name: CIccMpeCLUT::Describe
Purpose:
Args:
Return:
Implements CIccMultiProcessElement.
References icSigUnknownData.
virtual const icChar* CIccMpeCLUT::GetClassName () const inline virtual
Implements CIccMultiProcessElement.
CIccCLUT* CIccMpeCLUT::GetCLUT () inline
virtual icElemTypeSignature CIccMpeCLUT::GetType () const inline virtual
Implements CIccMultiProcessElement.
References icSigCLutElemType.
virtual CIccMultiProcessElement* CIccMpeCLUT::NewCopy () const inline virtual
Implements CIccMultiProcessElement.
CIccMpeCLUT & CIccMpeCLUT::operator= (const CIccMpeCLUT & clut)
Name: &CIccMpeCLUT::operator=
Purpose:
Args:
Return:
References CIccMultiProcessElement::m_nInputChannels, CIccMultiProcessElement::m_nOutputChannels, CIccMultiProcessElement::m_nReserved, and m_pCLUT.
bool CIccMpeCLUT::Read (icUInt32Number size, CIccIO * pIO) virtual
Name: CIccMpeCLUT::Read
Purpose:
Args:
Return:
Implements CIccMultiProcessElement.
References CIccIO::Read16(), CIccIO::Read32(), CIccIO::Read8(), and CIccIO::ReadFloat32Float().
void CIccMpeCLUT::SetCLUT (CIccCLUT * pCLUT)
Name: CIccMpeCLUT::SetCLUT
Purpose:
Args:
Return:
References CIccCLUT::GetInputDim(), CIccCLUT::GetOutputChannels(), and CIccCLUT::SetClipFunc().
icValidateStatus CIccMpeCLUT::Validate (icTagSignature sig, std::string & sReport, const CIccTagMultiProcessElement * pMPE = NULL) const virtual
Name: CIccMpeCLUT::Validate
Purpose:
Args:
Return:
Implements CIccMultiProcessElement.
References CIccInfo::GetSigName(), icValidateCriticalError, icValidateCriticalErrorMsg, and CIccMultiProcessElement::Validate().
bool CIccMpeCLUT::Write (CIccIO * pIO) virtual
Name: CIccMpeCLUT::Write
Purpose:
Args:
Return:
Implements CIccMultiProcessElement.
References CIccIO::Write16(), CIccIO::Write32(), CIccIO::Write8(), and CIccIO::WriteFloat32Float().
Member Data Documentation
icCLUTElemType CIccMpeCLUT::m_interpType protected
CIccCLUT* CIccMpeCLUT::m_pCLUT protected
Referenced by CIccMpeCLUT(), and operator=().
The documentation for this class was generated from the following files:
IccMpeBasic.h
IccMpeBasic.cpp