CIccPRMG Class Reference
CIccPRMG Class Reference
#include <IccPrmg.h>
Public Member Functions
CIccPRMG ()
icFloatNumber GetChroma (icFloatNumber L, icFloatNumber h)
bool InGamut (icFloatNumber *Lab)
bool InGamut (icFloatNumber L, icFloatNumber c, icFloatNumber h)
icStatusCMM EvaluateProfile (CIccProfile *pProfile, icRenderingIntent nIntent=icUnknownIntent, icXformInterp nInterp=icInterpLinear, bool buseMpeTags=true)
icStatusCMM EvaluateProfile (const icChar *szProfilePath, icRenderingIntent nIntent=icUnknownIntent, icXformInterp nInterp=icInterpLinear, bool buseMpeTags=true)
Public Attributes
icUInt32Number m_nDE1
icUInt32Number m_nDE2
icUInt32Number m_nDE3
icUInt32Number m_nDE5
icUInt32Number m_nDE10
icUInt32Number m_nTotal
bool m_bPrmgImplied
Constructor & Destructor Documentation
CIccPRMG::CIccPRMG ()
Member Function Documentation
icStatusCMM CIccPRMG::EvaluateProfile (CIccProfile * pProfile, icRenderingIntent nIntent = icUnknownIntent, icXformInterp nInterp = icInterpLinear, bool buseMpeTags = true)
References CIccCmm::AddXform(), CIccCmm::Apply(), CIccCmm::Begin(), icHeader::deviceClass, CIccProfile::FindTag(), CIccTag::GetType(), CIccTagSignature::GetValue(), icCmmStatCantOpenProfile, icCmmStatInvalidProfile, icCmmStatOk, icDeltaE(), icLabFromPcs(), icPerceptual, icSaturation, icSigColorSpaceClass, icSigDisplayClass, icSigInputClass, icSigLabData, icSigOutputClass, icSigPerceptualReferenceMediumGamut, icSigPerceptualRenderingIntentGamutTag, icSigSignatureType, icXformLutColor, and CIccProfile::m_Header.
icStatusCMM CIccPRMG::EvaluateProfile (const icChar * szProfilePath, icRenderingIntent nIntent = icUnknownIntent, icXformInterp nInterp = icInterpLinear, bool buseMpeTags = true)
References icCmmStatCantOpenProfile, and ReadIccProfile().
icFloatNumber CIccPRMG::GetChroma (icFloatNumber L, icFloatNumber h)
bool CIccPRMG::InGamut (icFloatNumber * Lab)
References icLab2Lch().
bool CIccPRMG::InGamut (icFloatNumber L, icFloatNumber c, icFloatNumber h)
Member Data Documentation
bool CIccPRMG::m_bPrmgImplied
icUInt32Number CIccPRMG::m_nDE1
icUInt32Number CIccPRMG::m_nDE10
icUInt32Number CIccPRMG::m_nDE2
icUInt32Number CIccPRMG::m_nDE3
icUInt32Number CIccPRMG::m_nDE5
icUInt32Number CIccPRMG::m_nTotal
The documentation for this class was generated from the following files:
IccPrmg.h
IccPrmg.cpp