CIccTagLutBtoA Class Reference
CIccTagLutBtoA Class Reference
#include <IccTagLut.h>
Public Member Functions
CIccTagLutBtoA ()
CIccTagLutBtoA (const CIccTagLutBtoA &ITLB2A)
CIccTagLutBtoA & operator= (const CIccTagLutBtoA &ITLB2A)
virtual CIccTag * NewCopy () const
virtual icTagTypeSignature GetType () const
virtual icValidateStatus Validate (icTagSignature sig, std::string &sReport, const CIccProfile *pProfile=NULL) const
Public Member Functions inherited from CIccTagLutAtoB
CIccTagLutAtoB ()
CIccTagLutAtoB (const CIccTagLutAtoB &ITLA2B)
CIccTagLutAtoB & operator= (const CIccTagLutAtoB &ITLA2B)
virtual ~CIccTagLutAtoB ()
bool Read (icUInt32Number size, CIccIO *pIO)
bool Write (CIccIO *pIO)
Public Member Functions inherited from CIccMBB
CIccMBB ()
CIccMBB (const CIccMBB &IMBB)
CIccMBB & operator= (const CIccMBB &IMBB)
virtual ~CIccMBB ()
virtual bool IsMBBType ()
virtual icUInt8Number GetPrecision ()
virtual bool IsInputMatrix ()
virtual bool UseLegacyPCS () const
bool IsInputB ()
bool SwapMBCurves ()
void Cleanup ()
void Init (icUInt8Number nInputChannels, icUInt8Number nOutputChannels)
icUInt8Number InputChannels () const
icUInt8Number OutputChannels () const
virtual void Describe (std::string &sDescription)
virtual void SetColorSpaces (icColorSpaceSignature csInput, icColorSpaceSignature csOutput)
LPIccCurve * NewCurvesA ()
CIccCLUT * NewCLUT (icUInt8Number nGridPoints, icUInt8Number nPrecision=2)
CIccCLUT * NewCLUT (icUInt8Number *pGridPoints, icUInt8Number nPrecision=2)
CIccMatrix * NewMatrix ()
LPIccCurve * NewCurvesM ()
LPIccCurve * NewCurvesB ()
CIccMatrix * GetMatrix () const
CIccCLUT * GetCLUT () const
LPIccCurve * GetCurvesA () const
LPIccCurve * GetCurvesB () const
LPIccCurve * GetCurvesM () const
CIccCLUT * SetCLUT (CIccCLUT *clut)
Public Member Functions inherited from CIccTag
CIccTag ()
virtual ~CIccTag ()
virtual bool IsArrayType ()
virtual const icChar * GetClassName () const
virtual IIccExtensionTag * GetExtension ()
virtual bool IsSupported ()
Additional Inherited Members
Static Public Member Functions inherited from CIccTag
static CIccTag * Create (icTagTypeSignature sig)
Public Attributes inherited from CIccTag
icUInt32Number m_nReserved
Protected Attributes inherited from CIccTagLutAtoB
icUInt16Number m_nReservedWord
Protected Attributes inherited from CIccMBB
bool m_bInputMatrix
bool m_bUseMCurvesAsBCurves
icUInt8Number m_nInput
icUInt8Number m_nOutput
icColorSpaceSignature m_csInput
icColorSpaceSignature m_csOutput
LPIccCurve * m_CurvesA
CIccCLUT * m_CLUT
CIccMatrix * m_Matrix
LPIccCurve * m_CurvesM
LPIccCurve * m_CurvesB
Detailed Description
Class: CIccTagLutBtoA
Purpose: The LutB2A tag type
Constructor & Destructor Documentation
CIccTagLutBtoA::CIccTagLutBtoA ()
Name: CIccTagLutBtoA::CIccTagLutBtoA
Purpose: Constructor
References CIccMBB::m_bInputMatrix.
CIccTagLutBtoA::CIccTagLutBtoA (const CIccTagLutBtoA & ITLB2A)
Name: CIccTagLutBtoA::CIccTagLutBtoA
Purpose: Copy Constructor
Args: ITLB2A = The CIccTagLutBtoA object to be copied
Member Function Documentation
virtual icTagTypeSignature CIccTagLutBtoA::GetType () const inline virtual
Function: GetType()
Purpose: Get Tag Type. Each derived tag will implement it's own GetType() function.
Reimplemented from CIccTagLutAtoB.
References icSigLutBtoAType.
virtual CIccTag* CIccTagLutBtoA::NewCopy () const inline virtual
Function: NewCopy(sDescription) Each derived tag will implement it's own NewCopy() function.
Parameter(s): none
Returns a new CIccTag object that is a copy of this object.
Reimplemented from CIccTagLutAtoB.
CIccTagLutBtoA & CIccTagLutBtoA::operator= (const CIccTagLutBtoA & ITLB2A)
Name: CIccTagLutBtoA::operator=
Purpose: Copy Operator
Args: ITLB2A = The CIccTagLutBtoA object to be copied
References CIccMBB::operator=().
icValidateStatus CIccTagLutBtoA::Validate (icTagSignature sig, std::string & sReport, const CIccProfile * pProfile = NULL) const virtual
Name: CIccTagLutBtoA::Validate
Purpose: Check tag data validity.
Args: sig = signature of tag being validated, sReport = String to add report information to
Return: icValidateStatusOK if valid, or other error status.
Reimplemented from CIccTagLutAtoB.
References icHeader::colorSpace, CIccInfo::GetSigName(), icGetSpaceSamples(), icMaxStatus(), icSigBToA0Tag, icSigBToA1Tag, icSigBToA2Tag, icSigGamutTag, icValidateCriticalError, icValidateCriticalErrorMsg, icValidateNonCompliant, icValidateNonCompliantMsg, icValidateWarningMsg, CIccMBB::m_CLUT, CIccMBB::m_CurvesA, CIccMBB::m_CurvesB, CIccMBB::m_CurvesM, CIccProfile::m_Header, CIccMBB::m_nOutput, icHeader::pcs, and CIccMBB::Validate().
The documentation for this class was generated from the following files:
IccTagLut.h
IccTagLut.cpp