CIccTagCreator Class Reference
CIccTagCreator Class Reference
#include <IccTagFactory.h>
Public Member Functions
~CIccTagCreator ()
Static Public Member Functions
static CIccTag * CreateTag (icTagTypeSignature tagTypeSig)
static const icChar * GetTagSigName (icTagSignature tagTypeSig)
static const icChar * GetTagTypeSigName (icTagTypeSignature tagTypeSig)
static void PushFactory (IIccTagFactory *pFactory)
static IIccTagFactory * PopFactory ()
Detailed Description
Class: CIccTagCreator
Purpose: CIccTagCreator uses a singleton pattern to provide dynamically upgradeable CIccTag derived object creation based on tag signature.
Constructor & Destructor Documentation
CIccTagCreator::~CIccTagCreator ()
Member Function Documentation
static CIccTag* CIccTagCreator::CreateTag (icTagTypeSignature tagTypeSig) inline static
Function: CreateTag(tagTypeSig) Create a tag of type tagTypeSig.
Parameter(s): tagTypeSig = signature of the ICC tag type for the tag to be created
Returns a new CIccTag object of the given signature type. Each factory in the factoryStack is used until a factory supports the signature type.
Referenced by CIccTag::Create().
static const icChar* CIccTagCreator::GetTagSigName (icTagSignature tagTypeSig) inline static
Function: GetTagSigName(tagSig) Get display name of tagSig.
Parameter(s): tagSig = signature of the ICC tag to get a name for
Returns ptr to string containing name of tag type if it is recognized by any factory, NULL if all factories do not create tagTypeSig tags.
Referenced by CIccInfo::GetTagSigName().
static const icChar* CIccTagCreator::GetTagTypeSigName (icTagTypeSignature tagTypeSig) inline static
Function: GetTagTypeSigName(tagTypeSig) Get display name of tagTypeSig.
Parameter(s): tagTypeSig = signature of the ICC tag type to get a name for
Returns ptr to string containing name of tag type if it is recognized by any factory, NULL if all factories do not create tagTypeSig tags.
Referenced by CIccInfo::GetTagTypeSigName().
static IIccTagFactory* CIccTagCreator::PopFactory () inline static
Function: PopFactory() Remove the top IIccTagFactory from the stack of tag factories tracked by the system.
Parameter(s): None
Returns the top IIccTagFactory from the stack of tag factories tracked by the system. The returned tag factory is no longer owned by the system and needs to be deleted to avoid memory leaks.
Note: The initial CIccSpecTagFactory cannot be popped off the stack.
static void CIccTagCreator::PushFactory (IIccTagFactory * pFactory) inline static
Function: PushFactory(pFactory) Add an IIccTagFactory to the stack of tag factories tracked by the system.
Parameter(s): pFactory = pointer to an IIccTagFactory object to add to the system. The pFactory must be created with new, and will be owned CIccTagCreator until popped off the stack using PopFactory(). Any factories not popped off will be taken care of properly on application shutdown.
The documentation for this class was generated from the following files:
IccTagFactory.h
IccTagFactory.cpp