CIccTagProfileSequenceId Class Reference
CIccTagProfileSequenceId Class Reference
#include <IccTagProfSeqId.h>
Public Member Functions
CIccTagProfileSequenceId ()
CIccTagProfileSequenceId (const CIccTagProfileSequenceId &lut)
CIccTagProfileSequenceId & operator= (const CIccTagProfileSequenceId &lut)
virtual CIccTag * NewCopy () const
virtual ~CIccTagProfileSequenceId ()
virtual icTagTypeSignature GetType () const
virtual const icChar * GetClassName () const
virtual void Describe (std::string &sDescription)
virtual bool Read (icUInt32Number size, CIccIO *pIO)
virtual bool Write (CIccIO *pIO)
virtual icValidateStatus Validate (icTagSignature sig, std::string &sReport, const CIccProfile *pProfile=NULL) const
bool AddProfileDescription (CIccProfile &profile)
bool AddProfileDescription (const CIccProfileIdDesc &profileDesc)
CIccProfileIdDesc * GetFirst ()
CIccProfileIdDesc * GetLast ()
CIccProfileIdDescList::iterator begin ()
CIccProfileIdDescList::iterator end ()
Public Member Functions inherited from CIccTag
CIccTag ()
virtual ~CIccTag ()
virtual bool IsArrayType ()
virtual bool IsMBBType ()
virtual IIccExtensionTag * GetExtension ()
virtual bool IsSupported ()
Static Public Member Functions
static CIccTagProfileSequenceId * ParseMem (icUInt8Number *pMem, icUInt32Number size)
Static Public Member Functions inherited from CIccTag
static CIccTag * Create (icTagTypeSignature sig)
Protected Member Functions
void Cleanup ()
Protected Attributes
CIccProfileIdDescList * m_list
Additional Inherited Members
Public Attributes inherited from CIccTag
icUInt32Number m_nReserved
Detailed Description
Class: CIccTagProfileSequenceId
Purpose: The ProfileSequenceId tag
Constructor & Destructor Documentation
CIccTagProfileSequenceId::CIccTagProfileSequenceId ()
Name: CIccTagProfileSequenceId::CIccTagProfileSequenceId
Purpose:
Args:
Return:
References m_list.
Referenced by ParseMem().
CIccTagProfileSequenceId::CIccTagProfileSequenceId (const CIccTagProfileSequenceId & psi)
Name: CIccTagProfileSequenceId::CIccTagProfileSequenceId
Purpose:
Args:
Return:
References m_list.
CIccTagProfileSequenceId::~CIccTagProfileSequenceId () virtual
Name: CIccTagProfileSequenceId::~CIccTagProfileSequenceId
Purpose:
Args:
Return:
References m_list.
Member Function Documentation
bool CIccTagProfileSequenceId::AddProfileDescription (CIccProfile & profile) inline
References AddProfileDescription().
Referenced by AddProfileDescription().
bool CIccTagProfileSequenceId::AddProfileDescription (const CIccProfileIdDesc & profileDesc)
Name: sampleICC::CIccTagProfileSequenceId::AddProfileDescription
Purpose:
Args: CIccProfileIdDesc &profileDesc
Return: bool
References m_list.
CIccProfileIdDescList::iterator CIccTagProfileSequenceId::begin () inline
void CIccTagProfileSequenceId::Cleanup () protected
void CIccTagProfileSequenceId::Describe (std::string & sDescription) virtual
Name: CIccTagProfileSequenceId::Describe
Purpose:
Args:
Return:
Reimplemented from CIccTag.
References m_list.
CIccProfileIdDescList::iterator CIccTagProfileSequenceId::end () inline
virtual const icChar* CIccTagProfileSequenceId::GetClassName () const inline virtual
Reimplemented from CIccTag.
CIccProfileIdDesc * CIccTagProfileSequenceId::GetFirst ()
Name: sampleICC::CIccTagProfileSequenceId::GetFirst
Purpose:
Args:
Return: CIccProfileIdDesc *
References m_list.
CIccProfileIdDesc * CIccTagProfileSequenceId::GetLast ()
Name: sampleICC::CIccTagProfileSequenceId::GetLast
Purpose:
Args:
Return: CIccProfileIdDesc *
References m_list.
virtual icTagTypeSignature CIccTagProfileSequenceId::GetType () const inline virtual
Function: GetType()
Purpose: Get Tag Type. Each derived tag will implement it's own GetType() function.
Reimplemented from CIccTag.
References icSigProfileSequceIdType.
Referenced by Write().
virtual CIccTag* CIccTagProfileSequenceId::NewCopy () const inline virtual
Function: NewCopy(sDescription) Each derived tag will implement it's own NewCopy() function.
Parameter(s): none
Returns a new CIccTag object that is a copy of this object.
Reimplemented from CIccTag.
CIccTagProfileSequenceId & CIccTagProfileSequenceId::operator= (const CIccTagProfileSequenceId & psi)
Name: &operator=
Purpose:
Args:
Return:
References m_list.
CIccTagProfileSequenceId * CIccTagProfileSequenceId::ParseMem (icUInt8Number * pMem, icUInt32Number size) static
Name: CIccTagProfileSequenceId::ParseMem
Purpose:
Args:
Return:
References CIccMemIO::Attach(), CIccTagProfileSequenceId(), and Read().
bool CIccTagProfileSequenceId::Read (icUInt32Number size, CIccIO * pIO) virtual
Name: CIccTagProfileSequenceId::Read
Purpose:
Args:
Return:
Reimplemented from CIccTag.
References icSeekSet, m_list, CIccTag::m_nReserved, icPositionNumber::offset, CIccProfileIdDesc::Read(), CIccIO::Read32(), CIccIO::Seek(), icPositionNumber::size, and CIccIO::Tell().
Referenced by ParseMem().
icValidateStatus CIccTagProfileSequenceId::Validate (icTagSignature sig, std::string & sReport, const CIccProfile * pProfile = NULL) const virtual
Name: CIccTagProfileSequenceId::Validate
Purpose:
Args:
Return:
Reimplemented from CIccTag.
References CIccInfo::GetSigName(), icMaxStatus(), m_list, and CIccTag::Validate().
bool CIccTagProfileSequenceId::Write (CIccIO * pIO) virtual
Name: CIccTagProfileSequenceId::Write
Purpose:
Args:
Return:
Reimplemented from CIccTag.
References CIccIO::Align32(), GetType(), icSeekSet, m_list, CIccTag::m_nReserved, icPositionNumber::offset, CIccIO::Seek(), icPositionNumber::size, CIccIO::Tell(), and CIccIO::Write32().
Member Data Documentation
CIccProfileIdDescList* CIccTagProfileSequenceId::m_list protected
Referenced by AddProfileDescription(), CIccTagProfileSequenceId(), Describe(), GetFirst(), GetLast(), operator=(), Read(), Validate(), Write(), and ~CIccTagProfileSequenceId().
The documentation for this class was generated from the following files:
IccTagProfSeqId.h
IccTagProfSeqId.cpp