CIccTagTextDescription Class Reference
CIccTagTextDescription Class Reference
#include <IccTagBasic.h>
Public Member Functions
CIccTagTextDescription ()
CIccTagTextDescription (const CIccTagTextDescription &ITTD)
CIccTagTextDescription & operator= (const CIccTagTextDescription &TextDescTag)
virtual CIccTag * NewCopy () const
virtual ~CIccTagTextDescription ()
virtual icTagTypeSignature GetType () const
virtual const icChar * GetClassName () const
virtual bool Read (icUInt32Number size, CIccIO *pIO)
virtual bool Write (CIccIO *pIO)
virtual void Describe (std::string &sDescription)
const icChar * GetText () const
void SetText (const icChar *szText)
const icChar * operator= (const icChar *szText)
icChar * GetBuffer (icUInt32Number nSize)
void Release ()
icUInt32Number Capacity () const
icUInt16Number * GetUnicodeBuffer (icUInt32Number nSize)
void ReleaseUnicode ()
virtual icValidateStatus Validate (icTagSignature sig, std::string &sReport, const CIccProfile *pProfile=NULL) const
Public Member Functions inherited from CIccTag
CIccTag ()
virtual ~CIccTag ()
virtual bool IsArrayType ()
virtual bool IsMBBType ()
virtual IIccExtensionTag * GetExtension ()
virtual bool IsSupported ()
Protected Attributes
icChar * m_szText
icUInt32Number m_nASCIISize
icUInt16Number * m_uzUnicodeText
icUInt32Number m_nUnicodeSize
icUInt32Number m_nUnicodeLanguageCode
icUInt8Number m_szScriptText [67]
icUInt8Number m_nScriptSize
icUInt16Number m_nScriptCode
bool m_bInvalidScript
Additional Inherited Members
Static Public Member Functions inherited from CIccTag
static CIccTag * Create (icTagTypeSignature sig)
Public Attributes inherited from CIccTag
icUInt32Number m_nReserved
Detailed Description
Class: CIccTagTextDescription()
Purpose: The textType ICC tag
Constructor & Destructor Documentation
CIccTagTextDescription::CIccTagTextDescription ()
Name: CIccTagTextDescription::CIccTagTextDescription
Purpose: Constructor
CIccTagTextDescription::CIccTagTextDescription (const CIccTagTextDescription & ITTD)
Name: CIccTagTextDescription::CIccTagTextDescription
Purpose: Copy Constructor
Args: ITTD = The CIccTagTextDescription object to be copied
References m_bInvalidScript, m_nASCIISize, m_nScriptCode, m_nScriptSize, m_nUnicodeLanguageCode, m_nUnicodeSize, m_szScriptText, m_szText, and m_uzUnicodeText.
CIccTagTextDescription::~CIccTagTextDescription () virtual
Name: CIccTagTextDescription::~CIccTagTextDescription
Purpose: Destructor
Member Function Documentation
icUInt32Number CIccTagTextDescription::Capacity () const inline
void CIccTagTextDescription::Describe (std::string & sDescription) virtual
Name: CIccTagTextDescription::Describe
Purpose: Dump data associated with the tag to a string
Args: sDescription - string to concatenate tag dump to
Reimplemented from CIccTag.
icChar * CIccTagTextDescription::GetBuffer (icUInt32Number nSize)
Name: CIccTagTextDescription::GetBuffer
Purpose: This function allocates room and returns pointer to data buffer to put string into
Args: nSize = Requested size of data buffer.
Return:
virtual const icChar* CIccTagTextDescription::GetClassName () const inline virtual
Reimplemented from CIccTag.
const icChar* CIccTagTextDescription::GetText () const inline
Referenced by CIccProfileIdDesc::CIccProfileIdDesc().
virtual icTagTypeSignature CIccTagTextDescription::GetType () const inline virtual
Function: GetType()
Purpose: Get Tag Type. Each derived tag will implement it's own GetType() function.
Reimplemented from CIccTag.
References icSigTextDescriptionType.
icUInt16Number * CIccTagTextDescription::GetUnicodeBuffer (icUInt32Number nSize)
Name: CIccTagTextDescription::GetUnicodeBuffer
Purpose: This function allocates room and returns pointer to data buffer to put string into
Args: nSize = Requested size of data buffer.
Return:
virtual CIccTag* CIccTagTextDescription::NewCopy () const inline virtual
Function: NewCopy(sDescription) Each derived tag will implement it's own NewCopy() function.
Parameter(s): none
Returns a new CIccTag object that is a copy of this object.
Reimplemented from CIccTag.
CIccTagTextDescription & CIccTagTextDescription::operator= (const CIccTagTextDescription & TextDescTag)
Name: CIccTagTextDescription::operator=
Purpose: Copy Operator
Args: TextDescTag = The CIccTagTextDescription object to be copied
References m_bInvalidScript, m_nASCIISize, m_nScriptCode, m_nScriptSize, m_nUnicodeLanguageCode, m_nUnicodeSize, m_szScriptText, m_szText, and m_uzUnicodeText.
const icChar * CIccTagTextDescription::operator= (const icChar * szText)
Name: CIccTagTextDescription::operator=
Purpose: Define assignment operator to associate text with tag.
Args: szText - zero terminated string to put in the tag
Return: A pointer to the string assigned to the tag.
bool CIccTagTextDescription::Read (icUInt32Number size, CIccIO * pIO) virtual
Name: CIccTagTextDescription::Read
Purpose: Read in the tag contents into a data block
Args: size - # of bytes in tag, pIO - IO object to read tag from
Return: true = successful, false = failure
Reimplemented from CIccTag.
References CIccIO::Read16(), CIccIO::Read32(), CIccIO::Read8(), and CIccIO::Tell().
void CIccTagTextDescription::Release ()
Name: CIccTagTextDescription::Release
Purpose: This will resize the buffer to fit the zero terminated string in the buffer.
void CIccTagTextDescription::ReleaseUnicode ()
Name: CIccTagTextDescription::ReleaseUnicode
Purpose: This will resize the buffer to fit the zero terminated string in the buffer.
void CIccTagTextDescription::SetText (const icChar * szText)
Name: CIccTagTextDescription::SetText
Purpose: Allows text data associated with the tag to be set.
Args: szText - zero terminated string to put in tag
icValidateStatus CIccTagTextDescription::Validate (icTagSignature sig, std::string & sReport, const CIccProfile * pProfile = NULL) const virtual
Name: CIccTagTextDescription::Validate
Purpose: Check tag data validity.
Args: sig = signature of tag being validated, sReport = String to add report information to
Return: icValidateStatusOK if valid, or other error status.
Reimplemented from CIccTag.
References CIccInfo::GetSigName(), icMaxStatus(), icValidateNonCompliant, icValidateNonCompliantMsg, and CIccTag::Validate().
bool CIccTagTextDescription::Write (CIccIO * pIO) virtual
Name: CIccTagTextDescription::Write
Purpose: Write the tag to a file
Args: pIO - The IO object to write tag to.
Return: true = succesful, false = failure
Reimplemented from CIccTag.
References CIccIO::Write16(), CIccIO::Write32(), and CIccIO::Write8().
Member Data Documentation
bool CIccTagTextDescription::m_bInvalidScript protected
Referenced by CIccTagTextDescription(), and operator=().
icUInt32Number CIccTagTextDescription::m_nASCIISize protected
Referenced by CIccTagTextDescription(), and operator=().
icUInt16Number CIccTagTextDescription::m_nScriptCode protected
Referenced by CIccTagTextDescription(), and operator=().
icUInt8Number CIccTagTextDescription::m_nScriptSize protected
Referenced by CIccTagTextDescription(), and operator=().
icUInt32Number CIccTagTextDescription::m_nUnicodeLanguageCode protected
Referenced by CIccTagTextDescription(), and operator=().
icUInt32Number CIccTagTextDescription::m_nUnicodeSize protected
Referenced by CIccTagTextDescription(), and operator=().
icUInt8Number CIccTagTextDescription::m_szScriptText[67] protected
Referenced by CIccTagTextDescription(), and operator=().
icChar* CIccTagTextDescription::m_szText protected
Referenced by CIccTagTextDescription(), and operator=().
icUInt16Number* CIccTagTextDescription::m_uzUnicodeText protected
Referenced by CIccTagTextDescription(), and operator=().
The documentation for this class was generated from the following files:
IccTagBasic.h
IccTagBasic.cpp