CIccXformNDLut Class Reference
CIccXformNDLut Class Reference
#include <IccCmm.h>
Public Member Functions
CIccXformNDLut (CIccTag *pTag)
virtual ~CIccXformNDLut ()
virtual icXformType GetXformType () const
virtual icStatusCMM Begin ()
virtual void Apply (CIccApplyXform *pApplyXform, icFloatNumber *DstPixel, const icFloatNumber *SrcPixel) const
virtual bool UseLegacyPCS () const
Checks if version 2 PCS is to be used.
virtual LPIccCurve * ExtractInputCurves ()
virtual LPIccCurve * ExtractOutputCurves ()
Public Member Functions inherited from CIccXform
CIccXform ()
virtual ~CIccXform ()
virtual CIccApplyXform * GetNewApply (icStatusCMM &status)
virtual bool RemoveIO ()
virtual icColorSpaceSignature GetSrcSpace () const
Returns the source color space of the transform.
virtual icColorSpaceSignature GetDstSpace () const
Returns the destination color space of the transform.
virtual bool IsVersion2 () const
Checks if the profile is version 2.
bool IsInput () const
Checks if the profile is to be used as input profile.
void SetParams (CIccProfile *pProfile, bool bInput, icRenderingIntent nIntent, icXformInterp nInterp, CIccCreateXformHintManager *pHintManager=NULL)
The following function is for Overridden create function.
virtual bool NoClipPCS () const
const CIccProfile * GetProfile () const
Returns the profile pointer. Profile is still owned by the Xform.
icRenderingIntent GetIntent () const
Returns the rendering intent being used by the Xform.
Protected Attributes
const CIccMBB * m_pTag
int m_nNumInput
const LPIccCurve * m_ApplyCurvePtrA
Pointers to data in m_pTag, used only for applying the xform.
const LPIccCurve * m_ApplyCurvePtrB
const LPIccCurve * m_ApplyCurvePtrM
const CIccMatrix * m_ApplyMatrixPtr
Protected Attributes inherited from CIccXform
CIccProfile * m_pProfile
bool m_bInput
icRenderingIntent m_nIntent
icXYZNumber m_MediaXYZ
icXformInterp m_nInterp
IIccAdjustPCSXform * m_pAdjustPCS
bool m_bAdjustPCS
icFloatNumber m_PCSScale [3]
icFloatNumber m_PCSOffset [3]
Additional Inherited Members
Static Public Member Functions inherited from CIccXform
static CIccXform * Create (CIccProfile *pProfile, bool bInput=true, icRenderingIntent nIntent=icUnknownIntent, icXformInterp nInterp=icInterpLinear, icXformLutType nLutType=icXformLutColor, bool bUseMpeTags=true, CIccCreateXformHintManager *pHintManager=NULL)
Note: The returned CIccXform will own the profile.
static CIccXform * Create (CIccProfile &pProfile, bool bInput=true, icRenderingIntent nIntent=icUnknownIntent, icXformInterp nInterp=icInterpLinear, icXformLutType nLutType=icXformLutColor, bool bUseMpeTags=true, CIccCreateXformHintManager *pHintManager=NULL)
Protected Member Functions inherited from CIccXform
const icFloatNumber * CheckSrcAbs (CIccApplyXform *pApply, const icFloatNumber *Pixel) const
void CheckDstAbs (icFloatNumber *Pixel) const
void AdjustPCS (icFloatNumber *DstPixel, const icFloatNumber *SrcPixel) const
virtual bool HasPerceptualHandling ()
Detailed Description
Type: Class
Purpose: This is the general ND-LUT Xform
Constructor & Destructor Documentation
CIccXformNDLut::CIccXformNDLut (CIccTag * pTag)
Name: CIccXformNDLut::CIccXformNDLut
Purpose: Constructor
Args: pTag = Pointer to the tag of type CIccMBB
References CIccTag::IsMBBType().
CIccXformNDLut::~CIccXformNDLut () virtual
Name: CIccXformNDLut::~CIccXformNDLut
Purpose: Destructor
Member Function Documentation
void CIccXformNDLut::Apply (CIccApplyXform * pApply, icFloatNumber * DstPixel, const icFloatNumber * SrcPixel) const virtual
Name: CIccXformNDLut::Apply
Purpose: Does the actual application of the Xform.
Args: pApply = ApplyXform object containging temporary storage used during Apply DstPixel = Destination pixel where the result is stored, SrcPixel = Source pixel which is to be applied.
Implements CIccXform.
icStatusCMM CIccXformNDLut::Begin () virtual
Name: CIccXformNDLut::Begin
Purpose: Does the initialization of the Xform before Apply() is called. Must be called before Apply().
Reimplemented from CIccXform.
References CIccCurve::Begin(), CIccXform::Begin(), icCmmStatInvalidLut, icCmmStatInvalidProfile, and icCmmStatOk.
LPIccCurve * CIccXformNDLut::ExtractInputCurves () virtual
Name: CIccXformNDLut::ExtractInputCurves
Purpose: Gets the input curves. Should be called only after Begin() has been called. Once the curves are extracted, they will not be used by the Apply() function. WARNING: caller owns the curves and must be deleted by the caller.
Return: Pointer to the input curves.
Implements CIccXform.
LPIccCurve * CIccXformNDLut::ExtractOutputCurves () virtual
Name: CIccXformNDLut::ExtractOutputCurves
Purpose: Gets the output curves. Should be called only after Begin() has been called. Once the curves are extracted, they will not be used by the Apply() function. WARNING: caller owns the curves and must be deleted by the caller.
Return: Pointer to the output curves.
Implements CIccXform.
virtual icXformType CIccXformNDLut::GetXformType () const inline virtual
Implements CIccXform.
References icXformTypeNDLut.
virtual bool CIccXformNDLut::UseLegacyPCS () const inline virtual
Checks if version 2 PCS is to be used.
Reimplemented from CIccXform.
Member Data Documentation
const LPIccCurve* CIccXformNDLut::m_ApplyCurvePtrA protected
Pointers to data in m_pTag, used only for applying the xform.
const LPIccCurve* CIccXformNDLut::m_ApplyCurvePtrB protected
const LPIccCurve* CIccXformNDLut::m_ApplyCurvePtrM protected
const CIccMatrix* CIccXformNDLut::m_ApplyMatrixPtr protected
int CIccXformNDLut::m_nNumInput protected
const CIccMBB* CIccXformNDLut::m_pTag protected
The documentation for this class was generated from the following files:
IccCmm.h
IccCmm.cpp