CIccXformMatrixTRC Class Reference
CIccXformMatrixTRC Class Reference
#include <IccCmm.h>
Public Member Functions
CIccXformMatrixTRC ()
virtual ~CIccXformMatrixTRC ()
virtual icXformType GetXformType () const
virtual icStatusCMM Begin ()
virtual void Apply (CIccApplyXform *pApplyXform, icFloatNumber *DstPixel, const icFloatNumber *SrcPixel) const
virtual LPIccCurve * ExtractInputCurves ()
virtual LPIccCurve * ExtractOutputCurves ()
Public Member Functions inherited from CIccXform
CIccXform ()
virtual ~CIccXform ()
virtual CIccApplyXform * GetNewApply (icStatusCMM &status)
virtual bool RemoveIO ()
virtual icColorSpaceSignature GetSrcSpace () const
Returns the source color space of the transform.
virtual icColorSpaceSignature GetDstSpace () const
Returns the destination color space of the transform.
virtual bool UseLegacyPCS () const
Checks if version 2 PCS is to be used.
virtual bool IsVersion2 () const
Checks if the profile is version 2.
bool IsInput () const
Checks if the profile is to be used as input profile.
void SetParams (CIccProfile *pProfile, bool bInput, icRenderingIntent nIntent, icXformInterp nInterp, CIccCreateXformHintManager *pHintManager=NULL)
The following function is for Overridden create function.
virtual bool NoClipPCS () const
const CIccProfile * GetProfile () const
Returns the profile pointer. Profile is still owned by the Xform.
icRenderingIntent GetIntent () const
Returns the rendering intent being used by the Xform.
Protected Member Functions
virtual bool HasPerceptualHandling ()
CIccCurve * GetCurve (icSignature sig) const
CIccCurve * GetInvCurve (icSignature sig) const
CIccTagXYZ * GetColumn (icSignature sig) const
Protected Member Functions inherited from CIccXform
const icFloatNumber * CheckSrcAbs (CIccApplyXform *pApply, const icFloatNumber *Pixel) const
void CheckDstAbs (icFloatNumber *Pixel) const
void AdjustPCS (icFloatNumber *DstPixel, const icFloatNumber *SrcPixel) const
Protected Attributes
icFloatNumber m_e [9]
CIccCurve * m_Curve [3]
bool m_bFreeCurve
const LPIccCurve * m_ApplyCurvePtr
used only when applying the xform
Protected Attributes inherited from CIccXform
CIccProfile * m_pProfile
bool m_bInput
icRenderingIntent m_nIntent
icXYZNumber m_MediaXYZ
icXformInterp m_nInterp
IIccAdjustPCSXform * m_pAdjustPCS
bool m_bAdjustPCS
icFloatNumber m_PCSScale [3]
icFloatNumber m_PCSOffset [3]
Additional Inherited Members
Static Public Member Functions inherited from CIccXform
static CIccXform * Create (CIccProfile *pProfile, bool bInput=true, icRenderingIntent nIntent=icUnknownIntent, icXformInterp nInterp=icInterpLinear, icXformLutType nLutType=icXformLutColor, bool bUseMpeTags=true, CIccCreateXformHintManager *pHintManager=NULL)
Note: The returned CIccXform will own the profile.
static CIccXform * Create (CIccProfile &pProfile, bool bInput=true, icRenderingIntent nIntent=icUnknownIntent, icXformInterp nInterp=icInterpLinear, icXformLutType nLutType=icXformLutColor, bool bUseMpeTags=true, CIccCreateXformHintManager *pHintManager=NULL)
Detailed Description
Type: Class
Purpose: This is the general Matrix-TRC Xform
Constructor & Destructor Documentation
CIccXformMatrixTRC::CIccXformMatrixTRC ()
Name: CIccXformMatrixTRC::CIccXformMatrixTRC
Purpose: Constructor
CIccXformMatrixTRC::~CIccXformMatrixTRC () virtual
Name: CIccXformMatrixTRC::~CIccXformMatrixTRC
Purpose: Destructor
Member Function Documentation
void CIccXformMatrixTRC::Apply (CIccApplyXform * pApply, icFloatNumber * DstPixel, const icFloatNumber * SrcPixel) const virtual
Name: CIccXformMatrixTRC::Apply
Purpose: Does the actual application of the Xform.
Args: pApply = ApplyXform object containging temporary storage used during Apply DstPixel = Destination pixel where the result is stored, SrcPixel = Source pixel which is to be applied.
Implements CIccXform.
icStatusCMM CIccXformMatrixTRC::Begin () virtual
Name: CIccXformMatrixTRC::Begin
Purpose: Does the initialization of the Xform before Apply() is called. Must be called before Apply().
Reimplemented from CIccXform.
References CIccXform::Begin(), icCmmStatBadSpaceLink, icCmmStatInvalidProfile, icCmmStatOk, icCmmStatProfileMissingTag, icFtoD(), icMatrixInvert3x3(), icSigBlueMatrixColumnTag, icSigBlueTRCTag, icSigGreenMatrixColumnTag, icSigGreenTRCTag, icSigRedMatrixColumnTag, icSigRedTRCTag, and icSigXYZData.
LPIccCurve * CIccXformMatrixTRC::ExtractInputCurves () virtual
Name: CIccXformMatrixTRC::ExtractInputCurves
Purpose: Gets the input curves. Should be called only after Begin() has been called. Once the curves are extracted, they will not be used by the Apply() function. WARNING: caller owns the curves and must be deleted by the caller.
Return: Pointer to the input curves.
Implements CIccXform.
LPIccCurve * CIccXformMatrixTRC::ExtractOutputCurves () virtual
Name: CIccXformMatrixTRC::ExtractOutputCurves
Purpose: Gets the output curves. Should be called only after Begin() has been called. Once the curves are extracted, they will not be used by the Apply() function. WARNING: caller owns the curves and must be deleted by the caller.
Return: Pointer to the output curves.
Implements CIccXform.
CIccTagXYZ * CIccXformMatrixTRC::GetColumn (icSignature sig) const protected
Name: CIccXformMatrixTRC::GetColumn
Purpose: Gets the XYZ tag from the profile.
Args: sig = signature of the XYZ tag to be found.
Return: Pointer to the XYZ tag.
References CIccTag::GetType(), and icSigXYZType.
CIccCurve * CIccXformMatrixTRC::GetCurve (icSignature sig) const protected
Name: CIccXformMatrixTRC::GetCurve
Purpose: Gets the curve having the passed signature, from the profile.
Args: sig = signature of the curve to be found
Return: Pointer to the curve.
References CIccTag::GetType(), icSigCurveType, and icSigParametricCurveType.
CIccCurve * CIccXformMatrixTRC::GetInvCurve (icSignature sig) const protected
Name: CIccXformMatrixTRC::GetInvCurve
Purpose: Gets the inverted curve having the passed signature, from the profile.
Args: sig = signature of the curve to be inverted
Return: Pointer to the inverted curve.
References CIccCurve::Begin(), and CIccCurve::Find().
virtual icXformType CIccXformMatrixTRC::GetXformType () const inline virtual
Implements CIccXform.
References icXformTypeMatrixTRC.
virtual bool CIccXformMatrixTRC::HasPerceptualHandling () inline protected virtual
Reimplemented from CIccXform.
Member Data Documentation
const LPIccCurve* CIccXformMatrixTRC::m_ApplyCurvePtr protected
used only when applying the xform
bool CIccXformMatrixTRC::m_bFreeCurve protected
CIccCurve* CIccXformMatrixTRC::m_Curve[3] protected
icFloatNumber CIccXformMatrixTRC::m_e[9] protected
The documentation for this class was generated from the following files:
IccCmm.h
IccCmm.cpp