CIccXformNamedColor Class Reference
CIccXformNamedColor Class Reference
#include <IccCmm.h>
Public Member Functions
CIccXformNamedColor (CIccTag *pTag, icColorSpaceSignature csPCS, icColorSpaceSignature csDevice)
virtual ~CIccXformNamedColor ()
virtual icXformType GetXformType () const
virtual icStatusCMM Begin ()
icApplyInterface GetInterface () const
Returns the type of interface that will be applied.
virtual void Apply (CIccApplyXform *pApplyXform, icFloatNumber *DstPixel, const icFloatNumber *SrcPixel) const
icStatusCMM Apply (CIccApplyXform *pApplyXform, icChar *DstColorName, const icFloatNumber *SrcPixel) const
icStatusCMM Apply (CIccApplyXform *pApplyXform, icFloatNumber *DstPixel, const icChar *SrcColorName) const
virtual bool UseLegacyPCS () const
Checks if version 2 PCS is to be used.
icStatusCMM SetSrcSpace (icColorSpaceSignature nSrcSpace)
icStatusCMM SetDestSpace (icColorSpaceSignature nDestSpace)
icColorSpaceSignature GetSrcSpace () const
Returns the source color space of the transform.
icColorSpaceSignature GetDstSpace () const
Returns the destination color space of the transform.
bool IsSrcPCS () const
Checks if the source space of the transform is PCS.
bool IsDestPCS () const
Checks if the destination space of the transform is PCS.
virtual LPIccCurve * ExtractInputCurves ()
Use these functions to extract the input/output curves from the xform.
virtual LPIccCurve * ExtractOutputCurves ()
Public Member Functions inherited from CIccXform
CIccXform ()
virtual ~CIccXform ()
virtual CIccApplyXform * GetNewApply (icStatusCMM &status)
virtual bool RemoveIO ()
virtual bool IsVersion2 () const
Checks if the profile is version 2.
bool IsInput () const
Checks if the profile is to be used as input profile.
void SetParams (CIccProfile *pProfile, bool bInput, icRenderingIntent nIntent, icXformInterp nInterp, CIccCreateXformHintManager *pHintManager=NULL)
The following function is for Overridden create function.
virtual bool NoClipPCS () const
const CIccProfile * GetProfile () const
Returns the profile pointer. Profile is still owned by the Xform.
icRenderingIntent GetIntent () const
Returns the rendering intent being used by the Xform.
Protected Member Functions
virtual bool HasPerceptualHandling ()
Protected Member Functions inherited from CIccXform
const icFloatNumber * CheckSrcAbs (CIccApplyXform *pApply, const icFloatNumber *Pixel) const
void CheckDstAbs (icFloatNumber *Pixel) const
void AdjustPCS (icFloatNumber *DstPixel, const icFloatNumber *SrcPixel) const
Protected Attributes
CIccTagNamedColor2 * m_pTag
icApplyInterface m_nApplyInterface
icColorSpaceSignature m_nSrcSpace
icColorSpaceSignature m_nDestSpace
Protected Attributes inherited from CIccXform
CIccProfile * m_pProfile
bool m_bInput
icRenderingIntent m_nIntent
icXYZNumber m_MediaXYZ
icXformInterp m_nInterp
IIccAdjustPCSXform * m_pAdjustPCS
bool m_bAdjustPCS
icFloatNumber m_PCSScale [3]
icFloatNumber m_PCSOffset [3]
Additional Inherited Members
Static Public Member Functions inherited from CIccXform
static CIccXform * Create (CIccProfile *pProfile, bool bInput=true, icRenderingIntent nIntent=icUnknownIntent, icXformInterp nInterp=icInterpLinear, icXformLutType nLutType=icXformLutColor, bool bUseMpeTags=true, CIccCreateXformHintManager *pHintManager=NULL)
Note: The returned CIccXform will own the profile.
static CIccXform * Create (CIccProfile &pProfile, bool bInput=true, icRenderingIntent nIntent=icUnknownIntent, icXformInterp nInterp=icInterpLinear, icXformLutType nLutType=icXformLutColor, bool bUseMpeTags=true, CIccCreateXformHintManager *pHintManager=NULL)
Detailed Description
Type: Class
Purpose: This is the general Xform for Named Color Profiles.
Constructor & Destructor Documentation
CIccXformNamedColor::CIccXformNamedColor (CIccTag * pTag, icColorSpaceSignature csPCS, icColorSpaceSignature csDevice)
Name: CIccXformNamedColor::CIccXformNamedColor
Purpose: Constructor
Args: pTag = Pointer to the tag of type CIccTagNamedColor2, csPCS = PCS color space, csDevice = Device color space
References CIccTag::GetType(), icSigNamedColor2Type, and icSigUnknownData.
CIccXformNamedColor::~CIccXformNamedColor () virtual
Name: CIccXformNamedColor::CIccXformNamedColor
Purpose: Destructor
Member Function Documentation
virtual void CIccXformNamedColor::Apply (CIccApplyXform * pApplyXform, icFloatNumber * DstPixel, const icFloatNumber * SrcPixel) const inline virtual
Implements CIccXform.
Referenced by CIccApplyNamedColorCmm::Apply().
icStatusCMM CIccXformNamedColor::Apply (CIccApplyXform * pApply, icChar * DstColorName, const icFloatNumber * SrcPixel) const
Name: CIccXformNamedColor::Apply
Purpose: Does the actual application of the Xform.
Args: pApply = ApplyXform object containging temporary storage used during Apply DstColorName = Destination string where the color name result is stored, SrcPixel = Source pixel which is to be applied.
References CIccTagNamedColor2::FindCachedPCSColor(), CIccTagNamedColor2::FindDeviceColor(), CIccTagNamedColor2::GetColorName(), icCmmStatBadXform, and icCmmStatOk.
icStatusCMM CIccXformNamedColor::Apply (CIccApplyXform * pApply, icFloatNumber * DstPixel, const icChar * SrcColorName) const
Name: CIccXformNamedColor::Apply
Purpose: Does the actual application of the Xform.
Args: pApply = ApplyXform object containging temporary storage used during Apply DstPixel = Destination pixel where the result is stored, SrcColorName = Source color name which is to be applied.
References SIccNamedColorEntry::deviceCoords, CIccTagNamedColor2::FindColor(), CIccTagNamedColor2::GetDeviceCoords(), CIccTagNamedColor2::GetEntry(), icCmmStatBadSpaceLink, icCmmStatColorNotFound, icCmmStatOk, icCmmStatProfileMissingTag, icSigLabData, icSigNamedData, and SIccNamedColorEntry::pcsCoords.
icStatusCMM CIccXformNamedColor::Begin () virtual
Name: CIccXformNamedColor::Begin
Purpose: Does the initialization of the Xform before Apply() is called. Must be called before Apply().
Reimplemented from CIccXform.
References CIccXform::Begin(), icApplyNamed2Pixel, icApplyPixel2Named, icApplyPixel2Pixel, icCmmStatAllocErr, icCmmStatIncorrectApply, icCmmStatOk, icCmmStatProfileMissingTag, icSigNamedData, and icSigUnknownData.
virtual LPIccCurve* CIccXformNamedColor::ExtractInputCurves () inline virtual
Use these functions to extract the input/output curves from the xform.
Implements CIccXform.
virtual LPIccCurve* CIccXformNamedColor::ExtractOutputCurves () inline virtual
Implements CIccXform.
icColorSpaceSignature CIccXformNamedColor::GetDstSpace () const inline virtual
Returns the destination color space of the transform.
Reimplemented from CIccXform.
Referenced by CIccNamedColorCmm::SetLastXformDest().
icApplyInterface CIccXformNamedColor::GetInterface () const inline
Returns the type of interface that will be applied.
Referenced by CIccApplyNamedColorCmm::Apply().
icColorSpaceSignature CIccXformNamedColor::GetSrcSpace () const inline virtual
Returns the source color space of the transform.
Reimplemented from CIccXform.
Referenced by CIccApplyNamedColorCmm::Apply(), and CIccNamedColorCmm::SetLastXformDest().
virtual icXformType CIccXformNamedColor::GetXformType () const inline virtual
Implements CIccXform.
References icXformTypeNamedColor.
virtual bool CIccXformNamedColor::HasPerceptualHandling () inline protected virtual
Reimplemented from CIccXform.
bool CIccXformNamedColor::IsDestPCS () const inline
Checks if the destination space of the transform is PCS.
bool CIccXformNamedColor::IsSrcPCS () const inline
Checks if the source space of the transform is PCS.
icStatusCMM CIccXformNamedColor::SetDestSpace (icColorSpaceSignature nDestSpace)
Name: CIccXformNamedColor::SetSrcSpace
Purpose: Sets the destination space of the Xform
Args: nDestSpace = signature of the color space to be set
References icCmmStatBadSpaceLink, icCmmStatOk, and icSigNamedData.
Referenced by CIccNamedColorCmm::AddXform(), and CIccNamedColorCmm::SetLastXformDest().
icStatusCMM CIccXformNamedColor::SetSrcSpace (icColorSpaceSignature nSrcSpace)
Name: CIccXformNamedColor::SetSrcSpace
Purpose: Sets the source space of the Xform
Args: nSrcSpace = signature of the color space to be set
References icCmmStatBadSpaceLink, icCmmStatOk, and icSigNamedData.
Referenced by CIccNamedColorCmm::AddXform().
virtual bool CIccXformNamedColor::UseLegacyPCS () const inline virtual
Checks if version 2 PCS is to be used.
Reimplemented from CIccXform.
Referenced by CIccApplyNamedColorCmm::Apply().
Member Data Documentation
icApplyInterface CIccXformNamedColor::m_nApplyInterface protected
icColorSpaceSignature CIccXformNamedColor::m_nDestSpace protected
icColorSpaceSignature CIccXformNamedColor::m_nSrcSpace protected
CIccTagNamedColor2* CIccXformNamedColor::m_pTag protected
The documentation for this class was generated from the following files:
IccCmm.h
IccCmm.cpp