#!/bin/bash

if [ ! -e bin ]; then
    echo "This file has to be run from main mrViewer directory"
    exit
fi


function remove_mo_files
{
    rm -rf share/locale/*
}

function create_copies()
{
    rm -rf LICENSE.txt
    cp  ../../../LICENSE.txt .
    rm -rf HISTORY.txt
    cp ../../../HISTORY.txt .
    rm -rf Videos.txt
    cp ../../../Videos.txt .
    rm -rf ctl
    cp -r ../../../ctl .
    rm -rf shaders
    cp -r ../../../shaders .
    rm -rf docs
    cp -r ../../../docs .
    rm -rf rails
}

function create_symlinks()
{
    rm -rf LICENSE.txt
    ln -s ../../../LICENSE.txt .
    rm -rf HISTORY.txt
    ln -s ../../../HISTORY.txt .
    rm -rf Videos.txt
    ln -s ../../../Videos.txt .
    rm -rf ctl
    ln -s ../../../ctl .
    rm -rf shaders
    ln -s ../../../shaders .
    rm -rf docs
    ln -s ../../../docs .
    rm -rf rails
}

if [[ "$RELEASE" == "" ]]; then
    $RELEASE=`cmd.exe /c 'ver'`
    echo $RELEASE
    echo "Could not determine OS version"
    exit 1
fi

cd BUILD/Windows-$RELEASE-32/Release
create_copies
remove_mo_files
cd ../../..

cd BUILD/Windows-$RELEASE-64/Release
create_copies
remove_mo_files
cd ../../..

release=`uname -r`
cd BUILD/Linux-$release-64/Release
create_symlinks
remove_mo_files
cd ../../..
