// generated by Fast Light User Interface Designer (fluid) version 2.1000

#include "mrvAudioOffset.h"
#include "core/CMedia.h"

fltk::Window *main=(fltk::Window *)0;

fltk::ValueInput *uiFrameOffset=(fltk::ValueInput *)0;

static void cb_OK(fltk::Button* o, CMedia* v) {
  v->audio_offset( o->value() );
  main->hide();
}

static void cb_Cancel(fltk::Button* o, fltk::Window*) {
  o->hide();
}

fltk::Window* edit_audio_cb( fltk::Widget* o, mrv::ImageView* view ) {
  fltk::Window* w;
   {fltk::Window* o = main = new fltk::Window(185, 140);
    w = o;
    o->shortcut(0xff1b);
    o->begin();
     {fltk::Group* o = new fltk::Group(10, 10, 160, 115);
      o->begin();
       {fltk::ValueInput* o = uiFrameOffset = new fltk::ValueInput(45, 25, 70, 25, _("Frame Offset"));
        o->user_data((void*)(img));
        o->align(fltk::ALIGN_TOP);
        mrv::media fg = view->foreground();
        if ( !fg ) return;
        
        CMedia* img = fg->image();
        if ( !img->has_audio() ) return;
        
        o->value( img->audio_offset() );
      }
       {fltk::Button* o = new fltk::Button(5, 70, 70, 25, _("OK"));
        o->callback((fltk::Callback*)cb_OK, (void*)(img));
      }
       {fltk::Button* o = new fltk::Button(80, 70, 75, 25, _("Cancel"));
        o->callback((fltk::Callback*)cb_Cancel, (void*)(main));
      }
      o->end();
    }
    o->end();
    o->set_modal();
    o->resizable(o);
  }
  return  w;
}
