// generated by Fast Light User Interface Designer (fluid) version 2.1000

#ifndef mrvAudioOffset_h
#define mrvAudioOffset_h
#include <fltk/Window.h>
extern fltk::Window* main;
#include <fltk/Group.h>
#include <fltk/ValueInput.h>
extern fltk::ValueInput* uiFrameOffset;
#include <fltk/Button.h>
fltk::Window* edit_audio_cb( fltk::Widget* o, mrv::ImageView* view );
#endif
