/*
    mrViewer - the professional movie and flipbook playback
    Copyright (C) 2007-2014  Gonzalo Garramuño

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/
// generated by Fast Light User Interface Designer (fluid) version 2.1000

#ifndef mrvIccProfileUI_h
#define mrvIccProfileUI_h
#include <cstring>
#include <string>
class CIccProfile;
#include <fltk/Window.h>
#include <fltk/PackedGroup.h>
#include <fltk/Group.h>
#include <fltk/Browser.h>
#include <fltk/WizardGroup.h>
#include <fltk/TextDisplay.h>
#include <fltk/Widget.h>
#include <fltk/Button.h>

namespace mrv  {
class ViewerUI;

class ICCProfileUI  {
  CIccProfile* _profile;
public:
  ICCProfileUI();
  ~ICCProfileUI();
  fltk::Window* make_window();
  fltk::Window *uiMain;
        fltk::Browser *uiTags;
private:
        inline void cb_uiTags_i(fltk::Browser*, ICCProfileUI*);
        static void cb_uiTags(fltk::Browser*, ICCProfileUI*);
public:
        fltk::WizardGroup *uiWizard;
          fltk::TextDisplay *uiText;
            fltk::Widget *uiDrawing;
  void replace( const std::string& name );
private:
  void fill( const std::string& name );
public:
  void fill_text();
};

class ICCProfileListUI  {
  ICCProfileUI* _info;
public:
  fltk::Window* make_window();
  fltk::Window *uiMain;
        fltk::Browser *uiProfiles;
private:
        inline void cb_Info_i(fltk::Button*, ICCProfileListUI*);
        static void cb_Info(fltk::Button*, ICCProfileListUI*);
public:
  ICCProfileListUI( mrv::ViewerUI* main );
  ~ICCProfileListUI();
  void fill();
  void show_info();
};
}
#endif
